### ISSUE TITLE
bump_e2e_image.sh script fails while pulling bazel git dependency

### ISSUE THREAD

**Issue by imkin** [kubernetes/test-infra#10261]
**What happened**:
Ran
`$ ./expermiment/bump_e2e_image.sh`

failed with

> Starting local Bazel server and connecting to it...
> ERROR: error loading package '': Encountered error while reading extension file 'lib.bzl': no such package '@bazel_skylib//': Error cloning repository: git@github.com:/bazelbuild/bazel-skylib.git: Auth fail caused by git@github.com:/bazelbuild/bazel-skylib.git: Auth fail caused by Auth fail
> ERROR: error loading package '': Encountered error while reading extension file 'lib.bzl': no such package '@bazel_skylib//': Error cloning repository: git@github.com:/bazelbuild/bazel-skylib.git: Auth fail caused by git@github.com:/bazelbuild/bazel-skylib.git: Auth fail caused by Auth fail
> INFO: Elapsed time: 5.973s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> FAILED: Build did NOT complete successfully (0 packages loaded)

**What you expected to happen**:
bump command to end successfully

**How to reproduce it (as minimally and precisely as possible)**:
cleanup the bazel cache (by running `bazel clean` or purging the bazel cache directory) and run the command `$ ./expermiment/bump_e2e_image.sh`
**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
Discussion on slack. 
https://kubernetes.slack.com/archives/C5NV3MT97/p1543291125233000

/kind bug

**Comment by ixdy** [comment]
Yup, somehow we unintentionally missed fixing
https://github.com/kubernetes/test-infra/blob/84054b3bac433350fc77b8154004607e50ecda65/WORKSPACE#L3-L7

Moving https://github.com/kubernetes/test-infra/blob/84054b3bac433350fc77b8154004607e50ecda65/WORKSPACE#L13-L14 up to the beginning of the file (after the `workspace()` line) should fix this.

It'd be good to get this fixed ASAP, since I think this will break for everyone in bazel 0.20.

**Comment by imkin** [comment]
@ixdy thanks yes generating a PR for this.
