### ISSUE TITLE
Ability to "reset" a PR state

### ISSUE THREAD

**Issue by bparees** [kubernetes/test-infra#10317]
If you create a PR that changes some files that trigger a run_if_changed job, and then you update the PR to not change those files, the initially triggered job will remain required for the PR to merge.

Similarly if you "/test all" on a PR, any jobs triggered become permanently mandatory for the PR.

I would like a way to "/reset" my PR. This should cause the system to treat the PR as if it was just opened (throw away any test history, re-evaluate what jobs are required for merging based on the files currently being changed by the PR, etc).

/cc @stevekuznetsov

**Comment by bparees** [comment]
(currently I deal w/ this situation by closing the PR and opening a new one, so i'm basically looking for behavior that would mimic what happens when I do that)

**Comment by BenTheElder** [comment]
resetting a PR is creating a new one from the same branch?

we have `/skip` and `/override` for admins to clear statuses. closing / re-opening will also somewhat do this
https://prow.k8s.io/command-help

I don't think we want to build "throw away results" functionality - we also persist these to longer term storage (GCS), but we do have "add newly passing results" or "mark non-required jobs as skipped".

pushing a new commit _should_ clear the run_if_changed job results, that seems like the actual bug here. @cjwagner 

I don't have an example handy, but it might just be commenting that the job failed while still marking it as passed in the github context (which is what the merge robot cares about) -- if that's the case then there's another log standing bug related to this.

**Comment by bparees** [comment]
Closing and reopening has not worked for me historically, i've had to create a new branch and generate a new PR.  Maybe I did not explore that path sufficiently.

The "i triggered something I didn't want because i ran /test all" is also annoying since again at that point there's no way out of it that i have found, anyway, other than creating a new PR.

perhaps "reset" is too strong.  "re-evaluate"?

**Comment by BenTheElder** [comment]
~ `/skip` is supposed to do that (re-evaluate)

**Comment by bparees** [comment]
that was the first thing i tried.  After some discussion with @stevekuznetsov i think he concluded /skip only applies to "optional" jobs.  Which is not the same as a run_if_changed job that was inadvertently triggered by "/test all"

**Comment by BenTheElder** [comment]
we should fix /skip to understand that.

imho, this is just further proof that run_if_changed is a footgun that we
should not have added :/
-- if that job is failling and you can't get it to pass, then it should not
be blocking, and something is wrong with the job or your PR if it continues
to fail ... this happens when jobs only run sometimes :|

**Comment by bparees** [comment]
yes in our case it is an issue with a particular job that really needs to be removed or fixed, but in the meantime people run into it.

run_if_changed is useful for us though in cases where we have some very lengthy (and sometimes moderately flaky) test buckets that we don't want to subject everyone to, but do want to run when we're changing relevant code in the area.  So i'd be remiss to see it go away.

**Comment by BenTheElder** [comment]
"not relevant" in what way? how was it not optional?

**Comment by stevekuznetsov** [comment]
Jobs can be not optional for merge but not relevant if;

 - they are `run_always: false` and expected to be triggered by a human in specific circumstances
 - they are `run_if_changed: ...` on something the PR does not touch in it's current state but did touch in the past, or if a human triggered the conditional job with an explicit `/test foo`

**Comment by BenTheElder** [comment]
/skip or /override seems appropriate for first of those. (though of course may need changes)

The second seems like a bug, `run_if_changed` and then a new commit that does not match _should_ be clearing it.


I don't think a `/reset` is a good idea because it won't reset all of the things unless we reset a LOT of things and try to keep up with that, and we do a lot of identification via PR #.  A full PR reset is a new PR. Clearing some statuses makes sense.

... also human triggered but merge blocking (!?) what are y'all doing over there? :scream:

**Comment by stevekuznetsov** [comment]
`/skip` has the strong interface that it gets rid of _optional_ jobs that have posted contexts -- the jobs we are talking about are not optional

An admin `/override` would be good, yes.

If `run_if_changed: ...` does not match, but was somehow triggered. IIRC the trigger code will see that the status ran and failed, so it will re-test it on `/retest`.

> ... also human triggered but merge blocking (!?) what are y'all doing over there? scream

I just run the system, man .... users do some silly things

**Comment by BenTheElder** [comment]
I would expect `/skip` to mark things as skipped, which should already be
the case for things that should not have been triggered for a new commit.

If it was triggered for the current commit, we should require override,
otherwise it is not in fact actually required.

**Comment by stevekuznetsov** [comment]
I think this is fixed after the refactor
/close
