### ISSUE TITLE
deck should degrade gracefully when tide is unavailable

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#10351]
Currently, deck serves 502s when it can't reach tide, such as when updating the prow cluster to a new version.

It'd be nice if deck degraded gracefully instead, only failing to show the components it couldn't reach.

/area prow
/kind feature

**Comment by taragu** [comment]
@ixdy "only failing to show the components it couldn't reach" --> is there currently a dashboard for deck?

**Comment by Katharine** [comment]
Looking into this some more, it looks to me like we don't generally serve 502s when tide isn't available.

What I think is actually happening here is that on startup we [make two blocking requests to tide in sequence](https://github.com/kubernetes/test-infra/blob/7f5424ec0d9088ed42b317b5564991de65db0df6/prow/cmd/deck/tide.go#L60-L67), which can each retry for up to several minutes (it was actually much shorter when this issue was filed; #10530 significantly increased the max delay). Since at this time we haven't actually started serving, the proxy in front of it serves 502 Bad Gateway.

Is it actually necessary to ensure we have tide data before we start up? We continue on blindly if this fails anyway. Perhaps we could instead handle this in the UI and carry on to ensure we can actually _serve_ some UI.
