### ISSUE TITLE
Migrate Prow GitHub authentication from Personal Access Token to a GitHub App

### ISSUE THREAD

**Issue by ccojocar** [kubernetes/test-infra#10423]
**What would you like to be added**:

Prow is currently using a Personal Access Token to authenticate with GitHub API. In the meantime, GitHub has revamped the API authentication mechanism and introduced [GitHub Apps](https://developer.github.com/apps/about-apps/), which will replace soon the Personal Access Token and OAuth tokens. 

Migrate prow from a Personal Access Token to a GitHub App. 

**Why is this needed**:

GitHub Apps provide some advantages over Personal Access Tokes which are listed here:
https://developer.github.com/apps/migrating-oauth-apps-to-github-apps/

cc @rawlingsj @wbrefvem

/kind feature
/area prow

**Comment by stevekuznetsov** [comment]
Not sure it's required for V4 -- we're successfully using OAuth tokens for the V4 API access we do today. I think we've talked about this in the past but it was unclear what the effort involved would be and what the downsides might be for the project.

/cc @fejta @spiffxp

**Comment by michaelneale** [comment]
certainly for access to checks api (perhaps not v4). Github are very keen on shifting to app vs PAT

**Comment by ccojocar** [comment]
I updated the description of the issue with the official reasons mentioned by GitHub in order to avoid any controversy.

**Comment by BenTheElder** [comment]
cc @cjwagner

**Comment by jlewi** [comment]
I think an advantage of GitHub apps over using PAT is that GitHub apps are owned by the organization. I think this will make them much easier to administer than bot accounts which requires sharing access to a GitHub account.

I dug into this an it looks to me like the way it works is that GitHub apps use private certs to generate JWTs which are then used to authenticate to the GitHub APIs: e.g. see the examples
https://github.com/github-developer/using-the-github-api-in-your-app/blob/master/server.rb#L104

So I think the primary work would be updating your GitHub client to generate JWTs
https://github.com/kubernetes/test-infra/blob/e591cdfa2e2b442fd92b9e6aba4b7c78f95cbb0b/ghclient/core.go#L49

Some googling turned up the following library for generating JWTs in go:
https://github.com/dgrijalva/jwt-go

**Comment by fejta** [comment]
Here is how we can update tackle to help make this easier: https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/

Note that this change would have some downsides. We could not, for example, react to a comment/issue

**Comment by stevekuznetsov** [comment]
It was noted that this approach will not give us the same access to the API as we have with PAT -- some APIs are PAT-only. Not sure if any of those are ones we use, though, or what the set is, even.

**Comment by michaelneale** [comment]
I have heard that github want to replace PAT at some point so any gaps in api coverage are likely temporary anyway.

**Comment by stevekuznetsov** [comment]
Sure, but:

 - PAT is not going away in the near future
 - we cannot migrate until we have all of our API usage supported

Not a blocker, just more things to think about when this work is undertaken. Agreed that the official stance from GitHub is that we should in a perfect world move away from PAT.

**Comment by spiffxp** [comment]
We would also get way, way more tokens if we interacted as an app against high-volume orgs like kubernetes.

**Comment by petr-muller** [comment]
/remove-lifecycle rotten

We'll eventually need to tackle this...

**Comment by jlewi** [comment]
I think this is still relevant.

**Comment by petr-muller** [comment]
/remove-lifecycle rotten

I do too

**Comment by jlewi** [comment]
I was looking for a go library to handle authentication as a GitHub app. I found this
https://github.com/bradleyfalzon/ghinstallation

**Comment by spiffxp** [comment]
>we cannot migrate until we have all of our API usage supported

It would be helpful to understand what API usage we need to look for, and see where things stand (e.g. what's supported? what's not yet supported?)

**Comment by alvaroaleman** [comment]
I've played around with this a little, the basic workflow  of create pr/tests get triggered/comments get posed/comments get cleaned up/labels get added on command/tide merges with hook/crier/tide running as an app seems to work for both public and private repos: https://github.com/alvaro-bot-prow/test-repo/pull/17

The code for this is here, but its POC quality at best, has no unit tests and is incomplete: https://github.com/kubernetes/test-infra/compare/master...alvaroaleman:prow-app?expand=1 It contains a set of TODOs and will probably give an okayish impression of the required work.

Next steps would most likely be to go over all endpoints we currently support, check if there are any that are not supported by a github app and write a small design doc.

Also, this introduces a decent bit of complexity as we won't have a global token anymore but need one for the `/apps` endpoints and a different one (which we can mint from the first) for each installation. This implies for example that we have to disassemble the tide queries in one query per installation (unless everything is public, then it doesn't matter).

So a good starting point for now would be to discuss the motivation, as there doesn't seem to be much in this issue other than "github might deprecate personal access tokens". I'll start below, please comment if there is more!

* Token budget scales[0]
* Webhook target and hmac token only need to be setup on the app, not on each org or repo where it should be installed, making changes to either of them trivial
* The privileges required by the app are configured on the app, so its not possible to run into issues because someone didn't grant enough privileges to one of the bot users
* Its easier to setup and remove
* The app itself has a list of all recent webhook delieveries, which could help in debugging
* Automation is even more obviously marked as such by getting a `[bot]` in its name when commenting
* An App doesn't consume a seat in a GitHub Enterprise setup



[0] From https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/
```
GitHub Apps making server-to-server requests use the installation's minimum rate limit of 5,000 
requests per hour. Organization installations with more than 20 users receive another 50 requests
per hour for each user. Installations that have more than 20  repositories receive another 50
requests per hour for each repository. GitHub Apps making user-to-server requests use the 
user's rate limit of 5,000 requests per hour.
```

**Comment by jglick** [comment]
I think what GitHub deprecated (or might deprecate) was using actual _passwords_ for authenticate. Not personal access tokens.

Besides better security, manageability, and scalability, using an App allows you to use the Checks API, which can provide a nicer experience than adding comments to a PR. A check can also include buttons wired up to arbitrary actions, as an alternative to parsing slash-commands in comments.

**Comment by alvaroaleman** [comment]
> using an App allows you to use the Checks API, which can provide a nicer experience than adding comments to a PR. A check can also include buttons wired up to arbitrary actions, as an alternative to parsing slash-commands in comments.

@jglick But using the checks api does not require a github app and can be done with personal acess tokens as well, right?

**Comment by jglick** [comment]
> But using the checks api does not require a github app and can be done with personal acess tokens as well, right?

No. The Checks API is accessible only via App authentication.

**Comment by alvaroaleman** [comment]
So I went through all endpoints we currently support in our GH client: https://gist.github.com/alvaroaleman/71867bda4e06a8b90cace8da96d26dbb

There are only two that are not supported by GH apps:

* `/user': Returns the user ID. We can use the [`/app`](https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#get-the-authenticated-app) endpoint instead. It doesn't provide an e-mail (as apps don't have one) but the E-Mail is only used by the cherrypicker to set up its git user
* [Create an issue reaction](https://docs.github.com/en/free-pro-team@latest/rest/reference/reactions#create-reaction-for-an-issue): Used to add a reaction to an issue. Probably a docs bug, as the similar delete endpoint supports gh apps: https://github.com/github/docs/discussions/854

**Comment by alvaroaleman** [comment]
I've written a proposal for adding github app authentication to prow (but not to remove the existing PAT auth, because the benefit of doing that is unclear to me): https://docs.google.com/document/d/1q9NagH0xB2vcuK-TC_X6V_LHc0syBrNrLqiuAQ8zGWY/edit#

Would love to hear everyones feedback!

**Comment by alvaroaleman** [comment]
/remove-lifecycle rotten

This is currently missing the Tide bits, the rest works already. I'll try to get the tide bits done in the near future, I have some work on that locally already.

**Comment by spiffxp** [comment]
maybe ref: https://github.com/kubernetes/test-infra/issues/20713 (if Actions integration implies interacting with Checks)

**Comment by alvaroaleman** [comment]
Tide gh apps support was finished in #23036, we rolled it out in Openshift today and it appears to be working fine.

That means the only thing left here is to update our documentation and samples.

**Comment by BenTheElder** [comment]
Was that the last thing to being able to migrate prow fully? Should we start looking at moving prow.k8s.io as well?

**Comment by alvaroaleman** [comment]
> Was that the last thing to being able to migrate prow fully?

Yes

>  Should we start looking at moving prow.k8s.io as well?

I think that would be great :) I am not sure if there is an immediate practical benefit to that, though. It is primarily useful to simplify onboarding orgs as the webhook and hmac secret is configured on the app instead of on the org and to alleviate token exhaustion issues (which afaik do not exist for prow.k8s.io).

One thing to note is that if a github apps needs to be installed in more than one GH org, everyone will be able to install it[[1]](https://docs.github.com/en/developers/apps/managing-github-apps/making-a-github-app-public-or-private). While not great this is IMHO ok, as Prow won't do anything for events in orgs or repos it has no config for.

**Comment by chaodaiG** [comment]
> Tide gh apps support was finished in #23036, we rolled it out in Openshift today and it appears to be working fine.

I assume that the gh apps user name is different from previous prow bot account, so during the transition period prow might do something inconsistent, for example it will not find previous existing bot comment and comment something new.

Is there any other side effect that you have observed? In another word, if we want to migrate one of our prow instance over, what should we communicate with our users?

**Comment by alvaroaleman** [comment]
> I assume that the gh apps user name is different from previous prow bot account, so during the transition period prow might do something inconsistent, for example it will not find previous existing bot comment and comment something new.

Yes, that is correct, e.G. `approve` will leave a stale comment behind on existing PRs.

> Is there any other side effect that you have observed? In another word, if we want to migrate one of our prow instance over, what should we communicate with our users?

No, we actually did this relatively silently (and gradually through the `--github-enabled/disabled-org/repo` settings as we are the first user and it took some time until all the org owners installed the app).
