### ISSUE TITLE
Allow specify podutil timeout in duration string format

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#10470]
Currently we have to do something like

```
decoration_config:
  timeout: 37200000000000 # 620 minutes
```

Which is different UX than other configs (has a string field and parses into actual duration)

We might want to unify the behavior here :-)

cc @stevekuznetsov @cjwagner

**Comment by cjwagner** [comment]
This is defined as a `time.Duration` is should parse properly with `620m` if I am not mistaken: https://github.com/kubernetes/test-infra/blob/8eb6f414a388506f29c434e667e709b507a6c7bf/prow/apis/prowjobs/v1/types.go#L162

**Comment by idealhack** [comment]
I don't think I can actively work on this in 1.14 cycle, so someone else feel free to take it.

/unassign

**Comment by krzyzacy** [comment]
@stevekuznetsov thoughts beside https://github.com/kubernetes/test-infra/pull/10597? I think this is still a pain point...

**Comment by cjwagner** [comment]
I just chatted with Steve. We're thinking the best path forward is probably to make a new `timeout-duration` field that uses the [`metav1.Duration`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/duration.go) type. We can print deprecation warnings for any jobs using the old `timeout` field and switch `timeout` to use `metav1.Duration` after 6 months.
This will leave both the `timeout` and `timeout-duration` fields. We can decide if we want to deprecate `timeout-duration` then or just leave both as supported so that a second migration is not mandatory.

**Comment by spiffxp** [comment]
/assign @cjwagner 
/milestone clear
where do we stand on this?

**Comment by cjwagner** [comment]
All done. https://github.com/kubernetes/test-infra/pull/12100

The `timeout` and `graceperiod` fields can be specified in either format now (integer number of nanoseconds or a duration string like "2h15m")
/close
