### ISSUE TITLE
label_sync: split into repo specific config files

### ISSUE THREAD

**Issue by nikhita** [kubernetes/test-infra#10519]
I wanted to add new labels to some of the published staging repos and while discussing about this in #sig-contribex in slack, @spiffxp pointed out that while adding the new labels to [`labels.yaml`](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml) is the right way to proceed, adding lots of new ones is soon going to make that file 5k lines long. :)

From a scalability standpoint, it is important to refactor that file. One way of doing so is to split it up into smaller repo-specific configs -- similar to how we do for [jobs](https://github.com/kubernetes/test-infra/tree/master/config/jobs) today.

/sig contributor-experience
/area label_sync
/kind feature
/cc @spiffxp @cblecker @fejta

**Comment by midnightconman** [comment]
@fejta - Can you comment more on the benefit of this approach? Is this still limited by the 1MB configMap limit?

**Comment by stevekuznetsov** [comment]
The Prow approach is nice, though, because it lets other deployments of Prow have their config repos set up without bazel and still benefit from the split

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/help
I'm personally still not sold on the learning curve of `bazel`, but I agree with @fejta that the pattern used in `kubernetes/org` is pretty straightforward and has worked well there.  So I think this is clear enough for a new contributor to follow, but not marking as `good first issue` because of bazel.

Another option would be to bake that merging logic into the tool itself, and update it to point at a path with a well-defined structure instead of a single file.
