### ISSUE TITLE
Prow issue:  How do I reopen bugs it if I am not author or collaborator?

### ISSUE THREAD

**Issue by ktrOpenSource** [kubernetes/test-infra#10566]
I need to reopen: https://github.com/kubernetes/kubernetes/issues/59477 as this is still present.  How do I reopen it if I am not author or collaborator?

**Comment by idealhack** [comment]
thanks for your feedback, I'll reopen that issue while keeping this one open in case if there's any related discussion.

**Comment by idealhack** [comment]
Prow will help those are not collaborators mention GitHub teams by repeating after them, should it also help with reopening issues?

/area prow
/sig contributor-experience

**Comment by fejta** [comment]
You cannot reopen issues unless you are a member of the kubernetes organization (aka a collaborator).

Why is it important to you whether or not that issue is open? I suspect it may be because you want someone to fix the issue. Unfortunately the issue has not attracted the attention of anyone willing and able to fix it. Instead it has been ignored for a year. Reopening is unlikely to change this sad state of affairs.

Maybe you can help this issue find someone's attention? My recommendation would be one of the following:

1) send a PR to fix the issue (would be great grounds for joining the organization)
2) find someone in the organization who is willing to fix the issue. They can assign it to themselves and reopen it. You can start by contacting the sig associated with the issue to see if they will put fixing it on their roadmap.

**Comment by fejta** [comment]
The core problem on that issue is the community ignored it for a year, not that we closed it after detecting that it was ignored and sending multiple notices that it is being ignored.

**Comment by nikhita** [comment]
Closing as we want to restrict closing/reopening to only authors or collaborators. 

/close
