### ISSUE TITLE
Tide: add an option to prevent partial batch merges.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#10621]
**What would you like to be added**:
A config option that indicates that if a batch merge fails part way through, any members of the batch that were successfully merged should be reverted.
Alternatively, if we could find a way to merge all the members of the batch atomically, this problem would disappear.

**Why is this needed**:
Tide batches are tested as a single unit so if a batch is only partially merged, the repo is left in an untested state. In the vast majority of cases there won't be dependencies between PRs in the batch and this won't cause any issues so merging the partial batch is probably fine (and should be done because merging batches should be prioritized).
While this might be preferable in practice for most repos, some repos may want to strictly enforce that the repo does not go into an untested state if a batch merge fails and would prefer that the partial merge be reverted.

/area prow/tide
cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
We could create an ephemeral branch at the tested ref from the target branch, merge in all the PRs, and merge that into the target branch if we wanted to do it atomically. Seems messy though. If we reverted, how would we

**Comment by stevekuznetsov** [comment]
C'mon, GitHub mobile interface.

**Comment by stevekuznetsov** [comment]
How would we return the changes to the queue after a revert? We couldn't reopen the PR

**Comment by wking** [comment]
> Alternatively, if we could find a way to merge all the members of the batch atomically, this problem would disappear.

[GitHub's API][1] doesn't support this directly, but you could perform a local [octopus merge][2] and then push that octopus commit to the target branch (GitHub would automatically close the PRs as their tips appeared in the target branch history).  The downsides to this approach are:

* You'd need a whole bunch of code to support the local merge.  I don't think we have anything in this line at the moment.
* You'd need to run Tide with sufficient permissions to be able to push to the target branch despite any branch-protection configured in GitHub.  If you've checked [Include administrators][3], this may not be possible.

> We could create an ephemeral branch at the tested ref from the target branch, merge in all the PRs, and merge that into the target branch if we wanted to do it atomically. Seems messy though.

This gains Tide-codebase cleanliness over the local-merge approach but sacrifices GitHub-state-cleanliness, because now you're pushing PRs as scratch space to perform the merge on the GitHub side.  You may also have to put these PRs through additional rounds of testing as quasi-single-jobs to satisfy GitHub's branch protection?  But if the push-to-target-branch approach is deemed infeasible for permissions reasons, this way is the best approach I can think of too.

> If we reverted, how would we

You wouldn't have to revert, you'd just close your scratch PR as a failed attempt.  The original PRs would remain open until the scratch PR was successfully constructed and merged into the target branch.

[1]: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button
[2]: https://git-scm.com/docs/git-merge

**Comment by BenTheElder** [comment]
I don't think tide should push to the target branch at risk of a bug wiping history. 

Ephemeral branches are messy but if we name them predictably they can be easily tracked and removed (EG "tide-...").

Is this a problem we've seen "in the wild"? Wondering what the actual failure mode with merging was here, I can see where two PRs would only pass together test-wise.

**Comment by cjwagner** [comment]
@BenTheElder See the "Why is this needed" section in the issue body.
This is a low priority issue in my opinion. Basically our merge automation isn't technically correct in this case because we are ending up in an untested state, but in practice it is probably better to partially merge a batch than not merge any of it because merging batches is Tide's highest priority and the chances of two PRs only passing together is very low.

I have only ever seen one instance of mutually dependent PRs in k/k and there would only have been a problem if Tide failed to merge some of the PRs in the batch for some reason. I don't think we really need to address this now. If we don't care about it at our scale, it seems unlikely that anyone else will.

I mainly opened this issue to document the imperfection and suggest a solution in case this becomes a problem for someone.
