### ISSUE TITLE
Add git source to Prowjob refs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#10667]
We are having all kinds of issue try to decouple links for other git platforms (namely gerrit, and soon will have pubsub)... Currently there are not-so-elegant checks against labels/annotations like https://github.com/kubernetes/test-infra/blob/master/prow/gerrit/reporter/reporter.go#L69-L75, also like https://github.com/kubernetes/test-infra/pull/10644 - and I need something for github soon as well..

I think whoever creates a prowjob from a ref will be responsible for setting a platform field - opening the issue before writing code to see if you supports/objects the idea :-)

/assign

cc @ibzib @stevekuznetsov @fejta @cjwagner

**Comment by ibzib** [comment]
That's a +1 from me. Re implementation I was envisioning a couple fields in `Refs`, maybe one for the platform type (e.g. `"github"`, `"gerrit"`, ....) and another for the URL (which would default to `"github.com"` to avoid breaking anything)

**Comment by ibzib** [comment]
Had to add some fields to new `common` functions
/cc @cjwagner

**Comment by stevekuznetsov** [comment]
Why is this necessary? Having a set of annotations that inform `crier` shards on how to report and where, then checking them before reporting seems perfectly fine to me. What added benefit would these new fields have over that?

**Comment by krzyzacy** [comment]
@stevekuznetsov annotations can work, but we'll have to duplicate the same check for deck for different ways of configuring links though... Currently we are assuming everything is github and doing hacks to try to generate the gerrit links, so maybe it's better if we can generate the links to ref/authors when creating the prowjob. (Annotations is per prowjob but not per ref, that's the limitation I can see... )

**Comment by stevekuznetsov** [comment]
If we just have one "source" or whatever, how are you going to do something like this?

https://github.com/kubernetes/test-infra/blob/c81fbc2b6f487c790f58b9e95d3906545506c454/prow/gerrit/reporter/reporter.go#L77-L81

It seems totally reasonable to have each crier shard do a watch, determine if it owns the object it is processing and proceed from there. Isn't there enough data in the ProwJob to determine the full set of ref cloning options to use when decorating and creating the Pod? 

I guess I am still confused as that what, specifically, is:

 - not elgant
 - missing information from the current ProwJob CRD

**Comment by krzyzacy** [comment]
@stevekuznetsov problem I have currently (if you can advise how to work around with existing label/annotations):

1. I don't know if something is a github job. (I probably don't want to assume not gerrit + not pubsub = is github)
2. We need similar ways to tell if a ref is from github or gerrit in deck (#10644), we probably can write some util function but I think it's better to pre-populate some info when create the prowjob though.

**Comment by ibzib** [comment]
@cjwagner and Sen have both suggested it's better to generate links when a job is created rather than somewhere further downstream. I agree with that approach because it will keep platform-specific logic confined to inherently platform-specific code, where it belongs. That would entail adding links to `Refs`, but wouldn't require the platform field Sen is proposing here.

As for crier, I feel it's more elegant to have a dedicated string field for a job's corresponding platform type, so we could do something like `if job.Refs.Platform == "gerrit"` instead of https://github.com/kubernetes/test-infra/blob/master/prow/gerrit/reporter/reporter.go#L69-L75. It's true that we already have sufficient information to derive this--it's just better design to keep that information in a dedicated struct where it's clearly visible and documented rather than using a map with some magic string key. (On that note, I might be missing something here, but is there a difference between `pj.ObjectMeta.Labels[kube.ProwJobTypeLabel]` and `pj.Spec.Type`??)

**Comment by krzyzacy** [comment]
@stevekuznetsov My argument is label/annotation belongs to per prowjob, not per ref.. We can probably respect the main ref, but technically we do have job checks out from both gerrit and github... (I don't mind if we have both :-) )

**Comment by krzyzacy** [comment]
The original problem is solved by https://github.com/kubernetes/test-infra/pull/10891
