### ISSUE TITLE
sig-node-ppc64le unit-tests result is not showing up in testgrid dashboard

### ISSUE THREAD

**Issue by sudeeshjohn** [kubernetes/test-infra#10871]
**What happened**:
sig-node-ppc64le unit-tests results are not showing up in testgrid dashboard.

**Please provide links to example occurrences, if any**:

https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests

**Anything else we need to know?**:

The results are pushed after each run . and able to fetch back from the storage.

**Comment by BenTheElder** [comment]
The metadata for failures invalid, they say `"result": "FAILED"` in finished.json, but the value is `SUCCESS` or `FAILURE`. [see docs here](https://github.com/kubernetes/test-infra/blob/da192baabd4c52e4a68b5c71bd39c5738928e110/gubernator/README.md)

There has not been a successful run since `2019-01-07`, so TestGrid has no results https://gubernator.k8s.io/builds/ppc64le-kubernetes/logs/ci-unit-kubernetes

**Comment by mkumatag** [comment]
> The metadata for failures invalid, they say `"result": "FAILED"` in finished.json, but the value should be `SUCCESS` or `FAILURE`. [see docs here](https://github.com/kubernetes/test-infra/blob/da192baabd4c52e4a68b5c71bd39c5738928e110/gubernator/README.md)
> 
> There has not been a successful run since `2019-01-07`, so TestGrid has no results https://gubernator.k8s.io/builds/ppc64le-kubernetes/logs/ci-unit-kubernetes

Thanks for the information @BenTheElder, now I know what to fix!

**Comment by sudeeshjohn** [comment]
corrected the metadata and pushed a new set of results. Looks like its still not updating the dashboard.
New data : https://gubernator.k8s.io/build/ppc64le-kubernetes/logs/ci-unit-kubernetes/502/

**Comment by michelle192837** [comment]
Hmm, there's an ASCII encode problem when TestGrid's translating the results. Taking a look.

**Comment by BenTheElder** [comment]
[followed up on this with testgrid internally] - Michelle already filed a patch 👍

**Comment by mkumatag** [comment]
this one fixed.
/close
