### ISSUE TITLE
Remove milestonestatus prow plugin

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#11037]
**What should be cleaned up or changed**:

The milestonestatus plugin should go away.

**Provide any links for context**:

Don't have the issue(s) handy right now, but we stopped using `status/foo` labels (they've been removed from label_sync) so `/status` doesn't mean anything to us, and the `milestone` plugin does what we need for `/milestone`

There are repos that "use" it in that they have it enabled in plugins.yaml, but that's just due to cargo culting, I couldn't find any actual status labels in use.

/area prow
/sig release
/sig testing

**Comment by spiffxp** [comment]
/milestone v1.14
/good-first-issue
FWIW I'm pretty sure this is a straightforward fix if someone wants to give it a shot.  First contribution as net-negative lines FTW!

**Comment by munnerz** [comment]
We've recently enabled this plugin along with a few other milestone related ones.

We've not collectively as a team made much use of it yet, but this issue does raise a larger question for me around what Prow intends to be wrt versions and stability.

I understand that changes like removing 'run_after_success' are required in order to facilitate other new features, but this reads more like it's being removed because it isn't utilised by prow.k8s.io anymore.

I'm used to having to deal with breaking changes between bumps of Prow, but I think for a lot of people evaluating Prow this could put them off.

What's the deprecation strategy for things like this? Can old plugins be moved into a 'contrib/' dir as external plugins with limited support, assuming k/test-infra no longer wants to support it? 🙂

**Comment by stevekuznetsov** [comment]
We can also just keep it around? It doesn't cost us any maintenance burden AFAICT

**Comment by BenTheElder** [comment]
this came up because I wasn't aware we didn't want to use it anymore and
approved a PR enabling it for one of the k8s repos along with other config
changes. perhaps if we just don't want it for k8s repos we can add a
test-infra specific config check for it.

**Comment by nikhita** [comment]
Going to remove good-first-issue from here because the direction isn't completely clear.

/remove-good-first-issue
