### ISSUE TITLE
Per-node folders missing from recent test artifacts

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/test-infra#1149]
See for example:
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/kubernetes-e2e-gci-gke-reboot-release-1.4/1324/artifacts/
contains a folder with the logs for each node, whereas
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot-release-1.4/84/artifacts/
does not.

Note that these are corresponding jobs; the name recently changed to include the `ci-` prefix.

/cc @fejta @Random-Liu @dchen1107

**Comment by mtaufen** [comment]
Just clicking on random things in the test grid, it seems a lot of jobs are exhibiting this behavior as of late.

**Comment by Random-Liu** [comment]
This also happens to node e2e. I've run the test script in my own cluster, everything is fine, test results and logs of different OS distros are collected to different directories:
```
$ ls /tmp/_artifacts/
junit_containervm01.xml  junit_coreos-alpha01.xml  junit_gci-family-gci-dev-56-8977-0-001.xml  junit_ubuntu-docker1001.xml  junit_ubuntu-docker901.xml  tmp-node-e2e-7bbfd769-coreos-alpha-1122-0-0-v20160727
junit_containervm02.xml  junit_coreos-alpha02.xml  junit_gci-family-gci-dev-56-8977-0-002.xml  junit_ubuntu-docker1002.xml  junit_ubuntu-docker902.xml  tmp-node-e2e-7bbfd769-e2e-node-containervm-v20160604-image
junit_containervm03.xml  junit_coreos-alpha03.xml  junit_gci-family-gci-dev-56-8977-0-003.xml  junit_ubuntu-docker1003.xml  junit_ubuntu-docker903.xml  tmp-node-e2e-7bbfd769-e2e-node-ubuntu-trusty-docker10-v1-image
junit_containervm04.xml  junit_coreos-alpha04.xml  junit_gci-family-gci-dev-56-8977-0-004.xml  junit_ubuntu-docker1004.xml  junit_ubuntu-docker904.xml  tmp-node-e2e-7bbfd769-e2e-node-ubuntu-trusty-docker9-v1-image
junit_containervm05.xml  junit_coreos-alpha05.xml  junit_gci-family-gci-dev-56-8977-0-005.xml  junit_ubuntu-docker1005.xml  junit_ubuntu-docker905.xml  tmp-node-e2e-7bbfd769-gci-dev-56-8977-0-0
junit_containervm06.xml  junit_coreos-alpha06.xml  junit_gci-family-gci-dev-56-8977-0-006.xml  junit_ubuntu-docker1006.xml  junit_ubuntu-docker906.xml
junit_containervm07.xml  junit_coreos-alpha07.xml  junit_gci-family-gci-dev-56-8977-0-007.xml  junit_ubuntu-docker1007.xml  junit_ubuntu-docker907.xml
junit_containervm08.xml  junit_coreos-alpha08.xml  junit_gci-family-gci-dev-56-8977-0-008.xml  junit_ubuntu-docker1008.xml  junit_ubuntu-docker908.xml
```

However, on gubernator there is only logs for one OS distro. I guess the log uploading logic was broken recently.

This deserves a P0 because we can't debug anything now because of the lack of logs.

**Comment by dchen1107** [comment]
We should treat this as P0 release-blocker for 1.5 release since it affects us to debug any flakiness.

**Comment by ixdy** [comment]
maybe https://github.com/kubernetes/test-infra/pull/1020, though not sure.

**Comment by mtaufen** [comment]
In #1020, this:
`artifacts, path`
changed to this:
`'%s/*' % artifacts, path`

Probably we used to each folder back to `path` and we are now copying the contents of each folder back to `path`, overwriting on name collision.

**Comment by fejta** [comment]
@ixdy might be able to help with this.

Previously we had an issue where if we ran e2e jobs we would wind up uploading artifacts twice, and the second time we did that (which is the real one) we would wind up copying the artifacts into the wrong location (gs://prefix/job/build_number/artifacts/artifacts insetad of gs://prefix/job/build_number/artifacts).

However now that https://github.com/kubernetes/kubernetes/pull/36949 is in I suspect we can revert to the previous behavior (copy to `...artifacts` instead of `...artifacts/*`)

BTW the way I've been testing this sort of thing is to take something like jobs/ci-kubernetes-e2e-gce.sh and then changing the PROJECT=foo to my personal project and then changing the ginkgo args to --ginkgo.focus=SingleJob (changing SingleJob) to something that selects a small number of tests.
