### ISSUE TITLE
[failing test] kubeadm-gce-1.14 gcp account issues

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/test-infra#11526]
`kubeadm-gce-1.14` is failing in both:
- [sig-release-1.14-blocking](https://testgrid.k8s.io/sig-release-1.14-blocking#kubeadm-gce-1.14)
- [sig-cluster-lifecycle](https://testgrid.k8s.io/sig-cluster-lifecycle-all#kubeadm-gce-1.14)
dashboards.

The error message hints at gcp account issues:
```
I0220 00:39:55.015] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W0220 00:39:55.519] Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
I0220 00:39:55.575] process 580 exited with code 0 after 0.0m
I0220 00:39:55.575] Call:  gcloud config get-value account
I0220 00:39:55.911] process 592 exited with code 0 after 0.0m
```

/sig cluster-lifecycle
/kind failing-test

**Comment by neolit123** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-14/14

```
gsutil cat gs://kubernetes-release-dev/ci/latest-bazel-1.14.txt
W0226 12:50:20.682] 2019/02/26 12:50:20 main.go:307: Something went wrong: error creating deployer: error during gsutil cat gs://kubernetes-release-dev/ci/latest-bazel-1.14.txt: exit status 1
```

^ this is the problem. it's because the endpoint doesn't exist yet for 1.14.

but the deployer insists it does:
https://github.com/kubernetes/test-infra/blob/8b4bb87e4361ec0bfe8a73ac9302ca3016b26a1e/kubetest/anywhere.go#L209

and this fails every cycle, before the endpoint is created at GS.  :grumble:

it should be doing this instead:
```
curl https://storage.googleapis.com/kubernetes-release-dev/ci/latest-1.14.txt

```

i will try sending a PR later today.

/assign

**Comment by neolit123** [comment]
started a discussion on slack:
https://kubernetes.slack.com/archives/C09QZ4DQB/p1551223217339100

**Comment by neolit123** [comment]
^ should be a fix, but let's re-open if it still fails tomorrow.
