### ISSUE TITLE
The Ability To Set Default Clone URI

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11592]
**What would you like to be added**:
I would like the ability to be able to set the default `clone_uri` to be used by `clonerefs`... so I don't have to specify a `clone_uri` for every job, if my github endpoint is different.

**Why is this needed**:
Without this feature, GitHub Enterprise users would have to specify `clone_uri` for each `prowJob`.

/area prow/clonerefs

**Comment by stevekuznetsov** [comment]
I wonder where we could put that default configuration.

/cc @cjwagner @fejta

**Comment by midnightconman** [comment]
I was thinking at the root of `presets` in `config.yaml`, maybe something like:
```
presets:
default_clone_uri: https://github.mycorp.com
- labels:
  preset-service-account: "true"
  ...
```

**Comment by cjwagner** [comment]
I think this applies to `path_alias` and `skip_submodules` as well. It might also be nice to include `extra_refs`: https://github.com/kubernetes/test-infra/blob/e808085f74d1f6f87820f56647f95f03d1bbfddf/prow/config/jobs.go#L384-L399

I think we could add the defaults to `plank` config like we did with [`default_decoration_config`](https://github.com/kubernetes/test-infra/blob/19196f3b9fab235f197b970aedbe7e9cbcccf903/prow/config/config.go#L176).

**Comment by midnightconman** [comment]
Sweet, I'll take this.

/assign

**Comment by Multiply** [comment]
@midnightconman Any progress on this?

We're kind of in the same boat, where we'd like to always have a `clone_uri` of `git@github.com:` rather than `https://github.com/`, to make private repos work without having to define `clone_uri` for all jobs.

Alternatively if we could define `clone_uri` with template variables like `clone_uri: git@github.com:{{ .Refs.Org }}/{{ .Refs.Repo }}.git`
