### ISSUE TITLE
Automatically apply /milestone when a PR is merged

### ISSUE THREAD

**Issue by nikopen** [kubernetes/test-infra#11611]
**What would you like to be added**:

Whenever a PR is merged, a bot applies the /milestone v1.xx relevant to the upcoming release. 

**Why is this needed**:

Many PRs are merged during non-freeze periods and there is little visibility on that. With this change,they can all be encapsulated by a simple query for easier management / overview: https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=milestone%3Av1.14+is%3Apr+is%3Amerged+sort%3Aupdated-asc+

**Comment by cjwagner** [comment]
I think we'd want the bot to apply the label directly instead of using a `/milestone` command, but the feature sounds like a good idea to me.

/help

**Comment by nikopen** [comment]
Sure, it applies things directly.

If you can point me to a relevant part of code I could try to write it @cjwagner

**Comment by cjwagner** [comment]
This might be best suited as a new plugin. I don't think its behavior or configuration will overlap with the `milestone` or `milestonestatus` plugins. The new plugin would just be configured with a mapping from "org" or "org/repo" -> current milestone and would handle pull request merge events for PRs that don't already specify a milestone. [`config-updater`](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/updateconfig/updateconfig.go) may be a good reference because it also handles webhooks for PR merges.

**Comment by nikopen** [comment]
I can more easily write a Github Action that does the above, and is commissioned/decommisioned/changed at every Code Freeze. Will Actions be soon available for k/k ?

**Comment by stevekuznetsov** [comment]
I would rather not see that behavior as a GitHub Action. If we have Prow, we do not need those and fragmenting the ecosystem would do more harm than good I think

**Comment by nikopen** [comment]
The Github Action is ready: https://github.com/nikopen/milestone-applier/blob/master/milestone-applier

I see no problem with implementing some behavior as Actions.
Not only you avoid Prow/token load, but you have a simple script for a simple behaviour.
I don't see any 'ecosystem fragmentation', Actions will be (soon?) supported as a native Github feature.

@stevekuznetsov

**Comment by liggitt** [comment]
I constantly have to reverse-engineer what milestone a historical PR merged into... I think I'd like having the current milestone auto-added on merge

**Comment by nikhita** [comment]
Take two as a prow plugin: https://github.com/kubernetes/test-infra/pull/12968

/remove-help
