### ISSUE TITLE
The pr I submitted was assigned to me again

### ISSUE THREAD

**Issue by xichengliudui** [kubernetes/test-infra#11777]
**What happened**:
https://github.com/kubernetes/website/pull/13178 the pr I submitted was assigned to me again.

**What you expected to happen**:
Two ways: 
Personally, I think the second implementation is more reasonable.

* Robots should assign pr to reviews or owners other than me.
* like this https://github.com/kubernetes/kubernetes/pull/75354 

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by fejta** [comment]
You're an approver for the files you modified. Therefore you're the most appropriate person to /approve the change. 

This is by design.

**Comment by xichengliudui** [comment]
https://github.com/kubernetes/website/pull/13178#issuecomment-472761153 
Thank you for your reply，but I can't approve my own pr

**Comment by stevekuznetsov** [comment]
You can! Users may not `/lgtm` their own PRs, but _may_ approve their own work.

**Comment by stevekuznetsov** [comment]
It looks like you first posted `/approved` to the comment, which would not trigger the approval. Currently Prow does not update if you edit the comment, but if you try re-posting the comment it will work as you expect.

**Comment by stevekuznetsov** [comment]
@cjwagner do we get comment edit actions? Would it be hard to make those a `GenericCommentEvent`?

**Comment by cjwagner** [comment]
Yes, we receive edit webhooks and they are already coerced into GenericCommentEvents. Here is the action coercion: https://github.com/kubernetes/test-infra/blob/ad4ecf6d6e497dd8071043beafbe938302cfe7a7/prow/hook/events.go#L352-L365

That being said, the vast majority of Prow plugins ignore edit events to avoid reacting multiple times to the same command as it isn't possible to determine what was changed by the edit and it is possible something unrelated to the command was changed.
This may not be a problem for the `approve` plugin since it has more of a 'munge everything always' approach, but I don't know if we should add support for reacting to edit webhooks since that would be inconsistent with how other commands behave.

**Comment by xichengliudui** [comment]
thank you.
/close
