### ISSUE TITLE
Split prow config from prow codebase

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#11782]
We're getting close to being ready for the move. Items we know we need to accomplish is here:

 - [x] reconfigure config updater for prow.k8s.io https://github.com/kubernetes/test-infra/pull/11781
 - [x] move remaining config files to `config/` and run the `config-bootstrapper` in case any changed had landed in between  https://github.com/kubernetes/test-infra/pull/11784
 - [x] ensure all references to original config locations are updated
 - [x] move `prow/cluster` to `config/cluster`
 - [x] ensure all auto-bump etc automation around `prow/cluster` is updated
 - [ ] submit KEP to create repo

/cc @spiffxp @fejta @cjwagner @BenTheElder @krzyzacy

**Comment by spiffxp** [comment]
Need to see what PR's modify config.yaml and plugin.yaml and decide if we want those to go through rebase fun

**Comment by spiffxp** [comment]
Rescoping based on what we thought was feasible for this quarter, moving to its own repo can be done as a followup

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
> move prow/cluster to config/cluster
> ensure all auto-bump etc automation around prow/cluster is updated

sounds relatively easy, maybe we should do that. @cjwagner @fejta thoughts?

> submit KEP to create repo

you actually just have to file an issue in k/org after getting consensus from the SIG on wanting it, no KEP necessary. the process is pretty lightweight. moving code is a little more involved to do cleanly.

**Comment by fejta** [comment]
Moving prow/cluster files into config/prow or somewhat like that sgtm

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

I think this is _mostly_ done? pretty much everything is under `config/`.

> submit KEP to create repo

we can actually do this with much less than a KEP, SIGs can sponsor a repo without going full KEP 🙃

**Comment by BenTheElder** [comment]
I don't think there's any config lingering under prow/ now. some scripts / makefile stuff.

**Comment by alvaroaleman** [comment]
Yeah, the config is pretty much moved out of the prow directory. What would be needed to move prow into its own repo is:
* The repo itself
* Exporting the code to the new repo
* Setting up all prow-related jobs onto the new repo
* Announcing this in case other projects reference prow code (kubetest2?)
* Updating all references outside of /prow to prow

The point that is presumably most of the work is setting up the jobs on the new repo. It would be great to make this happen though, to better separate concerns and make certain tasks like updating dependencies easier :upside_down_face:

**Comment by listx** [comment]
> Yeah, the config is pretty much moved out of the prow directory. What would be needed to move prow into its own repo is:
> 
> * The repo itself

We have https://github.com/kubernetes-sigs/prow which could host the codebase. Currently it just holds Prow docs but most of the code there sits under a /site folder so it should be straightforward to move code in there (I expect us to basically do `mv prow/* <new-repo>` and commit that).

> * Setting up all prow-related jobs onto the new repo

I think at least for the jobs that publish new Prow images, they can be set up to use the code from the new repo and still publish into the same GCR locations, because the SHAs would be different so there wouldn't be any overlap. Once all of the presubmits and integration tests are set up to work on the new repo, I assume it would be OK to put a blockade on the old repo's `/prow` folder. Then the laborious task of setting up the Prow-related jobs can begin... and once that's done we can retire the old jobs.

I assume no one is currently working on this effort. But I am interested in this space.

**Comment by BenTheElder** [comment]
This old issue got lost but https://github.com/kubernetes-sigs/prow exists now.
