### ISSUE TITLE
Tide labels to override for all merge methods

### ISSUE THREAD

**Issue by deadmoose** [kubernetes/test-infra#11877]
Right now, it's possible to use `tide/squash` to manually override the repository's merge method and squash instead:
https://github.com/kubernetes/test-infra/blob/master/prow/tide/tide.go#L821-L829

In our use, we generally want to `squash` by default but occasionally override to `rebase` & keep the individual commits.

**Comment by cji** [comment]
👋 Hello! 

I was looking to work on this issue, but wanted to clarify slightly before getting started. 

Is the proposal to change the [default merge_method](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md#general-configuration) for all repositories from 'merge' to 'squash' and then instead of a `SquashLabel` have a `RebaseLabel` to override the default for a particular commit (instead of overriding the merge method for the repository as a whole)? 

Or should we leave the default `merge`, allowing users to override that at the repository level with `squash` [in the config](https://github.com/kubernetes/test-infra/blob/1a933dcdf71a3cc95006943c764ed25f5d45ed58/prow/config.yaml#L429), but then also have a `RebaseLabel` to be used on specific commits?

**Comment by stevekuznetsov** [comment]
@cji hey! Today, getting the default to `squash` is as simple as changing the configuration, so I don't think we want to change the default. Instead, we should honor a `tide/rebase` label that overrides a config-set default of `squash` for a PR.

**Comment by cji** [comment]
@stevekuznetsov awesome, will work on implementing that. Thanks for the help clarifying!

**Comment by deadmoose** [comment]
> Instead, we should honor a tide/rebase label that overrides a config-set default of squash for a PR.

Exactly. Today `tide/squash` ignores the default and overrides to squash. There should be a `tide/rebase` to override and do that. And similarly, a `tide/merge` (except that it's an ugly name :/ ) to do _that_.

I personally don't care about that last one, but having support for 2/3 of the options is even weirder than today's support for 1/3.

**Comment by fejta** [comment]
/lifecycle active

Good luck! May be worth a quick Google doc or issue explain how you intend to solve this before starting on the PR (vs just sending over the solution)

**Comment by cji** [comment]
Cool, thanks for the suggestion @fejta!	- I started riffing on a couple of options [here](https://docs.google.com/document/d/1PA1WBeNGn2sE4hqizwr6YtfRE1YYGnxnQP2kqmq3Io4/edit#)

**Comment by deadmoose** [comment]
:+1:

Thanks @cji!
