### ISSUE TITLE
ghproxy should be HA

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#11934]
Otherwise we cannot upgrade it without downtime

/assign @cjwagner

**Comment by cjwagner** [comment]
FWIW Prow doesn't experience any downtime when ghproxy is unavailable because Prow's GH client falls back to using the GH API directly.

And for a bit more context: The challenge with making ghproxy HA is that we need all requests for a resource to be deterministically routed to the same replica otherwise the caching and coalescing benefits will both be reduced. I think that is the only barrier to running multiple replicas.

**Comment by BenTheElder** [comment]
>  The challenge with making ghproxy HA is that we need all requests for a resource to be deterministically routed to the same replica otherwise the caching and coalescing benefits will both be reduced.

That's not _really_ HA anyhow.

There are other options for making this HA such as:
- decouple storage and share it between ghproxy instances (EG store to redis)
- replicate cache writes between instances
- use `ReadWriteMany` storage (NFS, ceph)

The second option shouldn't be very invasive (most invasive part would probably be periodically listing endpoints to locate peers) and would actually scale nicely for our read heavy workload. 

The first option is also pretty common, but I probably would not really consider the third right now.

Or we could just leave it with the fallback to live queries. ¯\\\_(ツ)\_/¯

**Comment by stevekuznetsov** [comment]
Might be nice to try to see how many tokens per version migration were lost from the direct-to-github calls. The fallback seems like a totally reasonable thing to do IMO
