### ISSUE TITLE
Boskos should have an automated push/bump/deploy like Prow

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#11957]
Doing things manually invites mistakes!

/assign @fejta

**Comment by Katharine** [comment]
/remove-lifecycle stale

it automatically pushes and bumps, but still does not automatically deploy.

**Comment by stevekuznetsov** [comment]
/remove-lifecycle rotten
/reopen

We're deploying it automatically on the OpenShift side, so this is definitely possible.

**Comment by cjwagner** [comment]
/kind oncall-hotlist

The boskos images are currently running at version `v20190621-ff01381` even though there have been many changes since then: https://github.com/kubernetes/test-infra/commits/master/boskos

@michelle192837 (current oncall) Could you please publish and deploy the latest boskos images when you get the chance (or make it automatic)?

**Comment by fejta** [comment]
This is the latest image:

9abcb3ce0bea  v20190621-ff01381                                         2019-06-21T09:04:24


The prow bump already autobumps this to the latest image whenever it changes.

**Comment by fejta** [comment]
We also have a job to push images whenever they change:

https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L178-L204

**Comment by cjwagner** [comment]
> We also have a job to push images whenever they change

I don't think this part is working right. There have been many changes to boskos since June 21, but that is the most recent image we've published: https://github.com/kubernetes/test-infra/commits/master/boskos

If you look at the post submit job statuses on those commits it does look like the `post-test-infra-push-boskos` job is running, but the images it says it is publishing are not actually being published. e.g. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-boskos/1173991256389324801 (should have published tag `v20190917-d326d2a31`.

**Comment by cjwagner** [comment]
Ooooh, looks like we have published boskos images to both `gcr.io/k8s-testimages` and `gcr.io/k8s-prow`. Our deployments are all referencing `gcr.io/k8s-testimages` still, but we only push to `gcr.io/k8s-prow` now so autobump isn't finding the newer images.

**Comment by michelle192837** [comment]
I believe this is fixed now, and automatically bumps when we do the Prow bump. (Reopen if I'm wrong :P )
