### ISSUE TITLE
Build and release greenhouse with prow

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12052]
If I'm at prow v20190401-deadbeef I should be able to also use this tag for greenhouse

**Comment by fejta** [comment]
/assign @Katharine 

does your PR fix this?

**Comment by Katharine** [comment]
It doesn't - I missed this one because it doesn't have a Dockerfile, which is what I used to find these.

I could probably take the same approach I took for the rest of the images, but given it's generated by bazel it could presumably join the rest of the `prow_push` crew? Although AFAICT that would result in it being in `k8s-prow` rather than `k8s-testimages`, which may not be desirable.

**Comment by fejta** [comment]
We use it for prow. I'm okay to package these sort of things up into the prow "distro"
