### ISSUE TITLE
tide: failed batches should re-trigger only failed presubmits

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#12216]
When `tide` determines than an in-progress batch has failed due to one or more presubmits in the batch failing, it re-triggers all of them. When a batch contains a perma-failed test, this causes `tide` to re-trigger batches on every sync. When other jobs in the batch require third-party resources like cloud computing quota, the issue quickly balloons. `tide` should re-trigger only the jobs it needs.

/cc @cjwagner @fejta 
/area prow/tide

**Comment by stevekuznetsov** [comment]
This is fixed by proxy by correctly aborting older batches but is still an issue when aborting them and the associated cleanup/grace period takes a while.

**Comment by alvaroaleman** [comment]
I've also noticed that tide seems to trigger retest for _all_ presubmits if one or more of them needs retesting, even for the ones that have up-to-date results. Is that related or a different issue? I'll probably look into this, this is really, really annoying.

**Comment by cjwagner** [comment]
> I've also noticed that tide seems to trigger retest for _all_ presubmits if one or more of them needs retesting, even for the ones that have up-to-date results. Is that related or a different issue? I'll probably look into this, this is really, really annoying.

Are you talking about when PRs have tests run against different base branch commits? We could optimize for that edge case more by trying to make Tide's triggering aware of existing jobs. This would complicate things, but is certainly doable.
Can you link to some occurrences? Roughly how frequently does this happen?

**Comment by alvaroaleman** [comment]
I don't have a public example because most of our code is not public, but the example I have basically boils down to:

* Some did a PR
* One test failed
* A couple of days later it succeeded after a `/retest`
* All except this one test need retesting
* Tide restarts _all_ tests
* We now have to successfull Prowjobs with the same base and head sha that were both successful:
```
$ k get prowjob -l prow.k8s.io/job=pull-dashboard-e2e-test,prow.k8s.io/refs.pull=1415,prow.k8s.io/job=pull-dashboard-e2e-test|grep 'success'|awk '{ print $1 }'|xargs kubectl get prowjob -o json|jq '.items[]|.spec.refs'
{
  "base_ref": "master",
  "base_sha": "6d38e4cbb5ccfed8e18cb2535378627f76edea95",
  "clone_uri": "git@github.com:kubermatic/dashboard-v2.git",
  "org": "kubermatic",
  "pulls": [
    {
      "author": "kdomanski",
      "number": 1415,
      "sha": "319c8f2069dc6ba1f14e49a16df619e75d1d1bf4"
    }
  ],
  "repo": "dashboard-v2"
}
{
  "base_link": "https://github.com/kubermatic/dashboard-v2/commit/6d38e4cbb5ccfed8e18cb2535378627f76edea95",
  "base_ref": "master",
  "base_sha": "6d38e4cbb5ccfed8e18cb2535378627f76edea95",
  "clone_uri": "git@github.com:kubermatic/dashboard-v2.git",
  "org": "kubermatic",
  "pulls": [
    {
      "author": "kdomanski",
      "author_link": "https://github.com/kdomanski",
      "commit_link": "https://github.com/kubermatic/dashboard-v2/pull/1415/commits/319c8f2069dc6ba1f14e49a16df619e75d1d1bf4",
      "link": "https://github.com/kubermatic/dashboard-v2/pull/1415",
      "number": 1415,
      "sha": "319c8f2069dc6ba1f14e49a16df619e75d1d1bf4"
    }
  ],
  "repo": "dashboard-v2",
  "repo_link": "https://github.com/kubermatic/dashboard-v2"
}
``

**Comment by stevekuznetsov** [comment]
Fixed in #13761 
/close

**Comment by alvaroaleman** [comment]
Err no, #13761 only fixes this for serial retesting, not for batches. Batches is a bit more involved, as we have to find existing tests that ran for the exact same batch.

/reopen

**Comment by stevekuznetsov** [comment]
Oh!. Well.

**Comment by alvaroaleman** [comment]
Okay, so I dug a bit into the related code here. The thing that surprised me the most is that we apparently do not report on batches, which is why we will silently retry batch tests indefinitely or until a PR with up-to-date results comes along the way. This is especially bad if a batch contains PRs that are incompatible with each other but do not have merge conflicts, because there is no feedback loop at all for this case.

IMHO the first thing we should do about this issue is to start reporting batch test results on all involved PRs, if the given job is mandatory for the PR. This will make tide stop considering PRs that were involved in a failed batch test until someone issues a `/retest` and that succeeds.

The only upside of the current behavior I can think of is in the case of flaky tests, where we get "unattended automatic retesting", but IMHO even then its bad:
* A CI system should not optimize based on assumptions about the tests its run which may or may not be accurate
* No feedback at all for incompatible PRs
* Flakyness should be visible and not silently swallowed


Does anyone have objections against starting to report to GitHub on failed batches @stevekuznetsov @cjwagner @fejta ?

**Comment by stevekuznetsov** [comment]
> This is especially bad if a batch contains PRs that are incompatible with each other but do not have merge conflicts, because there is no feedback loop at all for this case.

We generally have been operating on the assumption that this is very rare. Do we have data to change that opinion?

> The only upside of the current behavior I can think of is in the case of flaky tests, where we get "unattended automatic retesting"

I think that's the intended explicit design? Once things have gone green and been approved, `tide` "just makes it so"

**Comment by stevekuznetsov** [comment]
> Flakyness should be visible and not silently swallowed

This is only valuable if people care at a per-job level and are not using meta-trackers like test-grid, triage or the deck overview to look.

**Comment by alvaroaleman** [comment]
> We generally have been operating on the assumption that this is very rare. Do we have data to change that opinion?

Even if this happens rarely, this is a pretty big deal because it requires the person(s) operating Prow to know some of its implementation details to be able to ever get out of this situation. 

> I think that's the intended explicit design? Once things have gone green and been approved, tide "just makes it so"

okay? So we operate on the assumption that the tests Prow runs are flaky and that the code doesn't have issues anymore once it has the required labels, which is why just re-testing it indefinitely makes sense as we assume that just retrying will make all jobs green?

**Comment by stevekuznetsov** [comment]
> Even if this happens rarely, this is a pretty big deal because it requires the person(s) operating Prow to know some of its implementation details to be able to ever get out of this situation.

I'm not sure it's obvious what a better approach is. If some subset of a batch create some non-conflicting but non-functional state in the batch post-merge, how do we detect which those are? There were some thoughts about making log(N) batches where N is the size of the pool, each batch a factor of two larger, allowing us to find subsets that can merge and always merge the largest one we found. If we kick all jobs out of the pool when their batch fails, as long as at least two of the conflicting subset are re-tagged and re-enter together you'll get the same problem again, right? Instead of failing jobs and expecting devs to dig into what is an infrastructure (non-Jordan devs don't usually feel comfortable digging into repo-wide sets of PRs they did not author to discover which conflict and how), maybe it makes sense to improve our messaging in these cases to admins?

> So we operate on the assumption that the tests Prow runs are flaky and that the code doesn't have issues anymore once it has the required labels, which is why just re-testing it indefinitely makes sense as we assume that just retrying will make all jobs green?

That's what is assumed for k8s and k8s-adjacent repos, yeah

**Comment by alvaroaleman** [comment]
> I'm not sure it's obvious what a better approach is. If some subset of a batch create some non-conflicting but non-functional state in the batch post-merge, how do we detect which those are? There were some thoughts about making log(N) batches where N is the size of the pool, each batch a factor of two larger, allowing us to find subsets that can merge and always merge the largest one we found. If we kick all jobs out of the pool when their batch fails, as long as at least two of the conflicting subset are re-tagged and re-enter together you'll get the same problem again, right? Instead of failing jobs and expecting devs to dig into what is an infrastructure (non-Jordan devs don't usually feel comfortable digging into repo-wide sets of PRs they did not author to discover which conflict and how), maybe it makes sense to improve our messaging in these cases to admins?

The underlying problems remains because a CI system can not possibly distinguish "combination of PRs is defunct" from "tests are flaky".
What about just reporting on _one_ of the invoved PRs to introduce some jitter?

**Comment by alvaroaleman** [comment]
/reopen
/remove-lifecycle rotten

We should absolutely fix this, this may result in a huge waste of cluster capacity

**Comment by alvaroaleman** [comment]
Note for future passersby or probably just myself: With an index on successful+pending batches by refs plus a check prior to creation if we have something in there for the given refs, this should be not too hard to implement.
