### ISSUE TITLE
Prevent auto-close of some issues on "fixes" PR

### ISSUE THREAD

**Issue by jberkus** [kubernetes/test-infra#12240]
Per discussion on kubernetes-dev and elsewhere:

Currently, due to Github built-in, non-configurable functionality, "fixes #9999" in the body of the PR description will auto-close the named issue when the PR merges.  There are some specific cases where we don't want this to happen for Release management:

1. If the issue & PR is related to a failing test, we do not want the issue to close until the test is confirmed passing.  

2. If the PR fixes part of a complicated issue, we don't want it to auto-close.

Of the two above, (1) is the more persistent and problematic; the auto-close of the test fail issue frequently causes both the SIG and the RT to lose track of the failure for several testing cycles, delaying further work on fixing the test fail.  It also seems like the kind of thing that automation could detect.

(2) does not seem like the sort of thing that is amenable to automation (how do you analyze that something is a multi-part issue?), so we probably shouldn't do anything about it at this time.

Questions:

* are there other cases where we want to block auto-close based on "fixes"?
* how should we block this, given that we can't alter the GH functionality?

For blocking logic, I can think of a couple possibilities:

a) we prevent the PR from merging if the body says "fixes" and the named issue is test-fail.
b) we nag the PR author if the body says "fixes"
c) if an issue that is test-fail/flake *and* has a milestone is auto-closed, prow should reopen it.

Of those three options, (c) seem like the least problematic.

**Comment by jberkus** [comment]
attn:
@nikhita @fejta @claurence @alejandrox1 @imkin 
/priority important-longterm

**Comment by johnbelamaric** [comment]
In the conformance work, we see #2 happen because we are using tracking issues to manage the promotion and creation of conformance tests in different areas. I think though that the easiest remediation for this is just to tell the author not to say "fixes" for a tracking issue. Maybe some simple check on the title ("Tracking Issue" or "Umbrella Issue") to identify issues that should not be auto-closed?

**Comment by nikhita** [comment]
xref https://groups.google.com/d/msg/kubernetes-dev/MOnwc8_76wo/546zDpEsBwAJ

**Comment by BenTheElder** [comment]
we could also consider just not suggesting that people do this in the PR template :upside_down_face:

**Comment by cblecker** [comment]
Another way of handling this:
Have a "keep open" or "prevent close" label.. then run a search query for `is:issue is:closed label:prevent-close` and re-open those issues. Then no matter what is trying to close things, they'll get re-opened if GitHub closes them, rather than preventing PRs from merging in the first place.

cc @fejta who might have opinions on this.

**Comment by fejta** [comment]
What are some examples where this has been a problem?

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/assign @nikhita 
/close
I believe @nikhita fixed this by adding the `invalidcommitmsg` plugin via https://github.com/kubernetes/test-infra/pull/9387
