### ISSUE TITLE
Tide documentation on search query doesn't match github

### ISSUE THREAD

**Issue by hopkiw** [kubernetes/test-infra#12304]
1) The `tide` docs specify that all queries configured in the `tide` section of `config.yaml` will be translated into github search query parameters. However, the example shown for branch whitelisting and blacklisting indicates that e.g. `includedBranches: <branch>` will be translated to a github search query of `branch:<branch>`[1]. This latter is not apparently a supported github search parameter, rather github supports either `base:<branch>` or `head:<branch>`. 

2) Before filing this issue I poked a bit deeper into the code to see where I might test my hypothesis, and I find that the code apparently responsible for the `includedBranches` feature is actually doing a client-side filter[2]. 

So my question: is this feature working as documented? And how can I see what PRs `tide` will attempt to take action on when I enable it?

[1]: https://github.com/kubernetes/test-infra/blame/master/prow/cmd/tide/config.md#L67
[2]: https://github.com/kubernetes/test-infra/pull/7611/files#diff-20d0baada46f0a2923ce9ea49813fde3R230

**Comment by krzyzacy** [comment]
cc @cjwagner @stevekuznetsov

**Comment by cjwagner** [comment]
The documentation has a mistake. `includeBranches` is translated to `base:` search query tokens, not `branch:`. See here: https://github.com/kubernetes/test-infra/blob/e28581a6fca499b625cfbe5d79cbf29d00c5c2ec/prow/config/tide.go#L176-L178

The client side filtering you see is not responsible for the main functionality of `includeBranches` the client side filtering is only part of the status controller which must do client side filtering because it is searching through PRs that may not match the search query. 

So the feature is mostly working as documented, there is just a typo. `branch: <branch>` should be `base: <branch>`.

> And how can I see what PRs tide will attempt to take action on when I enable it?

Run Tide in dry run mode (the default): https://github.com/kubernetes/test-infra/blob/93b5c073cbb329e75229e428336741de6bb1a6c0/prow/cmd/tide/main.go#L90

**Comment by hopkiw** [comment]
Thanks!
