### ISSUE TITLE
/uncc does not work for teams

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#12356]
**What happened**:  teams assigned to review by prow cannot be unassigned. `/uncc <team>` does not produce any visible results.

**What you expected to happen**: the team should be removed

**How to reproduce it (as minimally and precisely as possible)**: cc a team and then attempt to uncc the team

**Please provide links to example occurrences, if any**: see https://github.com/kubernetes/kubernetes/pull/77038

**Anything else we need to know?**: 
/area prow
/cc @cblecker

**Comment by cblecker** [comment]
Ugh. Okay, so this might actually be a bug on GitHub's side.

There looks to be a difference in handling of API objects against the `requested_reviewers` endpoints, depending on if you `POST` or `DELETE` against them.

There are two different cases where providing the same input to the POST endpoint and the DELETE endpoint offer different results.

### Lowercase login:
- Input file: https://gist.github.com/cblecker/a9e3b3ba5f0a49c776e1244a6f8dc053#file-input1-json
- When you run a [`POST`](https://gist.github.com/cblecker/a9e3b3ba5f0a49c776e1244a6f8dc053#file-post-input1-log), GitHub will take the lowercase username and request a review from that user successfully. This is the expected behaviour.
- However, when you run a [`DELETE`](https://gist.github.com/cblecker/a9e3b3ba5f0a49c776e1244a6f8dc053#file-delete-input1-log) the request will come back with a 200 OK, but the review request won't actually be removed. However, if you modify the input to use the proper casing (e.g. `BenTheElder`), then this call will work.

### Reviewers array:
- Input file: https://gist.github.com/cblecker/a9e3b3ba5f0a49c776e1244a6f8dc053#file-input2-json
- When you run a [`POST`](https://gist.github.com/cblecker/a9e3b3ba5f0a49c776e1244a6f8dc053#file-post-input2-log), GitHub will accept this input only specifying `team_reviewers`, but omitting the empty `reviewers` array. It will add the requested review for that team successfully. This is the expected behaviour.
- However, when you run a [`DELETE`](https://gist.github.com/cblecker/a9e3b3ba5f0a49c776e1244a6f8dc053#file-delete-input2-log) the request will come back with a 422 Unprocessable Entity, and state that the `reviewers` array wasn't specified. If you add an empty array to the request, then GitHub will process the empty `reviewers` array, and the `team_reviewers` array, removing the review request as expected.


There should be enough information here for GitHub to debug. I would expect both of the payloads I specified above to work consistently for both POST and DELETE actions.

cc: @nickvanw
I'm going to put this into support too, but this looks like a problem on the API side.

**Comment by nickvanw** [comment]
Thanks @cblecker! Based on your description, this does sound like some problems with case sensitivity in the API. Your support ticket opened an issue internally, and I'll make sure we find the right team to take a look at this!

If anything else related comes up, feel free to comment in this issue!

**Comment by cblecker** [comment]
/remove-lifecycle stale

@nickvanw Any update on this? :)

**Comment by cblecker** [comment]
I tested this again, and the first issue (case sensitivity) is solved. The second issue (reviewers array not required for POST, but is for DELETE), is still an issue.

@nickvanw Any update on this?

**Comment by BenTheElder** [comment]
/shrug
oh well
I think we should reconsider assigning teams as opposed to individuals. assigning lots of people makes it nobody's problem :-)
