### ISSUE TITLE
Add Readme for prow/github

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#12760]
**What should be cleaned up or changed**:
test-infra/prow/github/ appears to be a useful library for reading & modifying GitHub programmatically using the v4 API. It would be great to use wherever we're doing GitHub Things, but it's got some very large files.

A README.md in this directory would help a lot.

**Provide any links for context**:
https://github.com/kubernetes/test-infra/tree/master/prow/github

**Comment by stevekuznetsov** [comment]
@chases2 are you hoping to use it inside of prow our in other projects? The directory vendors a v4 (graphql) client and implements a v3 (REST) client, but exposes them in opinionated ways that make sense for Prow but maybe not other projects. Fields Prow does not use, for instance, are elided.

**Comment by chases2** [comment]
I was looking at using it for a TestGrid feature (see Issue #10701 and PR #12753), because it might be duplicating the functionality I've written in that PR.

The thing is, it's tough to tell whether or not it meets those needs, or exactly what it's doing with GitHub's API. I've been parsing through it, but it's thousands of lines. It would be real neat if the next new person didn't have to.

In addition, a note on its purpose ("This is suitable for re-use" or "This is really just for Prow, and maybe here's why") would give some insight that code can't.

**Comment by stevekuznetsov** [comment]
Inside of this repo it's definitely suitable for re-use since it will be compile-time enforced that refactors won't break you. Right now the biggest risks with using it are:
 - if Prow needs it to change, it will change
 - when Prow does not need fields on objects that GitHub sends, it does not deserialize them and they are therefore ignored

If you're in the repo, the first issue is nullified since you will be refactored as well to continue to compile. If you hit the second issue, please just feel free to add the fields you need to the objects we have.

**Comment by chases2** [comment]
Fix has been merged; closing
/close
