### ISSUE TITLE
Use testgrid annotations instead of updating config.yaml

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#13057]
**What should be cleaned up or changed**:
The testgrid configurator can now read prowjob annotations to create test groups (ref: https://github.com/kubernetes/test-infra/pull/12576), which was used to simplify the creation of configs for release jobs and dashboards (https://github.com/kubernetes/test-infra/pull/12608)

We should ensure this is documented.  Then we should encourage more people to use these annotations instead of updating testgrid/config.yaml.  One way we could do this is by setting the example and moving much of the existing config out of config.yaml.  Perhaps piece by piece, maybe in an automated manner, etc.

**Provide any links for context**:

/sig testing
/help
/area jobs
/area testgrid

**Comment by chases2** [comment]
I'm going to do some research into this and am looking to deliver two things:
1) 1+ PRs that move configuration out of config.yaml when it's not needed 
2) A modification to Prow Job documentation that makes it clear what these annotations are, and why they are good

/assign

**Comment by chases2** [comment]
Item 2 has been delivered. Item 1 is in progress.
In addition, I'd like to 3) write a test that will detect future tabs that could be annotated.

We also need to take into account the recent [expansion](https://github.com/kubernetes/test-infra/commit/6246b079652edcc8530c16c7ae34e469be155da0#diff-5feab98ac486cd3f18bbce6e5c0d28a5) to what's annotatable.

/remove-help

**Comment by chases2** [comment]
With the addition of the manual migration PR and the Prow-Job-Detecting test, I think the issue is very close to resolved.

I'd like to get the Prow-Job-Detecting test in so that it can, eventually, be upgraded into a check that requires annotations where possible. Other than this one nice-to-have, the issue is as resolved as I can get it.

**Comment by chases2** [comment]
As mentioned in #13312, there are currently only 60 prow jobs that don't use annotations, and that's primarily due to special configurations.

Between these improvements and sharding the Testgrid Configurations (#13541), I don't anticipate this becoming an issue again in the near future. If it does, many of these tools can be reused to handle it.

/close
