### ISSUE TITLE
k8s-ci-robot requested review from non-OWNERS

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/test-infra#13291]
**What happened**: On a PR made to https://github.com/kubernetes-sigs/krew repository, @k8s-ci-robot has requested review from irrelevant 
https://github.com/kubernetes-sigs/krew/pull/235#event-2452859941

> @k8s-ci-robot k8s-ci-robot requested review from `krousey` and `thockin` 4 hours ago

Neither of these are in the OWNERS for this repo:
- https://github.com/kubernetes-sigs/krew/blob/82a267d/OWNERS
- https://github.com/kubernetes-sigs/krew/blob/82a267d/OWNERS_ALIASES

**What you expected to happen**: Choose from the OWNERS on this repo.

**How to reproduce it (as minimally and precisely as possible)**: Not sure

**Please provide links to example occurrences, if any**: https://github.com/kubernetes-sigs/krew/pull/235#event-2452859941

**Comment by nikhita** [comment]
My very raw guess is that it's requesting reviews from `krousey` and `thockin` because it touches this OWNERS file: https://github.com/kubernetes-sigs/krew/pull/235/files?file-filters%5B%5D=No+extension#diff-4a6df383843b81c52f1fb38439b8754b

i.e. we are removing files that are touching this OWNERS file.

https://github.com/kubernetes/test-infra/pull/12460 should help (I'll address the review comments today)

**Comment by ahmetb** [comment]
Yeah that totally explains it, thanks.

**Comment by nikhita** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/12460. Tested in https://github.com/kubernetes/kubernetes/pull/80396.

/close
