### ISSUE TITLE
Pipeline - Fail to reconcile prowjobs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#13404]
```
failed to reconcile default/test-pods/44a2bb86-a402-11e9-a91c-4e77ce7c1900: get pipelinerun default/test-pods/44a2bb86-a402-11e9-a91c-4e77ce7c1900: no cluster configuration found for default context "default"
```

also the log probably should have a component field?

/cc @cjwagner

**Comment by cjwagner** [comment]
There are a number of issues with the current state of the pipeline controller that make it unusable. I think I've addressed the critically blocking ones here except for PipelineResource garbage collection which I'll do in a follow up: https://github.com/kubernetes/test-infra/pull/13114

I'd like to get that in before debugging more since it makes a lot of fixes.

**Comment by krzyzacy** [comment]
Thanks for the info Cole - I just saw these errors after the bump, might as well let you know here.
