### ISSUE TITLE
Modify invalidcommitmsg plugin to disallow issue refs

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#13438]
**What should be cleaned up or changed**:
It's possible to include an issue number to an issue you're referencing or addressing. In other workflows that's a best practice, but with the number of rebases and force-pushes that occur in refining our code, it's easy to make an issue look like this:

![image](https://user-images.githubusercontent.com/1386266/61162896-91014880-a4bf-11e9-8b07-889367b92fa9.png)

It would be great if the kind robots stopped me from accidentally flooding issues with references

**Comment by spiffxp** [comment]
/good-first-issue

This would involve changing code in https://github.com/kubernetes/test-infra/tree/master/prow/plugins/invalidcommitmsg

**Comment by spiffxp** [comment]
One caveat: before rolling this out, we would want to ensure an announcement is sent out to kuberentes-dev@

**Comment by nikhita** [comment]
/sig contributor-experience

I sometimes find it useful to reference issue numbers in commit messages for context. It might also prove helpful while doing a `git bisect` or just going through commit history.

Are there lots of cases where we see this spam? I'm not entirely sure that the spam outweighs the benefits around additional context...

cc @cblecker @tpepper

**Comment by tpepper** [comment]
IMO philosophically a change control system's history is best when its commit messages include sufficient detail to understand what is being done and why, without additional context beyond that present in the repo.

Multiple sources of truth generally complicates life.

But that said, we do actually have multiple sources today with a heavy bias to information being only available in GitHub.  With that k8s project operational context it's a bit sad to punish somebody who actually chooses to give the additional connection of "Fixes #XXXXX".

So where _should_ that linkage exist if we want to capture it?  Today since most commits do not include an issue number, the best practice for somebody doing archeology against k8s repos and trying to jump off to all of the massive artifact history in GitHub is to look at commits' parent merge commits, which are autogenerated and include structured, consistent references to GitHub.  From there you get a variety of other conversation and associated PR and Issue links.

So I can see prohibiting issue refs in commits as being an acceptable tradeoff, leveraging the PR infrastructure and linkages instead.

I also wonder if this might better be solved as a generic feature request to GitHub.  On large projects which have thousands of forks, the type of flooding described here could be a general problem.  A UI preference setting to auto-hide such references from forks (still show them from mainline?) could be broadly applicable to GitHub's users.

**Comment by spiffxp** [comment]
If the commit message contains `foo/bar#123` github will link it.  If the commit message contains `https://github.com/foo/bar/issues/123` github will not link it.

I'm fine walking away from this if I'm the only who has feelings about it.  I couldn't find a quick way to survey how often rebase-spam happens.  Across the org people definitely use the short refs more often.

eg:
```
spiffxp@spiffxp-macbookpro:test-infra (master)$ git log --no-merges | grep issues/ | wc -l
      96
spiffxp@spiffxp-macbookpro:test-infra (master)$ git log --no-merges | grep '#[0-9]' | wc -l
     656
```

**Comment by cblecker** [comment]
Yeah, I'm a -1 on this. We disallow closes in commit messages because of the bad UX of having unintentional closing over and over again. It's "loud", but I think it would be overly restrictive. And it doesn't prevent non-kubernetes repos from doing the same thing.

**Comment by spiffxp** [comment]
/close
Sounds good, I will learn to deal with it
