### ISSUE TITLE
Tackle does not build in Bazel.

### ISSUE THREAD

**Issue by jeremyje** [kubernetes/test-infra#13495]
**What happened**:

```bash
git clone https://github.com/kubernetes/test-infra.git
bazel run //prow/cmd/tackle                                                                                                                                                           
Starting local Bazel server and connecting to it...
ERROR: Failed to load Starlark extension '@npm_bazel_typescript//:index.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @npm_bazel_typescript
This could either mean you have to add the '@npm_bazel_typescript' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 12.630s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by spiffxp** [comment]
/assign @fejta 
please assign to someone else if you don't have time to look at this

**Comment by clarketm** [comment]
@jeremyje - was this `bazel` build/run issue continual or did you only get this error on the first invocation?

Also, what is your machine hardware (e.g. Mac or Linux)?

**Comment by oxddr** [comment]
I was about to write that I was affected by this issues yesterday too, but now it seems to be working fine. 

I think the bug was caused by an older version of bazel on my mac. I've reinstalled it yesterday from brew using official bazel tap, but the bazel-server was running an older version up until this morning, when the bazel server restarted and picked a new version.

**Comment by clarketm** [comment]
@oxddr - What was the *old* version # of bazel that you were using?

**Comment by spiffxp** [comment]
/area prow
(may need a tackle label)

I'm inclined to suggest we call this closed unless it's still a problem, but knowing the bazel version would be a useful datapoint

**Comment by oxddr** [comment]
> janluk - What was the _old_ version # of bazel that you were using?

The new one was 0.28.1 definitely. According to [brew formula](https://formulae.brew.sh/formula/bazel) the *old* version was also 0.28.1, but I can't confirm it now. For some reason an [official documentation](https://docs.bazel.build/versions/master/install-os-x.html#step-2-install-the-bazel-homebrew-package) suggest to not use the package from brew core. It could be something related to they way it's compiled or configured (I was actually able to make some progress by passing some experimental flags, when I hit the issue and try to debug it). 

However since the problem solved itself and I don't think it's worth spending more time on it.

**Comment by clarketm** [comment]
/shrug

If the versions are the same, then it may in fact be how `bazel` is compiled or configured. I am not convinced that this is specific to tackle in anyway but rather a general build issue with an external rule, how WORKSPACE is used, or system-independent compilation. 

I suggest we close this if it cannot be reproduced and the problem is no longer being experienced.

**Comment by spiffxp** [comment]
/close
closing per above
