### ISSUE TITLE
shard testgrid config

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#13541]
**What should be cleaned up or changed**:
Similar to how we have sharded up job configs by owning SIG to enable better self-service, let's shard up testgrid configs by owning SIG.

**Provide any links for context**:
Work has already started on this, linking relevant PR's:
- https://github.com/kubernetes/test-infra/pull/13472 (initial impl)
- https://github.com/kubernetes/test-infra/pull/13530 (revert)
- https://github.com/kubernetes/test-infra/pull/13539 (bugfix)

/area testgrid
/area config
/milestone v1.16
/priority important-soon
/assign @chases2

**Comment by chases2** [comment]
Our current system is now configured to take a directory tree at /config/testgrids, allowing us to split these files into any number of arbitrary, smaller files.

For the sake of example, I plan to split "sig-testing" stuff out into its own directory, but there isn't a great metric for if this file is "sharded" enough to be easy or good yet.

Unless there's objection, after I shard out at least one file, I plan to close this issue.

**Comment by chases2** [comment]
What goes where is going to vary by SIG, so we'll need to get them involved in the process.

/help-wanted

Sharding for a SIG can be done similarly to #13609: 
1. Remove the appropriate Dashboard Groups and Dashboards from the central file
2. Put them in any file in the /config/testgrids directory tree. Subdirectories are fine, and encouraged in moderation, since OWNERS files can be nested in this way.

**Comment by chases2** [comment]
What goes where is going to vary by SIG, so we'll need to get them involved in the process.

Sharding for a SIG can be done similarly to #13609: 
1. Remove the appropriate Dashboard Groups and Dashboards from the central file
2. Put them in any file in the /config/testgrids directory tree. Subdirectories are fine, and encouraged in moderation, since OWNERS files can be nested in this way.

/help

**Comment by spiffxp** [comment]
I've attempted to model what sharding to sig-owned dirs would look like, using the sig-testing and sig-contribex testgrids: https://github.com/kubernetes/test-infra/pull/13720
