### ISSUE TITLE
Grafana "API Token saved: Last hour" breaks if range is > 24 hours

### ISSUE THREAD

**Issue by tehcyx** [kubernetes/test-infra#13651]
**What happened**:
Going to the GitHub Cache dashboard: https://monitoring.prow.k8s.io/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1&from=now-3h&to=now&refresh=1m

Right now it shows for me 2417 tokens saved. If I change the range to "Last 24 hours" it will still show this, but if I change it to "Today" it breaks. Same with everything greater than 24 hours.

**What you expected to happen**:
Should still show 2417 tokens saved for the last hour no matter if I go back a year or 25 hours.

**How to reproduce it (as minimally and precisely as possible)**:
Click on this link: https://monitoring.prow.k8s.io/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1&from=now-3h&to=now&refresh=1m
Change time range to e.g. "Today".

**Please provide links to example occurrences, if any**:
https://monitoring.prow.k8s.io/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1&from=now%2Fw&to=now%2Fw&refresh=1m

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/917785/62022544-b198f600-b181-11e9-81da-e0f129a6c54e.png)

pinging @stevekuznetsov @hongkailiu

**Comment by hongkailiu** [comment]
@tehcyx thanks for report.
after some simple testing, i feel it could be related to `instant=true`

https://github.com/kubernetes/test-infra/blob/b8a4d156128df3747e25e1590f47ec010e5ef9a5/prow/cluster/monitoring/mixins/grafana_dashboards/ghproxy.jsonnet#L138

But i cannot explain why the last one (API Tokens Saved: last 7 days) works more often (which also have `instant=true`.

I will test more.

**Comment by tehcyx** [comment]
It seems weird to me, that the numbers in the "last 7 days" column are so different in your samples. Maybe that's a starting point?

**Comment by hongkailiu** [comment]
just for my own record (still not able to answer your Qs ^_^), piling up some googling results:

https://stackoverflow.com/questions/51728031/what-does-the-instant-checkbox-in-grafana-graphs-based-on-prometheus-do/51729483#51729483

https://github.com/grafana/grafana/pull/9186/files

**Comment by hongkailiu** [comment]
Let me show my understanding of the query API (instance or not) and the time range by the following table (data from our own monitoring stack where it is easier for me to debug).

|            | last hour (in.=t) | last 7 days (in.=t) | last hour (in.=f) | last 7 days (in.=f) |
|------------|-------------------|---------------------|-------------------|---------------------|
| today      | N/A               | 915 K               | 356               | 915 K               |
| this week  | N/A               | 247 K               | 5.52 K            | 247 K               |
| this month | N/A               | 663 K               | 5.52 K            | 685 K               |
| this year  | N/A               | N/A                 | 5.16 K            | 3.30 K              |
| today sf   | 5.70 K            | 927 K               | 5.69 K            | 929 K               |
| month sf   | 5.71 K            | 927 K               | 5.52 K            | 929 K               |
| month sf   | 5.71 K            | 928 K               | 5.52 K            | 929 K               |
| year sf    | 5.71 K            | 927 K               | 5.16 K            | 890 K               |

time range: eg, week
this week: `start` `2019-07-28T00:00:00` to `end` `2019-08-03T23:59:59`
this week so far: `start` `2019-07-28T00:00:00` to `end` `now`

our queries:
```
sum(increase(ghcache_responses{mode=~"COALESCED|REVALIDATED"}[1h]))
sum(increase(ghcache_responses{mode=~"COALESCED|REVALIDATED"}[7d]))
```

if `instant=true`, then the query api is `/api/v1/query` (with time=`end`); otherwise `/api/v1/query_range` (with `start` and `end`)
https://prometheus.io/docs/prometheus/latest/querying/api/
https://github.com/grafana/grafana/pull/9186/files

[Singlestat Panel shows the last value in the series. If the series ends on null the previous value will be used.](https://grafana.com/docs/features/panels/singlestat/)
instant=false: `query_range` returns a series of values and grafana chooses the last non-null one.
instant=true: `query` returns only 1 value at time point `end`. N/A means no data at that time point.

My 2 cents:
* for our queries, it makes sense only for `so-far` time ranges. Our goal is to check the increase of the counter `ghcache_responses{...}` in the last `1h` or `7d`. The last hour of 7 days counts from now. If it counts from a future time point, the value does not tell much because the data for the future have not been sampled yet. If this explanation is accepted, then the value of `instant` does not matter that much (last 4 rows in the table, but still i cannot explain 927K vs 890K above). I cannot tell why they are not identical. From [this thread](https://stackoverflow.com/questions/51728031/what-does-the-instant-checkbox-in-grafana-graphs-based-on-prometheus-do), i got the impression that they should.
* Results when `instant=true` are less misleading because in the return of `increase` function the last point would be at a future time point (eg, 356 in above table) in case that `instance=false`. `N/A` tells us that our current time range is not valid for that query in case that `instance=true`.

**Comment by hongkailiu** [comment]
>  I cannot tell why they are not identical. From this thread, i got the impression that they should.

```
$ curl "localhost:9090/api/v1/query_range?query=sum(increase(ghcache_responses%7Bmode%3D~%22COALESCED%7CREVALIDATED%22%7D%5B1h%5D))&start=1564450859.469&end=1564454459.469&step=14"               
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":...
[1564454443.469,"5729.747899159664"],[1564454457.469,"5719.662263399927"]]}]}}

$ curl "localhost:9090/api/v1/query?query=sum(increase(ghcache_responses%7Bmode%3D~%22COALESCED%7CREVALIDATED%22%7D%5B1h%5D))&time=1564454459.469"
{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1564454459.469,"5719.662263399927"]}]}}
```

Yes, they should. My guess is when I did the tests manually i was not fast enough. `now` is different when I execute the queries.

**Comment by hongkailiu** [comment]
Closing.

@tehcyx
Please reopen if you still have concerns.
