### ISSUE TITLE
pull-kubernetes-{dependencies,verify} shouldn't be manually forked

### ISSUE THREAD

**Issue by nikhita** [kubernetes/test-infra#13886]
Ref: https://github.com/kubernetes/test-infra/pull/13723#issuecomment-517158167

See https://github.com/kubernetes/test-infra/pull/13672 and https://github.com/kubernetes/test-infra/pull/13885 where the jobs are being added manually per-release. Instead, this should be automatically handled by config-forker and shouldn't need manual update.

/cc @Katharine

**Comment by cblecker** [comment]
Why didn't `fork-per-release: "true"` work?

**Comment by cblecker** [comment]
/remove-help
/assign @Katharine 

Would you be able to help us shed light on why the config forker didn't work? I thought I added the right annotation in #13672

**Comment by justaugustus** [comment]
Copying this over from https://github.com/kubernetes/test-infra/pull/13885#pullrequestreview-274663325:

- Do we need these jobs for all active release branches i.e., do we need to add release-{1.14,1.13} versions?
- Should the job names be different per branch e.g., pull-kubernetes-dependencies-[release-{1.16,1.15,1.14,1.13|beta,stable{1,2,3}]?
- What dashboards do/should these jobs appear on?

**Comment by nikhita** [comment]
> Do we need these jobs for all active release branches i.e., do we need to add release-{1.14,1.13} versions?

We need it for all active releases, and we have them for 1.14 and 1.13 today:

https://github.com/kubernetes/test-infra/blob/89e6e9743b74a646ca883c21a127773e8eb35e7d/config/jobs/kubernetes/sig-testing/dependencies.yaml#L88

and

https://github.com/kubernetes/test-infra/blob/89e6e9743b74a646ca883c21a127773e8eb35e7d/config/jobs/kubernetes/sig-testing/verify.yaml#L77-L81 and for 1.13, etc below that


> Should the job names be different per branch e.g., pull-kubernetes-dependencies-[release-{1.16,1.15,1.14,1.13|beta,stable{1,2,3}]?

Since these are presubmits, I _think_ it's fine to let them have the same name.

> What dashboards do/should these jobs appear on?

Hmm, good question! Right now it exists here https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-verify, https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-dependencies and https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-godeps, but I'm not entirely sure if it should exist somewhere else as well (per-release dashboard?)...

cc @kubernetes/patch-release-team

**Comment by justaugustus** [comment]
Okay, so it sounds like:
- We need to make sure the SIG Testing release branch presubmits target all active release branches e.g., https://github.com/kubernetes/test-infra/blob/89e6e9743b74a646ca883c21a127773e8eb35e7d/config/jobs/kubernetes/sig-testing/dependencies.yaml#L88-L96 targets some stale/dead release branches
- Crucial release branch presubmits are captured on a SIG Release dashboard (maybe `sig-release-kubernetes-presubmits`) and notify someone (release-managers@kubernetes.io + SIG Testing)

**Comment by justaugustus** [comment]
/assign
(to keep track of the SIG Release bits)

cc: @kubernetes/release-engineering

**Comment by cblecker** [comment]
pull-kubernetes-godeps and pull-kubernetes-dependencies provide equivalent coverage, but one is for godep based branches, and the other is for go mod based branches. Every active branch should be covered by one or the other.

**Comment by Katharine** [comment]
> Would you be able to help us shed light on why the config forker didn't work? I thought I added the right annotation in #13672

Excellent question - I don't see why it wouldn't. I actually tried running it locally, and it _does_ fork that job. 

Are we sure the job configuration used in forking was up to date?

**Comment by justaugustus** [comment]
@Katharine -- when I initially ran it, it did create the job, but they seemed to conflict with other jobs, so I stripped them.

If you run locally and then run the configurator test, it should error out.

**Comment by Katharine** [comment]
Ahh, interesting. I'm not sure why it does that, either. Hmmmmm...

**Comment by Katharine** [comment]
Got it - the config forker is working fine.

The testgrid configurator has a behaviour in which it complains if it tries to create a duplicate testgroup based on a prowjob annotation that explicitly requests a prowjob be created.

 Because all our presubmit branch jobs have the same names and so end up in the same place in GCS (despite being different jobs testing different things), they count as duplicates for this purpose. The issue didn't previously exist, but was created during an automated bulk migration from explicit to automatic testgrid configuration.

Almost all jobs either do not explicitly specify the flag (`testgrid-create-test-group: "true"`), or do not get duplicate. This one, however, hits that problem and gets stuck.

The solution is probably to make the forker just drop testgrid annotations on presubmits that aren't being renamed (and so will have duplicates) - their effects will be surprising even if we make it not an error.

**Comment by Katharine** [comment]
I've made the above change in #13911, which I think should cause the existing fork annotation to function as expected.

We may also want to go back and drop testgrid annotations in presubmits on existing forked jobs, since they are definitely doing nothing useful and may be doing something surprising.

**Comment by justaugustus** [comment]
I think we've solved for this in recent releases, but I'm going to freeze it so we can look into it and properly close the loop.

/lifecycle frozen
/remove-lifecycle stale

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/17179 should close this out
