### ISSUE TITLE
Deck plugin config validation fails

### ISSUE THREAD

**Issue by mirandachrist** [kubernetes/test-infra#13951]
In order to reuse /test logic for presubmit reruns from the frontend (see #13321), deck needs access to the plugin config. Currently, it throws a fatal error on validation because we don't import all the plugins. We either need to avoid doing this specific validation in deck, import the plugins, or find some other solution.

**Comment by stevekuznetsov** [comment]
Yeah in general I think we need to snip dependencies so that importing the config loading or types packages for our (plugin or otherwise) config does not pull in the entire world.

**Comment by cjwagner** [comment]
The options I can think of are:
- Hard code a list of valid plugin names into the `plugins` package so that it can still do validation without actually registering all the plugins themselves.
- Make that part of the validation optional and only check if all the plugin names are valid in `hook` where we register all the plugins.

**Comment by stevekuznetsov** [comment]
I think the latter makes sense -- validating that users have put down valid plugin names is the domain of `checkconfig` and `hook`, not others. Downstream dependencies that want to load and use the plugin types don't really need to validate that.
