### ISSUE TITLE
Need help finding job definitions/details under new schema

### ISSUE THREAD

**Issue by jberkus** [kubernetes/test-infra#14018]
**What should be cleaned up or changed**:

The new schema is a leap forward for both operations and avoding merge conflicts.  However, it can be a little hard to figure out exactly where the details of a particular job live, starting from testgrid.k8s.io.  It would be nice to have some breadcrumbs or other clues as to how to find the configs, which can be in any of multiple locations.

As an example, here's two questions I was just trying to answer and was unable to.  It may be that sig-release dashboards are a special case here and just need to be treated specially.

1. Trying to determine if the ci-kubernetes-e2e-gce-cos-k8sbeta-reboot test job on the sig-release dashboards has a defined owner's email, and which team that owner is, so that I can see if it belongs in Blocking or not.

2. Looking up the list of all tests that are supposed to be run by https://testgrid.k8s.io/sig-release-orphaned#gce-new-master-upgrade-cluster, given that it's not actually running them due to timeouts, and compare that list with the list of tests run by https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-15-master

**Provide any links for context**:

attn: @Katharine

**Comment by michelle192837** [comment]
From me from Slack:
I'll note that this is going to be non-trivial from the TestGrid side, since TestGrid doesn't know about Prow jobs or .yaml files, just the resulting config.proto

i.e. if it shows up in TestGrid, it'll probably need to be via some config-defined link or something
(Though that COULD be added in the description or about dashboard link)

**Comment by Katharine** [comment]
We have a policy that says that release-blocking jobs need an owner and email associated with them. However, the owner gets lost when a job is forked because we discard the description (I don't remember why I did this - because they'd tend to be misleading, I think?). So no branched job has this information attached to it.

Additionally, there is not necessarily an easy way to reverse from a branched job to the original, because we mangle the name in ways that require some thought before you know what to search for. We can mitigate that by including the original job name as metadata in the forked prowjob yaml.

For these specific jobs (the `ci-kubernetes-[platform]-[runtime]-[version]-test` ones), they're actually completely autogenerated, making the real ownership even fuzzier. I don't know how you would figure them out. I do think most of them are at this point considered to be deprecated...

**Comment by neolit123** [comment]
> However, it can be a little hard to figure out exactly where the details of a particular job live

potentially this page can include a URL called "Find job":
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-15-master/1164516821852753920

which can link to:
https://github.com/kubernetes/test-infra/search?q=ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-15-master+language:yaml

the search query is in the form of:
```
https://github.com/kubernetes/test-infra/search?q=<JOB_ID>+language:yaml
```

**Comment by justaugustus** [comment]
/remove-lifecycle rotten
/lifecycle frozen
/reopen

This is definitely still valid.
@kubernetes/ci-signal -- Let's keep this in mind for the cycle.

/assign @droslean

**Comment by spiffxp** [comment]
/close
Testgrid descriptions automatically have the test name and a URI to the job config as of 2021-02-12: https://github.com/kubernetes/test-infra/pull/20844
