### ISSUE TITLE
Prioritize PRs in Merge Queue by approval timestamp not PR number

### ISSUE THREAD

**Issue by klueska** [kubernetes/test-infra#14134]
**What would you like to be added**:
Would it be possible to prioritize PRs included in batch merges by their approval timestamp rather than their PR number?

It seems like it would be a fairly straightforward change to make, given the existence of the `createdAt()` API for github labels:
https://developer.github.com/v4/object/label/

**Why is this needed**:
As code freezes approach, many (often older) PRs start to get approved right near the deadline. This displaces newer, already-approved PRs that made it into the merge queue before the older PRs, but have not been merged yet.

In at least one instance I had to wait 4 days for my PR to get merged because lower numbered PRs kept bumping my PRs place in the merge queue. The displaced PR was a dependency for another PR, which never made it into the release because it could not be approved until the displaced PR got merged.

**Comment by stevekuznetsov** [comment]
Why is approval time a better metric for ordering than code creation time? In theory, the batches should be large enough and successful enough that ordering does not matter. I think I would personally prefer to focus efforts on improving merge throughput to get to that place. We don't need to stick to 5-PR batches, either. Larger should be fine.

/area prow/tide
/cc @cjwagner

**Comment by klueska** [comment]
I think approval time is a better metric than code creation time because approval time marks the time when the PR enters the merge pool. The difference between `now` and `approval time` is the wait time in the queue.

It seems more intuitive for me to prioritize PRs that have been waiting longer in the queue over PRs that may have just been added to the queue, but happen to have a lower PR number.

**Comment by Katharine** [comment]
I agree that approval time is a better metric than PR creation time. It is deeply frustrating if you create a PR that gets approved quickly but you are stuck in the pool for _days_ because a) the merge rate is incredibly awful, and b) PRs that were approved after yours keep jumping yours in the queue.

It shouldn't be possible for a PR to be waiting to merge for days (this is certainly not the only case!) and we need to ensure that this does not keep happening.

**Comment by cjwagner** [comment]
Tide intentionally avoids prioritizing PRs based on variables that can change after entering the queue because that causes the queue to be reorder more frequently which negatively impacts the merge rate. This is one of the problems that the submit queue had.

"Last approval time" could change and may be expensive to determine for all PRs, but that might be acceptable given how useful it would be. I think `priority/*` labels were the primary cause of queue thrashing with the submit queue anyways.
I don't think the `createdAt` API you mentioned tells us when the label was added to a PR, I suspect it is actually the time the label itself was created. I could be wrong about that though. We also actually want to be determining when the PR first enters the tide pool, not when the approval label is applied. That means we need to consider the configured merge requirements for each Tide query that matches the PRs repo so we can take into account things like the `lgtm` label, `do-not-merge/*` labels, and passing tests the first time.

**Comment by cjwagner** [comment]
If we're ok with storing some more persistent state this is pretty easy and cheap to solve I think.

**Comment by stevekuznetsov** [comment]
It looks like the longest test for `k/k` running in a batch takes [~1h45m](https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=batch).

If we have successful batches, that should be ~14 batches a day and ~70 merged PRs in a day. Today, we see about [~25](https://monitoring.prow.k8s.io/d/d69a91f76d8110d3e72885ee5ce8038e/tide-dashboard?orgId=1&fullscreen&panelId=3) per day. I think increasing batch size to 10 or 20 or improving the pass rate of batches will fix this in a more meaningful way than re-odering the queue/

**Comment by stevekuznetsov** [comment]
(There's nothing special about 5 as the size of a batch. Collisions between batch candidates is really, really, rare and I don't think we'd see negative effects from quadrupling batch size)

**Comment by klueska** [comment]
I agree that an increased batch size would likely make it so this "jump ahead" problem would become unnoticable. As it stands today though, it is a real issue (I'm still waiting for a PR to merge that was approved 4 days ago because it keeps losing its place in line).

**Comment by stevekuznetsov** [comment]
I think there's an argument to be made (and I have heard it made) that ordering by PR number makes sense as well from a principled point of view: work that has been iterated on longer and taken longer to validate should not get edged out by new PRs flying through quickly. 

In any case I think we should focus on making batches better and increasing the merge throughput, instead of splitting hairs on ordering, as this is specifically not supposed to be something `tide` worries about. If we can increase the merge throughput with a two-character change to the batch size, I'd much prefer that.

**Comment by klueska** [comment]
> I think there's an argument to be made (and I have heard it made) that ordering by PR number makes sense as well from a principled point of view: work that has been iterated on longer and taken longer to validate should not get edged out by new PRs flying through quickly.

Yes. Except when you create a new PR to address an issue that your really old PR now depends on.

Anyway, I'm all in favor of seeing how an increased batch size will affect things. It may likely be that the percieved issue disappears.
