### ISSUE TITLE
AWS janitor: Impossible to configure to clean all regions

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#14318]
**What happened**:

The AWS janitor cleans all regions if the configured `region` is empty: https://github.com/kubernetes/test-infra/blob/1f6f51be4661fda50c9cd144ec405e4eae7ee068/maintenance/aws-janitor/resources/clean.go#L37
However its impossible to configure an empty region because if done so, it gets defaulted to `us-east-1`: https://github.com/kubernetes/test-infra/blob/1f6f51be4661fda50c9cd144ec405e4eae7ee068/maintenance/aws-janitor/regions/regions.go#L31

**What you expected to happen**:

Be able to set up the AWS janitor to clean all regions

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/CC @liztio

**Comment by ixdy** [comment]
@alvaroaleman I'm having trouble understanding the issue here.

`regions.Default` does default to `us-east-1`, but it isn't used when cleaning up; it's only used to get the account:
https://github.com/kubernetes/test-infra/blob/ef445ba16d8066ef91dfe69ea2561afba9221372/boskos/aws-janitor/resources/clean.go#L35

`CleanAll` instead takes a parameter indicating what region to clean:
https://github.com/kubernetes/test-infra/blob/ef445ba16d8066ef91dfe69ea2561afba9221372/boskos/aws-janitor/resources/clean.go#L34

and if it's empty, it cleans all regions:
https://github.com/kubernetes/test-infra/blob/ef445ba16d8066ef91dfe69ea2561afba9221372/boskos/aws-janitor/resources/clean.go#L42-L50

`CleanAll` is called from main.go:
https://github.com/kubernetes/test-infra/blob/ef445ba16d8066ef91dfe69ea2561afba9221372/boskos/aws-janitor/main.go#L52-L55

The region flag defaults to empty string (clean all regions):
https://github.com/kubernetes/test-infra/blob/ef445ba16d8066ef91dfe69ea2561afba9221372/boskos/aws-janitor/main.go#L35

The default for the `cleanAll` flag is false, but it looks like the alternate path (which calls `markAndSweep`) has similar logic for checking all regions.

**Comment by alvaroaleman** [comment]
Hm you are right, seems I misread the code when I looked into this.

Thank you for investigating!
