### ISSUE TITLE
gazelle spam from testgrid

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14446]
/assign @michelle192837 @chases2 @fejta 
/area testgrid

```console
gazelle: rule @gcp_testgrid//cmd/summarizer:go_default_test imports "github.com/GoogleCloudPlatform/testgrid/cmd/summarizer/response" which matches multiple rules: @gcp_testgrid//cmd/summarizer/response:go_default_library and @gcp_testgrid//cmd/summarizer/response:response_go_proto. # gazelle:resolve may be used to disambiguate
````

**Comment by chases2** [comment]
Is this still occuring? What command produces this output?

**Comment by michelle192837** [comment]
I don't _think_ this is an issue anymore, though can't remember the command to reproduce and can't verify (via running update scripts and doing 'bazel build ...'). Going to close for now since changes were made to proto import paths/build files that likely affected this, will reopen if there's a way to reproduce.
