### ISSUE TITLE
Prow issue: Missing CLA

### ISSUE THREAD

**Issue by ronaldpetty** [kubernetes/test-infra#1448]
Hello,

I did a PR and signed the CLA, however it seems to just be sitting around.

https://github.com/kubernetes/kubernetes.github.io/pull/2069

I have contributed before so thought I had already done this.  It did make me think, the troubleshooting says to confirm the CNCF email.  So currently my default GH email is my personal email (ronald.petty@gmail.com) however my CNCF email is (ronald.petty@minimumdistance.com).  I confirmed I have both emails in my GH account but personal is primary.  Is that something that needs to be changed? (if that is the issue.)

Happy new year.

Ron

**Comment by spxtr** [comment]
@foxish

**Comment by foxish** [comment]
@ronaldpetty, thanks for your PR. I saw that your previous PR was https://github.com/kubernetes/kubernetes.github.io/pull/979, and that was back when we were using the Google CLA. We've since moved to the CNCF CLA, which needs to be signed afresh. Did you sign the agreement as an [individual contributor/member of an org](https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ)?. If after the process, it still does not work, one can contact helpdesk@rt.linuxfoundation.org who can check what happened.

**Comment by ronaldpetty** [comment]
Hi Anirudh, have singed it anew, someone else got back in tough and said I
need to do it with the proper email.  I will try again!

Thanks.

Ron

**Comment by ronaldpetty** [comment]
For the record, changing the primary GH email and resubmitting worked.  Now
that I have experienced it, might be nice to allow multiple emails, or
simply tie to the GH (or other bedrock) user?

Keep up the good work and happy holidays!

Ron
