### ISSUE TITLE
Prow cluster monitoring - missing instructions for fresh deployment on another cluster

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#14604]
**What would you like to be added**:
Instructions for setting up deployment of monitoring on a separate cluster for a downstream org/repo, i.e. Knative

**Why is this needed**:
Current [monitoring/README](https://github.com/kubernetes/test-infra/blob/master/prow/cluster/monitoring/README.md) mentioned "The deployment has been integrated into our CI system", but not detailed steps, would be helpful to have a detailed instruction for setting this up on a separate cluster for any downstream Prow cluster, like the one used by Knative. 

It would be even better if there can be a separate instruction on how to deploy and/or add new dashboard without using `bazel`

/cc @stevekuznetsov 
/cc @hongkailiu

**Comment by stevekuznetsov** [comment]
Given that this is a package of deployments and config together, tailored to Prow, I would wonder what the benefit is to doing it without `bazel`, but in general all `bazel` does is `kubectl apply -f`. @hongkailiu can provide more detail but you should be good to just create the secrets as noted in the readme and run:

```
bazel run //prow/cluster/monitoring:production.apply
```

**Comment by hongkailiu** [comment]
Since prow.k8s.io is deployed by bazel, we follow the same way here for monitoring stack:

https://github.com/kubernetes/test-infra/blob/201c7788b244ab2fc3efae7249fb939223ef6e1e/prow/deploy.sh#L91-L92

The above two lines does most of parts (you can dig into the bazel rules for details) except the secrets whose `yaml`s are also included in the [prow/cluster/monitoring](https://github.com/kubernetes/test-infra/tree/master/prow/cluster/monitoring). You need to edit/apply them manually, eg,

https://github.com/kubernetes/test-infra/blob/201c7788b244ab2fc3efae7249fb939223ef6e1e/prow/cluster/monitoring/grafana_secret.yaml#L9-L10

Personally, I would recommend `kubectl apply -f` for easy debugging unless you are a big fan of `bazel`. :)

Some is specific to the cloud provider of your k8s cluster, you might need to adjust accordingly, e.g.,

https://github.com/kubernetes/test-infra/blob/201c7788b244ab2fc3efae7249fb939223ef6e1e/prow/cluster/monitoring/grafana_expose.yaml#L26-L30

**Comment by hongkailiu** [comment]
https://github.com/kubernetes/test-infra/pull/14610

**Comment by chaodaiG** [comment]
Thanks @stevekuznetsov and @hongkailiu  for looking into this. 
FYI @cjwagner

**Comment by stevekuznetsov** [comment]
The related PR closed and no more questions came in,

/close
