### ISSUE TITLE
Bazel builds fail with python 3.7 becase pylint==1.9.5 has python<3.7 dependency

### ISSUE THREAD

**Issue by petr-muller** [kubernetes/test-infra#14654]
**What happened**:
```
$ bazel build //prow/cmd/hook # but basically any bazel run
...
No matching distribution found for pylint==1.9.5 (from -r /home/afri/Projects/RH/go/src/k8s.io/test-infra/requirements.txt (line 16)
$ python -V
Python 3.7.4
```

**What you expected to happen**:
Build to succeed

**Anything else we need to know?**:
From https://pypi.org/project/pylint/1.9.5/:
> Requires: Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <3.7

**Comment by fejta** [comment]
/assign @clarketm 

Given that 90% of the jobs now support py3, can we switch the pylint job to use this too?

**Comment by clarketm** [comment]
I have this working locally but cannot get it to work in CI #14015. I will continue to experiment.

**Comment by eisraeli** [comment]
Any updates ?

**Comment by clarketm** [comment]
Employed a fix:
https://github.com/kubernetes/test-infra/pull/14015

Then subsequently reverted: 
https://github.com/kubernetes/test-infra/pull/14853

I will rework an alternative solution and follow-up with an update.

**Comment by matthyx** [comment]
@clarketm I would like to help solving this issue... could you please update me on what was wrong with your previous attempt, and what you had in mind to fix it?
/assign

**Comment by clarketm** [comment]
@matthyx

Thanks. #14015 was reverted because it was non-hermetic and dependent on a system version of `python3` to be installed (https://github.com/kubernetes/test-infra/pull/14015#issue-309706806). 

The good news is now that https://github.com/bazelbuild/rules_python/issues/220 has been merged, **rules_python** now natively supports specifying the python interpreter using either `python_interpreter` or `pip3_import` (https://github.com/bazelbuild/rules_python/blob/master/README.md#recent-updates) in the `bazel` rule which resolves this issue once implemented.
