### ISSUE TITLE
Enable prow test users to get signedUrl of GCS bucket 

### ISSUE THREAD

**Issue by YangLu1031** [kubernetes/test-infra#14670]
**What would you like to be added**:

Add `roles/iam.serviceAccountTokenCreator` to prow test user. Or any ways to let prow test users get signedUrl of GCS bucket.

**Why is this needed**:

Currently we cannot dump GKE windows node logs after prow test, because in upstream `kubernetes/cluster/log-dump/log-dump.sh`, it uses SSH to copy the logs files out. But SSH on windows is not enabled on GKE, as it needs to be evaluated and still pending on security check.

To solve this problem, we use [diagnostics tool from GCE](https://github.com/GoogleCloudPlatform/compute-image-tools/tree/master/cli_tools/diagnostics) to dump logs to Google Cloud Storage and copy back to local target path. And this tool needs `roles/iam.serviceAccountTokenCreator` to get [signedUrl](https://cloud.google.com/storage/docs/access-control/signed-urls) of GCS bucket.

But our prow test user i.e. `pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com` doesn't have permissions to grant it for itself. This is the [PR](https://github.com/kubernetes/kubernetes/pull/83517) failed to pass the [prow test](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83517/pull-kubernetes-e2e-gce/1181276647706333187/). 
```
I1007 19:12:53.412] Dumping logs from nodes locally to '/workspace/_artifacts'
I1007 19:12:53.413] Detecting nodes in the cluster
W1007 19:13:05.077] ERROR: (gcloud.projects.add-iam-policy-binding) User [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com] does not have permission to access project [k8s-jkns-e2e-gce-gci-slow:setIamPolicy] (or it may not exist): The caller does not have permission
W1007 19:13:05.147] 2019/10/07 19:13:05 process.go:155: Step './cluster/log-dump/log-dump.sh /workspace/_artifacts' finished in 1m0.641913394s
```

**Comment by pjh** [comment]
@krzyzacy perhaps you could comment on the feasibility of this change or point us in the right direction?

My expectation is that the easiest thing to do would be to enable `roles/iam.serviceAccountTokenCreator` for the service accounts in all projects (e.g `k8s-jkns-e2e-gce-gci-slow` in the above example) that are used to run the kubernetes prow jobs, but I'm not quite sure if this is safe to do, and I'm not exactly sure if it can be done at the project level or if it needs to be done for every service account.

**Comment by pjh** [comment]
cc @yliaog

**Comment by krzyzacy** [comment]
/assign @fejta 
is this something we can grant on the k8s prow SA?

**Comment by fejta** [comment]
Please use https://github.com/kubernetes/test-infra/tree/master/logexporter and https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity to solve this problem.

AKA:
Run the log exporter on any node you want to export logs. Ensure this container's service account can write to the bucket you want to write to.

**Comment by YangLu1031** [comment]
> Please use https://github.com/kubernetes/test-infra/tree/master/logexporter and https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity to solve this problem.
> 
> AKA:
> Run the log exporter on any node you want to export logs. Ensure this container's service account can write to the bucket you want to write to.

@fejta To clarify, logexporter works only for linux node, not applicable to windows nodes. As you can see the commands and paths:
https://github.com/kubernetes/test-infra/blob/70267a4f2454906562b8e9cd722a373b658540d4/logexporter/cmd/main.go#L50

**Comment by fejta** [comment]
There are a lot of options.

I am not convinced that granting `roles/iam.serviceAccountTokenCreator` to `pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com` in all projects is the right way to solve this problem.

Some alternatives:

a) Improve logexporter such that it will work on windows
b) Prioritize getting SSH to work on windows
c) Run the diagnostic tool in a container that has the right workload identity to run the tool.

**Comment by pjh** [comment]
Thanks for the suggestions @fejta. A few clarifications and questions:

> a) Improve logexporter such that it will work on windows

Yes, we've considered porting logexporter to Windows. The biggest hurdle is that Windows containers do not have privileged access to the host, so they cannot easily copy the log files that we'd want to export. It may be possible to work around this by mounting various host directories into the logexporter container, but the `gcloud alpha compute diagnose export-logs` command already does what we want when run on the node, so we'd prefer to use it if possible.

There's also the possibility that at log-fetching time we'll want to run commands on the host to generate or transform some log files; we don't need this right now, but if we do in the future then we'll need something that runs on the Windows host and not in a container.

> b) Prioritize getting SSH to work on windows

Agreed, this is the long-term solution and the GCE team is working on this but it's not ready yet.

> c) Run the diagnostic tool in a container that has the right workload identity to run the tool.

Thanks, I reviewed the [Workload Identity page](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) that you shared. My high-level understanding (which may be wrong) is that Workload Identity lets you connect a Kubernetes service account to a GCP service account so that pods running as the former can assume the IAM roles/permissions of the latter. I have a few questions for how we'd use this to achieve what we need:

- Would we create a new GCP service account (GSA) with the `roles/iam.serviceAccountTokenCreator` role that we need, or would we add that role to some existing kubernetes/test-infra GSA?
- Does the Kubernetes SA (KSA) need to be created and linked to the GSA every time the prow test job runs, or is it possible to create and configure the KSA once and then use it for any future test job / cluster? If the KSA needs to be created and linked every time the test job runs, it feels like the linking step (step 7 in the [workload identity doc](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_workload_identity_on_a_new_cluster)) would require the GSA to have IAM permissions more expansive/troublesome than just adding `roles/iam.serviceAccountTokenCreator`, but I'm not sure about the GSA (previous question) and my understanding may be wrong.

At a high level, is there an example we could look at where someone already set up Workload Identity for their prow test job?

Thanks for your help on figuring out the best way to do this!

**Comment by YangLu1031** [comment]
Thanks @fejta, we discussed offline, since our prow tests are running on Git-on-Borg, so it's fine to add `roles/iam.serviceAccountTokenCreator` to prow test users.

Also current prow test users have `roles/iam.serviceAccountActor` which is [deprecated](https://cloud.google.com/iam/docs/service-accounts#the_service_account_actor_role), recommend to replace with `roles/iam.serviceAccountUser` + `roles/iam.serviceAccountTokenCreator`.

**Comment by fejta** [comment]
There's nothing we need to do here upstream, let's use an internal issue to track the Google-specific work
/close
