### ISSUE TITLE
bump PRs still get force pushed

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14801]
/assign @cjwagner 

Didn't you merge the thing so this doesn't happen?

https://github.com/kubernetes/test-infra/pull/14781#event-2718959646

/kind oncall-hotlist

**Comment by cjwagner** [comment]
Ah, my change only tried to update the PR if there is no `lgtm` or `approved`, but it still pushes the updated changes to the branch which causes the PR to update. We'd need to separate the "check if there is a PR to update" logic from the "EnsurePR" function if we want to handle that correctly.

IMO it is easier to just not run the autobumper every hour since we don't ever bump that frequently anyways.  I'll revert my change. If anyone else cares about this they can try to fix it the right way or decrease the update frequency.
