### ISSUE TITLE
post-test-infra-upload-testgrid-config failing

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#14888]
See https://testgrid.k8s.io/sig-testing-maintenance#testgrid-config-upload

Example: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-upload-testgrid-config/1186365177063280640

```
2019/10/21 19:38:38 FAIL: could not apply prowjob annotations: couldn't find dashboard "wg-multi-tenancy-hnc" for job "pull-hnc-test"
```

Looks like the config change introduced is #14660, going to revert that to un-fail the job. Also looks like we should check if the configurator refactor recently caused any issues.

**Comment by chases2** [comment]
`wg-multi-tenancy-hnc` appears to be legitimately missing. However, the test at [`config/tests/testgrid`](https://github.com/kubernetes/test-infra/tree/master/config/tests/testgrids) should have caught it as a presubmit.

**Comment by chases2** [comment]
Bazel thinks that only files that end in `.yaml` are part of the Prow config. [src](https://github.com/kubernetes/test-infra/blob/b5562fcd6e375d553e267060abef265843615e1c/config/BUILD.bazel#L21-L26)
Configurator (and its test) thinks that anything that looks like yaml in that directory is part of the Prow config. [src](https://github.com/kubernetes/test-infra/blob/b5562fcd6e375d553e267060abef265843615e1c/prow/config/config.go#L726)

First commit: #14660: Adds a `.yml` file to prow config
The Prow config isn't regenerated, because according to Bazel, nothing changed. A valid, but old, configuration is passed to [the test](https://github.com/kubernetes/test-infra/tree/master/config/tests/testgrids) and [`testgrid-config-upload`](https://testgrid.k8s.io/sig-testing-maintenance#testgrid-config-upload) passes.

First failure: #14845: Makes any change to prow config
The Prow config is regenerated, including the invalid `yml` file. The test fails; `testgrid-config-upload` is now stuck failing.

**Comment by chases2** [comment]
It [looks like](https://testgrid.k8s.io/sig-testing-maintenance#testgrid-config-upload) the job is running again, and the root cause has been addressed.
