### ISSUE TITLE
Improve admissions controller to prevent Prow jobs with bad config from taking down Prow.

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#14925]
**What would you like to be added**:
Improve admissions controller to prevent Prow jobs with bad config from taking down Prow. Countless times, misconfigured jobs I have created have caused Prow to crash. 

**Why is this needed**:
Reduce downtime and Increase reliability.

/assign

**Comment by stevekuznetsov** [comment]
While this is valuable I do want to ask how this happens "countless times" -- are people posting YAML they wrote in an editor manually? Use `mkpj` and this does not happen -- may be nice for your deployment to not crash while the (more challenging) work is done to reject those ProwJobs.

**Comment by stevekuznetsov** [comment]
Also, depending on the version of k8s the validation available from the APIServer for CRDs may be better, should look into that before writing an admission controller.

**Comment by clarketm** [comment]
@stevekuznetsov 

> While this is valuable I do want to ask how this happens "countless times" -- are people posting YAML they wrote in an editor manually?

I would say most, if not all, of the *countless times* I am referring to are from editor mishaps (i.e. taking an existing PJ, tweaking it slightly in editor, then applying it). 

> Also, depending on the version of k8s the validation available from the APIServer for CRDs may be better, should look into that before writing an admission controller.

I was *aware* that an admission controller could assist with *validation*, but I have yet to explore other options. I will investigate alternative validation options.

**Comment by stevekuznetsov** [comment]
Yeah whoever is editing PJ YAML by hand should have their hand slapped and told to use `mkpj` ;)

**Comment by clarketm** [comment]
/remove-lifecycle stale

I have not prioritized this but will get to it when I have time.

**Comment by clarketm** [comment]
/assign @cjwagner 

He is working on a formal design document for this.

**Comment by jprzychodzen** [comment]
Adding information from #23283 

**What happened**:
I've applied on the cluster manually edited job. Plank was unable to unmarshal the object, and entered into the restart loop. It seems that CRD definition [1] is much more accepting than Go object[2].

[1] https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/starter-gcs.yaml#L153
[2] https://github.com/kubernetes/test-infra/blob/master/prow/apis/prowjobs/v1/types.go#L115

**What you expected to happen**:
Malformed prowjobs.prow.k8s.io should be validated on kube-apiserver level by appropriate CRD. If not possible, then malformed objects should be logged then ignored, instead of crashlooping Prow components.

**How to reproduce it (as minimally and precisely as possible)**:

Change field to non-matching type, for example set `spec.agent` to object `{}`. This results in error like 

```
"external/io_k8s_client_go/tools/cache/reflector.go:167: Failed to watch *v1.ProwJob: failed to list *v1.ProwJob: v1.ProwJobList.Items: []v1.ProwJob: v1.ProwJob.Spec: v1.ProwJobSpec.Agent: ReadString: expects " or n, but found {, error found in #10 byte of ...|{"agent":{},"cluster|..., bigger context ...
```

/kind bug

**Comment by alvaroaleman** [comment]
Yeah the CRD definition is basically schema free, so you can throw almost anything at the cluster which will then potentially fail unmarshaling. IMHO the solution for this issue is to generate a proper schema for the CRD, which I started in https://github.com/kubernetes/test-infra/pull/19522 but never finished

**Comment by jkaniuk** [comment]
@alvaroaleman - Is there any change for you to pick up that unfinished work? It is a pain that grows with number of custom Prow instances.

**Comment by alvaroaleman** [comment]
> @alvaroaleman - Is there any change for you to pick up that unfinished work? It is a pain that grows with number of custom Prow instances.

Updated #19522 . Main issue is the CRD is so big, it fails `kubectl apply -f` without `--server-side=true` because the annotation `kubectl` tries to add exceeds the max annotation size. If you have any thoughts forcing a cluster that can support that is ok or not, please comment them on the PR.
