### ISSUE TITLE
Question : why config-updater keeps using binaryData instead of data ?

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/test-infra#15105]
I have some yaml files in a github repository that are kept in sync with a configmap.

These yaml files are regular utf8, though the config-updater sets them in the binaryData section of the configmap instead of the data section.

Looking at the code, the only check is `utf8.ValidString(string(value))`, that should be true in  my case.

Can it be related to the way the file content is retrieved from github ?

**Comment by stevekuznetsov** [comment]
What version of `hook` are you running? Could you have set the [`gzip`](https://godoc.org/k8s.io/test-infra/prow/plugins#ConfigUpdater) option? Otherwise, as you note, the choice of data versus binary is driven by that switch:

https://github.com/kubernetes/test-infra/blob/5f21eec9b62c037f997ab80f98b70370a1be07c3/prow/plugins/updateconfig/updateconfig.go#L143-L149

**Comment by stevekuznetsov** [comment]
FWIW I have seen data correctly uploaded, so this is not ubiquitous.

**Comment by eddycharly** [comment]
Actually i was using the gzip option, i forgot to remove it after testing various config options 😱 
Now it behaves as expected, thanks !
