### ISSUE TITLE
sinker not GCing pods

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#15244]
**What happened**:
in one of our prow deployments we have a pod from november 6th that was not GCed, however we seem to have had more runs since then and it should be configured to delete PJs after 48 hours

/cc @cjwagner

**Comment by cjwagner** [comment]
ref: https://github.com/kubernetes/test-infra/pull/11641
As Sen notes at the bottom of the PR, we keep the latest ProwJob for every periodic so that we know the last time it was triggered. It sounds like this was a presubmit job so that is not the problem here, but we should probably handle terminating pods for the latest run of periodic jobs. The pod should be terminated after the max_prowjob_age has elapsed even if we need to keep the ProwJob around.

**Comment by clarketm** [comment]
> in one of our prow deployments we have a pod from november 6th that was not GCed, however we seem to have had more runs since then and it should be configured to delete PJs after 48 hours

Can you provide me a link to the logs or instance details, so that this can be investigated?
