### ISSUE TITLE
deck: logs view to render ansi colors

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/test-infra#15261]
**What would you like to be added**:

Today, the default handler for `/log` in deck just pipes the container logs. That works fine in most of cases, however the output isn't really readable if there are ansi colors decorations which most of fancy tools do. `ginkgo` for example.

I would like to propose adding a new option like `?ansi=true` so it can convert the logs into html. I find that https://github.com/buildkite/terminal-to-html might be helpful.

**Why is this needed**:

This enhances the logs view experience.

**Comment by alvaroaleman** [comment]
@zhouhaibing089 I think this already works, look e.G. here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/1789/pull-cluster-api-integration/1197948440802234372#1:build-log.txt%3A1489

Maybe the problem is that whatever is emitting these logs is disabling ANSI when there is no TTY?

**Comment by zhouhaibing089** [comment]
@alvaroaleman: It looks like spyglass(`/view/prowjob` and `/view/gcs`) does it. However the `/log` handler doesn't. I'm uncertain whether we should enhance `/log` or just go with support other storage providers or maybe we should do both.
