### ISSUE TITLE
Boskos is running out of AWS Projects

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#15649]
**What happened**:
Boskos project usage for AWS projects has been climbing for the past couple of hours, and has run out. See https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1

Tests reliant on this resource will be blocked or throttled by waiting on these projects to free up.

**What you expected to happen**:
Using every resource isn't necessarily bad, but should be monitored; if it occurs for a long period of time, it may indicate there aren't enough resources or there's an issue with cleaning the jobs properly. 

I'm assigning this to people who know about the tests in question to look into this.

/assign @ncdc @detiber

**Comment by detiber** [comment]
In this specific case, we've been testing changes to the tests and triggering quite a few manual jobs alongside the periodic and post-submit jobs, which has led to account exhaustion.

This is definitely not a "normal" situation, but we do generally run at ~50% utilization of the current AWS accounts that we have allocated currently. It might not hurt to have additional accounts created to add a bit more headroom, but it is not currently a blocking need today.

As of right now (16:32 ET on Dec 18th), it looks like we are back down to 80% utilization of the pool, and I'll hold off on triggering any additional manual jobs until it's come back down a bit further.

**Comment by detiber** [comment]
The current number of AWS accounts is sufficient for it's current normal use, but we quickly get into a situation where we easily deplete the number of available accounts if we are testing fixes for the tests that consume AWS accounts (within kubernetes-sigs/cluster-api-provider-aws).

Ideally it would also be nice to extend the use of the boskos managed accounts to the kops testing (and other testing that would need AWS accounts) vs the existing shared account that they are currently using.

With those considerations in mind, I think we should still look at increasing the number of AWS accounts managed by Boskos.

/assign @justinsb

**Comment by justinsb** [comment]
Well good news ... I sent a PR with my terrible scripts to create accounts.  I created a handful of kops AWS accounts in the new approach, but we can certainly do more of them - they aren't terribly hard now.  I'm not sure if we should share accounts between the various consumers (kops,capa etc); on the one hand it means we average out to a smaller size, on the other hand it means that we could leave something behind that breaks the other tests (but ... if we do, maybe we would just add that to boskos).

I also haven't yet figured out whether boskos supports multiple pools for items of the same type (i.e. AWS accounts).

Anyway, rip apart my PR here: https://github.com/kubernetes/k8s.io/pull/660

I actually tried to convert this to terraform, and hit a problem in that I think that account creation with impersonation is not easy in terraform.  Someone may know better.  I don't think it's the end of the world if account creation is done in bash TBH - though I already don't love the IAM permissions so that might be a good thing to split out.

Do you have an idea how big the pool for CAPA should be @detiber ?  (Assuming it isn't shared)

**Comment by detiber** [comment]
> I also haven't yet figured out whether boskos supports multiple pools for items of the same type (i.e. AWS accounts).

It should be fine as long as we call them different things (similar to how the GPU project, Ingress project and Scalability project are separate from the GCE project pools).

> Do you have an idea how big the pool for CAPA should be @detiber ? (Assuming it isn't shared)

I think doubling it to 20 should be sufficient, we generally only peak at 6 during normal usage, which only allows for 4 PR triggered jobs, which can easily be exhausted taking into account account cleaning time.

**Comment by BenTheElder** [comment]
I think this was fixed?

**Comment by detiber** [comment]
Based on looking at the chart for boskos resource utilization, there are still 10 accounts: https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1

**Comment by chases2** [comment]
There are still 10 accounts, but it seems that demand on these accounts hasn't spiked in this same way for months. Closing the issue.
