### ISSUE TITLE
Inrepoconfig: Support postsubmits

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#15656]
**What would you like to be added**:

The inrepoconfig feature can be used to configure jobs alongside the code in a `.prow.yaml` file and have Prow load them on-demand. Right now this is only implemented for presubmits, it would be nice if we also had it for postsubmits.

**Why is this needed**:

* To avoid drift by versioning the jobs in the same repository as the code
* To have an easely discoverable location for everyone working on the project

/area prow

**Comment by eddycharly** [comment]
@alvaroaleman i would love to see this feature added to prow.
Is it ok if i work on implementing it ?

**Comment by alvaroaleman** [comment]
> Is it ok if i work on implementing it ?

Absolutely!

/assign @eddycharly 

To give a rough sketch on what has to be done:

* The current `Postsubmits` property in `prow/config/Config` needs to be renamed, e.G. to `PostsubmitsStatic` to indicate that it may not contain all `Postsubmits`
* A new function `GetPostsubmits` analogous to the existing `GetPresubmits` needs to be added
* All code that accesses Postsubmits needs to be changed to either
    * Use `PostsubmitsStatic` if it has no way to fetch them, this is e.G. the case in the `checkconfig` cli
    * Use the new `GetPostsubmits`

Let me know if you have any questions. Also, are you in the Kubernetes slack?

**Comment by eddycharly** [comment]
I'm not in the Kubernetes slack yet, i will join asap.

It doesn't sound too difficult to implement as all the code is already there, you made all the hard work for presubmits.

I am looking at prow config right now, i don't think we want to enable inrepoconfig differently for presubmits and postsubmits so nothing to change in the `InRepoConfig` struct.

The `GetPostsubmits` function should be simpler then `GetPresubmits` as there is no need to merge, only one sha is needed i guess.

After that i will look into `hook/trigger` so that it can see the in repo postsubmits also.

As soon as i have a basic compiling version i will open a WIP pr so that you can have a look at the same time i work on it.

**Comment by alvaroaleman** [comment]
This was implemeted in #15667
