### ISSUE TITLE
config-updater needs to use clusters instead of namespaces

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#15662]
**What happened**:
The logs for `hook`, `deck`, and `status-reconciler` are all very loud about a deprecated format:
```
jsonPayload: {
  component: "hook"   
  file: "prow/plugins/config.go:865"   
  func: "k8s.io/test-infra/prow/plugins.(*ConfigUpdater).SetDefaults"   
  level: "warning"   
  msg: "'namespace' and 'additional_namespaces' are deprecated for config-updater plugin, use 'clusters' instead"   
 }
```

It looks like there was an attempt to move to a new format, but there were issues with it. See https://github.com/kubernetes/test-infra/pull/15632

**What you expected to happen**:
These warnings are crowding out most other warnings. I don't expect this many warnings about the same thing over and over again.

**Comment by Katharine** [comment]
I filtered this out of the go links. We should still actually fix this.

/remove-kind oncall-hotlist

**Comment by matthyx** [comment]
@cjwagner do you remember what went wrong with the first attempt?

**Comment by cjwagner** [comment]
This slack thread has the details: https://kubernetes.slack.com/archives/C7J9RP96G/p1576614298013700

`hook` doesn't mount the kubeconfig so it doesn't know about the `test-infra-trusted` cluster even though this is a self loop back to the cluster `hook` is running in. Currently things are working because the `default` cluster is used which is the in-cluster context since the kubeconfig is omitted. (See the currently resolved plugin config here: https://prow.k8s.io/plugin-config)
My first attempt should work if we also mount the kubeconfig to `hook`. Alternatively we could just copy the config from the resolved plugin-config, but that config is only correct so long as we do not mount a kubeconfig. I'm pretty sure mounting the kubeconfig will change what the `default` context points to because that will become the build cluster. So I think redoing my original change and then immediately mounting the kubeconfig to hook might be the best path forward.
