### ISSUE TITLE
Azure jobs failure on v1.17 branch

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/test-infra#15703]
**What happened**:

PR #15701 tried upgrading Azure jobs to v1.17, however, all the jobs would fail because of aks-engine validation:

```
Error: validating API model after populating values: customHyperkubeImage has no effect in Kubernetes version 1.17.0 or above
```

This is because kubetest is using image version in [format ](https://github.com/kubernetes/test-infra/blob/master/kubetest/azure.go#L107)of `fmt.Sprintf("azure-e2e-%s", buildID)`, however aks-engine [expected a semver >= 1.17.0](https://github.com/Azure/aks-engine/blob/4562fbb835e5457c6376f7a164485ac05e8e6382/pkg/api/vlabs/validate.go#L1580-L1583).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/area provider/azure
/cc @ritazh @chewong

**Comment by chewong** [comment]
This validation was triggered because aks-engine no longer uses hyperkube for k8s >= 1.17. In short, #15701 would work if the following changes are added:
- `--aksengine-hyperkube=True` is replaced by `--aksengine-deploy-custom-k8s=True` (Added in https://github.com/kubernetes/test-infra/pull/15388)
- Change `--build=bazel` to `--build=quick`. This will allow us to build custom images of k8s components

On a side note, we have been successfully running CI jobs on k8s `release-1.17` branch. You could check out https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cloud-provider/azure/release-1.17.yaml for reference.

**Comment by feiskyer** [comment]
@chewong thanks, let me update according to https://github.com/kubernetes/test-infra/issues/15703#issuecomment-569707912
/assign

**Comment by chewong** [comment]
Thanks for the PR. But it looks like cloud-provider-azure's periodic jobs are failing because it is missing the following env var - https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L596-L597. I will open another PR to switch the preset label from `preset-cloudprovider-azure-cred` to `preset-azure-cred`.
