### ISSUE TITLE
Bad `/assign` causes "Error handling GenericCommentEvent" instead of user feedback

### ISSUE THREAD

**Issue by petr-muller** [kubernetes/test-infra#15811]
We saw someones `/assign <someone> please take a look` command to log an error instead of replying to the user that "please, take, a, look" could not be assigned. It used to do this in the past.

Log:
```
{
  component: "hook"   
  error: "status code 404 not one of [201], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue"}"   
  event-type: "issue_comment"   
  level": "error"   
  msg: "Error handling GenericCommentEvent."   
  plugin: "assign"   
 }
```

See: https://github.com/openshift/console/pull/3765#issuecomment-571508312

xref: https://github.com/openshift/release/issues/6581

**Comment by stevekuznetsov** [comment]
cc @cjwagner this used to report an error when trying to assign `"take a look"` -- now it errors silently and assigns nobody, regression?

**Comment by adshmh** [comment]
After running a few tests, it seems GitHub API will ignore requests for assignment if the user cannot be assigned the issue. The plugin uses the API's response which lists the assigned users to figure out the list of ignored users and adds a comment accordingly. 

However, if any of the specified users do not exist (or, interestingly, are an organisation account), GitHub API will return 404, which the plugin does not handle for assignment (for reviews it handles 422 code by making separate requests per login)

The `please take a look` fails because  `please` is currently an organisation account (perhaps this is what changed, triggering a 404 response from GitHub API).
