### ISSUE TITLE
Prow issue:How do I change the default api-server ip address?

### ISSUE THREAD

**Issue by Jimmol-Singh** [kubernetes/test-infra#16553]
I want to change the default Kube API server IP address from 10.96.0.1 to something else. How and where would I do this?

Thanks!

**Comment by alvaroaleman** [comment]
Hi,

The default kube apiserver address is inferred from the `KUBERNETES_SERVICE_HOST` environment variable, which gets set to the ClusterIP of the `kubernetes` service in the `default` namespace. Per convention, this is the first IP in the service CIDR range. [The CIDR range in turn is `10.96.0.0/12` by default in Kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/), which I guess you are using. You can configure a different `ServiceCIDR` by passing it as argument to the `kubeadm init` command.

You can not change the default kubernetes VIP and its supposed to work, otherwise a set of core services like kube-dns will not work either, essentially breaking basic cluster functionality.

Your question sounds more like a generic Kubernetes support question rather than something specific to Prow, so I am closing this issue. Please feel free to `/reopen` if I misunderstood anything.
/close

**Comment by kirillyesikov** [comment]
Why does the official documentation has it as a private address ?

The default config has a 
```localAPIEndpoint:
  advertiseAddress: "1.2.3.4" ```

**Comment by alvaroaleman** [comment]
Please re-post your question to our [Discussion Forums](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Discussion Forums to field
support requests. Before posting a new question, please search these for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

/triage support
