### ISSUE TITLE
AWS specific ginko tags

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#1679]
We have some testing scenarios where we need to only run tests against AWS.  @zmerlynn do we have a tag for this?

**Comment by zmerlynn** [comment]
There's a couple options. In general, if the test is in a specific area (storage, networking, etc), I think it would be preferable to just add the test guarded by `framework.SkipUnlessProviderIs`. Tagging these with `[AWS]` is not unreasonable, either, because then we could just focus on AWS.

There's no real procedure for creating a tag, just do it.
