### ISSUE TITLE
Approvers: Optimize So Reviewers and Approvers are same person

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#1688]
if the suggested reviewers and approvers can be the same people, make them the same people.

Goes with #1639

**Comment by liggitt** [comment]
If a long term goal is to grow the reviewers pool, but approvers remain one of many possible reviewers in the pool, this will negate the larger reviewer pool and keep targeting the approver for reviews, right?

**Comment by apelisse** [comment]
I agree with @liggitt. Doing that would be mostly equivalent to going back to one-tier mechanism.

**Comment by fejta** [comment]
Yes, a one-tier mechanism is the goal because it is most efficient.

We do not want approvers who do not understand the code and do not do reviews.

The only time we want the reviewer to be someone other than the approver is during a time where demand for code reviews in an area has rapidly expanded. We can add non-owner reviewers as a temporary measure to help expedite training those reviewers.

**Comment by apelisse** [comment]
> Yes, a one-tier mechanism is the goal because it is most efficient.

That is pretty controversial :-)

**Comment by fejta** [comment]
It shouldn't be. The intent of the approvers initiative is to make reviews faster and increase review velocity.

One-tier of reviewers will have lower latency than two.

**Comment by grodrigues3** [comment]
might be fixed by https://github.com/kubernetes/test-infra/pull/2199
and 
https://github.com/kubernetes/test-infra/pull/2344
