### ISSUE TITLE
'Overall' row reports Running for completed jobs in testgrid

### ISSUE THREAD

**Issue by bparees** [kubernetes/test-infra#17151]
**What happened**:

For some of our job templates, the vast majority of the jobs show an Overall status of running, despite having completed:

**What you expected to happen**:
Expected the overall status to be success or failure for the job.

**How to reproduce it (as minimally and precisely as possible)**:
Seems to recur consistently for those jobs, but our other jobs all report their Overall status fine.

**Please provide links to example occurrences, if any**:
https://testgrid.k8s.io/redhat-openshift-ocp-release-4.4-informing#release-openshift-origin-installer-e2e-aws-ovn-network-stress-4.4&show-stale-tests=
https://testgrid.k8s.io/redhat-openshift-ocp-release-4.4-informing#release-openshift-origin-installer-e2e-aws-sdn-network-stress-4.4&show-stale-tests=

cc @michelle192837 @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@michelle192837 do you think you'll be able to take a look at what's causing this?

**Comment by michelle192837** [comment]
Thaaat's weird. The result does seem to show up in finished.json and is a status that we recognize. :/  And it's not like these jobs take an inordinate amount of time to complete, nor are they running super-frequently (I might expect this issue with presubmits for instance, where jobs run at a high frequency and don't always update older runs).

How are results for these jobs uploaded? pod-utils or something bespoke?

**Comment by michelle192837** [comment]
Oh, huh. Error in logs:
`Could not read /bigstore/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-ovn-network-stress-4.4/436/finished.json`

Can find the result fine at https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-ovn-network-stress-4.4/436/finished.json, so not sure what's up exactly...It's failing to get the file from storage somehow though.

**Comment by michelle192837** [comment]
Oh, huh. Error in logs indicate that storage is failing to find the file.

Can find the result fine at https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-ovn-network-stress-4.4/436/finished.json, so not sure what's up exactly...

**Comment by michelle192837** [comment]
Ah, nope, nvm, I'm pretty sure that's legit because the file wasn't uploaded at the time. :/ Back to looking.

**Comment by michelle192837** [comment]
Okay no, it's because the updater stops looking back after it finds 100 invocations with no changes, and each cell counts as a new invocation. 

I don't have a good suggestion for how to resolve this, but something's weird with the results. :/

**Comment by bparees** [comment]
@michelle192837 Thanks for looking into it...anything else I can do/look-at/provide from my end?

**Comment by michelle192837** [comment]
Hmm, you can try and see if there's a significant difference between how logs appear for your job vs some other jobs with a lot of targets (since I'm not seeing the same issue with others; something with a similar number of rows might be a good check?). I can try and look in a bit more tomorrow too. ^^

**Comment by michelle192837** [comment]
Also if you happen to know how logs for these jobs are uploaded (podutils? custom script/job? something else?), that would be helpful!

**Comment by bparees** [comment]
> Also if you happen to know how logs for these jobs are uploaded (podutils? custom script/job? something else?), that would be helpful!

i'm going to have to defer to @stevekuznetsov on that, but it shouldn't be any different for this job than our working ones.

**Comment by stevekuznetsov** [comment]
@michelle192837 this is a normal pod-utils upload! What is the file that's missing?

**Comment by michelle192837** [comment]
Mmk, I don't think files are missing, but I do want to ask if you expect tests to be rerun like 15 times?

Since these are counting as different invocations, we're hitting the '100 same invocations' limit quickly because of repeatedly hitting tests with the same name and status. (This is visible in Spyglass I believe if you look at failed tests and expand results to see a number of runs: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-ovn-network-stress-4.4/452 for example).

I think there's some ways to help mitigate this in TestGrid processing, but also if these are NOT supposed to be reruns, we'll want to figure out what's different about them and how to display that.

**Comment by michelle192837** [comment]
Bleh, looking more at how this works in TestGrid atm, this is not a trivial fix; it'd require a pretty big change to how we process test results for JUnit. :(

Reducing reruns should help (anything to avoid processing the same named tests over and over).

**Comment by bparees** [comment]
> Since these are counting as different invocations, we're hitting the '100 same invocations' limit quickly because of repeatedly hitting tests with the same name and status. (This is visible in Spyglass I believe if you look at failed tests and expand results to see a number of runs: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-ovn-network-stress-4.4/452 for example).

interesting, that is likely unique to this job and i do not know why it's doing that.  

@knobunc or @danwinship can you explain the retry test behavior in your stress job?  it seems to be wreaking havoc on testgrid.

![image](https://user-images.githubusercontent.com/4974046/81231362-0c893480-8fc1-11ea-9254-90ec90a46ed9.png)

**Comment by danwinship** [comment]
No idea. @smarterclayton wrote that

**Comment by smarterclayton** [comment]
These are all rerun tests.  The tests are deliberately rerun in order to ensure they are stable.  This is a "flake finder" job.  We could optionally skip successful jobs, but we try to capture multiple failure jobs to make sure they are the same flake.  We *could* dedupe them at run time in test/e2e, but this won't be the only time we try to have deflake jobs.
