### ISSUE TITLE
prow: `marque` (and the kube client) are unreliable/buggy

### ISSUE THREAD

**Issue by colemickens** [kubernetes/test-infra#1718]
1. `marque` only works if there is already a matching secret in the cluster.

2. Even if you bootstrap it with a dummy cert secret, you will get errors when it tries to update the cert -
 complains about modifying the immutable `type` field.

3. The logic needs to delete-if-existing and then create the secret anew.

Note: I have fixes for this, but they're intertwined with a bunch of other changes that make `prow` *also* work on non-GKE|GCE Clusters (such as Azure Container Service cluster). As soon as I get a job running e2e and reporting status back to ~~Jenkins~~ GitHub, I'll start cleaning up these commits and send a couple PRs.

**Comment by spxtr** [comment]
Sounds good. I think we should cache certbot's saves on a PD so that it doesn't try to get a new cert from scratch whenever the pod restarts.

As for running prow on not-GKE, I'd love for it to happen. As you've probably discovered, there are several places where I assume GKE behavior, but I don't think there's anything that can't be fairly simply ported. Also, some things are hard-coded that are specific to our instance, such as `prow.k8s.io` and `k8s-ci-robot`. We should keep this stuff in a configmap.

Are you trying to set up your own prow instance to run tests on Azure? I have some cycles to spare and I can maybe work on this effort as well.

**Comment by colemickens** [comment]
>Are you trying to set up your own prow instance to run tests on Azure? I have some cycles to spare and I can maybe work on this effort as well.

Yes, and I've made at least some progress. I think I have jobs kicking off from `hook`/`trigger` with @acs-bot (or else I got `splicer` configured correctly finally and it kicked a job for my PR - not fully sure which yet).

Big picture, I'm still missing a few details... I can file a more generic issue and ask them, and/or I'm in `#sig-testing` as well.

I'm less interested in using it to run the already-present k8s conformance/e2e scenarios as much as I am seeing if I can leverage `prow` to run some tests for our `ACS-Engine` project. In some sense, `ACS-Engine` is similar to `kops` and I want e2e tests for it that may overlap or leverage the e2e tests already in `prow`/`test-infra` in general.

(BTW: I'm doing this here: https://github.com/colemickens/test-infra/commits/azhack)

**Comment by spxtr** [comment]
[This file](https://github.com/colemickens/test-infra/blob/d3945b18fd44f4e3127169b9d91257bf649ac85d/prow/postsubmit.yaml) makes me extremely happy!

I suggest filing a more generic tracking issue.

**Comment by colemickens** [comment]
Ha, it doesn't work yet - it's still starting a `line` Pod with `bootstrap.py` cmd+args. (that's what I'm trying to fix now!)

I'll file a more generic issue in the next day or two!

**Comment by spxtr** [comment]
> I'll file a more generic issue in the next day or two!

Awesome, I look forward to it.
