### ISSUE TITLE
Allow repo customize highlight regex in Spyglass config

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#17266]
**What would you like to be added**:
Like some of the other Prow components, allow repo specify its own highlight rege, such as example below:

```
deck:
  spyglass:
    lenses:
    - lens:
        name: buildlog
        config:
          '*':
            highlight_regexes:
            - default error
          'orgA/repoB':
            highlight_regexes:
            - error only happen in repoB 
      required_files:
      - build-log.txt
```

The example above is just for illustrative purpose, it'll also fulfil this request if any layer above is customized

Link to README of spyglass: https://github.com/kubernetes/test-infra/blob/561dc2e96d5984bce2536cbdf4ee6dea8994b403/prow/spyglass/README.md#configuring-lenses

**Why is this needed**:
Currently all tenants of a Prow shares the same set of highlight regex, which is pretty hard to optimize especially when there are many tenants/repos. Would be nice to allow repo owners being able to specify it's own highlight regex

**Comment by BenTheElder** [comment]
this sounds reasonable.
AIUI nobody works on this currently, katharine maintained this tool but has moved on.

if you want this you'll probably have to implement it 🙃

**Comment by chaodaiG** [comment]
Will add this to my backlog and see what I can do

**Comment by stevekuznetsov** [comment]
Realistically we would rather have specific federated spyglass lenses, right?

**Comment by chaodaiG** [comment]
@cjwagner and me took a stab at it today, trying to do it the "correct" way in our opinions:
```
deck:
  spyglass:
    lenses:
    - lens:
        name: buildlog
        configs:
            highlight_regexes:
            - legacy
        configs:
          '*':
            highlight_regexes:
            - default error
          'orgA/repoB':
            highlight_regexes:
            - error only happen in repoB 
      required_files:
      - build-log.txt
```

It turned out that the related changes required spyglass lenses API changes, which will break all remote lenses. We could make it work by versioning spyglass lenses API and duplicate lots of code to not break remote lenses, but figured it's probably not worthy the effort in thinking about the return value

**Comment by cjwagner** [comment]
I thought about this some more and realized we don't need to change the lens interface at all if we pass the appropriate map entry rather than the entire `configs` map. This avoids breaking changes to the lens API and generalizes the logic for determining which entry to use. 

To determine which map entry applies to the request we'll need to fetch the associated ProwJob somewhere around here: https://github.com/kubernetes/test-infra/blob/c2f45283c2716b00e8e06ba4575fd22a64d06493/prow/spyglass/lenses/common/common.go#L112
The `PJFetcher` is insufficient if the PJ has already been garbage collected so we'll need to fall back to fetching the prowjob.json from GCS. This means we'll need to validate that the `gcsreporter` crier reporter is enabled if any lens uses the `configs` field rather than the `config` field.
Once we have the PJ we can use the same logic used with the `default_decoration_configs` field to determine which config applies to the PJ.

I don't have time to work on this at the moment, so I wanted to document my updated thoughts.
