### ISSUE TITLE
Make it easier for people to rerun jobs

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#17321]
Why do we so severely limit who can rerun jobs? It is not very productive anyone to have to contact oncall to rerun a job. Seems like they should just be able to click the rerun button.

On the other hand, giving just the milestone maintainers team the ability to rerun job seems somewhat odd.

Thoughts?

/assign @cblecker @cjwagner 

ref https://github.com/kubernetes/test-infra/pull/17320

**Comment by cjwagner** [comment]
I'd certainly like to make this feature more accessible. I think my concerns about jobs being rerun improperly fall into 2 classes. I'm happy with anyone in the org rerunning other things, but we should properly limit access to rerunning jobs that either of these concerns apply to. 
1. Some jobs could cause correctness issues if they are run at the wrong time. In particular I'd be worried about jobs related to release processes or infrastructure since they could overwrite the latest artifacts with older ones or deploy old versions of infrastructure components.
2. A job being rerun excessively or at the wrong time could exhaust resources whether that be a `max_concurrency`, boskos resources, or hardware resources. This seems less likely to me, but it would allow a malicious org member to DOS Prow or a contributor who doesn't know any better might rerun scalability jobs and waste/exhaust resources.

Presubmits should already be rerunnable by anyone who can `/test` so I'm assuming this is mainly concerning postsubmits and periodics. We can grant access to presubmits/postsubmits at the global, org, repo, and job scopes, but access to rerun periodic can only be specified at the global and job scopes currently. 

Adding support for specifying rerun auth config at the build cluster scope might help, but I don't think it would completely resolve this problem. I think allowing users specified in OWNERS files for the job config to rerun the jobs they own would be more effective, but is a bit trickier: https://github.com/kubernetes/test-infra/issues/15194

**Comment by spiffxp** [comment]
Do we have a way of identifying who triggered a given re-run?

In terms of specifying more granular teams per org/repo, can we do this for periodics, or does that need to be done per-job?

**Comment by cjwagner** [comment]
> Do we have a way of identifying who triggered a given re-run?

We do from the logs. I don't think it is annotated on the ProwJob itself, but that would be easy to add.
https://github.com/kubernetes/test-infra/blob/d0d57e6b0929fdd8385784e650a9a14f369258e7/prow/cmd/deck/main.go#L1477 https://github.com/kubernetes/test-infra/blob/d0d57e6b0929fdd8385784e650a9a14f369258e7/prow/cmd/deck/main.go#L1490-L1491

**Comment by spiffxp** [comment]
I suspect some of the jobs for `1.` fall under the purview of the release-eng folks who I would trust to understand the implications of wrong order / wrong time.

Another reasonable use of rerun I could see would be having the ci-signal (or maybe broader release-team) folks kick off a release-blocking periodic sooner than scheduled.  I think getting by with per-job for that would be fine

milestone-maintainers as a team isn't that bad of a default, it has this weird convenience of including most everyone from the release team, as well as sig leads (ref: https://github.com/kubernetes/sig-release/tree/master/release-team#milestone-maintainers; it's ostensibly the set of people we trust enough to say whether something lands in a release.  I do agree that it feels too broad if I consider the implications @cjwagner raises above

**Comment by cblecker** [comment]
I agree with both the sentiment that we can/should open this more broadly, but I strongly share the concerns that @cjwagner raises. milestone-maintainers is both too broad and there is zero education for those folks about the above issues.

Release managers have access to re-run certain jobs on the per-job level: https://github.com/kubernetes/test-infra/blob/5a4fed7c316e763e69d5555e858738a1c3c73a73/config/jobs/kubernetes/release/release-config.yaml#L84-L86

I suggest we revert #17320, and if this is really causing problems that we create some docs around it. The retry button is too easy to hit on prow.k8s.io if you don't know what you're doing.

**Comment by cblecker** [comment]
also cc @kubernetes/release-engineering
