### ISSUE TITLE
Prow's not running tests on draft PRs counterproductive

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/test-infra#17696]
**What happened**:

I created a draft WIP PR, in order to get CI signal while indicating to humans that the change was not ready for code review.

**What you expected to happen**:

Prow CI jobs to run and provide results and log artifacts.

**How to reproduce it (as minimally and precisely as possible)**:

Create a GitHub draft PR.

**Please provide links to example occurrences, if any**:

kubernetes/kops#9172

**Anything else we need to know?**:

Using the suggested `/test all` was not helpful as Prow would not re-test on a subsequent push.

Converting the PR back to non-draft state did not cause Prow to run tests.

**Comment by stevekuznetsov** [comment]
Looks like we are not going to be able to please everyone with this. @cjwagner should we make this enabled on an org/repo level?

**Comment by johngmyers** [comment]
It looks like there are three author-no-desire-merge use cases: desire both review and CI, desire review but no CI, and desire CI but no review.

I don't think this would make a good org/repo setting.

**Comment by alvaroaleman** [comment]
This was delibaretely introduced in https://github.com/kubernetes/test-infra/pull/17374 by @kwiesmueller because for him, the noise of the testing was undesired.

/cc @cblecker @nikhita 
As this is not a technical question but a question of policy. Sorry for not pinging you prior to merging that PR, I should have anticipated that any kind of workflow change will break someones usecase. Not sure what the least bad option here is.

**Comment by kwiesmueller** [comment]
After being suggested to me the Draft PR seemed like a good way of skipping CI.

It is a draft (and not a wip) with the draft overruling wip.

What would be the reason to create a draft PR with the existing WIP mechanics right now?

I agree it should be documented and communicated to have this behavior, but in general I think the possibility to skip drafts in ci saves time, resources and makes longer PRs easier to review.

If there is a suggestion for a different mechanic, I'd love to hear them.

Changing this on a per repo basis could make it even more complicated/inconsistent for contributors as they have to know which repo behaves how.

**Comment by kwiesmueller** [comment]
Oh and the initial discussion can be found here: https://github.com/kubernetes/test-infra/issues/17187

**Comment by cblecker** [comment]
@stevekuznetsov: I don't care if we make this a trigger setting, but I don't think we'll use it for @kubernetes. We want things to be pretty uniform amongst repos.

I am okay with draft == no CI, as long as bringing a PR out of draft form ([pull_request](https://developer.github.com/webhooks/event-payloads/#pull_request) `ready_for_review`) triggers tests. We just need to document this so it's not surprising.

@johngmyers Opening a non-draft PR with `WIP` or `[WIP]` in the title will do what you are looking for.

It's tricky as there are two different entities we are telling to ignore the PR (CI and humans).. we only have so many ways to do that, but the red WIP label and WIP in the title is easy for humans to interpret.

**Comment by cjwagner** [comment]
> @cjwagner should we make this enabled on an org/repo level?

That might be handy so that the feature can be explicitly enabled on repos where CI testing is expensive or noisy, but I suspect in most cases we'd prefer to run presubmits a few extra times rather than have to explicitly request testing. While scoping this by org/repo will give more control I agree that that isn't really the best indicator of how the PR should be handled.

I don't like the idea of WIP and draft meaning different things. I don't think that distinction will be obvious to users. If we want CI to be dependent on a separate mechanism from indicating a PR is ready for a review we should ensure the mechanisms are clearly distinguished.
My 2 cents on policy is that skipping CI doesn't gain much. Presubmits should be cheap to run. Running them on a draft PR will expose errors automatically instead of wasting a human's time in review and if the PR isn't expected to pass tests yet the only downside is a little noise from each batch of test failures.

My votes is that we default to running presubmits on draft PRs and provide a separate mechanism for skipping CI like a `/not-ok-to-test` command.

**Comment by johngmyers** [comment]
Opening a non-draft PR with `WIP` in the title is frequently used in kubernetes/kops for requesting both human review and CI but blocking Prow from merging until the author says otherwise.

I think an `/ok-to-test cancel` command would be a more consistent UI for the no-CI case. It would mirror the `/approve cancel` command for removing the implicit approval for approver authored PRs.

For the don't-want-human-review case it would be nice if there was a way to keep blunderbuss from assigning reviewers. An open PR of any type can always garner attention, but the intent is to avoid an implied request.
