### ISSUE TITLE
GhProxy --legacy-disable-disk-cache-partitions-by-auth-header flag enabled

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#17855]
```
{
  component: "ghproxy"   
  file: "ghproxy/ghproxy.go:139"   
  func: "main.main"   
  level: "warning"   
  msg: "The deprecated `--legacy-disable-disk-cache-partitions-by-auth-header` flags value is `true`. If you are a bigger Prow setup, you should copy your existing cache directory to the directory mentioned in the `Not using a partitioned cache because legacyDisablePartitioningByAuthHeader is true` messages to warm up the partitioned-by-auth-header cache, then set the flag to false. If you are a smaller Prow setup or just started using ghproxy you can just unconditionally set it to `false`."   
 }
```

The "Not using a partitioned cache"... message appeared 4 times at startup.

/assign @chases2 @cjwagner

**Comment by cjwagner** [comment]
>you should copy your existing cache directory to the directory mentioned in the `Not using a partitioned cache because legacyDisablePartitioningByAuthHeader is true` messages

There are a large number of `Not using a partitioned cache because legacyDisablePartitioningByAuthHeader is true` messages that each mention two different directories (`cache-base-path` and `cache-temp-path`) and each of the messages has different pairs of directories. After digging through the code a bit I'm pretty confident that this is asking us to copy this directory https://github.com/kubernetes/test-infra/blob/67ee5303deaca78f3e0a83bf2089399be4a20783/config/prow/cluster/ghproxy.yaml#L58
to the `cache-base-path` directory.

However the logs identify a large number of distinct values for this field and it is unclear which should be used. I think this is related to the strange behavior we see on this graph:
https://monitoring.prow.k8s.io/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1&fullscreen&panelId=7

For some reason our ghproxy instance is reporting that requests are providing many different `Authorization` header values even though the only things using the proxy should be Prow components which should all have identical Authorization headers. On top of this, many of the values for the remaining token count are unreasonably high at approximately 15,000 which doesn't seem possible given that the limit should be 5,000.

We need to determine the cause of this behavior and address it before trying to switch to a partitioned cache.

**Comment by chases2** [comment]
This error is still being seen in logs regularly. Refreshing lifecycle.

**Comment by spiffxp** [comment]
/reopen
/remove-lifecycle rotten
Is this still occurring in the wild? It sounds like it would be relevant to our use of ghproxy for potentially N instances of triage-party each using their own GitHub token over in kubernetes/k8s.io

**Comment by fejta** [comment]
Yes, still relevant. This feature was added without an easy migration plan and we don't need the feature so we just haven't ever migrated.

**Comment by listx** [comment]
I've looked into k8s-prow [logs](https://pantheon.corp.google.com/logs/query;query=jsonPayload.component%3D%22ghproxy%22%0AlegacyDisablePartitioningByAuthHeader;timeRange=P7D;cursorTimestamp=2021-11-11T11:15:31Z?orgonly=true&project=k8s-prow&supportedpurview=organizationId&query=%0A) and this is still happening. But, I'm not sure what the severity of this bug is. Is there an actual problem other than "we are using a deprecated flag"? Does this block anything else?

**Comment by cjwagner** [comment]
My comment here has some more context: https://github.com/kubernetes/test-infra/issues/17855#issuecomment-706349394

We are using the deprecated unpartitioned cache and never migrated to the partitioned cache. The partitioned cache prevents requests with different authorization headers from clobbering each other's cache entries. It improves cache efficiency.

I think we have enough info to determine which `cache-base-path` value to use now and I think it should also be safe to copy the cache to multiple of the identified paths. IIUC that shouldn't hurt beyond wasting some disk space and it will mitigate the (possibly negligible) cache cooling we'd otherwise see.
