### ISSUE TITLE
Make prow easy to deploy and run in a variety of environments.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#1792]
Currently prow makes a few assumptions:

* ~~`k8s-ci-robot` and the like are hardcoded in several places.~~ Done in #1804.
* ~~GKE local SSDs are assumed to exist, GCE PDs are used in a few places.~~ #2192
* ~~The Makefile's create cluster target is woefully outdated and GKE-specific.~~ Done in #2135.
* Deploying prow from scratch requires touching a whole bunch of deployment yaml files and understanding the entire system.

I'm going to spend some time making this better, and I'll use this issue to track.

cc @colemickens

**Comment by spxtr** [comment]
cc @kargakis

**Comment by colemickens** [comment]
Since I just saw #2185 and I've been dragging my feet on getting all of my notes posted... here's a few other quick ones I've noticed:

* lots of assumptions that GCE ServiceAccount is present. `line` adds secrets/configmaps to every job because every GCE job uses them, but they're meaningless for my uses.
* at least as of a month ago, there was a hostPort added to every job so that jobs would get a full Node. Again, something that was hard-coded probably to avoid being repeatedly specified in the config yaml, but it seems to be mis-modeled.
* `marque` hard codes the domain/email/secretName. I have changes for this but can't seem to find time to add tests and send a PR

**Comment by spxtr** [comment]
> lots of assumptions that GCE ServiceAccount is present. line adds secrets/configmaps to every job because every GCE job uses them, but they're meaningless for my uses.

Just fixed that. Will need to come up with some way to cut back on boilerplate in config.yaml without hard-coding it.

**Comment by spxtr** [comment]
> `marque` hard codes the domain/email/secretName. I have changes for this but can't seem to find time to add tests and send a PR

Might be worth looking at [kube-lego](https://github.com/jetstack/kube-lego) now that it's a bit more mature.

**Comment by colemickens** [comment]
* `marque`: really simple, no magic, a bit inflexible, something to maintain that might not be essential to maintain. Requires user to orchestrate proper Ingress rules.
* `kube-lego`: magical, a good number of things to deploy. Auto-creates Ingress objects to wire up the http challenge. (Bonus, already has a Helm chart)
* `kube-cert-manager` (PSGLuna's, not Kelsey's...): lots of different LE challenges supported, requires user to create Ingress rules.

Sounds like you'd consider removing `marque` and replacing with instructions for how to setup `kube-lego`?

**Comment by spxtr** [comment]
> Sounds like you'd consider removing `marque` and replacing with instructions for how to setup `kube-lego`?

Yes. It looks pretty straightforward but I've never used it before.

**Comment by spxtr** [comment]
I'm going to close this in favor of #2529 and #2041.
