### ISSUE TITLE
environments-bar div sometimes occludes dashboard-summary-canvas div 

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/test-infra#18162]
**What happened**:  
On a 27in 1080p screen I docked my browser to the left edge of the screen to improve the readability of the status summary page for the sig-release-master-blocking. (The job data, Last run etc. is far too far away from the job group name on a wide screen monitor name owing to the row-layout of the summary data. A Card/Grid layout _might_ be better)

**What you expected to happen**:
I expect to still be able to see the three buttons, **Show Alerts**, **Hide Alerts** and **Show Status**

**How to reproduce it (as minimally and precisely as possible)**:
Set width of browser to half the width of a 1080p monitor

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
I can reposition the occluded div id'd by `dashboard-summary-canvas` setting its position to about 225 in dev tools, then I can see the buttons.

I would prefer to not have to click on the buttons at all. 

As part of the CI-Signal work I never want to see the page not sorted by status. 

So every time I go to the summary page **I always click on Sort By Status** and it would be great if the page was sorted by status by default. I do not see the point of (or indeed know or care about) the default ordering of the summary report.

**Comment by BenTheElder** [comment]
I assume this is testgrid but it doesn't appear to say so anywhere.

/area testgrid

The contributors to this repo don't all work on all parts of it, and aren't handling every issue, it helps to note what component is involved explicitly 🙃

**Comment by BenTheElder** [comment]
@michelle192837

**Comment by michelle192837** [comment]
Oh, I think I see what you mean. So the issue is that we're not re-rendering/moving elements when the width of the window changes, so the top bar actually obscures the buttons, like this?

![TGDivEx](https://user-images.githubusercontent.com/652853/88420375-a29c5200-cd9b-11ea-963e-061745157fcf.png)

Yeah this is probably something with our absolute positioning/rendering. :/

(For the other part of your issue, summaries are listed in the order they show up in the tab bar, which remains pretty consistent over time instead of changing when statuses do. But I do get the annoyance there; think that might be something we want to keep consistently as a user preference)

**Comment by RobertKielty** [comment]
Thanks @BenTheElder. Thanks @michelle192837 apologies for not naming test-grid up top and logging this here instead of in the new repo https://github.com/GoogleCloudPlatform/testgrid 

I will migrate this off of test-infra and close this.

**Comment by RobertKielty** [comment]
I  haven't encountered this issue in while and if I do a window resize, page refresh or ctrl +/- usually fixes it.

/close
