### ISSUE TITLE
area/robots in OWNERS file in this repo but the label doesn't exist

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#18249]
see the title.

https://github.com/kubernetes/test-infra/blob/ecf543aff552f93db46b43edf09dbdbfdd8f9074/robots/OWNERS

spotted in logs for https://github.com/kubernetes/test-infra/pull/18244

**Comment by nikhita** [comment]
Labeling this as a good first issue!

/good-first-issue

For anyone picking this up, here's how to go about it:

Since we have lots of repos and lots of GitHub orgs in the upstream Kubernetes project, we need a way to make sure that all repos have the same minimum set of labels and that we have a way to document and define labels in a transparent way.

We manage this through (yet another) yaml file today :)

The labels are defined in https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml. https://github.com/kubernetes/test-infra/tree/master/label_sync contains general info about how the yaml file is structure and how to use it.

For this issue:

1. You'd need to add `area/robots` under the `kubernetes/test-infra` key similar to other labels here:

https://github.com/kubernetes/test-infra/blob/1ac27d740c71dbb7dd039c4f241bab52144614ab/label_sync/labels.yaml#L1054-L1061

2. Once that's done, a few files need to be autogenerated. Running the last command listed in https://github.com/kubernetes/test-infra/tree/master/label_sync#usage will generate them.

**Comment by himani93** [comment]
Can I work on this?

**Comment by nikhita** [comment]
@himani93 Yes, all yours! :smile: 

/assign @himani93 

If you need help, please feel free to ping me on slack! (I'm `@nikhita` there as well)

**Comment by BenTheElder** [comment]
thanks!
