### ISSUE TITLE
Publish podinfo.json for ProwJobs that fail or timeout on scheduling

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/test-infra#18701]
**What would you like to be added**:

If a `ProwJob` fails or is times out before it can be scheduled, the `podinfo.json` is not published as an artifact, but it would be helpful to be able to see it.

**Why is this needed**:

Prow users are given no additional insight when a job fails or experiences a scheduling timeout, which can make it hard to determine how to adjust resource limits and requests. It would likely also be useful to be able to see events on the pod and potentially surface them in spyglass.

**Comment by hasheddan** [comment]
@alvaroaleman @cjwagner does this sound like a reasonable change to y'all?

**Comment by alvaroaleman** [comment]
Conceptionally its absolutely reasonable, the question is what that entails. Right now we delete the pod when we run in this condition which means crier can not upload the `pod.json` anymore.

We could add a finalizer before we delete that gets cleared up by the crier reporter after reporting (that would be a good idea regardless of this concrete situation) however the problem is that we don't know for sure if ppl use the pod reporter and if they don't, nothing will ever clear up the finalizer and the pod stays dangling in the cluster.

Maybe declare the pod reporter mandatory?

**Comment by spiffxp** [comment]
/area prow

It's possible to run prow with only jenkins or tekton pipeline jobs, so I'm not sure making the pod reporter mandatory by default makes sense.

**Comment by alvaroaleman** [comment]
> It's possible to run prow with only jenkins or tekton pipeline jobs, so I'm not sure making the pod reporter mandatory by default makes sense.

Make it mandatory when Plank is being used? It should also be mentioned that the pod reporter is somewhat weird in that it is in crier, I believe this was mostly done to avoid implementing a new controller. We could probably instead replaces all occurences in Plank where it today deletes a pod with a `reportAndDeletePod` and remove it entirely from crier?

As a small sidenote we had weird cases where jobs failed but the pod was gone and hence didn't get reported, so a finalizer here would be dope.

/cc @stevekuznetsov
