### ISSUE TITLE
Spyglass spamming logs with 'found no artifacts'

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#18910]
Low-priority since links on Deck seem fine still.

There's a lot of logs (multiple every minute) from Spyglass that I thought were normal requests but might be due to a recent change instead? Example:

```
jsonPayload: {
  component: "deck"   
  error: "found no artifacts for gs/kubernetes-jenkins/pr-logs/pull/90301/pull-kubernetes-integration/1252244688220459022"   
  file: "prow/cmd/deck/main.go:937"   
  func: "main.handleRequestJobViews.func1"   
  handler: "/view"   
  level: "error"   
  msg: "error rendering spyglass page"   
 }
```

Has been happening regularly since 10:08 AM PDT (5:08 PM UTC) yesterday (August 18th), which lines up with yesterday's bump: https://github.com/kubernetes/test-infra/pull/18879.

https://github.com/kubernetes/test-infra/compare/1330dc0906...6369dfaef5 has the changes between those times (including Spyglass changes, so CC'ing some peeps if y'all have more info.)

/cc @anthonyrtong @cjwagner @e-blackwelder

**Comment by anthonyrtong** [comment]
Looking into it now!

**Comment by anthonyrtong** [comment]
Are these logs always for the same job?

**Comment by michelle192837** [comment]
Not always the same job (there's a lot mentioned in logs), though I am seeing repeats of the same job ID + build number (e.g. for the error in the first post, that pops up repeatedly for a while)

**Comment by anthonyrtong** [comment]
https://github.com/kubernetes/test-infra/pull/18429

Extra log errors are coming from here because `ListArtifacts()` can now return an empty list.  Before we used to hardcode "build-log.txt" to always be in artifact names so it was actually not possible to ever encounter this error.  The new behavior of determining build-log names based on the actual running pod makes it so that it is now possible to trigger this error if the job has no artifacts in gcs and if the job is not running.
