### ISSUE TITLE
node-kubelet-master and node-kubelet-conformance seem like duplicates

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/test-infra#18973]
CC: @MHBauer 

**What should be cleaned up or changed**:

node-kubelet-master and node-kubelet-conformance seem like duplicates. Need to investigate on whether we need both or some restructure is needed.

**Provide any links for context**:

Discussed that needs to be investigated during today's meting: https://docs.google.com/document/d/1fb-ugvgdSVIkkuJ388_nhp2pBTy_4HEVg5848Xy7n5U/edit#

**Comment by knabben** [comment]
my 2 cents, the `node-kubelet-conformance` uses the `--test-suite=conformance` flag when starting the test. 

Without the flag `node-kubelet-master` the command only copy the binaries ("kubelet", "e2e_node.test", "ginkgo", "mounter") to the tar directory (the tar file is created for the e2e node, after copying it).

On the other hand, the flag --test-suite=conformance as value, builds the entire docker image with --conformance=true on Ginkgo as the image Entrypoint, what is not very clear is the usage of a docker image to build this.

**Comment by mmerkes** [comment]
Below is a diff (without analysis) of the two different jobs. I'll update this post or follow up with a separate one with more information on the differences.

**node-kubelet-master**

*+annotations*

- `fork-per-release: 'true'`
- `fork-per-release-periodic-interval: 1h 2h 6h 24h`
- `testgrid-alert-email: kubernetes-sig-node+testgrid@googlegroups.com`
- `testgrid-dashboards:`
  - `sig-release-master-blocking`
  - `sig-node-release-blocking`

*interval*

`interval: 1h` vs `interval: 2h` for conformance

*container args*

- `--test_args=--nodes=8` vs. `--test_args=--nodes=8`
- `--skip="\[Flaky\]|\[Serial\]"` vs. `--skip="\[Flaky\]"`

*+containers.resources*

```
      resources:
        limits:
          cpu: 6
          memory: 6Gi
        requests:
          cpu: 6
          memory: 6Gi
```

**node-kubelet-conformance**

*+container args*

- `--gcp-project-type=node-e2e-project`
- `--test-suite=conformance`
- `--node-test-args=--feature-gates=DynamicKubeletConfig=true`

*+containers.securityContext*

```
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
```

**Comment by mmerkes** [comment]
I found a little more information on the reasoning behind running conformance tests in Docker:

[PR: Node Conformance Test: Containerize the node e2e test #31093](https://github.com/kubernetes/kubernetes/pull/31093)
[Issue: Node Conformance Test Planning #30122](https://github.com/kubernetes/kubernetes/issues/30122)
[Issue: Node Conformance Test: Package Node Conformance Test #30174](https://github.com/kubernetes/kubernetes/issues/30174)

**Comment by dchen1107** [comment]
Here is the doc Yuju and I proposed to SIG Node 2 years ago: https://docs.google.com/document/d/1BdNVUGtYO6NDx10x_fueRh_DLT-SVdlPC_SsXjYCHOE/edit#

The doc describes the difference between node-kubelet-master & node-kubelet-conformance tests. Basically we hope node-conformance-test should be passed for every PRs, and they are agnostic to cloud providers, OS distributions, and container runtimes. node-kubernete-master should include all tests for supported features, and it should pass for each releases.

**Comment by mmerkes** [comment]
As @dchen1107 summarizes above and described in [this doc](https://docs.google.com/document/d/1BdNVUGtYO6NDx10x_fueRh_DLT-SVdlPC_SsXjYCHOE/edit#), the expected state of `NodeConformance` tests is:

* Runs tests sig-node e2e tests agnostic of cloud providers, OS distributions and container runtimes
* Expected to pass for every PR

**Current State**

* The [pull-kubernetes-node-e2e test group, which uses the NodeConformance tag, is a required presubmit for PRs](https://github.com/kubernetes/test-infra/blob/a3e91ab92763fd22265d497d3a9aa2252cf8c39c/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L3) as seen in [this PR (and any other)](https://github.com/kubernetes/kubernetes/pull/89155).
* As described in [this doc](https://kubernetes.io/docs/setup/best-practices/node-conformance/), the `node-kubelet-conformance` run using Docker due to the `--test-suite=conformance` tag. However, that tag is not set for `pull-kubernetes-node-e2e`.

**Open Questions**

1. What was the intended way of achieving and testing the everything agnostic piece? [The current state of pull-kubernetes-node-e2e?](https://github.com/kubernetes/test-infra/blob/a3e91ab92763fd22265d497d3a9aa2252cf8c39c/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L3)
2. Given that the tests are intended to be everything agnostic, it seems undesirable for the conformance tests to run in Docker, right? If so, what should we do about `node-kubelet-conformance`?
  - Leave as is.
  - Remove the `--test-suite=conformance` tag and run without Docker.
  - Remove `node-kubelet-conformance` entirely or replace with `pull-kubernetes-node-e2e` in the dashboard to validate that those tests are healthy.
3. Where should we document this? Given that we have pieces of guidance in various places, we should move this to a more formal location and update accordingly.

**Comment by mmerkes** [comment]
Per the SIG-node CI subgroup meeting, we discussed sending an email to sig-architecture and sig-node to discuss the expectations and desired state for the `NodeConformance` tests. Here's a draft:

Greeting all,

In the SIG-Node CI subgroup, we've been discussing an initiative from 2018 to create node conformance tests "as part of the effort to establish process and policy for testing CRI implementations," as defined in [this doc](https://docs.google.com/document/d/1BdNVUGtYO6NDx10x_fueRh_DLT-SVdlPC_SsXjYCHOE/edit#). The tests in the `test/e2e_node` were excluded by the Kubernetes Conformance Test Suite, so the `NodeConformance` tag was created to verify node conformance.

Tests tagged with NodeConformance were intended to include sig-node e2e tests agnostic of cloud providers, OS distributions and container runtimes and expected to pass for every PR. [pull-kubernetes-node-e2e](https://github.com/kubernetes/test-infra/blob/a3e91ab92763fd22265d497d3a9aa2252cf8c39c/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L3), which used the NodeConformance tag, is a required presubmit for PRs and does not specify a container runtime, and there's a separate Prow job that runs tests with NodeConformance tag in Docker.

Today, the NodeConformance tag is rarely added to new tests and details on it can only be found [here](https://kubernetes.io/docs/setup/best-practices/node-conformance/) in the documentation, so we want to use this as an opportunity to clarify the expectations of NodeConformance tests and update the documentation accordingly, and possibly bring us in closer alignment with Kubernetes Conformance tests and expectations around our CRI testing policy.

Do you have guidance or documentation that will be helpful in defining the expectations for NodeConformance tests?

Thanks,

SIG-Node CI subgroup

**Comment by mmerkes** [comment]
Email sent. Not sure if it went to SIG-Architecture as well. Looks like I may need to be in the Google group to email it.

**Comment by SergeyKanzhelev** [comment]
@mmerkes is extending the e-mail to the form of a google doc for review and setting up the long term goal

**Comment by ehashman** [comment]
@mmerkes what's the status of this issue?

**Comment by pacoxu** [comment]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-conformance?buildId=
keeps failing.

Should we remove it?
https://github.com/kubernetes/test-infra/blob/f38f16e9b66de7d746e69bcd59fe4c80b08b12ea/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L74-L104

**Comment by ehashman** [comment]
@pacoxu it seems to me it's been failing for all available prow history (back to March), probably longer. I have no objections to removing it.

Email did not receive any replies but did not go to SIG Arch: https://groups.google.com/g/kubernetes-sig-node/c/kuKftmB_UYg

I see no benefit in keeping the perpetually failing, duplicate job.

**Comment by ehashman** [comment]
Currently, the only difference I can see is that the ci-kubernetes-node-kubelet job skips Serial tests and the node-kubelet-conformance job does not.

However, I can't actually find any Serial tests marked NodeConformance. The only match in the codebase is https://github.com/kubernetes/kubernetes/blob/master/test/conformance/walk_test.go#L183 which is just an annotation test case and not an actual test.

Thus, I think we can safely remove the job.
