### ISSUE TITLE
"Tide Status > GitHub Search Link" broken near utf8=✓ query parameter

### ISSUE THREAD

**Issue by e-blackwelder** [kubernetes/test-infra#19108]
### Reproduction Steps:
- Open Prow in a browser, navigate to [Tide Status](https://prow.k8s.io/tide)
- Expand the "Merge Requirements (click to expand)" area
- Hover over an/all of the "GitHub Search Link" hyperlinks...
- ... Notice they link to
`https://prow.k8s.io/github-link?dest=search?utf8=%E2%9C%93&q=<lots-of-params>`
- Click on any/all of the "Github Search Links"...
- ... Notice the link redirects you to `https://github.com/search?utf8=✓`

### Expected Results:
The search links open github search with all the redirected link params, not just the utf8=<checkmark>.

### Actual Results:
You only get the `utf8=<checkmark>` param in the redirected github search URL.

### Workaround/Tips:
Editing the redirect URL to either remove the `utf8=` parameter (or to put it at the end) seems to give you an appropriate redirect.

### Research notes:
- The `utf8=` query-parameter has been around for years and the `/github-link` redirect for months: 
https://github.com/kubernetes/test-infra/blob/cf4e9a034b78df8020f52cd370602fdab13f8dd9/prow/cmd/deck/static/tide/tide.ts#L127
- ... so I don't know when this issue first started happening.
- Not sure yet if this is a Prow bug (in the redirect-handling) or in Github's URL-handling. (But either way, simply moving the query parameter could be a workaround for a Github-side error.)

**Comment by habibrosyad** [comment]
Turns out it's because of the encoding:
https://github.com/kubernetes/test-infra/blob/cf4e9a034b78df8020f52cd370602fdab13f8dd9/prow/cmd/deck/static/tide/tide.ts#L127

`&` in `&q` should be encoded or it will be treated as another query param.

In here: https://github.com/kubernetes/test-infra/blob/cf4e9a034b78df8020f52cd370602fdab13f8dd9/prow/cmd/deck/main.go#L1565

The only accepted query param is `dest`, hence why it's redirected to `https://github.com/search?utf8=✓` and disregard the query.

A fix has been submitted in #19129
