### ISSUE TITLE
Move pr-test.k8s.io over to gubernator

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#195]
rather than a direct gcs link

**Comment by ixdy** [comment]
ci-test.k8s.io too, please, though its requirements are a little bit more complicated:

* http://ci-test.k8s.io/ should show all builds - maybe that even goes to test grid?
* http://ci-test.k8s.io/BUILD_NAME should show all builds for that build
* http://ci-test.k8s.io/BUILD_NAME/BUILD_NUMBER should show the build detail
* ideally we also support things like http://ci-test.k8s.io/BUILD_NAME/BUILD_NUMBER/build-log.txt or ../BUILD_NUMBER/artifacts or whatever, which either redirects to the file or to the storage console browser. This is basically what ci-test.k8s.io does right now.

I'd also say we should probably try to keep as much logic as possible out of the redirector, since it's not version controlled at all.

**Comment by ixdy** [comment]
x-ref https://github.com/kubernetes/kubernetes/issues/20161 which has discussion of the redirectors as they are currently set up

**Comment by thockin** [comment]
pr-test is done

**Comment by thockin** [comment]
@ixdy Can you spec precisely what redirects you want?

**Comment by ixdy** [comment]
Can we please fix ci-test.k8s.io too?

**Comment by thockin** [comment]
Sorry, I was waiting fro a precise mapping of URL patterns.

**Comment by ixdy** [comment]
@rmmh can you do this?

**Comment by thockin** [comment]
I just need the mappings

**Comment by rmmh** [comment]
pr-test.k8s.io was fixed earlier, this was fixed in kubernetes/k8s.io#7
