### ISSUE TITLE
Include a comment response for /check-cla failure

### ISSUE THREAD

**Issue by leeyspaul** [kubernetes/test-infra#19568]
**What would you like to be added**:

Upon running /check-cla, if the check is not successful, append a comment to a PR to notify the user of the issue.

**Why is this needed**:

It would be useful in notifying users that /check-cla failed with a comment and some output from the bot to know that it indeed ran, instead of a silent run.

For example, in this PR: https://github.com/kubernetes/website/pull/24556 I can assume /check-cla ran but I cannot confirm.

**Comment by BenTheElder** [comment]
Note that /check-cla is meant to force re-synchronizing the state between the label (applied by prow / the bots in this repo) and the CLA status check (at the bottom of the page with other CI results) which is the source of truth from the CNCF's robot (which we don't control and isn't open source).

Most of the history on https://github.com/kubernetes/website/pull/24556 `/check-cla` comments are actually just incidentially triggering the CNCF robot because _any_ event triggers it (you could comment "baz" repeatedly instead and it would trigger). Only once the CNCF bot's status was green does our robot come into play.

Both robots are silent, but you can see the results via the status for the CNCF bot, and the label change events from the bot in this repo (prow).

Because the behavior is so simple (check the status posted by the CNCF and update the label), generally the only thing to check for the bot in this repo is "does the label match the status after I commented" (and in most cases you don't need to comment `/check-cla` at all, it will react to the PR change event), the command mostly exists due to occasionally missing events from github.

The other robot can't comment whenever it does something because it reacts to *all* events.

**Comment by leeyspaul** [comment]
Awesome, thank you for the context!
