### ISSUE TITLE
Boskos AWS resource creation for image-builder CI

### ISSUE THREAD

**Issue by kkeshavamurthy** [kubernetes/test-infra#19630]
**What would you like to be added**:
Atleast 2 AWS boskos resources of type `image-builder-aws` [here](https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/boskos-resources.yaml)

**Why is this needed**:
[image-builder](https://github.com/kubernetes-sigs/image-builder) is looking to have CI for building AMIs and would like to utilize boskos to manage the AWS resources. 

CC: @detiber @codenrhoden @CecileRobertMichon

**Comment by detiber** [comment]
I would likely recommend starting with more than 2 resources, otherwise it will be very easy to exhaust the pool. I would likely suggest 5 as a bare minimum, but likely 10 as a more reasonable starting point.

@kkeshavamurthy you should be able to create the PR to add the resources to that file. Will need to coordinate with @justinsb on the subaccount creation and with `test-infra-oncall` to populate the credentials into the prow cluster.

This will also likely require updates to the boskos reaper deployment configuration (https://github.com/kubernetes/test-infra/blob/983896656456bc61f0e444e603f362a4de3d7139/config/prow/cluster/boskos-reaper_deployment.yaml) to ensure that resources are properly cleaned up.

It will also likely require an update to the aws-janitor itself to support resources that are named differently: https://github.com/kubernetes-sigs/boskos/blob/42ac27d5e774dda33a8a476eba79ea4e09286e81/common/aws/common.go. The GCE janitor allows for specifying which resource types to act on, would probably be a good addition here as well since we'll likely add additional AWS account pools in the future as well.

The last bit will be to ensure that we can monitor the usage of the new boskos pool, for that you'll need to update https://github.com/kubernetes/test-infra/blob/091ee05c82ba23ea9ed826169703773b38255b8d/config/prow/cluster/monitoring/mixins/lib/config.libsonnet to include the new resource type.

**Comment by kkeshavamurthy** [comment]
Thanks a lot for all the pointers @detiber . I'll start looking into them.

**Comment by detiber** [comment]
As an aside, there are a couple of outstanding PRs by @justinsb for automation of accounts for AWS
https://github.com/kubernetes/k8s.io/pull/660
https://github.com/kubernetes/k8s.io/pull/1016

**Comment by spiffxp** [comment]
To repeat my review of https://github.com/kubernetes/k8s.io/pull/1016#pullrequestreview-566665404

> I want to unblock, but:
> - I don't have appropriate access to run all of this
> - My terraform environment isn't setup for this (I'll look into whether upgrading to 0.13 or 0.14 for all of our other modules is a heavy lift)
> - I would rather see more use of `gcloud secrets` vs. storing encrypted in GCS

> I see `gs://k8s-infra-clusters-terraform/aws/k8s/accounts-boskos.yaml` already exists, so if we want to unblock, I'm assuming it's a matter of getting test-infra-oncall access to that file and manually uploading?

/milestone v1.21
/priority important-soon
/assign @justinsb
