### ISSUE TITLE
Allow Repositories to Enable Select OWNERS Files Only

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#19986]
As a maintainer of a forked repository or one that contains vendored code,
I want to ensure that only an appropriate set of users is allowed to `/approve` PRs to my repository
So that I can develop my fork or derivative project correctly

---

When a repository uses Prow and forks another repository that uses Prow, or uses vendoring and has dependencies that use Prow, a large number of OWNERS files in the repository will exist by proxy and not as intentional creations of the maintainers. This creates a situation where inappropriate members of GitHub have approval rights on this repository. An allow-list in the Prow configuration could be added to let the maintainers of this repository choose which OWNERS files should and should not be valid, using perhaps glob syntax:

```yaml
approve:
  repos:
    some-org/a-fork:
    - ./OWNERS
    - ./carried-patches/**/OWNERS
```

/cc @alvaroaleman @cjwagner

**Comment by alvaroaleman** [comment]
They shouldn't have approval rights unless they are also a member of the org that contains the fork

**Comment by stevekuznetsov** [comment]
Yes, and in many cases users expect to be able to disallow approval rights _even for members of the org who have approval rights in the upstream_. It's their repository, so they want full control.

**Comment by cjwagner** [comment]
We already have [OwnersDirBlacklist](https://godoc.org/k8s.io/test-infra/prow/config#OwnersDirBlacklist) which is similar to what you are describing, but applies to all plugins, not just `approve`. Does that satisfy your use case?

An alternative solution would be to add support for another OWNERS file field that indicates child OWNERS files should be ignored (kind of like the `no_parent_owners` field). That would also keep OWNERS file config in the OWNERS files themselves rather than the Prow config which is probably preferable.

**Comment by alvaroaleman** [comment]
Resolved via https://github.com/kubernetes/test-infra/pull/20482
/close
