### ISSUE TITLE
Testgrid not reporting any job status since 11-18-2020

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/test-infra#20010]
**What happened**:

No jobs are reporting status of runs on testgrid, though I can see they are running successfully in Prow.

**Please provide links to example occurrences, if any**:

All jobs on `sig-release-master-blocking`: https://testgrid.k8s.io/sig-release-master-blocking

/cc @kubernetes/ci-signal

**Comment by MushuEE** [comment]
See https://github.com/GoogleCloudPlatform/testgrid/issues/211
Adding &grid=old shows results 👍 
[Updated runs](https://testgrid.k8s.io/sig-release-master-blocking#build-master&grid=old)

**Comment by michelle192837** [comment]
The cause is known (Updater is unable to run), but unsure how to fix atm. Will continue working on this today, apologies for the trouble folks!

**Comment by michelle192837** [comment]
Related to https://github.com/GoogleCloudPlatform/testgrid/issues/211 (though this is not code issues, this is an issue with actually running the updater).

Until the issue is resolved, I am going to make grid=old results the default results on testgrid.k8s.io.

**Comment by michelle192837** [comment]
Tabs should be showing more recent results now! However, the summary tab will still show old summaries for now. (I'll look at a mitigation if we can't get things running properly today).

**Comment by hasheddan** [comment]
Thanks @michelle192837!

**Comment by michelle192837** [comment]
Summary issue is mitigated, so recent summaries should also be showing up! (I'll keep this issue open since the underlying cause isn't _fixed_, but users broadly shouldn't have issues with stale summaries or tabs anymore.)

**Comment by michelle192837** [comment]
Alright, underlying issue appears to be fixed, so I'm going to remove the mitigations and go back to the official way of running stuff. (That should be live tomorrow morning, around 9-11 AM PT?)

**Comment by thejoycekung** [comment]
@michelle192837 Looks like the summaries are updating correctly:
![image](https://user-images.githubusercontent.com/13409103/101371967-5f89d980-3879-11eb-8980-3df97ff442d3.png)

But the tabs are still showing old data:
![image](https://user-images.githubusercontent.com/13409103/101372046-76303080-3879-11eb-98a0-db74965ec6a7.png)

The `&grid=old` workaround will still show the new data though.

**Comment by michelle192837** [comment]
The updater _is_ running this time, so that's good. It appears to log that it's updated states (and I've confirmed that the states in storage _are_ recently updated, so the timestamps on the summary check out), but all the dashboards I've checked don't have recent results, so something seems suspicious here.

**Comment by wojtek-t** [comment]
We have the same problem for *some* of our jobs, e.g.:
https://testgrid.k8s.io/sig-scalability-gce#gce-cos-master-scalability-100

But surprisingly, this one looks fine as an example:
https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-performance

**Comment by michelle192837** [comment]
Ah, thanks for pointing this out!

Pinging @fejta in case you have ideas!

Yeah, correlating some of the update messages with their tabs more closely, it does look like some of these are perfectly fine and have updated pretty recently, but not a high percentage of groups.

From the logs, it looks like we're making progress such that logs report up to 25% of groups updated...but then they stop? (Main updater is on the 10-20 image I believe, canary is on 12-03 but seems to have the same issue, though it looks like it got to 31% sometimes).

We also aren't seeing the message `Update completed in <time>`. The last time we saw this was on 12-03, `Update completed in 2h15m31.458828297s`, so it seems like we aren't actually updating all groups. (I believe update order is consistent, so that would explain why some are up to date even though a number aren't).

**Comment by fejta** [comment]
Two issues are 1) concurrency/node size is too high, resulting in evictions and 2) always update in the same order

I have a solution for (2) and trying to mitigate (1) without just using a bigger node

**Comment by michelle192837** [comment]
Looks like Erick's fixes have resolved this issue, and everything is updating consistently. Thanks Erick! 🎉 

/assign @fejta

**Comment by Rajalakshmi-Girish** [comment]
Test-grid is not reporting job status for "ppc64le unit tests" since 11-12-2020
https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests is showing results only till 11th December (11-12-2020)
As per the workaround mentioned in https://github.com/kubernetes/test-infra/issues/20010, I am able to view all the latest results via https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests&grid=old

**Comment by Rajalakshmi-Girish** [comment]
![69015e80-43ae-11eb-8a6d-dd91393aa1fa](https://user-images.githubusercontent.com/63038004/102774987-06aa5d00-43b2-11eb-8d3b-6b19cce45bef.png)

**Comment by fejta** [comment]
https://github.com/GoogleCloudPlatform/testgrid/pull/303 should have mitigate this @Rajalakshmi-Girish and is now in production

This is also caused by the 27k stale tests, which I can look into
