### ISSUE TITLE
Fix post submit jobs that are not running

### ISSUE THREAD

**Issue by hickeyma** [kubernetes/test-infra#20194]
**What happened**:

Post submit jobs for cri-tools do not seem to be running:
https://testgrid.k8s.io/sig-node-cri-tools
https://prow.k8s.io/?job=post-cri-tools-push-image-user-multi-arch

**What you expected to happen**:

The jobs to run when there was a change to https://github.com/kubernetes-sigs/cri-tools/tree/master/images/image-user as per PR kubernetes-sigs/cri-tools#698

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

https://testgrid.k8s.io/sig-node-cri-tools
https://prow.k8s.io/?job=post-cri-tools-push-image-user-multi-arch

**Anything else we need to know?**:

Post submit job added in kubernetes/test-infra#20092

**Comment by chaodaiG** [comment]
So the job says run_if_changed: '^\/images\/image-user\/' at https://github.com/kubernetes/test-infra/pull/20092/files#diff-95554f967ae5f74d1a2e6feaff604d62d18736b332f7b3cb8d88fb3298cdc17eR100, which means it’ll only be triggered if changes include files under /images/image-user . Since https://github.com/kubernetes-sigs/cri-tools/pull/698/files only modifies `images/image-user/cloudbuild-manifests.yaml` file, it’s expected to not be triggered

**Comment by hickeyma** [comment]
@chaodaiG Thanks for the feedback. So, does this mean that it only triggers if files are added/removed from the directory? If so, is there a way to trigger it if an existing file is modified?

**Comment by chaodaiG** [comment]
Other than added/removed, any file change that matches the given regex would trigger this job, so if any file under this directory is modified it'll also trigger this job. I believe as long as the changeset contains file with such a path`/images/image-user/*` it will work.

**Comment by hickeyma** [comment]
Thanks for the help @BenTheElder @chaodaiG
