### ISSUE TITLE
Submit queue should sort by when LGTM *and* Approved were both present

### ISSUE THREAD

**Issue by davidopp** [kubernetes/test-infra#2035]
Currently the submit queue sorts by "First time at which the LGTM label was applied." This is a holdover from when the "can be merged" signal was the LGTM label. Now the "can be merged" signal is presence of both the LGTM *and* Approved labels. As a result, the sort order should be "First time at which the LGTM and Approved labels were both present."

(Personally, I think it should be *most recent* time, not *first time*, but that's completely orthogonal.)

**Comment by davidopp** [comment]
@kubernetes/test-infra-maintainers

**Comment by wojtek-t** [comment]
> Personally, I think it should be most recent time, not first time, but that's completely orthogonal.

I don't agree. Basically this would mean that whenver you need to rebase the PR, it gets to the end of the queue again (because rebase + push of new version removes lgtm label and you need the PR to be lgtm-ed again). That means that if you are unlucky you can potentially never have your PR merged (especially if this is really big and touches a lot of different place in the code).
So I'm really really against it.


> Currently the submit queue sorts by "First time at which the LGTM label was applied." This is a holdover from when the "can be merged" signal was the LGTM label. Now the "can be merged" signal is presence of both the LGTM and Approved labels. As a result, the sort order should be "First time at which the LGTM and Approved labels were both present."

I'm also not 100% convinced about (though maybe it is the right thing to do). The counter argument for this might be that the "owners approval" is in many cases just acceptance of the idea/design etcd, not a very detailed code review. So if noone didn't approve the already lgtm-ed for some time it may not be your fault, but e.g. too-busy approver.

So I would modify your proposal to something:
If the PR was lgtm-ed and then without changes approved (even few days) later, the the "lgtm" signal should be the valid one. But if after lgtm there were other comments, re-pushes, etc. then probably the approve also is required.

**Comment by wojtek-t** [comment]
Now, when I'm thinking about it, I would formulate it as:
1. If PR was lgtm'ed affter approval, then you the time of "lgtm"
2. otherwise, use the time  of "last LGTM before the approval"

**Comment by davidopp** [comment]
Very good point about rebases -- I hadn't thought of that. 

I think what I want is something like "sorted by first time PR became eligible to merge and had no subsequent changes other than rebases." In other words, if you have any change other than a rebase, you go to the back of the line.

I guess I'd also be OK with "LGTM applied" instead of "became eligible to merge" (i.e. had LGTM and Appoved) in the above rule, although as you say it depends a lot on how people are using the "approved" label.

Anyway, these are just my opinions...

**Comment by shyamjvs** [comment]
>
> I think what I want is something like "sorted by first time PR became
> eligible to merge and had no subsequent changes other than rebases." In
> other words, if you have any change other than a rebase, you go to the back
> of the line.
>
IIUC, a rebase is seen as a new commit, and it is possible to have new code
changes (as part of the rebase) other than just fixing rebase conflicts and
there's no trivial way to figure out if such changes have been made. So, we
might still have to remove the PR from the SQ and wait for it to get
re-lgtm'd for the changes as it's as good as a new commit. Am I missing
something here?

**Comment by davidopp** [comment]
There's what is the ideal policy, and what is possible to implement.

We could just say that any commit added immediately after a "needs rebase" message from the bot, is assumed to just be a rebase and not new code. Of course we would still require a re-LGTM from reviewers; this is just from the perspective of sorting the queue.

**Comment by shyamjvs** [comment]
Thanks for pointing this out. However, even with respect to the SQ, it might give me the unfair advantage of being at the top, even though I've added new code just because I did it along with a rebase. This might not be a big deal usually when the SQ is not so long. But close to the code freeze, I might just add some extra code (which ideally should've been in a separate commit) while rebasing, just so I can get my changes pushed faster. If the reviewer is not skeptic enough, this hack would just work for me. Though I'm not very sure how seriously this issue weighs over losing the position in the SQ on rebase.

**Comment by wojtek-t** [comment]
I don't think it happens often that you add new changes during rebase (at least, I'm pretty much never doing this).
That said, in such situation I think we can add an explicit comment for a bot like:
/move_to_back
(probably with better name) and use it together with LGTM.
But I guess it's so rare issue that we may want to ignore it.

[ @shyamjvs - if you are adding new code to already lgtm-ed PRs during rebases, you probably shouldn't]

**Comment by fejta** [comment]
I would really like to keep us focused on minimizing the depth of the queue.

The queue should stay below 10 items. At this size, the location of any PR should matter little. When we start debating where a PR should be on the queue, that is a strong signal that the queue is simply too long.

So I would like us to optimize things such we maximize merge throughput.

**Comment by fejta** [comment]
Closing in favor of prioritizing work that keeps the queue empty at all times.

Note that thanks to batched merges we cleared the entire accumulation of PRs during the 1.6 freeze in a weekend. This is better than investing in complicated prioritization strategies.
