### ISSUE TITLE
Clean up sig-windows-signal 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/test-infra#20542]
**What should be cleaned up or changed**:

```
https://testgrid.k8s.io/sig-windows-releases
```

Has ~ 8 tests that havent passed, in any recent history.

Lets remove the GCE tests from there, or else, see if folks from GCE wanted to fix them ? 

**Provide any links for context**:

https://testgrid.k8s.io/sig-windows-releases

Our goal here is to have a canonical endpoint (https://testgrid.k8s.io/sig-windows-releases) where we can go as the windows sig which give us clear test signal.  

This is espeically important as 
- containerd windows jobs get more common and we remove dockershim,  
- CSI proxy goes GA, 
- multiple CNIs with network policies begin to get integrated into jobs 

Is this ok with you @pjh  @jeremyje

**Comment by pjh** [comment]
Consistently failing tests that I see today under the GCE jobs at https://testgrid.k8s.io/sig-windows-releases:

Kubernetes e2e suite.[sig-network] Services should be able to change the type from ExternalName to ClusterIP [Conformance]
Kubernetes e2e suite.[sig-network] Services should be able to change the type from ExternalName to NodePort [Conformance]
Kubernetes e2e suite.[sig-network] Services should be able to create a functioning NodePort service [Conformance]

Since those are part of the [Conformance] suite, is removing them possible/advisable? Our team needs to look into the failures, not sure how long it will take. If removing them temporarily from these dashboards would be useful then I'm fine with that.

@jayunit100 are there more failing tests that you see somewhere?

Also, looks like gce-windows-1.17 job is consistently failing to start - we'll look at that too.

**Comment by pjh** [comment]
It looks like some "Kubernetes e2e suite.[sig-storage] In-tree Volumes [Driver: windows-gcepd] ..." tests are mostly (but not entirely) failing, as also mentioned in Slack.

This test is also mostly-failing: [sig-cli] Kubectl client Guestbook application should create and stop a working application [Conformance]

**Comment by neolit123** [comment]
> https://testgrid.k8s.io/sig-windows-releases

fix for `kubeadm-windows-gcp-k8s-stable` is here:
https://github.com/kubernetes-sigs/sig-windows-tools/pull/140

**Comment by claudiubelu** [comment]
> 
> 
> Consistently failing tests that I see today under the GCE jobs at https://testgrid.k8s.io/sig-windows-releases:
> 
> Kubernetes e2e suite.[sig-network] Services should be able to change the type from ExternalName to ClusterIP [Conformance]
> Kubernetes e2e suite.[sig-network] Services should be able to change the type from ExternalName to NodePort [Conformance]
> Kubernetes e2e suite.[sig-network] Services should be able to create a functioning NodePort service [Conformance]
> 
> Since those are part of the [Conformance] suite, is removing them possible/advisable? Our team needs to look into the failures, not sure how long it will take. If removing them temporarily from these dashboards would be useful then I'm fine with that.
> 
> @jayunit100 are there more failing tests that you see somewhere?
> 
> Also, looks like gce-windows-1.17 job is consistently failing to start - we'll look at that too.

Note that those 3 tests are passing on ``aks-engine-azure-1-18-windows`` and even on ``gce-windows-1909-1.19``. They are supposed to work. I would assume some DNS misconfiguration is on the gce 1.18 runs.
