### ISSUE TITLE
kOps: Test timeouts are not diagnosable when run in parallel

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#20738]
We have some test timeouts, for example: https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-grid-calico-amzn2-k20-docker

It's very difficult to see what the cause of the timeout is.  It appears that ginkgo only logs tests after they complete, it doesn't log on a signal, it doesn't write the junit output on a signal.  The ginkgo output isn't sufficiently self-descriptive to facilitate scripting.

Possibly passing --progress, --trace or -stream might help here.

We can also try a serial test to see if we can find the problem (I'll probably try this!)

cc @rifelpet

**Comment by BenTheElder** [comment]
this seems like something to fix in kubetest2? 🙃

**Comment by rifelpet** [comment]
thanks to e2e.test's `-test.timeout=` we now have artifacts on [timed out jobs](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-distro-imageubuntu2004/1361760470045822976). I've been doing some investigation trying to pinpoint any specific tests - any tests no longer having its status reported indicates it might be hung. Unfortunately there aren't any consistently missing test results, suggesting that random missing tests might be due to them not yet being ran on a hung ginkgo runner and ginkgo randomizing the order of tests on each runner.

One interesting clue is that all of the jobs that timeout are missing their `junit_01.xml` artifact ([example](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/e2e-kops-aws-distro-imageubuntu2004/1357766288260206592/artifacts/8a7b63b2-67e4-11eb-ab2f-eaa1dd33b81d/)) whereas successful jobs have that file ([kubetest2 example](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kops/10697/pull-kops-e2e-kubernetes-aws-kubetest2/1361541658469994496/artifacts/4adb043f-7014-11eb-b2e0-ba03bd28738d/), [kubetest 1 example](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/e2e-kops-aws-distro-imageubuntu2004/1357645245151449088/artifacts/)). Because [test suites are randomized across ginkgo nodes](https://github.com/onsi/ginkgo/blob/388ac7e50a3abf0798010091d5094171f4aefc0b/ginkgo/run_command.go#L104-L105) this leads me to believe its not a specific test that is at fault, rather something with our configuration of ginkgo, e2e.test, or the prow job container.

Looking at e2e.test flags, besides `--provider` and `--gce-zone` which are being added in https://github.com/kubernetes/kops/pull/10847, our kubetest2 setup is no longer passing these flags:

```
--gce-region=...
--gce-multizone=false
--cluster-tag=<clustername>
--repo-root=.
--num-nodes=0
--disable-log-dump=true
```

I may investigate the impact of these flags. I know that --num-nodes [defaults to the number of ready nodes](https://github.com/kubernetes/kubernetes/blob/c0841211fdafa032c717bdb6f4955fdcfc183464/test/e2e/e2e.go#L266-L271) and is used to [skip certain tests](https://github.com/kubernetes/kubernetes/blob/c0841211fdafa032c717bdb6f4955fdcfc183464/test/e2e/framework/skipper/skipper.go#L153-L165) so we might be no longer skipping certain tests.

[Our serial job](https://testgrid.k8s.io/kops-latest#kops-grid-scenario-serial-test-for-timeout) is timing out after 5 hours, we can consider extending that too.

**Comment by rifelpet** [comment]
The timeouts were fixed by increasing the prow job's memory in https://github.com/kubernetes/test-infra/pull/20931

We also have increased visibility with per-ginkgo-node logs via ginkgo's `--debug` (https://github.com/kubernetes/test-infra/pull/20893) and more useful cluster artifacts when tests timeout (https://github.com/kubernetes/test-infra/pull/20850). I will remove our serial job soon now that we're done with troubleshooting.

/close
