### ISSUE TITLE
Privatize the log for the private repo

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/test-infra#20774]
**What would you like to be added**:
Now, the Prow logs are public, but for some private Github repos, it not a good choice. 
The public logs may leak some sensitive info.

**Why is this needed**:
To protect sensitive info for the private repo.

**Comment by alvaroaleman** [comment]
@jianzhangbjz Can you elaborate on what exactly you want changed here? It is already possible to configure a private bucket and hide jobs from the frontend.

/area prow

**Comment by petr-muller** [comment]
Knowing some background I *assume* this is really an ask for the GH-backed access control for Deck and Spyglass where the frontends would only allow a user to view and access jobs and their artifacts related only to the repos that they can access on GH.

**Comment by BenTheElder** [comment]
[not really a prow maintainer, but some previous context ...]

We've intentionally not tried to put auth into prow directly before, it's possible to run a deck instance with access to privileged logs behind oauth and use this deck for your privileged projects (and better yet consider isolating the whole infra stack, where you may very likely have other issues with cross project security).

Prow currently is not intended as a seriours security boundary ... the existing support to hide jobs from the frontend was something we added quickly to fix some urgent issues with the github.com/kubernetes-security project CI while we figured out a long term plan. Due to staffing and interest we've since spun that down entirely, and was perhaps a questionable approach.

**Comment by petr-muller** [comment]
> We've intentionally not tried to put auth into prow directly before, it's possible to run a deck instance with access to privileged logs behind oauth and use this deck for your privileged projects (and better yet consider isolating the whole infra stack, where you may very likely have other issues with cross project security).

Thanks for the context, I was not around at that time... Yeah, it's certainly tricky to do right and I totally understand the reasoning behind trying to avoid it. The OpenShift Prow instance now grew enough that we now have different group of users that need some private content, but need to see a disjoint set of private repo jobs. And because there are embargos involved, one "private" deck instance does not cut it anymore, so it's possible that someone motivated from RH will try to push this.

**Comment by chaodaiG** [comment]
/remove-lifecycle stale
@petr-muller , has RH started something around this yet? I might be interested in trying a quick prototype some time next week

**Comment by petr-muller** [comment]
@chaodaiG nope, nothing moved on our end. if you could give it a shot it would be great!

**Comment by chaodaiG** [comment]
> @chaodaiG nope, nothing moved on our end. if you could give it a shot it would be great!

Thanks for the info! plans have changed on my end for a little bit, so I might not get to it very soon

**Comment by petr-muller** [comment]
/reopen
/remove-lifecycle rotten

We will still eventually need this :(

**Comment by petr-muller** [comment]
I am very vaguely aware of that effort, thanks a lot for the pointer to the docs! Let's close this issue then, I *think* the `tenant-id` may actually be sufficient for what we need.

/close
