### ISSUE TITLE
Configurator should detect the Prow instance being used and populate `open_test_template`

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#20859]
**What would you like to be added**:
Prow configuration knows about where its hosted (or more specifically, what prefix it should add to access the job viewer) from `job_url_prefix_config`: https://github.com/kubernetes/test-infra/blob/80cdac19030375fd7ee17fca11ddd5a0ec772cd0/config/prow/config.yaml#L6.

The key is either "*", an org, or an org/repo, with the most specific being used.

TestGrid's configuration should populate at least the Dashboard Tab Option [`open_test_template`](https://github.com/GoogleCloudPlatform/testgrid/blob/2ece0ecafcd93a6454d535055c9f22b478b6da65/pb/config/config.proto#L522) (and potentially `results_url_template`) using this information.

Currently, these are being populated for all users using a default setting in TestGrid: https://github.com/kubernetes/test-infra/blob/d34feb5af1fd5a07bd963ea04637f7039b3b00fb/config/testgrids/default.yaml#L22-L25

**Why is this needed**:
There are some use cases where TestGrid configuration is being imported from a different Prow instance (see [Transfigure](https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/transfigure)), requiring users to set their own local defaults to display correctly.

Example: https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubevirt/default.yaml

Unfortunately (and unrelated), nested defaults don't actually work.  https://github.com/kubernetes/test-infra/issues/20756
This enhancement would reduce our reliance on nested defaults and would make Prow and TestGrid operate more independently of their specific instance.

/help-wanted

**Comment by chases2** [comment]
@michelle192837 @alvaroaleman This seems like a reasonable integration to me. What do you think?

**Comment by fgimenez** [comment]
I'd like to give this one a try, was planning to start looking into https://github.com/kubernetes/test-infra/blob/4ddcfd375fcd021a16f696aa83b4bbbbd5c9ba91/testgrid/cmd/configurator/main.go#L192-L211 is that correct?

thanks!

**Comment by spiffxp** [comment]
/remove-help
/assign @fgimenez 
@fgimenez mentioned on slack being interested to take this on

**Comment by spiffxp** [comment]
I would try modifying [applySingleProwJobAnnotation](https://github.com/kubernetes/test-infra/blob/611b1212d9b9933f613dce33a2a8bbdacfd96994/testgrid/cmd/configurator/prow.go#L75) for this change

For examples of the logic that gets the most relevant `job_url_prefix_config` see: 
- https://github.com/kubernetes/test-infra/blob/611b1212d9b9933f613dce33a2a8bbdacfd96994/prow/config/config.go#L519
- https://github.com/kubernetes/test-infra/blob/611b1212d9b9933f613dce33a2a8bbdacfd96994/prow/pjutil/pjutil.go#L281

The testgrid configurator currently deals with `config.JobBase` instead of `prowapi.ProwJob`.  Ideally, we could modify prow's code to support getting this without a full fledged ProwJob CRD.  Otherwise it looks like you'll want to find the code path that allows you to convert from one to the other.

For an example of code that sets a testgrid property based on prowjob info, see
https://github.com/kubernetes/test-infra/blob/611b1212d9b9933f613dce33a2a8bbdacfd96994/testgrid/cmd/configurator/prow.go#L185-L200

**Comment by spiffxp** [comment]
/reopen
I think https://github.com/kubernetes/test-infra/pull/20902 caused https://github.com/kubernetes/test-infra/issues/20988, followup PR to fix: https://github.com/kubernetes/test-infra/pull/20987

Can manually close when we confirm things still work as expected

**Comment by chases2** [comment]
Links to spyglass are now working as intended. Closing issue. Thanks!
