### ISSUE TITLE
Prow issue: Internationalization

### ISSUE THREAD

**Issue by MjAbuz** [kubernetes/test-infra#21002]
DCO Signed Off By @MjAbuz azmikbal@gmail.com

**Comment by BenTheElder** [comment]
Hi: Do you have more details on what you're looking for here?

In most contexts I would suspect internationalizing Prow is impractical, as Kubernetes development is in english and comments are posted publicly for all readers instead of directly to one individual or grouup.

Aside: This project does not use the DCO and I've never seen DCO signatures on issues 🤔
