### ISSUE TITLE
Cherrypicker only applied a single cherrypick

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#21684]
**What happened**:

In PR https://github.com/istio/istio/pull/31798, the cherrypicker only applied to release-1.8

**What you expected to happen**:

Cherrypick applies to release-1.9 as well

**How to reproduce it (as minimally and precisely as possible)**:

Not sure, see PR above for context

**Please provide links to example occurrences, if any**:

https://github.com/istio/istio/pull/31798

**Comment by alvaroaleman** [comment]
Possibly a duplicate of https://github.com/kubernetes/test-infra/issues/21714

**Comment by matthyx** [comment]
@howardjohn I think in this case it failed to create the cherry pick for `release-1.8` and stopped here:
https://github.com/kubernetes/test-infra/blob/ef7abaaa70ae3626c5243a117d1d6955e56d4c08/prow/external-plugins/cherrypicker/server.go#L374

If you want, I could change the code to try on all branches and report an aggregated error at the end, instead of stopping at the first one.

**Comment by howardjohn** [comment]
Great! thank you
