### ISSUE TITLE
Feature Request: Prow: Pods w/out Commands/Args

### ISSUE THREAD

**Issue by aryeh-looker** [kubernetes/test-infra#22571]
**What would you like to be added**:

Ability to spin up a container without needing to provide a command or arg and have the container exit when all others have exited automatically.

**Why is this needed**:

It can be useful to have a test container and a container running a database side-by-side, with the database container starting (without necessarily needing a command/arg; see https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/#deploy-mysql for an example with MySQL) and exiting once the test container has exited.

**Comment by aryeh-looker** [comment]
Nice, but would call it low priority — have some workarounds.

**Comment by BenTheElder** [comment]
I think what you are describing is roughly `decorate: false`.

To get the magic that comes with `decorate: true` you unfortunately need to set the command. This is because the command is actually replaced in the pod with a prow tool that wraps the command, and that tool needs to know what command to replace.

The whole system could be designed differently, but it's not a minor change.

https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md

/area prow
/area prow/pod-utils
