### ISSUE TITLE
Add support for treating ProwJob workload containers as sidecar containers.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#22829]
**What would you like to be added**:
A way to indicate that one or more (but not all) of the workload containers in a ProwJob should be treated as sidecar containers. This means that they are sent a termination signal when the non-sidecar workload containers have all completed. I'd expect this to be configured as a new decoration_config field that is a list of container names to treat as sidecars.

**Why is this needed**:
Currently if a multi-container ProwJob includes a supporting container that needs to exist for the lifetime of the primary workload container, the job must include its own logic for signalling the supporting container to terminate. Since decorated ProwJobs already wrap workload containers with the `entrypoint` process in order to work with the `sidecar` pod utils component, we could simply extend the existing functionality to support treating some workload containers as sidecars.

It seems like progress on fixing this upstream has stalled so it may be worth adding support via the pod utilities: https://github.com/kubernetes/kubernetes/issues/25908#issuecomment-774743426

cc @alvaroaleman @chaodaiG @stevekuznetsov @fejta

**Comment by noahkawasakigoogle** [comment]
+1 thanks for filing this

**Comment by alvaroaleman** [comment]
conceptionally that makes a lot of sense, I am slightly concerned that it will end up being quite complicated (but open to be convinced otherwise)

**Comment by cjwagner** [comment]
> conceptionally that makes a lot of sense, I am slightly concerned that it will end up being quite complicated (but open to be convinced otherwise)

Here is what I'm thinking so far:
1. We add a new decoration_config field that is a list of container names to treat as sidecars
2. This field is wired through to the `sidecar` pod util.
3. Rather than waiting for all marker files to be written, only non-sidecar marker files will be waited on.
4. When all non-sidecar containers complete, terminate the sidecar containers by sending interrupt signals to their `entrypoint` wrappers.
5. `entrypoint` wrappers pass signal to sidecar processes and ensure graceful termination (this is already how things work).
6. `sidecar` can then wait for the sidecar containers to write their marker files and finish normally.

There is one part I'm not clear on how to accomplish which is (4) having the `sidecar` pod util send interrupt signals to the sidecar `entrypoint` wrappers. Any ideas what the best way to do this would be?

**Comment by noahkawasakigoogle** [comment]
Are there any ways to workaround this currently? 

I've got a main test runner container successfully killing other containers at the end of a job within its own pod by sending SIGTERM through `kubectl` commands, giving the pod permissions to exec into pods, and using the downward API to find its own Pod Name. 

However, as expected, this causes the the killed containers to have the entire job marked as a failure since not all containers exit'd 0.

I looked into setting [`AlwaysZero`](https://github.com/kubernetes/test-infra/blob/master/prow/entrypoint/options.go#L61) via a container's [`ENTRYPOINT_OPTIONS`](https://github.com/kubernetes/test-infra/tree/master/prow/entrypoint) but these didnt seem to make any difference.

If implementing the full logic in Prow itself sounds complicated, even just the ability to mark a container like `ignore_failures: true` or `always_zero: true` would be enough since people can handle the container killing outside of built-in Prow functionality.

**Comment by cjwagner** [comment]
> Are there any ways to workaround this currently?

You could try sending a different signal than SIGTERM to the sidecar(s) (e.g. SIGUSR1) and have the sidecars exit gracefully with an exit code of zero. SIGTERM can't be used for this case because `entrypoint` treats that specifically as an abort signal in order to mark the ProwJob as aborted rather than succeeded or failed. I think this would also require changes to `entrypoint` to forward that signal, but that would be straightforward and potentially generally useful.

I don't really like the idea of adding an `ignore_failures` or `always_zero` field since I can't think of a use outside of this kind of scenario and this scenario would be better to address completely within Prow rather than requiring users to supply half the implementation in their workload containers.
