### ISSUE TITLE
etcd versions

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#2300]
AIUI the version of etcd that will be installed by default in k8s 1.6 is `3.0.17`, but we will continue to support `2.2.1`.

* Some of the jobs still specify `3.0.14` (e.g. ci-kubernetes-e2e-gce-etcd3-release-1.5.env, but maybe this is because it is 1.5?, but ci-kubernetes-e2e-non-cri-gce-etcd3 is more suspicious).

* Some of the jobs still specify `2.2.1`, despite not being designated `etcd2` (pull-kubernetes-e2e-gce-canary.env, ci-kubernetes-e2e-gce.env)

* I thought also that we were going to double up on all 1.6 jobs, with etcd2 and etcd3, while we supported both versions of etcd... )

**Comment by ixdy** [comment]
cc @wojtek-t @kubernetes/release-team

**Comment by wojtek-t** [comment]
> Some of the jobs still specify 3.0.14 (e.g. ci-kubernetes-e2e-gce-etcd3-release-1.5.env, but maybe this is because it is 1.5?, but ci-kubernetes-e2e-non-cri-gce-etcd3 is more suspicious).

Fixed in https://github.com/kubernetes/test-infra/pull/2309

> Some of the jobs still specify 2.2.1, despite not being designated etcd2 (pull-kubernetes-e2e-gce-canary.env, ci-kubernetes-e2e-gce.env)

Those are kind of designated to etcd v2.

To clarify - the "ci-kubernetes-e2e-gce.env" is pretty much a copy of "ci-kubernetes-e2e-gce-etcd3.env" - the only difference is that one is using etcd v3 and the other etcd v2.
The same for the corresponding pull jobs.
Regarding canary - i think this is something experimental of test-infra team.

> I thought also that we were going to double up on all 1.6 jobs, with etcd2 and etcd3, while we supported both versions of etcd... )

Duplicating everything would be very expensive. As I wrote above, we have two copies of the main set of tests using etcd v2 and etcd v3 respectively. And the same for presubmit jobs. And all of them are submit-queue blocking.
So we are pretty much testing both etcd v2 and etcd v3 modes. And i'm not aware of any etcd-related but that has been discovered in non-main suite and was also not present in the main suite. So i think that what we are doing is pretty safe.
