### ISSUE TITLE
Not able to deploy custom resources

### ISSUE THREAD

**Issue by iamrsaravana** [kubernetes/test-infra#23322]
custom resource is not able to create it

my custom resource :

"topic.yaml"
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
name: my-pythontesttopic
labels:
strimzi.io/cluster: my-cluster
spec:
partitions: 3
replicas: 3
config:
retention.ms: 7200000
segment.bytes: 1073741824

body = yaml.safe_load("topic.yaml")
client_app =client.AppsV1Api()
client_app.create_namespaced_deployment(namespace="kafka", body=body, pretty=true)

i am getting below error message:
![image](https://user-images.githubusercontent.com/7235459/130183261-545c90be-80e5-4ffb-94e6-9bf96f34a472.png)

**Comment by alvaroaleman** [comment]
Please re-post your question to our [Discussion Forums](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Discussion Forums to field
support requests. Before posting a new question, please search these for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

/close
