### ISSUE TITLE
Prow issue: Support /assign me

### ISSUE THREAD

**Issue by karuppiah7890** [kubernetes/test-infra#23325]
I noticed someone tried to say `/assign me` and the bot didn't support it - https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2686#issuecomment-902138469

It's an interesting thing. `/assign me` sounds like saying a sentence and sounds intuitive too. It would be cool to support it if that's possible!

**Comment by karuppiah7890** [comment]
I'm not sure what SIG this comes under. I just know this is related to the Prow Bot https://github.com/k8s-ci-robot , also because when I clicked on the repo link in this message https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2686#issuecomment-902138479 it took me here with the title `Prow issue` which I just retained

**Comment by karuppiah7890** [comment]
SIG Testing maybe?

**Comment by MadhavJivrajani** [comment]
Allowing `/assign me` _might_ be an issue because there is a GitHub user by the name [`me`](https://github.com/me). `/assign` would assign someone in the following scenarios:
- The to-be-assignee comments `/assign` or `/assign assignee` or `/assign @assignee`
- Someone assigns the assignee by `/assign assignee` or `/assign @assignee` provided the assignee has commenting on the issue/is part of the org that repo is under/is a collaborator on the repo.

In either case, `/assign me` will have conflicts (as also seen by the linked comment)

**Comment by karuppiah7890** [comment]
Ah. Didn't know /assign username is supported too, apart from /assign @username . Cool ! I guess it's a tricky thing then. I'll close the issue
