### ISSUE TITLE
cadvisor-push job is not working

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/test-infra#23868]
**What happened**:

Job https://testgrid.k8s.io/sig-node-cadvisor#cadvisor-push is not working

**What you expected to happen**:

Job will be green or removed if not used

/sig node
/cc @mmiranda96 
/cc @bobbypage 
/kind failing-test

**Comment by bobbypage** [comment]
It looks like this job has been failing for a very long time. It looks like this job was responsible for building a canary version of cAdvisor and pushing it to dockerhub. We haven't been using the canary versions for as long as I can remember, and the target being pushed to (dockerhub: google/cadvisor:canary) is not up to date either (we have long switched to GCR instead of dockerhub).

I think we should delete this job since it's not being used anyways.

**Comment by SergeyKanzhelev** [comment]
What does this test do: https://testgrid.k8s.io/sig-node-cadvisor#cadvisor-e2e? Doesn't seem it test anything at all.

**Comment by bobbypage** [comment]
https://testgrid.k8s.io/sig-node-cadvisor#cadvisor-e2e is different, it will run kubetest against cadvisor test suite:

```
W1001 20:19:02.148] Run: ('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--deployment=node', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--gcp-project=ci-cadvisor-e2e', '--gcp-zone=us-central1-f', '--node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/image-config.yaml --test-suite=cadvisor', '--node-tests=true', '--test_args=--nodes=1', '--timeout=10m')
```

That will basically clone cAdvisor and run the integration tests - https://github.com/kubernetes/kubernetes/blob/82da9bdaab705a1a72e4c5915f6ddd8775592fdf/test/e2e_node/remote/cadvisor_e2e.go#L66-L76

I think long term we can move this out of k/k testgrid and into github actions on cAdvisor repo, but for now, it doesn't hurt to keep it.
