### ISSUE TITLE
Do not run CI tests when a PR needs rebase

### ISSUE THREAD

**Issue by manugupt1** [kubernetes/test-infra#24245]
**What would you like to be added**:
I pushed a commit that needed a rebase as it had a merge conflict.
https://github.com/kubernetes/kubernetes/pull/104049
The PR started the test because ok-to-test was applied. 

**Why is this needed**:
1. If a PR does have merge conflicts, not saving the CI would save resources for other PRs that do not have merge conflicts.
2. It reduces the number of comments from the ci-robot for test failures as well leading to a better reviewer experience.

/sig testing

**Comment by petr-muller** [comment]
/lifecycle-remove stale

I still want this

**Comment by chaodaiG** [comment]
This should only be applied to presubmit jobs as:
- Merged PRs should not have merge conflict, so not applicable to postsubmit jobs

The GitHub PullRequest webhook event already contains `Mergeable` field https://github.com/kubernetes/test-infra/blob/d8035cceb460e2f65888a6c2c7afa0c77af09796/prow/github/types.go#L273 that can be used for checking whether the PR is mergeable or not. According to the documentation that this field might not have been computed but since this is the best effort, it's still better than always trigger.

The only place that need to change is in `plugins/trigger`, https://github.com/kubernetes/test-infra/blob/master/prow/plugins/trigger/trigger.go, should check this field right before triggering.

One thing could happen is that:
- Commit-1 passed all prowjobs
- Commit-2 has a merge conflict

So not triggering prowjobs on Commit-2 means that all prowjobs still displayed as passing, which is fine as:
- PR with merge conflict won't be merged any ways
- Tide will ensure that prowjobs run against latest commits

/help
/label good-first-issue

**Comment by amirrmonfared** [comment]
Hey @Akshit42-hue are you still working on it? I'm interested, please assign me if you don't. thanks

**Comment by Akshit42-hue** [comment]
Hey @amirrmonfared, I am not working you can take it
For assigning just write /assign and the k8s-ci-robot will assign you 
For reference [comment](https://github.com/kubernetes/test-infra/issues/24245#issuecomment-1272310632)

**Comment by Sajiyah-Salat** [comment]
Hello @amirrmonfared this pr is already merged and probably this issue is solved please close this pr.

**Comment by amirrmonfared** [comment]
Hello @Sajiyah-Salat thanks for reminding me!

**Comment by amirrmonfared** [comment]
@droslean can you please close this issue?

**Comment by SD-13** [comment]
closing this as resolved
/close
