### ISSUE TITLE
Tide doesn't always start a batch when it should

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#24526]
**What happened**:

I noticed on a repo that multiple PRs got merge ready and just missed retesting (i.E. had all required labels and had passing, but outdated tests). Tide didn't start a batch, instead it seemed to have started serial retests for all of them. The PRs didn't get merge ready at the exact same time.

**What you expected to happen**:

Tide to start a batch

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a PR that fullfills all merge requirements but has outdated tests
2. Wait until tide starts a serial retest for that PR
3. Make another PR ready for merge except that it has outdated tests

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

I _think_ the issue is the `isPassingTests` function in `pickBatch`, we only look at the head contexts of the PR to see if it has passing tests. If Tide already started a serial retest, that context will be `pending` and not `success`. We also need to look at the prowjobs in the cluster. https://github.com/kubernetes/test-infra/blob/2701887636e5966ecda3c725da5970f9da9d2739/prow/tide/tide.go#L765-L775

/area prow
/area prow/tide

/cc @cjwagner @chaodaiG

**Comment by alvaroaleman** [comment]
I always get a headache when I try to reason about what Tide does, so I'd appreciate it if you could factcheck the following @cjwagner :

1. subpool PJs is all prowjobs for a given subpool with a current baseSHA
2. In `accumulate()` we find "pending" PRs by finding PRs that have pending or success jobs for all required jobs
3. This means that we correctly start at most one serial retest at a time, as we wont start one if there is at least one PR "pending"
4. However, the PR that is being retested ends up being excluded in `accumulateBatch()` (as it now has pending head contexts instead of success head contexts)

So this issue only happens in situations where we could have started a batch of size two but if a bigger batch is possible what we do is correct?

More things that make reasoning here hard are:
* PRs that fail serial retesting will not be retested again by Tide
* There can be PRs that have all required labels and pending tests but not because of retesting. In that case the status context shows "Retesting: $some_job" even though it is not actually retesting, it is still the initial testing (and probably a bug in itself?)

**Comment by cjwagner** [comment]
1. Correct.
2. Yes, this can now also be inferred from the status context if the ProwJob was GCed.
3. Yes, Tide will only start a serial retest if there are no others. Humans can trigger serial retests directly though and they will be respected by Tide.
4. No, that PR wouldn't have been considered by `accumulateBatch` at all because `accumulateBatch` only considers batch ProwJobs and we haven't created one yet.

> So this issue only happens in situations where we could have started a batch of size two but if a bigger batch is possible what we do is correct?

I don't think this is limited to batches of size two, the issue is more that we can fail to include PRs in a batch retest because they are already being serially retested. This could happen with any number of PRs in the pool.


> * There can be PRs that have all required labels and pending tests but not because of retesting. In that case the status context shows "Retesting: $some_job" even though it is not actually retesting, it is still the initial testing (and probably a bug in itself?)

Are you just referring to the incorrect wording of "Retesting job-name" rather than "Testing job-name"? I agree that is misleading and potentially a bit confusing, but I'm not sure that it is something that is important to fix. Users should treat them the same.


> I _think_ the issue is the `isPassingTests` function in `pickBatch`, we only look at the head contexts of the PR to see if it has passing tests. If Tide already started a serial retest, that context will be `pending` and not `success`. We also need to look at the prowjobs in the cluster.

This seems right to me. In particular we'd need to look at the newest run of each required presubmit for the PR at the current PR Head SHA, but at any base SHA (as long as the run of the job is the newest) and make sure we have a passing required set. Only considering the newest job run for each required job is important because if a presubmit on a PR becomes broken due to base branch changes we don't want to include it in the batch.
