### ISSUE TITLE
Fix ci-kubernetes-soak-gce-federation-test

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/test-infra#2457]
This job is broken due to problems in the corresponding deploy job. It has been in this state for a while due to test-infra issues and @shashidharatd has been tirelessly working on it. This issue is to track the progress towards making the soak test work.

**Comment by madhusudancs** [comment]
cc @kubernetes/sig-federation-bugs

**Comment by fejta** [comment]
Please:
* Recreate this issue in kubernetes/kubernetes 
* Add at least one sig and area label
* Link back to https://github.com/kubernetes/test-infra/issues/2453

**Comment by madhusudancs** [comment]
@fejta this is a test infra issue because it's not the tests that are broken, but the infrastructure itself. If you still think this should be filed in the core repo, I will be happy to move it. But this is really the right place IMO.

**Comment by shashidharatd** [comment]
@madhusudancs, @fejta,
I analyzed the latest failures in federation soak deploy job and below is my finding.
federation soak deploy job is failing to find `hyperkube` image which is pushed by federation-soak-build job. this is happening because we are using `ci/latest` version to run the job and it may happen that `ci/latest` version is recently updated with non-federation build.
This problem is not there in federation jobs apart from soak ones because in those builds, build and deploy jobs are chained. But in soak jobs the jobs are time triggered and there is no link between federation-soak-build and federation-soak-deploy.
Solution-1
So one solution is to add a reverse trigger from federation-soak-deploy job to federation-soak-build. I am not sure how feasible is this approach, as it may impact other soak jobs which don't have dependencies.
Solution-2
Publish a federation release into release-bucket. Then we can use something like `ci/federation-latest` to find latest federation release.

let me know your opinion.

**Comment by fejta** [comment]
Yes please move this into the primary repo. And understood that this is not the tests failing. Thanks!

**Comment by ixdy** [comment]
@shashidharatd option 3 is to block the federation-deploy job from running while the federation-build job is running. That is a 1-line fix.

**Comment by madhusudancs** [comment]
@fejta @ixdy @shashidharatd moved the discussion to https://github.com/kubernetes/kubernetes/issues/44402
