### ISSUE TITLE
A push after tag should cancel or skip the tag

### ISSUE THREAD

**Issue by soltysh** [kubernetes/test-infra#24609]
**What happened**:
We are using prow also in openshift, and in this particular PR: https://github.com/openshift/library-go/pull/1259
the situation was that I tagged the PR for merge, but the time between my tag and bot reaction was pretty long.
Roughly 20mins, due to rate limits (as I learned) and in between we got test results which failed and Mike updated
the PR and re-pushed it. So the timeline looks like this:

T0: me tagging a PR
T0+14min: Mike does a re-push
T0+19min: bot picks my tag and applies the label

**What you expected to happen**:
I'd expect that if there was a push between the tag and when the bot reacted to it, it should not apply the label and comment that a change was detected.

**How to reproduce it (as minimally and precisely as possible)**:
See above timeline. 

**Please provide links to example occurrences, if any**:
https://github.com/openshift/library-go/pull/1259

**Comment by BenTheElder** [comment]
To clarify: "tag" here is a github label (like `lgtm`, `approved`)?

I believe it is a known issue that tide is racy WRT once a PR has been considered for merge and is being retesting vs when it is merged, but I can't seem to quickly turn up previous discussion

/area prow
/area prow/tide

**Comment by petr-muller** [comment]
@BenTheElder yes, this talks about labels. In this case it is not related to Tide. The race here occurs because there is a window between someone doing a `/lgtm` and when the label is eventually applied. We have periods of time when Prow components are rate-limited, which can delay the actual label setting by minutes, and when the rate-limit is eventually lifted, the accumulated handlers that got stuck in client-side retry loops (Prow's GH client waits and retries GH calls that get rate-limited) start racing.

**Comment by BenTheElder** [comment]
That's extra exciting :-)

I don't think there's a good answer for this without substantially redesigning prow, since github-labels-as-a-state-store is inherently creating race conditions in this context
