### ISSUE TITLE
Enable all verify checks on presubmit

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2493]
ci version uses `--force`: https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L219
pull version doesn't: https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L402

Let's make the pull version (which runs on presubmit) use `--force` and then downgrade the ci version to non-blocking (since it just duplicates what we already ran on presubmit).

blocking list: https://github.com/kubernetes/test-infra/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L105

Scenario: https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_verify.py#L88

**Comment by ixdy** [comment]
The reason we don't `--force` in PRs right now is that the disabled checks are very slow.

**Comment by ixdy** [comment]
The reason we don't `--force` in PRs right now is that the disabled checks (which relate to godeps) are very slow.

We do run these checks when there are godep changes, but there's little signal provided by running them otherwise.

We force run the checks in CI because upstream changes can potentially break them (e.g. if a URL changes). We don't want to wait until the next time someone changes a godep to realize that things are broken.

**Comment by spxtr** [comment]
It seems to add about 10 minutes to the runtime, judging by [this](https://prow.k8s.io/?type=presubmit&job=pull-kubernetes-verify&state=success) vs [this](https://k8s-testgrid.appspot.com/google-unit#verify-master&graph-metrics=test-duration-minutes).

**Comment by rmmh** [comment]
it's also *really* flaky

**Comment by spxtr** [comment]
I've always found the verify-godep step a little suspicious. One major reason to vendor code in the first place is that if it breaks or disappears upstream then we don't break. Say we vendor a library called `github.com/spxtr/left-pad`. At some point I delete this repo from GitHub. Because kubernetes vendors the library, everything still builds fine. From a code perspective, no change is made. However, we'll block all merges until we no longer depend on `left-pad`, which is a bit absurd.

**Comment by fejta** [comment]
I want to pick one of these perspectives and act on it:
* Regressions in the `--force` checks are important enough that we want to block everyone's merges on it, so we run it in presubmit
* We do not need `--force` checks to block everyone's merges, so we take it out of the blocking suite

The current situation -- we do not test this on presubmit and yet block everyone's merges when it fails -- is an absurd state of affairs.

**Comment by rmmh** [comment]
I'm fine with 2. We *do* do vendor tests on presubmit if a file with the right smell changed (vendor or one of its metadata files). I'm fine with taking it out of the blocking suite. 

It has failed a few times when upstream goes away or does something weird, but that's something we can fix asynchronously.
