### ISSUE TITLE
Eliminate all prioritization logic from submit queue

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2496]
We expect the queue to remain at or near a depth of zero at all times. Batched merges ensure this is possible by increasing the maximum merge capacity.

When we did not have batched merges it would often take a week or more to merge code. This resulted in our adding a lot of complicated logic to the submit queue to order things correctly.

We want to favor maximizing the chance that a batched run can merge all the things, so eliminate reordering:
* based on priority labels: https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/submit-queue.go#L1114
* based on retest not required labels: https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/submit-queue.go#L1286

(we should still skip retesting with the retest not required labels, but we should only add things to the end of the queue)

**Comment by spxtr** [comment]
I'm generally in favor, but I think there are still cases where skipping the queue is appropriate. https://github.com/kubernetes/kubernetes/pull/40777 is an example. This PR will cause a merge conflict with just about any other PR in the repo. It is extremely difficult to get it to merge without priority labels.

**Comment by fejta** [comment]
A queue depth of zero generally resolves that problem, and manually merging a PR can handle this kind of (rare) scenario.

**Comment by spxtr** [comment]
A queue depth of zero doesn't resolve it, but manually merging does.

The reason a queue depth of zero doesn't resolve it is because it takes so long for presubmits to run. Once the PR gets booted off the queue, Mike has to rebase it, and it takes a full hour for it to get back on the queue again, or longer if it hits a flake. During that hour, if any other PR finds its way onto the queue then it will merge before Mike's and cause another rebase, ad infinitum.

That's why we should just ask build-cop to merge it for us :)

**Comment by fejta** [comment]
/area prow
/assign @spxtr 

Solving this with tide

**Comment by kargakis** [comment]
I think we can close this now - tide has no prioritization logic. 

/close
