### ISSUE TITLE
Prow issue: Kube-proxy did not come upon K8s Installation on Debian10

### ISSUE THREAD

**Issue by cpsrujana** [kubernetes/test-infra#25610]
We have installed Kubernetes using kubespray. we have observed that kube-proxy didnot come up. kubeadm-config.yaml has the required kubeproxy configuration.

In the api server logs, there is an error to connect etcd.
And etcd container seems to be recreated during that time.

Can somebody help me in understanding the root cause of this issue. We are trying on a fresh machine.

Below is the content from apiserver pod log.
I0310 20:53:39.554375 1 clientconn.go:825] blockingPicker: the picked transport is not ready, loop back to repick
I0310 20:53:39.554458 1 clientconn.go:825] blockingPicker: the picked transport is not ready, loop back to repick
W0310 20:53:39.554680 1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.27.172.191:2379/ 0 }. Err :connection error: desc = "transport: Error while dialing dial tcp 172.27.172.191:2379: connect: connection refused". Reconnecting...
W0310 20:53:39.554766 1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.27.172.191:2379/ 0 }. Err :connection error: desc = "transport: Error while dialing dial tcp 172.27.172.191:2379: connect: connection refused". Reconnecting...
W0310 20:53:39.554919 1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.27.172.191:2379/ 0 }. Err :connection error: desc = "transport: Error while dialing dial tcp 172.27.172.191:2379: connect: connection refused". Reconnecting...
I0310 20:53:39.554925 1 clientconn.go:825] blockingPicker: the picked transport is not ready, loop back to repick

**Comment by alvaroaleman** [comment]
Please re-post your question to our [Discussion Forums](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Discussion Forums to field
support requests. Before posting a new question, please search these for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

/kind support
/close
