### ISSUE TITLE
Prow issue:

### ISSUE THREAD

**Issue by vanthony022** [kubernetes/test-infra#25667]
/sig @k8s-ci-robot 
I'm using EKS version : 1.18,

Steps:
1.I created my database service with Loadbalancer type
2.I gave the security group rule permission to my company ip xx.xx.xx.xx/32
3.I find the that security group changed to worldwide 0.0.0.0/0 again and again.
4.From cloud trail, it showed clusterRole is changed the securitygroup to 0.0.0.0/0 it automatically.

pls let me know the solution
this is critical

**Comment by alvaroaleman** [comment]
Please re-post your question to our [Discussion Forums](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Discussion Forums to field
support requests. Before posting a new question, please search these for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

/kind support
/close
