### ISSUE TITLE
`/link org/repo#NNN` to *link-a-pull-request-to-an-issue*

### ISSUE THREAD

**Issue by hh** [kubernetes/test-infra#26019]
**What would you like to be added**:

Prow plugin to respond to `/link org/repo#NNN` to link a PR to a pull request without closing it.

**Why is this needed**:

We don't want issues prematurely closed via keywords, and more and more often we have Issues that are linked to multiple PRs.
https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#github-keywords

**Starting Point**:

It is possible for a github account with write permissions to the repo to do the linking:

https://docs.github.com/en/enterprise-server@3.2/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue

**Comment by hh** [comment]
No Public API at initial glance: https://docs.github.com/en/rest/reference

**Comment by BenTheElder** [comment]
the lack of a public API seems likely to mean this issue is not resolvable.

**Comment by JohnTitor** [comment]
Hmm, I don't get the point here. Linking a PR to issues will close them once it's merged. What difference between using GitHub keywords on OP are you looking for?

**Comment by hh** [comment]
Some groups use project boards to organize the work, with umbrella issues
that show multiple linked PRs (and their status) in the UI.
This even supports a table mode view. For project management this is very
useful.

- A single PR may be linked / or address several issues.
- GitHub default of closing an issue automatically is something we want to
avoid, hence k8s has a policy (and bot enforcement) against merging PRs
with keywords that link.
- Manual linking is possible, but requires write access to the repository.

**Comment by BenTheElder** [comment]
> hence k8s has a policy (and bot enforcement) against merging PRs
> with keywords that link.

We have a policy and bot enforcement against *commits* that link issues, because github will close the issue on every merge of the commit, even into forks (!)

PRs with "fixes #issue_number" are common, fine, and not against policy.

This remains an untenable feature request if no API exists, regardless.

**Comment by JohnTitor** [comment]
> - Manual linking is possible, but requires write access to the repository.

This makes sense as a bad actor can close any issues if a PR author/reviewer doesn't notice.
So is this for members who don't have the write access but org members (e.g. only have triage access)? I asked because I couldn't come up with a usecase.

> PRs with "fixes #issue_number" are common, fine, and not against policy.

Yeah, looking at some PRs on the org, this seems correct.
Anyway, yes, I also checked GraphQL API but it seems an API we want doesn't exist unfortunately.
