### ISSUE TITLE
Assign to PR author when PR title includes [WIP]

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2620]
/cc @cjwagner

**Comment by grodrigues3** [comment]
cc @kubernetes/sig-contributor-experience-misc

**Comment by xiangpengzhao** [comment]
What do we expect the author to do as an assignee?

**Comment by cjwagner** [comment]
I believe assignees are usually used to indicate who is responsible for getting the PR reviewed and merged (or helping to do so). This issue seems low priority though because a WIP PR is obviously the responsibility of the author and adding them as an assignee doesn't really change the expectations we have of them. I don't see any benefits to automatically assigning the author besides making it clear that they are responsible for completing the PR before it can proceed, but I think that is already apparent to the author given that they included a [WIP] tag.

**Comment by cblecker** [comment]
Someone can open a WIP PR for a number of reasons.. perhaps it's because they want CI to run, or perhaps it's because they know CI will fail, but they want review on the implementation direction. Assigning to the author isn't intuitive for newer contributors who may want review assistance.

@kubernetes/sig-contributor-experience-pr-reviews

**Comment by kargakis** [comment]
@cblecker how often new contributors tag their PRs as WIP? I can't remember seeing any from the reviews I've been doing for sig-apps related stuff the past year.

**Comment by kargakis** [comment]
That being said, I agree with @cjwagner. I think I would rather we not do this.
