### ISSUE TITLE
[BUG] Spyglass doesn't load anything

### ISSUE THREAD

**Issue by droslean** [kubernetes/test-infra#26344]
Spyglass doesn't load anything.

How to replicate?

Just open a spyglass page from any of the jobs in https://prow.k8s.io/

**Comment by smg247** [comment]
Note: we reverted our most recent bump including https://github.com/kubernetes/test-infra/compare/69ff551a87...bc723c0e51 and it is working again on OpenShift. None of those changes jump out as being a potential cause, but something seems to be...

**Comment by oliver-goetz** [comment]
Same at our prow installation for Gardener

**Comment by chaodaiG** [comment]
This is very much likely due to a flake in image building process. I have kicked off the prow images building job on the exactly same commit and deck works fine on prow.k8s.io with the newly built image.

For any affected party bumping forward should also fix.

I'll create a separate issue tracking the investigation of the image build flakiness.
