### ISSUE TITLE
Status Reconciler triggers a presubmit prowjob for all pull requests in a repo

### ISSUE THREAD

**Issue by qaifshaikh** [kubernetes/test-infra#26482]
**What happened**:
Status Reconciler triggers a presubmit prowjob for all pull requests in a repo whenever we add a new presubmit prowjob or change its regex

**What you expected to happen**:
A presubmit prowjob should only trigger for relevant pull requests whenever we add a new presubmit prowjob or change its regex

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by smg247** [comment]
We just encountered this problem with a presubmit change in `openshift` as well. It seems that it is not honoring the `run_if_changed` configuration.

**Comment by smg247** [comment]
Just a note for anyone who finds this one. I was able to workaround this issue by using the following workaround:

1. Add/change the presubmit to a simple command that just runs `echo SUCCESS`. Make sure you use the real `name`, and `trigger`/`run_if_changed`/`skip_if_only_changed` values that you want in the real check. (it isn't important what the test does, we just want it to be cheap and always pass)
2. This check will get added to the context on all active PRs and immediately run and pass.
3. Wait a bit for all of the jobs to trigger.
4. Swap the dummy check's image/command/etc.. out for the real one. Since the check already exists on the open PRs it will **not** be added again.
