### ISSUE TITLE
[peribolos] Adding new empty team fails during dry-run

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/test-infra#26542]
Adding a new team to a peribolos config should work when you perform a dry-run.

This PR adds an empty team to the peribolos config - we have presubmits where we run peribolos with a dry-run (`--confirm=false`

https://github.com/knative/community/pull/1091/files

But the dry-run fails: 
```
Configuration failed: failed to configure knative teams: failed to update Func Reviewers members: failed to list func-reviewers(Func Reviewers) members: return code not 2XX: 404 Not Found
```

Related: https://github.com/kubernetes/test-infra/issues/26331

**Comment by dprotaso** [comment]
cc @fejta

**Comment by fejta** [comment]
You cannot create a team and fix the team in the cycle

**Comment by kvmware** [comment]
@fejta Could you provide a little more guidance here please. We see that others https://github.com/cloudfoundry/community/blob/main/.github/workflows/org-management-check-prs.yml are using the same way to check PRs to validate the configuration. If using `-fix-*` with a `confirm=false` is not supported, then why is it allowed or what is the recommended way to do this?

**Comment by fejta** [comment]
You can't fix something that doesn't exist

**Comment by evankanderson** [comment]
Would `dry-run` treating missing teams as "empty" be acceptable?

**Comment by kvmware** [comment]
This is a bug in peribolos or at leas poor documentation for dry-run. The dry-run is not smart enough to realize that a team is being created and tries to ask github for the list of members which causes this failure. As @evankanderson pointed out the proper way would be to not ask for a member list (ie assume empty) when a new team is created in dry-run mode. That our update the documentation about what dry-run is meant for since it can't dry-run currently.

**Comment by BenTheElder** [comment]
/remove-sig k8s-infra
/sig contributor-experience
this is now at https://sigs.k8s.io/prow

I agree this sounds like a bug but we have limited bandwidth, if you're still interested, please re-file at the current prow-repo.
