### ISSUE TITLE
Support `--filter=blob:none` for repo checkouts

### ISSUE THREAD

**Issue by theaugy** [kubernetes/test-infra#26590]
**What would you like to be added**: A way to specify `--filter=blob:none`, similar to the way we can currently specify `--depth` with `clone_depth`.

Mentioned in [this comment](https://github.com/kubernetes/test-infra/issues/18226#issuecomment-881669171):

> aledbf shared https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/ and in particular --filter=blob:none

**Why is this needed**: Provides a way to reduce repo clone size that does not introduce the pitfalls of shallow cloning (like missing common ancestors).

**Comment by BenTheElder** [comment]
cc @cjwagner @droslean @listx 

I'd actually recommend just making this what clonerefs does normally.
It's faster and doesn't break `git describe --tags`. It does cause `git blame` or `git checkout $ref_we_didnt_fetch` slower but not broken. `depth: 1` breaks `git describe --tags` which breaks many repo's versioning workflows so we're stuck with slow expensive clones.

See: https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

We've had this by default in bootstrap.py since March 7th with no issues and improved performance. It is substantially faster to clone a large repo like Kubernetes with filter blob:none.

**Comment by listx** [comment]
Ack. This is in my radar, but it is not my top priority ATM. I expect to get to this later this quarter (unless someone beats me to it!).

**Comment by BenTheElder** [comment]
Thanks! I remembered you had b/272104240 to track at Google but I wanted to get some input on this, I intend to put it on my backburner similarly if we agree in principle.

If we were OK just making this the standard clone path instead of opt-in, the PR is probably pretty small. I don't _think_ this needs to be optional, though maybe setting depth should override it.

**Comment by listx** [comment]
> Thanks! I remembered you had b/272104240 to track at Google but I wanted to get some input on this, I intend to put it on my backburner similarly if we agree in principle.

I'm on board with this.
 
> If we were OK just making this the standard clone path instead of opt-in, the PR is probably pretty small. I don't _think_ this needs to be optional, though maybe setting depth should override it.

I'm OK with making it the default behavior. The CloneDepth field (https://github.com/kubernetes/test-infra/blob/f1af7f88632033880e5f742c866c5a0b7e978681/prow/apis/prowjobs/v1/types.go#L1079-L1081) should probably still be respected and override the partial clone default, but we could also print a warning to hopefully educate the user about the benefits of partial clones.

**Comment by listx** [comment]
> Yeah, YMMV [kubernetes/community#7194 (comment)](https://github.com/kubernetes/community/pull/7194#issuecomment-1478618976)
> 
> I forget why I didn't go with treeless, maybe the submodules warning?

I asked on Git and the author of the blog post [confirmed](https://discord.com/channels/1042895022950994071/1043101606549401661/1100732435181875253) that the submodules warning is still an issue. Using `blob:none` sounds like the easiest thing to do, esp. because there shouldn't be a ton of difference between `blob:none` and `tree:0`in terms of storage space (law of diminishing returns because blobs are by far the heavy objects).

**Comment by howardjohn** [comment]
looks like this was reverted https://github.com/kubernetes/test-infra/pull/29572

/reopen

what was the context for the revert?

**Comment by listx** [comment]
IIRC we had an issue with our internal Prow instance where our Git provider choked on this flag. @airbornepony might have more details.

**Comment by BenTheElder** [comment]
Let's make this a config option on decoration utils then?

Full Kubernetes clones are only getting more expensive, around 1GiB of objects ... very slow to do a full clone ...

```console
$ time git clone https://github.com/Kubernetes/Kubernetes
Cloning into 'Kubernetes'...
remote: Enumerating objects: 1492279, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 1492279 (delta 59), reused 54 (delta 54), pack-reused 1492180
Receiving objects: 100% (1492279/1492279), 969.62 MiB | 6.76 MiB/s, done.
Resolving deltas: 100% (1095657/1095657), done.
Updating files: 100% (24944/24944), done.

real	3m58.950s
user	7m53.736s
sys	1m26.011s
```

**Comment by airbornepony** [comment]
Design Doc: https://docs.google.com/document/d/1pSb7usLZAG2n5ktN-gIXus3lzuO85ncEgfoi7qE4F0o/edit?tab=t.0

**Comment by airbornepony** [comment]
https://github.com/kubernetes/test-infra/pull/31716 expands support for blobless clones to periodic jobs by defaulting into ExtraRefs.

Will review the behavior after the next bump, then we can likely close this issue.

**Comment by airbornepony** [comment]
Verified this is now working for periodic jobs on k8s prow. I'm seeing e.g.
```
  extra_refs:
  - base_ref: master
    blobless_fetch: true
    org: kubernetes
    repo: kubernetes
```

Are there any remaining concerns, or can we close this issue now?

**Comment by BenTheElder** [comment]
Thank you, looking great!

**Comment by BenTheElder** [comment]
Also: a quick sampling shows improvement on the order of 136s => 53s for clone-refs in `pull-kubernetes-e2e-kind` 🎉
