### ISSUE TITLE
Request to add PR template

### ISSUE THREAD

**Issue by chetak123** [kubernetes/test-infra#26620]
**What would you like to be added**:

I would like to add a proper PR template for this repository for better contribution experience.

**Why is this needed**:

I saw this repo has more than a thousand contributors and filled with issues - PRs but currently lacks a template for pull request.

**Comment by BenTheElder** [comment]
I think this needs more detail to be actionable.

What would you suggest adding to the PR template for this repo?
How would you expect it to help?

NOTE: first time contributors receive an automated welcome message with helpful details from the `welcome` prow plugin, we also have docs etc. For existing contributors, I'm not aware of anything we'd want to notify when filing PRs or anything that needs to be filled out when filing PRs in this repo (e.g. since it's a monorepo there are not release notes, prow has an ANNOUNCEMENTS file instead which may be PRed).

**Comment by BenTheElder** [comment]
> I didn't see automatic welcome message, which I think is very good for new contributors.

It should have been posted on your first PR, but you may have done so before the bot was enabled.

I'll defer to others, but I don't think we've had a problem with lack of PR descriptions, and we don't have any other form fields we need for managing PRs in this repo versus say kubernetes/kubernetes which requires sig labels, release notes, etc.

We post a lot of helpful info here, which can be edited to add anything missing:

https://github.com/kubernetes/test-infra/blob/b37e9ca5c4dd018ac16a3f8c8459654e92a3dcde/config/prow/plugins.yaml#L581

**Comment by BenTheElder** [comment]
example: https://github.com/kubernetes/test-infra/pull/26630#issuecomment-1160488588

**Comment by chetak123** [comment]
Okay then I'll close this issue.
