### ISSUE TITLE
Why do we have different timeouts for a test job?

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/test-infra#2680]
There seems to be 3 timeout values that can be configured for a single test job.

- `jenkins-timeout` is the timeout enforced by Jenkins.
- `timeout` is passed to and enforced by `jenkins/bootstrap.py'.
- `KUBEKINS_TIMEOUT` is passed to and used by kubetest.

Take `kubernetes-e2e-gci-gce` for example. Its [`jenkins-timeout`](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml#L262) is 170, [`timeout`](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml#L263) is 70 and [`KUBEKINS_TIMEOUT`](https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gci-gce.env#L14) is 50. If this is correct, is there a reason of having different timeout values here?

**Comment by yguo0905** [comment]
@Random-Liu

**Comment by krzyzacy** [comment]
KUBEKINS_TIMEOUT is for e2e-tests and passes into kubetest

--timeout is a bit more than KUBEKINS_TIMEOUT, which gives a bit room for things like activate gcloud, checkout repo, upload logs, etc, even after the e2e test is timed out.

jenkins-timeout is a enforcement for Jenkins, which is deprecated in prow, but has to be presented so that our Jenkins machine can exit gracefully in case something stuck somewhere.

**Comment by krzyzacy** [comment]
Although we want to get rid of KUBEKINS_TIMEOUT once we get rid of e2e-runner.sh.

**Comment by yguo0905** [comment]
Thanks for the clarification.
