### ISSUE TITLE
🐛 pip3.7 location for kubekins-e2e moved from `/usr/bin/pip3.7` to `/usr/local/bin/pip3.7` breaking tests

### ISSUE THREAD

**Issue by Skarlso** [kubernetes/test-infra#26900]
**What happened**:

Location of `pip3.7` moved to cause breaking changes on how other k8s-sig projects are using the test image.

From this point onward, pip is no longer under `/usr/bin/pip3.7` but under `/usr/local/bin/pip3.7`. Here is a corresponding issue on a the CAPA project for which tests are breaking: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3613

I couldn't find any other related commit that would justify/cause such an event in this timeframe. The last image still working for `python3 -m pip install requests` is this: `v20220607-4b3fb50c36-test-infra`. Which is 7th of June.

**What you expected to happen**:

For pip binary not to change places between releases.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3613

**Anything else we need to know?**:

I pulled the images and just run pip install. The next image which was no longer working is `v20220614-cde7860a33-test-infra`

**Comment by tobiasgiese** [comment]
Our periodic CAPO conformance and e2e tests are failing because of this issue

* [periodic-cluster-api-provider-openstack-conformance-test-main-with-k8s-ci-artifacts](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-openstack-conformance-test-main-with-k8s-ci-artifacts/1550494014325657600)
* [periodic-cluster-api-provider-openstack-e2e-test-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-openstack-e2e-test-main/1550493510786879488)

**Comment by tobiasgiese** [comment]
Fixed with https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1307
(See https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-openstack#periodic-conformance-test-main)

**Comment by BenTheElder** [comment]
We only guarantee that this image provides the tools needed to test kubernetes, not any particular binary paths or anything like that.

Is there a reason to depend on the particular location as opposed to just invoking it from PATH?

**Comment by Skarlso** [comment]
The PATH changed. And we aren't invoking it. We literally just call `python3 -m pip install requests` which fails.

We don't care where pip is, but at the very least, python should work. ;) I think that's a guarantee that is desired.

**Comment by BenTheElder** [comment]
Python is only still in this image to install the google cloud sdk, because the project used that to spin up GCE clusters etc. Otherwise it is an artifact of bazel which we no longer use. When running python we use a python image.

Pip is installed using the Debian python3-pip package, if it moved, Debian moved it.

The python system module path is not PATH and pip3 should still be in PATH

**Comment by Skarlso** [comment]
Hm, fair point. We'll make sure it's there ourselves. Thanks!
