### ISSUE TITLE
[tide] `skip-unknown-contexts` does not seem to do anything

### ISSUE THREAD

**Issue by kvmware** [kubernetes/test-infra#26958]
**What happened**:
- Set `skip-unknown-contexts=false`
- Open a PR with github actions
- github actions fail
- none of them are set to be required
**What you expected to happen**:
- github actions that fail block merge

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Please provide links to example occurrences, if any**:
https://github.com/knative/test-infra/pull/3457

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
skip-unknown-contexts=true should do something.
skip-unknown-contexts=false is the default.

https://github.com/kubernetes/test-infra/blob/d24f409b8fa140e327afc12c08f039379221e516/prow/config/tide.go#L725

> https://github.com/knative/test-infra/pull/3457

this PR isn't merged and is not selected for possible merge due to missing LGTM


> none of them are set to be required

That's not what this config is for, branch protection is not enabled by tide that is handled by `prow/cmd/branchprotector` and has it's own config for enabling branch protection on contexts. 

To enable `Required` status on a check in github you must set this on the branch for a specific check name so you must know of it ahead of time, so you have to configure them in the branchprotector config.

**Comment by kvmware** [comment]
According to https://github.com/kubernetes/test-infra/blob/master/prow/config/prow-config-documented.yaml#L1199 setting `skip-unknown-contexts` to false (the default) should make all unknown contexts required. The example given here https://github.com/knative/test-infra/pull/3457 shows that it needs a LGTM, but that should not be the case because there are couple of unknown contexts that have not passed and (if they should be required as the setting states) should not allow a merge.

**Comment by BenTheElder** [comment]
Those contexts are unknown but are not marked Required.

the skip unknown contexts field is only for tide. Not the branch protection settings with the branch protector tool

**Comment by BenTheElder** [comment]
I mean `required` on the GitHub side of things, which the branch protector can do or it can be done manually by a repo admin.

**Comment by kvmware** [comment]
Don't know if I am missing something here.
There are a few things in play here.
1. Prow jobs which can be marked to be required or not in the jobs themselves
2. Branch protection rules that can be applied manually or via branch protector (which makes those things required)
3. Github actions which to my understanding from https://github.com/kubernetes/test-infra/blob/master/prow/config/prow-config-documented.yaml#L1199 makes them required. If this is so then as explained above with the example that is not the case. If you are saying that is not the case then `skip-unknown-contexts` is really broken because when we set it to `false` it (tide) is not allowing merges because of github actions (although this is not always the case as shown in my example). Note that said github actions are not part of any branch protector rules.

**Comment by BenTheElder** [comment]
1. Yes, the branch protector is aware of prowjobs
2. Yes
3. No, false is the default for skip-unknown-contexts. Setting it to true makes it skip them. Leaving it false only makes it not do this. Setting them to required without setting this to true makes them fully required for merge and must be done in branch protector or manually. It’s not feasible to have a blanket required field for these. With prowjobs prow config includes the explicit or derived status names. With arbitrary statuses unless you list them in the branch protector prow cannot configure required status because there’s no way to know what statuses will be showing up on PRs

**Comment by kvmware** [comment]
So then it is not doing what you are saying. When left to `false` tide will refuse to merge because of failing GHAs which are not added as branch protection rules.

**Comment by BenTheElder** [comment]
So far there’s only been evidence that:
- tide will not merge without lgtm (previous state of PR)
- tide will not merge when prow tests are failing (current state of linked PR)

In the issue body:
> What you expected to happen:
> github actions that fail block merge

But this field lets you opt-in to bypassing unknown statuses, not opt-out to requiring them. Required setting / merge config for a particular status requires them.
