### ISSUE TITLE
Run some Test-Infra Jobs using Workload Identity

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#27191]
These jobs are reporting as flaky (or not forming the finished.json) frequently due to not using Workload Identity. Their signal is important, so it would be good to fix this issue.

- [x] [post-test-infra-upload-testgrid-config](https://testgrid.k8s.io/sig-testing-maintenance#testgrid-config-upload)
- [x] [ci-test-infra-autobump-prow-for-auto-deploy](https://testgrid.k8s.io/sig-testing-prow#autobump-prow-for-auto-deploy)
- [x] [ci-test-infra-autobump-prow](https://testgrid.k8s.io/sig-testing-prow#autobump-prow)
- [x] [post-test-infra-deploy-prow](https://testgrid.k8s.io/sig-testing-prow#deploy-prow)
- [x] [post-test-infra-push-prow](https://testgrid.k8s.io/sig-testing-prow#push-prow)
- [x] [post-test-infra-reconcile-hmacs](https://testgrid.k8s.io/sig-testing-prow#reconcile-hmacs)

Reference thread: https://kubernetes.slack.com/archives/C09QZ4DQB/p1660813165240589
The recommendation is disabling using GCS credentials, like this: https://github.com/kubernetes/test-infra/pull/27167/files

**Comment by listx** [comment]
Thanks for tracking this.

/assign @listx

**Comment by listx** [comment]
I'll be adding a PR shortly.

**Comment by listx** [comment]
So this is still broken for [ci-test-infra-autobump-prow](https://testgrid.k8s.io/sig-testing-prow#autobump-prow). Reason is that it's missing a WI annotation. BUT we want to create a separate GCP IAM SA (aka GSA) to reduce the perms for this job that runs on the trusted cluster, instead of just reusing the typical `prowjob-default-sa@k8s-prow-builds.iam.gserviceaccount.com` that all of the untrusted jobs use. So I need to create a new GSA/KSA pair for this job. Will post another update in a bit.

**Comment by listx** [comment]
Job appears to be [passing](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-test-infra-autobump-prow/1561763899097747456) (I manually applied the config at #27213). There should be no reason why this should start to fail (at least for the same reasons as before).

Closing this for now.

/close
