### ISSUE TITLE
Add support for CNI plugins and their configurations

### ISSUE THREAD

**Issue by klizhentas** [kubernetes/test-infra#2753]
## Description

Currently kubeadm has weave hardcoded:

https://github.com/kubernetes/test-infra/blob/master/kubetest/anywhere.go#L58

To support multiple plugins and their configurations I suggest to add two flags:

```bash
# CNI plugin to use (weave, flannel)
--cni=<plugin-name>
# Flannel specific parameters
--cni-config={"pod-network-cidr": "10.244.0.0/16", "backend": "vxlan"}
```

This will allow test-infra to use kubernetes-anywhere with multiple CNI backends. If the spec looks good, I can add this support.

**Comment by pipejakob** [comment]
Do you envision these flags being used by any other deployers in `kubetest`? The convention there is to scope flags to indicate what they actually apply to in order to avoid confusion. I assume these are going to apply only if the deployment option is set to `kubernetes-anywhere`, and additionally only if the provider is `kubeadm`, so as verbose as it sounds, I think the proper naming would be something like:

    --kubernetes-anywhere-kubeadm-cni=<provider>

I'm also scratching my head on what I would expect to happen with the cni-config when it's actually being used in kubernetes-anywhere. Is there a way to apply that configuration generically, or would there be a lot of special-casing logic for each cni provider to know what to do with this string?

There are many layers in our end-to-end tests (some would say too many) between someone's intent being declared and the actual work that happens to fulfill that intent. Your proposal here covers where someone declares that intent (by adding new flags to `kubetest`), but it's difficult to judge the addition without seeing the rest of the follow-through and plumbing required to actually make it work. I would suggest one of the following approaches:

1) Instead of starting near the top of the stack and then working downward, I would start all the way at the bottom and work your way back up to the top. That would mean first adding support for the new CNI provider into kubernetes-anywhere, then adding the `.config` option that drives it, etc., all the way up the stack before adding the `kubetest` flags to enable the behavior.
2) Do a quick-and-dirty prototype of the plumbing through the entire stack so we can see what transformations need to happen at what layers to fully support the new feature.

**Comment by pipejakob** [comment]
Of course I say all of that before I actually got to https://github.com/kubernetes/kubernetes-anywhere/pull/390 in my backlog, so all of that may be moot after I come up to speed on your other PR.

**Comment by klizhentas** [comment]
@pipejakob thanks for reviewing the issue, I think this is where I arrived after prototyping the support for CNI - kubernetes anywhere basically needs to specify `CNI` plugin name and some extra options in case if it's flannel `CIDR` range, that's the reason for my suggestion.

I saw in the review of https://github.com/kubernetes/kubernetes-anywhere/pull/390 you have mentioned setting the CIDR range flag to some value if the CNI plugin has been set up. We can do that by simply set the .config in kubernetes-anywhere in case if CNI has been set to flannel as you suggested, but I think we still need the `--kubernetes-anywhere-kubeadm-cni=<provider>` flag to allow switching between multiple CNI plugins while testing.

So the suggestion is then to keep one flag `--kubernetes-anywhere-kubeadm-cni=<provider>` while removing extra config and pre-setting the cidr range in case if it's flannel.

Let me know if that sounds OK to you.

**Comment by jamiehannaford** [comment]
https://github.com/kubernetes/test-infra/pull/2771 has been updated

**Comment by fejta** [comment]
Is this issue alive?

**Comment by jamiehannaford** [comment]
@fejta Yes, we can close as soon as #2771 is merged (hoping to get to it this week).
