### ISSUE TITLE
Same Head SHA PRed to different branch contains checks from original branch

### ISSUE THREAD

**Issue by smg247** [kubernetes/test-infra#27774]
**What happened**:
A PR with a head SHA that was originally accidentally opened against `master` branch still contained a failed job for that branch even when it was recreated for a different branch that doesn't contain that job. This caused a display issue with the failed job appearing on the PR, and `tide` confusion resulting in the need to override the check before merge would occur.

**What you expected to happen**:
PRs only contain references to jobs that were actually created for them, or at least `tide` doesn't require those outdated jobs to pass to merge.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create branch with a change.
2. Open PR against the master branch.
3. Close that PR after jobs start.
4. Using the same branch, open a PR against another (release) branch that doesn't have the same jobs configured.
5. Notice references to the original runs on the new PR.

**Please provide links to example occurrences, if any**:
https://github.com/openshift/cloud-credential-operator/pull/501

**Anything else we need to know?**:

**Comment by petr-muller** [comment]
This is always very confusing when it happens, I remember that quirk very well :( 

For anyone looking into this: The issue is that the [statuses](https://docs.github.com/en/rest/commits/statuses#create-a-commit-status) (=job results) are tied to a SHA in GitHub, so they get "carried" when you open a new PR with the same branch HEAD. Then, for Prow, these "old" statuses are basically unknown statuses, as if they were e.g. added by a non-Prow CI or something similar. I guess you could fix the issue by recognizing Prow statuses (we add some machine-readable bits to their description, see the indented `BaseSHA: ...` bits in any Prow-supplied status desciption) and figuring out they do not belong to any job that could trigger on a PR against the current branch. Then you could force-green them at some point (on PR-open or maybe on any push?), or maybe just ignore then when deciding about merges.

**Comment by smg247** [comment]
This problem is becoming more and more frequent. I think we could potentially solve this by deleting any existing, pending check statuses when a new PR is opened _or_ the base branch is modified. More research would have to be done here to assure that that wouldn't have any negative effects that are worse than this bug.

/reopen

**Comment by BenTheElder** [comment]
If you're still interested: https://sigs.k8s.io/prow
