### ISSUE TITLE
triage data is a ~week stale

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#27918]
https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1 is currently displaying data up through 2022-10-30. It's unclear what is preventing it from displaying more recent data

Are there logs or status visible for the process that updates the data for that site?

**Comment by BenTheElder** [comment]
that'd be due to https://github.com/kubernetes/test-infra/issues/27869

> Are there logs or status visible for the process that updates the data for that site?

https://prow.k8s.io/?job=ci-test-infra-triage but it's stale due to the underlying data source in https://github.com/kubernetes/test-infra/issues/27869 (there's two passes, one collects data into BQ, triage then processes that data and clusters it)

**Comment by liggitt** [comment]
Thanks, searched but didn't know the magic codenames

**Comment by BenTheElder** [comment]
FYI also https://github.com/kubernetes/test-infra/issues/27829
