### ISSUE TITLE
Change Prow components' container registry from `gcr.io` to `registry.k8s.io`

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/test-infra#28107]
**What would you like to be added**:

Recently, some K8s components' container registry was changed from `k8s.gcr.io` to `registry.k8s.io`.
(Ref: https://github.com/kubernetes/registry.k8s.io)

Similarly, would it be great to change the container registry for Prow components' container images
from `gcr.io/k8s-prow` to `registry.k8s.io` (or somewhere else)?

Currently, the images tags written in the [`starter-s3.yaml` file](https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/starter/starter-s3.yaml) are:
- `gcr.io/k8s-prow/crier:v20221123-4b1eb2a191`
- `gcr.io/k8s-prow/deck:v20221123-4b1eb2a191`
- ...

**Why is this needed**:

- Please see https://github.com/kubernetes/registry.k8s.io#background
- Please see https://deploy-preview-38059--kubernetes-io-main-staging.netlify.app/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/
- ...

**Comment by BenTheElder** [comment]
These images are not on registry.k8s.io because they're not promoted to production, they're in the staging registry only, with automated builds based on date + commit hash.

Prow has no named releases.

We need images on k8s.gcr.io to go to registry.k8s.io
We do not need staging images to move, though generally projects should not be hosting "production" out of staging registries.

Prow is a bit of an odd case in that it does have a few external users yet is not on the "production" registry, but not on the same scale as other parts of Kubernetes.

**Comment by BenTheElder** [comment]
closing since we're only hosting components in staging still
