### ISSUE TITLE
Standardize bot commands

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/test-infra#2820]
The k8s-bot commands are not consistent with other bot commands. A new set of commands below may be more coherent:
(1) `@k8s-bot test this` -> `/test this`
(2) `@k8s-bot ok to test` -> `/ok to test`
(3) `@k8s-bot tell me a joke` -> `/tell me a joke`

We may also can have a more abridged version of commands:
(1) `@k8s-bot test this` -> `/test`
(2) `@k8s-bot ok to test` -> `/ok`
(3) `@k8s-bot tell me a joke` -> `/joke`

**Comment by crimsonfaith91** [comment]
@fejta @spxtr 
/cc @grodrigues3

**Comment by grodrigues3** [comment]
Please include all of the `@k8s bot `commands when you refactor.

**Comment by cblecker** [comment]
to keep consistency with current commands, the very first part of the command after the / should be one "word", with dashes instead of white spaces.

so `/test` or `/ok-to-test` make sense.. but `/ok to test` and `/test this` probably don't.

I'd also suggest that if it makes sense to re-word the commands, we take this opportunity to do so. the `@k8s-bot` format was in the tone of you're talking to the bot and telling it to do something. if we're formatting these into slash commands, then something like:

**Comment by cblecker** [comment]
@kubernetes/sig-contributor-experience-misc

**Comment by spxtr** [comment]
I agree with @cblecker except instead of `/test ok` I prefer `/ok-to-test` or just `/ok`.

**Comment by crimsonfaith91** [comment]
i think `/ok` is good. :)

**Comment by apelisse** [comment]
`/ok` is good because it's short. But it's also so short that it's not very explicit, and it is a command that we may want to reserve for later use.

I vote `/ok-to-test` FWIW

**Comment by crimsonfaith91** [comment]
I have started to work at it, and found `@k8s-bot test this` command are used only in `config.yaml` file (and test files). Correct me if i am wrong.

If standardizing the bot commands aims to give a better experience for contributors, i wonder whether we need to change the `@k8s-bot test this` command. The change for `test this` is not trivial, and affects a lot of the configurations.
