### ISSUE TITLE
prow: deal with git safe.directory

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#28721]
https://github.com/kubernetes/test-infra/pull/28688 cc @stevekuznetsov 

https://github.blog/2022-04-12-git-security-vulnerability-announced/#cve-2022-24765

I think this one is going to be tricky ... one thought I had is we could make `entrypoint` mark the clonerefs mounted directories safe, but we'd need to edit gitconfig without depending on `git` in path then.

Alternatively we can add a shared mount that has the global gitconfig, but we have to be careful to make sure that file is where git actually looks. AFAICT it looks in `~/.gitconfig` and the user homedir may be image / pod config dependent, whereas presumably by the time we get to `entrypoint` we know the current homedir, unless the test command alters it, which .... at that point seems potentially reasonable not to handle.

We also have the option to control XDG_CONFIG_HOME, but that's not limited to git and could be a breaking change in other ways.

https://git-scm.com/docs/git-config#Documentation/git-config.txt---global

The system-wide config also looks like an interesting option to attempt to control:
https://git-scm.com/docs/git-config#Documentation/git-config.txt---system

**Comment by BenTheElder** [comment]
additional context: ideally clonerefs and test containers do not have to have the same UID

**Comment by stevekuznetsov** [comment]
> edit gitconfig without depending on git in path then.

It *is* just a plain-text file with pretty simple ordering semantics, so could we get away with this?

**Comment by BenTheElder** [comment]
Yeah, I lean towards suggesting this approach, if we replicate the logic to pick out the global or system-wide config path and just manipulate the file directly in `entrypoint` that seems like the most reliable approach across different test containers.

It seems more brittle to attempt to control the location ahead of time and add a shared mount.

**Comment by jmguzik** [comment]
I'll add input from my team, Openshift Test Platform. We decided to create two fixes for this issue downstream. The first fix is more similar to the solution discussed here, we added it to our `entrypoint-wrapper` tool to modify home, more details: https://github.com/openshift/ci-tools/pull/3292/files. The problem is it targets only specific types of tests we call multistage. 

The second fix is a kind of hotfix that solves this problem for almost all of our tests using the tool we call `ci-operator` https://github.com/openshift/ci-tools/pull/3293/files. We found that the problem can be solved by applying env vars: `GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=safe.directory GIT_CONFIG_VALUE_0='*'`. The solution seems obscure and targets all of our pods, not only test ones, but it's ok for now.

We are also interested in finding the fix at the upstream level. The best method would be, in my opinion, to apply system-wide config which in 99,9% of cases means an addition to `/etc/gitconfig` (0,1% is reserved for these _prefix_ scenarios). Unfortunately, I do not see a clear way to do that in `entrypoint` as we can't write to` /etc` in `entrypoint`, that would have to be a mount.

So, most likely the next best solution would be to do more or less the same as we did in `entrypoint-wrapper` and try to modify the file at the `HOME` dir level. I have not researched yet myself how that would it be a potential problem for `entrypoint`.

**Comment by BenTheElder** [comment]
I think modifying only the user homedir is reasonable, if the test command switches users (!) making sure the other users are reasonably configured seems like a problem for that unusual test command. We could also _try_ writing to both?

I can imagine that homedir gitconfig may still not by writable, we might want to only log a warning if we can't modify this and continue on. In that case it might be punted to the user to fix their image to be pre-configured with safedir or be writable.

**Comment by BenTheElder** [comment]
Just setting environment variables is also an interesting approach, if we can find docs for these that's a much simpler option and should apply to the full process tree.

**Comment by jmguzik** [comment]
> Just setting environment variables is also an interesting approach, if we can find docs for these that's a much simpler option and should apply to the full process tree.

Yeah, I agree it's tempting, especially when possibly facing some potential side effects related to home. The documentation can be found here: https://git-scm.com/docs/git-config#Documentation/git-config.txt-GITCONFIGCOUNT.

**Comment by BenTheElder** [comment]
cc @cjwagner @stevekuznetsov @droslean to agree on an approach.

If prow owners agree on an approach, we can mark this help-wanted.

For whatever reason at the moment this hasn't broken us yet, I'm guessing the git we use is still too old, but I'm sure one of the approaches will have to be done eventually.

Worst case we can stopgap add env to specific broken jobs until a long term fix is agreed, if any break.

ref discussion in https://github.com/kubernetes/test-infra/pull/28828

**Comment by droslean** [comment]
> 

Once we start using the affected version of git, jobs that use `git` in various ways have to be reconfigured. This isn't related directly to the prow and we could potentially allow users to configure their git not to get affected by the problem in question (https://github.com/kubernetes/test-infra/pull/28828). To my point of view, we are using git only in clonerefs, and we know exactly what we are cloning. We can make sure that that area is not affected but at the same time, we can give the ability to users to quickly add a basic git configuration to the test pod, as we do with the GOPATH as well. Hence my suggestion here: https://github.com/kubernetes/test-infra/pull/28828#issuecomment-1469833589

**Comment by stevekuznetsov** [comment]
I think we should use `entrypoint` to set `$GIT_CONFIG_COUNT=1` and enumerate the set of directories we know that `clonerefs` had previously written to, any `git` used in the test container will first consume the variables, then execute. This allows us to not assume that `git` will be present in the test container, has no effect if it is not present, and does not require any mount goofiness. 

@droslean IMHO it's OK for us to be setting this variable as it's necessary & required for `git` to function in the test environment - it's the same as how we set `$GOPATH`. 

Since we're a parent of the test process, collisions should be handled trivially: if the user is using this (obscure) git configuration mechanism as opposed to calling `git config` in their code, their environment variable declarations will over-write ours, and since we're only setting one value, any non-zero use from the user will wipe out everything from our end, so there's no partially-applied/corrupted state possible.

**Comment by jmguzik** [comment]
Just a technical remark, or maybe I need more clearance. Why?:
> think we should use entrypoint to set $GIT_CONFIG_COUNT=1 and enumerate the set of directories 

If you would like to enumerate you probably need to set `$GIT_CONFIG_COUNT=n` where `n` is a number of dirs.

```
...
GIT_CONFIG_COUNT=2 \
GIT_CONFIG_KEY_0=safe.directory GIT_CONFIG_VALUE_0=d0 \
GIT_CONFIG_KEY_1=safe.directory GIT_CONFIG_VALUE_1=d1 \
 git \
...
```

**Comment by stevekuznetsov** [comment]
I thought that newline-delimited options would be expanded out, but, they are not. In any case, I don't think it has any impact on the UX. Consider a user that sets `$GIT_CONFIG_COUNT` to a value:

- smaller than our initial list: they over-write the vars they need, and the count var keeps `git` from reading any of ours
- equal to our initial list: they over-write all of our data
- larger than our initial list: they over-write all of our data

**Comment by stevekuznetsov** [comment]
Notably, a [quick search](https://github.com/search?q=GIT_CONFIG_COUNT+%28org%3A3scale+OR+org%3Aapp-sre+OR+org%3Abackube+OR+org%3Ache-incubator+OR+org%3Acodeready-toolchain+OR+org%3AComplianceAsCode+OR+org%3Acontainers+OR+org%3Acoreos+OR+org%3Acrc-org+OR+org%3Acri-o+OR+org%3ACSPI-QE+OR+org%3Adevfile+OR+org%3Adroslean+OR+org%3Aeclipse-che+OR+org%3Afreeipa+OR+org%3Aibmz-eco+OR+org%3Aidentitatem+OR+org%3Aintegr8ly+OR+org%3Ajianzhangbjz+OR+org%3Akata-containers+OR+org%3Akcp-dev+OR+org%3Akiegroup+OR+org%3Akonveyor+OR+org%3Akube-reporting+OR+org%3Akubevirt+OR+org%3Akubevirt-ui+OR+org%3Amaistra+OR+org%3Amedik8s+OR+org%3Amigtools+OR+org%3Amonstorak+OR+org%3Aokd-virtualization+OR+org%3Aopendatahub-io+OR+org%3Aopenshift+OR+org%3Aopenshift-agent-team+OR+org%3Aopenshift-assisted+OR+org%3Aopenshift-cnv+OR+org%3Aopenshift-eng+OR+org%3Aopenshift-knative+OR+org%3Aopenshift-kni+OR+org%3Aopenshift-metal3+OR+org%3Aopenshift-pipelines+OR+org%3Aopenshift-priv+OR+org%3Aopenshift-psap+OR+org%3Aopenshift-qe+OR+org%3Aopenstack-k8s-operators+OR+org%3Aoperator-framework+OR+org%3Aostreedev+OR+org%3Apackage-operator+OR+org%3Akubernetes%29&type=code) finds no hits for `$GIT_CONFIG_COUNT` in any of the orgs that OpenShift Prow services (other than the implementation @jmguzik mentioned above in the infra), so it seems to be a safe thing to do here.

**Comment by stevekuznetsov** [comment]
> Well, that depends on what is UX in this context and how you measure it ... It makes the thing a little less predictable if you really want to use envs, and less readable. ... I just wanted to point out this technical obstacle.

Do you mind explaining what you mean? I think I speak for @BenTheElder and I when I say we want to make sure that your concern is heard, understood and taken into consideration, but I don't know that I understand the concern well right now.

Are you very specifically worried about how this approach might impact users of Prow that have `git` installed in their jobs, and are using this env-var based configuration setting mechanism? Does setting `*` using env vars alleviate this somehow, and if so, how? 

Or, are you worried that some user *might* start using this approach in the future and run into some issues? Or are you in general worried that code searches like the one I posted above are not capturing the current use well, and there's more risk here than meets the eye?
