### ISSUE TITLE
Prow issue:Ingress error "too long"

### ISSUE THREAD

**Issue by amagicalbrain** [kubernetes/test-infra#28790]
Hello There,

We have 4000 rewrite rules which I am adding that in ingress rule and after adding when I am trying to apply I am getting this error below:
"The Ingress "-app-" is invalid: metadata.annotations: Too long: must have at most 262144 bytes"

Kindly help in this issue.

**Comment by nzoueidi** [comment]
This is not a prow issue. You are probably seeing that error because when you do `kubectl apply` for your ingress file that has 4k rewrite rules , it will store the entire spec as an annotation where it cannot fit in the `last-applied-configuration` annotation. Thus, it is [exceeding](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L36) is the `TotalAnnotationSizeLimitB`.

You can use kubectl create if it is your first time creating that ingress object otherwise you can use kubectl replace.
