### ISSUE TITLE
Deck (prow.k8s.io) does not allow filtering by repo and pending state

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/test-infra#29061]
**What happened**:
I wanted to filter jobs by repository & state == peding, but it doesn't show any results.

**What you expected to happen**:
It should have worked.

**How to reproduce it (as minimally and precisely as possible)**:
Open this URL: https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api&state=pending

The result is that the state parameter is dropped and the list is not filtered (https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api)

The following works:
* https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api => filter by repo
* https://prow.k8s.io/?state=pending => filter by state pending

But not both together.

Interestingly it works for k/k: https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&state=pending

It seems like for the cluster-api repo it just discards the state, because maybe it doesn't find any jobs with state pending (?). But looking at https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api there definitely are pending jobs.

**Anything else we need to know?**:

I'm pretty sure this also worked for the ClusterAPI repository a few months ago.

**Comment by smg247** [comment]
OpenShift's instance of deck is experiencing this same issue with our `openshift/release` repo in the Tide History page. I think that it may be related.

**Comment by maahir22** [comment]
The problem arises from prow/cmd/deck/static/prow/prow.ts. Whenever the user visits the page https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api&state=pending, the following steps occur:
1) When the window is loaded, redrawOption is called - this function is responsible for adding all the options by parsing the Query Parameters.
2) Immediately after this function a redraw function is called, which further invokes an inner function call to for pushing all query params into args: 
`  function getSelection(name: string): string {
    const sel = selectionText(document.getElementById(name) as HTMLSelectElement);
    if (sel && name !== 'repo' && !opts[`${name  }s` as keyof RepoOptions][sel]) {
      return "";
    }
    if (sel !== "") {
      args.push(`${name}=${encodeURIComponent(sel)}`);
    }
    return sel;
  } `

3) This args is used for setting the browser history stack, unfortunately, the issue arises when !opts[`${name  }s` as keyof RepoOptions][sel] evaluates to false, in our case, this is !opts[states][pending] which evaluates to true.

4) The reason behind this is within the function that is used to fetch opts or options for the repo::
`function optionsForRepo(repository: string): RepoOptions {
  const opts: RepoOptions = {
    authors: {},
    clusters: {},
    jobs: {},
    pulls: {},
    repos: {},
    states: {},
    types: {},
  };

  for (const build of allBuilds.items) {
    const {
      spec: {
        cluster = "",
        type = "",
        job = "",
        refs: {
          org = "", repo = "", pulls = [], base_ref = "",
        } = {},
      },
      status: {
        state = "",
      },
    } = build;

    opts.types[type] = true;
    opts.clusters[cluster] = true;
    const repoKey = `${org}/${repo}`;
    if (repoKey) {
      opts.repos[repoKey] = true;
    }
    if (!repository || repository === repoKey) {
      opts.jobs[job] = true;
      opts.states[state] = true;

      if (pulls.length) {
        for (const pull of pulls) {
          opts.authors[pull.author] = true;
          opts.pulls[pull.number] = true;
        }
      }
    }
  }

  return opts;
}`

This function iterates over all the build items and since in our case we passed a repository parameter it tries to compare it to repoKey which is a combination of org/repo metadata inside the BuildItem, however, it's possible that the repoKey doesn't match the repository even if they are equivalent due to missing fields - this causes the state of these Items to be never marked as valid, in our case for the pending items there was no match of repository and repoKey which caused the pending state to never be marked as true in the opts.states map, hence, it was dropped from args.

5) This ambiguity can be resolved by moving opts.states[state] = true; out of the If condition - which makes sense for us, since even if a state hasn't been seen in a repo yet - we should display empty results, not adding it as an option can lead to ambiguity.
