### ISSUE TITLE
Multi Arch Supports (eg. arm64) for gcr.io/k8s-prow images

### ISSUE THREAD

**Issue by STRRL** [kubernetes/test-infra#29463]
**What would you like to be added**:

Making the Prow bot could run on arm64 machines

**Why is this needed**:

We have a multi-arch (x86 and arm64) kubernetes cluster for testing chaos-mesh. And we are trying to make prow run in this cluster. And I noticed that image like `gcr.io/k8s-prow/prow-controller-manager` is only available in x86. 

So I must use `nodeSelector` to make the pods run on x86 nodes.

Providing multi-arch images and making users ignore the arch-platform things is much better.

What do you think about it? If this proposal makes sense, I would be very glad to contribute to it. :D

**Comment by jbpratt** [comment]
hey @STRRL, I think it makes sense and support for this is (mostly) already there in [hack/prowimagebuilder/main.go](https://github.com/kubernetes/test-infra/blob/master/hack/prowimagebuilder/main.go) which is driven by the config file [prow/.prow-images.yaml](https://github.com/kubernetes/test-infra/blob/master/prow/.prow-images.yaml). There are already a few images being built with `all` but it is all or nothing for the arch. I'm not sure how (if at all) these non amd64 images are tested so that would raise the question of if any additional images need to also be tested. Swapping the arch to `all` of a few of the images prow needs should be easy enough but testing is still not clear to me.

There is also the `#prow` slack channel which could be of help!
