### ISSUE TITLE
Cancelling tekton pipeline gracefully

### ISSUE THREAD

**Issue by LuBingtan** [kubernetes/test-infra#29939]
**What would you like to be added**:
Using `CancelledRunFinally` instead of `Cancelled` when cancelling pipeline.
**Why is this needed**:

For now prow can cancel pipeline (https://github.com/kubernetes/test-infra/pull/28809). But the final task of pipeline won't be executed. IMO it's not friendly enough for pipeline with final tasks.

I have read the [tekton docs](https://tekton.dev/docs/pipelines/pipelineruns/#gracefully-cancelling-a-pipelinerun) about `Gracefully cancelling a PipelineRun`. I think this is exactly what we need in prow.

**Comment by jmguzik** [comment]
@LuBingtan why you would like to execute final tasks if this pipeline is meant to be aborted? The canceling as implemented is meant to be executed only if you push new changes to the PR or test everything again explicitly. This is also default prow behavior to abort the jobs in such a case.

**Comment by petr-muller** [comment]
So the question is whether Prow should abort jobs gracefully or not... I'd say we **do** want that if possible (I imagine `finally` tasks are used for various cleanup stuff). Is there a good reason why we should *not* want `finally` tasks to be executed?

I imagine we could worry about parallel execution of old / new jobs if the finally tasks take more time, but in that case I'd prefer if we fixed whatever the problem is rather than saying "oh well we dont do graceful abort".

**Comment by jmguzik** [comment]
> I imagine we could worry about parallel execution of old / new jobs if the finally tasks take more time, but in that case I'd prefer if we fixed whatever the problem is rather than saying "oh well we dont do graceful abort"

This plus resources, cost savings. That was my intuition when I implemented the change. I do not know tekton that much to say specifically what are the pros and cons of either solution. I feel I am against that change because if something is aborted then it should be aborted not running for unspecified amount of time to clean things up. If you are willing to accept the change anyways I guess it's ok for me as well. My opinion is not strong. I just wanted to raise that issue. Sorry for the delay (issue is one month old) but just spotted it.

**Comment by LuBingtan** [comment]
> @LuBingtan why you would like to execute final tasks if this pipeline is meant to be aborted? The canceling as implemented is meant to be executed only if you push new changes to the PR or test everything again explicitly. This is also default prow behavior to abort the jobs in such a case.

Hi @jmguzik , thanks for your reply.
In my opinion, the `finally` spec is widely used in tekton pipeline, so it would be better if Prow could provide `graceful abort` feature for tekton pipeline, or at least provide an options for people to choose how to abort the pipeline.

**Comment by jmguzik** [comment]
> In my opinion, the finally spec is widely used in tekton pipeline, so it would be better if Prow could provide graceful abort feature for tekton pipeline, or at least provide an option for people to choose how to abort the pipeline.

> For my experience, it make me confused when I observe the finally tasks not working as expected, until I check the prow code and find out why

Ok, then let's continue. Option would be nice but pipeline tool is quite old and there is no other way to introduce option than  command line param, which is kind of strange.

**Comment by petr-muller** [comment]
Thanks for voicing the opinions! I have acked the PR, if it turns out to be problematic in some way we can invest the effort to make in configurable or something...
