### ISSUE TITLE
[Flaky Test] unit-test-race-detector-nonblocking 

### ISSUE THREAD

**Issue by kannon92** [kubernetes/test-infra#31052]
**What happened**:
I see that the unit-test-race-detector-nonblocking fails somewhat often.
**What you expected to happen**:
Test succeeds.
**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
https://testgrid.k8s.io/presubmits-test-infra#unit-test-race-detector-nonblocking
**Anything else we need to know?**:

**Comment by rjsadow** [comment]
@pohly @aojea , it looks like we're still using the hashicorp simple-lru package in a prow Cache. There are a few interfaces missing from the forked [golang-lru](https://github.com/kubernetes/utils/blob/master/internal/third_party/forked/golang/golang-lru/lru.go) (specifically [Keys()](https://github.com/hashicorp/golang-lru/blob/v1.0.2/simplelru/lru.go#L132-L141). I'm not 100% confident that moving from simplelru to the community golang-lru will solve this specific issue, but would you support transitioning to the community package? I'm happy to do the legwork to transition.

**Comment by pohly** [comment]
Sounds like a useful thing to do. However, I have very little experience with Prow source code, so it would be better to get confirmation from someone who knows it better and then can also review a PR.

**Comment by rjsadow** [comment]
After some more testing it looks like switching from the hashicorp package will add some stability to this test. I'm working out where to add the `Keys()` implementation.

**Comment by rjsadow** [comment]
It looks like #31220 did resolve a significant number of flakes from `TestGetProwYAMLCached`. I don't see any occurrences of that test flaking since that PR. https://storage.googleapis.com/k8s-triage/index.html?date=2023-11-21&pr=1&job=pull-test-infra-unit-test-race-detector-nonblocking#26968037200eacffed78 https://storage.googleapis.com/k8s-triage/index.html?date=2023-11-21&pr=1&job=pull-test-infra-unit-test-race-detector-nonblocking#ecdf8f05dd4ce46ab0a2

I'm not sure if this is sufficient to resolve this issue as `unit-test-race-detector-nonblocking` is still failing quite frequently but doesn't seem to be flaking on specific jobs compared to before.

**Comment by listx** [comment]
Revert created at https://github.com/kubernetes/test-infra/pull/31390. Please take a look, thanks.
