### ISSUE TITLE
Current configuration of normal jobs makes some undesired tests running

### ISSUE THREAD

**Issue by carlory** [kubernetes/test-infra#31666]
**What happened**:

I raised a PR to add quota support for PVC with VolumeAttributesClass. It's an Alpha feature and I add some e2e tests.

The following jobs are always triggered and failed.
- pull-kubernetes-e2e-gce
- pull-kubernetes-e2e-kind
- pull-kubernetes-e2e-kind-ipv6

The JUnit report shows that the test failed because of timeout. 
```
Kubernetes e2e suite: [It] [sig-api-machinery] ResourceQuota [FeatureGate:VolumeAttributesClass] [Alpha] should create a ResourceQuota and capture the life of a persistent volume claim with a volume attributes class 
{ failed [FAILED] timed out waiting for the condition
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1256 @ 01/18/24 08:19:06.682
}
```

But the root cause is that my e2e test requires a feature gate `VolumeAttributesClass` which is not enabled in the normal jobs.

Besides, I also found that we may abuse `Feature`, `FeatureGate` labels in e2e tests. There's a [KEP-3041](https://github.com/kubernetes/enhancements/tree/master/keps/sig-testing/3041-node-conformance-and-features) tracking this issue, but sadly has been stuck for a while. 

This [PR](https://github.com/kubernetes/kubernetes/pull/121895) is following this KEP guide and add a `FeatureGate` label in the e2e test. But the normal jobs still run this test and failed later.

**What you expected to happen**:

Adding e2e tests for features is a hard requirement when promoting a feature to Beta stage. And for Alpha features, it's not a hard requirement.

There're at least three jobs for Alpha and Beta tests in test-infra.

- pull-kubernetes-e2e-kind-alpha-features
- pull-kubernetes-e2e-kind-beta-features
- pull-kubernetes-e2e-kind-alpha-beta-features

These jobs are not in the presubmit list and requires manual trigger. 

In a beta feature we can have the luxury on detecting the problem later, so these jobs won't block PRs merging. 

Talked with @aojea, @pohly and @pacoxu in [slack sig-testing channel](https://kubernetes.slack.com/archives/C09QZ4DQB/p1704859442079249), we agreed roughly on the following points.

1. Changes jobs' configuration
	- alpha: skip Feature:.*, focus: .
	- beta: skip Feature:.*|Alpha. focus: .
	- "normal": skip Feature:.*|Alpha|Beta, focus: .

2. The pull-kubernetes-.*-beta jobs maybe expected to always run, and those jobs maybe non-optional and mandatory. It's a good point and we can iterate on this.

3. Need to do more work to reconcile SIGs - KEPs - PRR , @aojea expect the testing strategy to be defined in the KEP, and the SIG reviewers to make sure those tests are added and are running and maintained.

After the changes, If a feature is in Alpha stage and some e2e tests are added, the normal jobs won't run these tests, so PRs can be merged without blocking when the manual alpha/beta jobs' result is successful.

If the option 2 and 3 were implemented, it would make kubernetes more stable and reliable.

**How to reproduce it (as minimally and precisely as possible)**:

Write a e2e test for an Alpha feature and add a `FeatureGate` label, then raise a PR and wait for the normal jobs to run.

Code snippet:
```go
import "k8s.io/kubernetes/pkg/features"
var _ = SIGDescribe("Something", framework.WithFeatureGate(features.Something), func() {})
```

**Please provide links to example occurrences, if any**:

- https://github.com/kubernetes/kubernetes/pull/121895

**Anything else we need to know?**:

- @pacoxu raised a [PR](https://github.com/kubernetes/test-infra/pull/31586) to skip some tests for kind alpha/beta fetures CI
  ```
  |\[Feature:.+\] ... In-tree.Volumes.\[Driver:.nfs\]|PersistentVolumes.NFS|Network.should.set.TCP.CLOSE_WAIT.timeout ...
  ```

**Comment by pohly** [comment]
This comes back to the discussion in https://github.com/kubernetes/enhancements/pull/3042 (for example [1](https://github.com/kubernetes/enhancements/pull/3042#discussion_r988842090), [2](https://github.com/kubernetes/enhancements/pull/3042#discussion_r989450658)):
- When should a test have a `Feature` and when a `FeatureGate` tag?
- Which jobs run which tests?

Here's my take on this.

* All tests which depend on some non-conformant cluster setup (whether it's a feature gate, an optional API group, or some particular functional aspect of a cluster) have to have a `Feature` tag that identifies what that special requirement is. We currently don't have that documented in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/feature/feature.go, which is setting a bad precedence when developers add new features. I intend to add more instructions to the file.

* "Generic" jobs are for tests that can run everywhere. Such jobs skip `Feature:.*`.

* The `-alpha-features` and `-beta-features` jobs are generic, i.e. they are not meant to run tests that depend on specific features. What they do is enable alpha resp. feature gates and API groups, then run "normal" tests to ensure that those still pass.

* All tests that depend on one of the currently defined feature gates reference that feature gate, which adds `FeatureGate` and `Alpha/Beta`. This is primarily for documentation purpose. It also forces touching the test when removing a feature gate, which ensures that at the latest at that point someone thinks about the tests and how to run them.

Let's consider the implications when adding and promoting a feature. Because "generic" jobs won't run a new test, the developer of the feature must find some other job to run it in, or create a new one. I would start by looking at the jobs owned by the SIG which is responsible for the feature. Perhaps there is a "SIG Storage GCE" job that can be reconfigured to run the `VolumeAttributesClass` tests?

One drawback of this approach is a potential proliferation of per-SIG Prow jobs. In particular when all of them need a GCE cluster, that could become expensive quickly. A KIND cluster for such jobs is cheaper and perhaps manageable?

Such a SIG job could use a suitable focus expression to only run tests a) of the SIG and b) of specific features that are being worked on. Previously, this would have been something like `FOCUS=\[sig-node\].*(Feature:(Foo|Bar)\)`. With labels, this becomes `ginkgo -label-filter="sig-node AND (Foo or Bar)"`.

**Comment by pohly** [comment]
>  the developer of the feature must find some other job to run it in

Note that the PRR KEP template is consistent with making the developer responsible when it asks to list jobs for the E2E tests that cover the feature.

**Comment by carlory** [comment]
@pohly  Sorry for the delay, I got sick some days ago and was not able to work on this. 

After read KEP, comments and [Conformance Test Requirements](https://github.com/kubernetes/community/blob/32a1c14d04ff78684d78b827ac7c49f70352d509/contributors/devel/sig-architecture/conformance-tests.md)

1. From KEP: 
   - If a test validates functionality that may only work outside the minimal conformant installation of Kubernetes, it receives a [Feature:.+] label. 
   - Depending on whether test targets all environments or specific ones, `NodeConformance` or `Feature:` labels are added. Note, the `Feature:` label may (but not necessarily) match the `FeatureGate:` name.

2. From comments:
   - All tests which depend on some non-conformant cluster setup (whether it's a **feature gate**, **an optional API group**, ...) have to have a `Feature` tag that ...
   - The -alpha-features and -beta-features jobs are **generic**. i.e. they are not meant to run tests that depend on specific features. **What they do is enable alpha resp**. feature gates and API groups, then run "normal" tests to ensure that those still pass.

3. From Conformance Test Requirements
   - Conformance tests currently test only GA, non-optional features or APIs. It tests only GA, non-optional features or APIs (e.g., **no alpha or beta endpoints**, no feature flags required, no deprecated features)

I still have some questions:

1. When a test depends on a feature gate and alpha/beta APIs, should we add both `FeatureGate:` and `Feature:` labels? 

2. If add `Feature` label, once the FeatureGate is GA and APIs are promoted to stable, the `Feature` label should be removed unless the test requires a non-conformant cluster setup, right?

3. The `Feature:` label may (but not necessarily) match the `FeatureGate:` name. Who decides whether the `Feature:` label matches the `FeatureGate:` name? If `Feature:` label don't match the `FeatureGate:` name, Who are responsible for maintaining the mapping, feature owner sig or sig testing?

4. When a PR introduce a new `Feature:` label, which sigs should participate in review work and how to notify them. Is it the responsibility of the person who reviewed KEP before it was frozen?

5. If the `*-alpha/beta-kind` jobs maintained by sig-testing can execute the new e2e test, is there no need to create a dedicated job in their SIG?

**Comment by carlory** [comment]
cc @aojea @pacoxu

**Comment by pohly** [comment]
>     1. When a test depends on a feature gate and alpha/beta APIs, should we add both `FeatureGate:` and `Feature:` labels?

Yes, I think so.

>     2. If add `Feature` label, once the FeatureGate is GA and APIs are promoted to stable, the `Feature` label should be removed unless the test requires a non-conformant cluster setup, right?

Right.

>     3. The `Feature:` label may (but not necessarily) match the `FeatureGate:` name. Who decides whether the `Feature:` label matches the `FeatureGate:` name? If `Feature:` label don't match the `FeatureGate:` name, Who are responsible for maintaining the mapping, feature owner sig or sig testing?

The feature owner. SIG Testing shouldn't need to understand what is being tested. We act as gatekeeper for `test/e2e/feature`, but that's just to ensure that developers provide enough information and understand what they are doing.

>     4. When a PR introduce a new `Feature:` label, which sigs should participate in review work and how to notify them. Is it the responsibility of the person who reviewed KEP before it was frozen?

I'm not sure whether this needs to be in the KEP. Finalizing the label during test implementation is good enough for me. The review then happens when a PR touches `test/e2e/features`.

>     5. If the `*-alpha/beta-kind` jobs maintained by sig-testing can execute the new e2e test, is there no need to create a dedicated job in their SIG?

I'd say that no separate job is needed, but I'll let @aojea provide the definite answer here.

**Comment by carlory** [comment]
> 1. When a test depends on a feature gate and alpha/beta APIs, should we add both `FeatureGate:` and `Feature:` labels?
>
> Yes, I think so.

@pohly If so, *-alpha/beta-kind jobs will not be able to run some e2e test because jobs always skip `[Feature:]` label. Why need enable beta/alpha API/feature-gate for these job?

**Comment by pohly** [comment]
To phrase it differently: the alpha/beta jobs ensure that new features do no harm. They don't check that they do anything useful.

**Comment by carlory** [comment]
https://github.com/kubernetes/kubernetes/pull/124350 will resolve this issue.
