### ISSUE TITLE
Support for configurable max concurrency per jobs in Prow

### ISSUE THREAD

**Issue by sebastienvas** [kubernetes/test-infra#3209]
We might not want a PR to take all the resources and therefore we might want the following:

- Ability to abort a job (hermetic tests) run when a new commit is added to a PR.
- Ability to configure the maximum concurrency per job: This can be useful when running a test on a limited test environment. 

As discussed with @spxtr, kubernetes does provide some "ways" to limit resources, and force (or prevent) a pod to run on a specific node, but some of the test environment setting cannot be expressed in those terms.

**Comment by spxtr** [comment]
> Ability to abort a job (hermetic tests) run when a new commit is added to a PR.

Currently, since our tests are so non-hermetic, we leave the actual test pods running. We should probably just delete them, but I need to check the extent to which that will leak resources.

> Ability to configure the maximum concurrency per job: This can be useful when running a test on a limited test environment.

This should be straightforward. We can add a `max_concurrency` field to the job configs. If 0, the default, there is no limit. Otherwise, `plank` can delay starting the pod until there are few enough currently running.

/area prow

**Comment by kargakis** [comment]
> Ability to abort a job (hermetic tests) run when a new commit is added to a PR.

> but I need to check the extent to which that will leak resources.

@spxtr can you elaborate on this more? I want to work on this issue.

**Comment by spxtr** [comment]
Sure, although we should probably close this issue since #3576 went in.

Our e2e test jobs currently do the following:

1. Turn up a cluster in some other project.
2. Run tests against the cluster.
3. Tear down the cluster.

If we kill the job during step 2 then we just leave the cluster around. If this happens several times then we might run out of quota in the project. We do have a janitor process that periodically cleans up old clusters, but I don't know if it's enough.

**Comment by kargakis** [comment]
Hrm, is this because you can't know if the pod was actually created or deleted?

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/test-infra/issues/3788

/close
