### ISSUE TITLE
prow: github client IsMember false if org is a github user

### ISSUE THREAD

**Issue by nlandolfi** [kubernetes/test-infra#3220]
The [IsMember](https://github.com/kubernetes/test-infra/blob/master/prow/github/client.go#L226) function will return false if the trusted org is a user (e.g., nlandolfi) and the user is said user.

This may be the desired behavior because the check is for a github org. Are we limiting prow repos to always be org repos?

I believe adding:
```go
if org == user {
    return true, nil
}
```
at the start of IsMember would allow org to be a username, and that user to be considered a member. I can create the PR if we thought it reasonable, curious to hear thoughts.

**Comment by spxtr** [comment]
This does seem fine for me even if it's only to make it easier to get started playing with prow, since most people will start by pointing it at some testing repo under their name. Please open a PR and mention me on it :)

However, it does suggest the question of how to do this properly for all the use cases in the future. It seems like we should have trusted orgs, trusted teams, trusted collaborators, and maybe a whitelist? Only the latter two will work if the repo isn't under an org.

cc @jfelten

**Comment by spiffxp** [comment]
>It seems like we should have trusted orgs, trusted teams, trusted collaborators, and maybe a whitelist?

Yes, these line up well with the different roles spelled out in https://github.com/kubernetes/community/blob/master/community-membership.md

**Comment by fejta** [comment]
Also I'd prefer we check whether a user has write access to the repo in question, rather than just org membership
