### ISSUE TITLE
pj-on-kind doesn't work anymore

### ISSUE THREAD

**Issue by ivanvc** [kubernetes/test-infra#32443]
**What happened**:

After the merge of #32418, it seems like `config/pj-on-kind.sh` wasn't properly cleaned up. It still refers to `prow/pj-on-kind.sh`, which no longer exists in the repo. See:

https://github.com/kubernetes/test-infra/blob/b4a7a2bd9d270b4f98e1c1c076d07b4a03e65296/config/pj-on-kind.sh#L26
 
**What you expected to happen**:

Either `config/pj-on-kind.sh` should work or be removed from the repository. However, after merging #32418, the documentation (https://docs.prow.k8s.io/docs/build-test-update) on how to test Prow jobs locally is also outdated.

**How to reproduce it (as minimally and precisely as possible)**:

* Open a terminal, run `./config/pj-on-kind.sh`, it returns the error:
    ```
    ./config/pj-on-kind.sh: line 26: /homa/ivan/Code/test-infra/prow/pj-on-kind.sh: No such file or directory
    ```
* Open https://docs.prow.k8s.io/docs/build-test-update/#using-pj-on-kindsh. It still references `pj-on-kind.sh` and other ways to run Prow jobs locally as if they were still in this repository.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by aojea** [comment]
@cjwagner the description references your PR, are you able to take a look at this? 

Thanks

cc: @BenTheElder

**Comment by cjwagner** [comment]
Yes, there is a trivial fix required for the config/pj-on-kind.sh script in this repo. The comment at the bottom of the script hints at what this is. I'll make a quick PR to fix it.


> Open https://docs.prow.k8s.io/docs/build-test-update/#using-pj-on-kindsh. It still references pj-on-kind.sh and other ways to run Prow jobs locally as if they were still in this repository.

pj-on-kind.sh does still exist in the same relative path that it did before. It was just moved with the rest of the Prow source code to kubernetes-sigs/prow. The docs are still valid, there are just some links that are broken due to the code moving repos. Feel free to open an issue about the broken links in kubernetes-sigs/prow (or even better open a PR :smile: ).

**Comment by cjwagner** [comment]
Looks like links in the docs are being fixed here: https://github.com/kubernetes-sigs/prow/pull/103
I just reviewed that.
