### ISSUE TITLE
Prevent reviewers label "release-note" if the release note in PR description is "NONE"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3296]
ref: #3295 

This is another case.

PR https://github.com/kubernetes/kubernetes/pull/32067 has `release-note` but it's release note content is `NONE`. It seems like it's because the PR has release note `NONE` in its description but its reviewer still add a `release-note` label to it. See:　https://github.com/kubernetes/kubernetes/pull/32067#event-778657660. If it was this case, bot should prevent reviewers label `release-note` is it has `NONE` release note.

/cc @crimsonfaith91

**Comment by crimsonfaith91** [comment]
@xiangpengzhao I think spxtr is a better candidate to discuss about this feature.

**Comment by kargakis** [comment]
It seems that the plugin today handles [only new comments](https://github.com/kubernetes/test-infra/blob/625ac8c55eaa2b44020805ff5304d3f6ad4e4418/prow/plugins/releasenote/releasenote.go#L66) and ignores edits.

**Comment by xiangpengzhao** [comment]
Thanks @crimsonfaith91 for poiting this out!
@spxtr any thoughts?

**Comment by spxtr** [comment]
That PR merged almost a year ago. I think there may have been a bug where adding `NONE` to the release note didn't properly add the label. I'm pretty sure this issue was fixed several months ago. Please reopen this issue if I'm incorrect.

Anyway, that release-note handling is still done by mungegithub, not prow. We should probably migrate that.

**Comment by crimsonfaith91** [comment]
@spxtr Thanks for the explanation! I am interested to work on this issue if reopened.

**Comment by xiangpengzhao** [comment]
Thanks @spxtr @crimsonfaith91！
