### ISSUE TITLE
NodeConformance testing with different OCI runtimes

### ISSUE THREAD

**Issue by kannon92** [kubernetes/test-infra#33300]
### What would you like to be added?

We would like to add node conformance tests with crun.

To start, we would like to add presubmits and periodics for crun and crio. 

We would like to switch runc to crun for the NodeConformance tests just to verify that there is no difference between these two OCI runtimes.

### Why is this needed?

We want to make sure that there is no regressions between runc and crun.

**Comment by kannon92** [comment]
> Aside: can we please use the test-infra issue tracker for CI jobs etc? It is more targeted to that purpose.

I will do that for now on. Transferred the issue.

**Comment by BenTheElder** [comment]
Also: The issue is not with these projects, it's with the proliferation of "conformance test with ___" which is not sustainable and will have everyone vying to add their favorite configuration. 

We generally do not overtly test third party integrations conformance or otherwise, sometimes it happens incidentally by necessity (e.g. most clusters are on GCP and AWS because that's where the funding is, so they use the necessary CSI drivers etc). 

Aside: NodeConformance != "Conformance"

/retitle NodeConformance testing with different OCI runtimes

For the main Kubernetes conformance tests, we have a few jobs that run them, but we only mention that we're testing with e.g. "kind" or "kube-up" from within the project itself, to make sure the tests themselves work for use with other clusters. There are some other related jobs to e.g. ensure that the conformance tests do not depend on non-GA APIs by running a kind cluster that disables them.

What we do NOT do is publish / run "conformance with cilium" "conformance with containerd" "conformance with debian" "conformance with GKE"

**Comment by samuelkarp** [comment]
> I'm wondering why we don't switch cgroupv2 completely to crun if the project decides to use that runtime as default in the future.

I'm having trouble parsing this sentence.  Does "the project" refer to Kubernetes or CRI-O?  For context, containerd and runc both fully support cgroupv2 as well.

**Comment by kannon92** [comment]
I think sasha's suggestion was to switch the crio cgroupv2 job to use crun by default.

So our team is discussing our goal here. It sounds like having replicated jobs for crun versus runc is not going to fly.

For context, we wanted to default to using crun and we discovered some edge cases in kubernetes around crun/runc that we did not catch in crun or CRIO.

K8s PR: https://github.com/kubernetes/kubernetes/pull/126641
crun PR: https://github.com/containers/crun/pull/1517

**Comment by kannon92** [comment]
@BenTheElder @aojea 

We met in sig-node to discuss this.

In CRI-O, we are going to explore ways to pull node-e2e into our CI so we can run the matrix that we want to support in the CRI-O side.

Our goal would be to confident to suggest that crun will be our default for CRI-O and once that happens, we will update our k8s CRI-O jobs to use crun instead of runc.

Since we are proposing release blocking jobs for CRI-O, we are thinking that we would keep those to be runc and create a counterpart for crun so not to block the release.

Timeframe on this is TBD as we need to flesh out the CRI-O CI first. https://github.com/cri-o/cri-o/issues/8503
