### ISSUE TITLE
Ensure prow can run on a non-GKE kubernetes cluster

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3334]
We're reasonably confident this is already so, just need confirmation

**Comment by spiffxp** [comment]
/assign @kargakis 
I'm guessing you can confirm prow runs on OpenShift, which would qualify as Not GKE

**Comment by kargakis** [comment]
We don't run prow on OpenShift today because we don't support TPRs in 3.6
(k8s 1.6) but we support CRDs in 3.7 (k8s 1.7) and we are going to move
[prow on OpenShift] soon. From my tests, prow is working fine on 3.7 given
we have the right RBAC rules in place. Will keep this thread posted once we
switch.

On Tuesday, August 15, 2017, k8s-ci-robot <notifications@github.com> wrote:
> Assigned #3334 to @kargakis.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/ORz8tf9mmNTxhkWTrr0SiAWPNa65xznXs5oDfdwTzxB9iRJvlfBRpdcdP3orpbwRkyqFgzQQHQfPSuzEWJAPqXBFmha8jrd1J0Hg2WvObX64CxC4l5NCYbXS8Oye_akX5WotLbJdRtEL1VL8VjOtiTmyN8LEZg=s0-d-e1-ft#https://github.com/notifications/beacon/ADuFf1Obu0FV44tJ9ihQBkiJhDVxlNMPks5sYfYPgaJpZM4OO-5K.gif>

**Comment by kargakis** [comment]
Successfully migrated on Openshift 3.7 today! Hooray! I will follow-up with the rbac rules.
