### ISSUE TITLE
Prow issue: bot should not tell to re-test if its not allowed

### ISSUE THREAD

**Issue by ash2k** [kubernetes/test-infra#3378]
Please take a look at https://github.com/kubernetes/kubernetes/pull/48384#issuecomment-313541203 - I was told I can run `/retest` but when I did it turned out I don't have enough powers :)
Perhaps bot could be a bit smarter.

Seems similar to #3071, but a bit different.

**Comment by spiffxp** [comment]
Since you're not a member, I believe the issue should have gotten a `needs-ok-to-test` label applied, but it didn't?  Then, since a member lgtm'ed and approved, the tests were run, but the PR is still acting like the `needs-ok-to-test` label is applied.  

[commands.md](https://github.com/kubernetes/test-infra/blob/master/commands.md) says anyone on a trusted PR should be able to retest.  I dropped an /ok-to-test to see if that helps in this specific case, try a /retest when you can @ash2k 

In general though, it's confusing when someone LGTM's, the PR gets tested, but is not "trusted".  Seems like one of the prow lgtm plugin or mungegithub approve munger should tackle this?

Also, commands.md wasn't linked in that comment, it linked to pull-requests.md instead?  weird

**Comment by xiangpengzhao** [comment]
>Also, commands.md wasn't linked in that comment, it linked to pull-requests.md instead? weird

commands.md  is linked by the second `here` as below. Yeah the first `here` links to pull-requests.md,  it'd be better to link to [pull-requests.md#the-testing-and-merge-workflow](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#the-testing-and-merge-workflow)

>Instructions for interacting with me using PR comments are available here. If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository. I understand the commands that are listed here.
