### ISSUE TITLE
Track release notes per-deliverable

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#3415]
Repos in the staging directory are published and consumed piecemeal by others. We need a way to provide accurate CHANGELOGs / release notes.

I suggest a tool that does this for each library in staging, for each change to the main repo:

* Use the go compilation libraries to evaluate if the change would cause a change in the public interface of staging/xxx.
* If so, require an xxx-release-note in the PR.

Then the release notes can be compiled at will.

(Example: A change to the API types repo requires a client-go-release-note, since client-go users will need to change their code to upgrade.)

**Comment by lavalamp** [comment]
@caesarxuchao

**Comment by caesarxuchao** [comment]
Apart from the public interface changes, we found changes to the comments on API types might worth a release note as well.

For example, https://github.com/kubernetes/kubernetes/pull/36355 didn't change the public interface, but it did announce that the Job API was to be deprecated in the next release. A client-go release note was also needed, since client-go users need to see the deprecation notice.

**Comment by mbohlool** [comment]
Would it make sense to check for changes in OpenAPI spec as it would include both public interface changes and any documentation changes. This of course would not include any structural changes in the client-go itself, but it would be a good tool to be used for all clients.

**Comment by caesarxuchao** [comment]
Checking OpenAPI change is also plausible for the case i brought up.

**Comment by caesarxuchao** [comment]
@ericchiang had put together a tool that records the public interfaces of a package. It is a good place to start. https://github.com/ericchiang/gopkgapi
