### ISSUE TITLE
Document prow plugins

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3476]
Similar to the [command descriptions](https://github.com/kubernetes/test-infra/blob/master/commands.md).

/kind documentation
/area prow

**Comment by spiffxp** [comment]
Assigning to milestone v1.9 since it seems like something we can get done while we're in the midst of migrating mungers away from mungegithub to prow.

What's the right compromise for now vs. too much scope that it'll get kicked to "next time"
- manually maintained table in prow/plugins/README.md
- prow/plugins/foo/README.md for all plugins
- help encoded in way that we could extract it from plugins and generate docs

**Comment by fejta** [comment]
@cjwagner aren't you working on this? /assign it if so?

**Comment by spiffxp** [comment]
Discussed during sig-testing, sounds like plan of record is to add a uri to prow that will display help for all currently configured plugins.  Possibly on a per-repo basis.

Maybe still room for a README that shows all potential plugins? I'll look to see if it appears worth the effort vs. just another thing that stagnates

**Comment by spiffxp** [comment]
@cjwagner I think we're safe to call this done now that we have prow.k8s.io/plugin-help.html, WDYT?

**Comment by cjwagner** [comment]
Yup!

**Comment by bweston92** [comment]
@spiffxp was going to update the block comment here https://github.com/kubernetes/test-infra/blob/3c776246ad7f2c801d41626b43069e10ddefcf91/prow/plugins/config.go#L43 but the link you posted no longer exists.

**Comment by kargakis** [comment]
@bweston92 try https://prow.k8s.io/command-help

**Comment by cjwagner** [comment]
Also https://prow.k8s.io/plugins to see all plugins, not just commands.
