### ISSUE TITLE
Should include repo info in "Associated issue" if the issue isn't in k/k repo

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3533]
See: https://github.com/kubernetes/kubernetes/pull/48943#issuecomment-315384071

The PR fixes kubernetes/kubeadm#323, but the bot only says `Associated issue: 323` in its comment. It's not so clear. Just a nit.

/cc @crimsonfaith91

**Comment by spiffxp** [comment]
This would be a nice thing to fix, but I think we're working on migrating to prow

@cjwagner are we holding off on any further fixes to the approval-handler munger until migration to prow

**Comment by cjwagner** [comment]
I'll fix this in the approve plugin.
/assign

**Comment by cjwagner** [comment]
I decided not to fix this yet as it may no longer be applicable if we decide to go through with #4460.
If we think that users only care about approval requirements they have not met then it isn't necessary to display the associated issue once it is identified since at that point the requirement has been met.

**Comment by xiangpengzhao** [comment]
Agreed. The authors themselves also know which repo's issue they are associating.
