### ISSUE TITLE
Data race in mungegithub

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#3639]
```
cd mungegithub/mungers
go test -race
```
```
==================
WARNING: DATA RACE
Write at 0x00c42040ce70 by goroutine 86:
  k8s.io/test-infra/mungegithub/mungers.TestSubmitQueue.func1()
      /home/spxtr/go/src/k8s.io/test-infra/mungegithub/mungers/submit-queue_test.go:905 +0x1dd
  net/http.HandlerFunc.ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:1942 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:2238 +0xa2
  net/http.serverHandler.ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:2568 +0xbc
  net/http.(*conn).serve()
      /home/spxtr/bin/go/src/net/http/server.go:1825 +0x71a

Previous write at 0x00c42040ce70 by goroutine 70:
  k8s.io/test-infra/mungegithub/mungers.TestSubmitQueue.func1()
      /home/spxtr/go/src/k8s.io/test-infra/mungegithub/mungers/submit-queue_test.go:905 +0x1dd
  net/http.HandlerFunc.ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:1942 +0x51
  net/http.(*ServeMux).ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:2238 +0xa2
  net/http.serverHandler.ServeHTTP()
      /home/spxtr/bin/go/src/net/http/server.go:2568 +0xbc
  net/http.(*conn).serve()
      /home/spxtr/bin/go/src/net/http/server.go:1825 +0x71a

Goroutine 86 (running) created at:
  net/http.(*Server).Serve()
      /home/spxtr/bin/go/src/net/http/server.go:2668 +0x35f
  net/http/httptest.(*Server).goServe.func1()
      /home/spxtr/bin/go/src/net/http/httptest/server.go:235 +0xa2

Goroutine 70 (running) created at:
  net/http.(*Server).Serve()
      /home/spxtr/bin/go/src/net/http/server.go:2668 +0x35f
  net/http/httptest.(*Server).goServe.func1()
      /home/spxtr/bin/go/src/net/http/httptest/server.go:235 +0xa2
==================
```
and others

**Comment by cjwagner** [comment]
Two of the races detected (including the one you posted) were true data races in the testing code and could have caused flakes. All of the other races detected appear to be safe though as they are just pointer assignments without ordering constraints. To make `go test -race` stop complaining about them we would need to add locks to every munge object and use them whenever accessing the object.

**Comment by spxtr** [comment]
I'm not thrilled about leaving data races in our code just because they're pointer assignments. This prevents us from ever turning on `-race` in our tests, which we can now do with bazel.

Prow doesn't have data races when it reloads config. Why does mungegithub?

**Comment by cjwagner** [comment]
The races are totally unrelated to reloading config, the races are all related to mungeobjects or combinedstatus objects being updated and read from at the same time by different submit-queue threads. There are tons of places throughout mungegithub's code where fields are read directly from mungeobjects. Every one of these uses would have to be changed to use a lock in order to eliminate races completely. I agree that it should be that way, but its a huge change to make for for no functional difference. If we end up re-writing the submit-queue as we've discussed, the change would likely be unnecessary so I think we might want to wait to fix this the right way until we see if it is actually going to be used. What do you think?

**Comment by spxtr** [comment]
OK, I guess that's acceptable if mungegithub is EOL. I guess we can turn on race detection for everything other than mungegithub in the meantime.

**Comment by spxtr** [comment]
I guess this is a Will Not Fix since it's not worth it when we want to tear down mungegithub entirely.
