### ISSUE TITLE
mungegithub: no-issue: Is it possible to turn off the "no associated issue" munger through config?

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#3704]
This munger does not always make sense for every repo and it would be cool if it could be disabled through config.

/area mungegthub

/cc @kargakis

**Comment by spiffxp** [comment]
FYI @kubernetes/sig-contributor-experience-misc @rmmh @cjwagner 

/area mungegithub

**Comment by grodrigues3** [comment]
@apelisse

**Comment by fejta** [comment]
My preference would just be to delete this everywhere. I do not think it is helpful/useful, just irritating.

**Comment by lavalamp** [comment]
I tend to agree. `/approve no-issue` means that this is just annoying
rather than causing a behavior change.

**Comment by cblecker** [comment]
@kubernetes/sig-release-misc Bringing in sig-release as I believe this was brought in via the 1.7 release team.

**Comment by grodrigues3** [comment]
[Link to Relnotes Improvement Proposal](https://docs.google.com/presentation/d/1f-Td0Fs1kR3rSWlYzR0EJ2PFgd8_R2srlE_O_vxwdlk/edit#slide=id.p)

(note it's shared with k8s-dev)

Two things in support of the current mechanism: 
- I really like the idea of being able to auto generate release notes on a per sig basis.  
- And visibility into a release is only going to get more challenging as the number of contributors/PRs increases.  

I don't want to disable it everywhere without out a replacement solution, but I think it makes sense to make it configurable.

**Comment by lavalamp** [comment]
I think it is great to aggregate PRs by issue in the case where multiple
PRs work together to solve an issue.

I think it is not great to *require* an issue for every PR, it is just
busywork for things like typo fixes etc.

**Comment by yutongz** [comment]
Agree, not really useful to have "/approve no-issue"

**Comment by grodrigues3** [comment]
@jdumars @pwittrock  @calebamiles (1.8 release team manager and sig-release leads)

This is a balance between getting better visibility into the release and velocity.  Right now, our release note process is very painful.  They are **manually** sharded into sigs and it's unclear which PRs are related and address the same issue.  

Having related PRs reference the same issue would solve part of the problem and having every sig associated with an issue would allow us to automatically divide relnotes by sig.  

Dawn's proposal uses the following example.

![relnotes](https://user-images.githubusercontent.com/4854198/28647846-84256b8a-721e-11e7-8732-3d9bcd0cb7c7.png)

**Comment by stevekuznetsov** [comment]
Looks like the check is just hard-coded to look for issues under the k8s repo, as well, which means it's not super useful for any other user of the tool.

**Comment by calebamiles** [comment]
I recently read Russ Cox's fantastic article about the process of [making a change to Go][]
and I feel that I have _personally failed_ to properly articulate the challenge that I
would like to solve as a person tangentially involved in the Kubernetes release process. In
my work I wear a couple of hats so I'll try and describe my various motivations and concerns
which may place this PR in a broader context.

In my capacity at CoreOS, I try to help communicate what is being worked on upstream so
that our wonderful marketing and communications teams can talk about all the amazing work
that goes into a Kubernetes release. I believe it would be very nice to be able to provide
high level summaries of ongoing or planned work which target a "C Level" understanding of
the project. As a recovering developer it would be a much easier task if there were high
quality documentation explaining the motivation and example usage for a proposed change to
Kubernetes that I could summarize without first. The inconsistency of the content found in
the `Design proposal link` section of the issues in `kubernetes/features` makes this
difficult to do across all SIGs and the `One-line feature description` section often
fails to capture the intent hammered out in private or out of band discussions among SIG
members or within their sponsoring organizations. I would love to have access to a 
[summary][rfc-summary] and [motivation][rfc-motivation] that I could summarize for our
teams. I would argue that for any established company the information contained in those
sections is known before work actually begins, my goal is to share this information more
broadly.

In my capacity as a member of a Kubernetes release team I am a little dispirited by how much
work is required to publish release notes. Again I believe that the _vast majority_ of the
information which _should_ go into a high quality release note is available before work
begins and it would be really nice to not have to wait until work begins, or is completed
in the case where release notes are attached to Pull Requests, to be able to generate a
[roadmap][], in my capacity as a member of SIG PM, which people interested in using
Kubernetes need in order to plan their consumption of the project or lobby their own
"C Level" internal sponsor that Kubernetes is the platform for their company. While all
reasonably organized Kubernetes vendors would have internal teams dedicated to producing
this material, I believe that as an open source community we should produce _authoritative_
information for the community.

In my personal experience over the last two Kubernetes releases it has taken 30 - 48
engineering hours to sort and edit the release notes which are automatically scraped by the
[relnotes][] tool, thanks to the community for its creation and maintenance, and this is
simply unworkable given the volunteer staffing of the release teams. I believe that
[Dawn's proposal][] is a great first step in laying out a process for collecting possibly
higher quality release notes, but I would also cation against the belief that automation is a
panacea for what are fundamentally process problems. It remains a challenge to design processes
and automation which reinforce each other but in the world of physical objects some companies
are rethinking their initial relentless drive [towards automation][]...there are probably
lessons for us as well. I also agree that for "trivial" pull requests requiring an issue before
a PR can be merged is probably too much overhead. Given the vague definition of "substantial"
in our [membership guidelines][] perhaps a reasonable compromise would be to require an
associated issue for any PR with a `substantial` label which we could also use to help us
ensure community members are progressing up the contributor ladder. Even absent any automation
to act on the label it could be useful to the release team and other interested parties tracking
our development progress. Anyway those are just my thoughts which I have tried to expand in
slightly less detail in a draft [proposal to adopt something similar to the Rust RFC process][]
which I would love high level feedback on, which is why it's a GitHub Gist to avoid the line by
line concerns that I don't want to address before getting some agreement on the goals of a new
process.

[making a change to Go]: https://blog.golang.org/toward-go2
[rfc-motivation]: https://github.com/aturon/rfcs/blob/d21ef4b21604dacb3e1b4419b28a43873ef86173/text/0000-epochs.md#motivation
[rfc-summary]: https://github.com/aturon/rfcs/blob/d21ef4b21604dacb3e1b4419b28a43873ef86173/text/0000-epochs.md#summary
[roadmap]: https://github.com/rust-lang/rust-roadmap
[relnotes]: https://github.com/kubernetes/release/blob/master/relnotes
[Dawn's proposal]: https://docs.google.com/presentation/d/1f-Td0Fs1kR3rSWlYzR0EJ2PFgd8_R2srlE_O_vxwdlk/edit#slide=id.p
[towards automation]: https://qz.com/196200/toyota-is-becoming-more-efficient-by-replacing-robots-with-humans/
[membership guidelines]: https://github.com/kubernetes/community/blob/ab27c92b9f197e178f637c82038123e076f71eae/community-membership.md
[proposal to adopt something similar to the Rust RFC process]: https://gist.github.com/calebamiles/66386dfe9e00d90b5f1c621bd2899dbf

**Comment by kargakis** [comment]
I am not sure that this is the right forum for discussing whether we should nuke "/approve no-issue" or not as it seems like a much larger topic than the intent of the present issue. We need to make the option configurable because it's not just the main k8s repo that is using the munger today but elsewhere we are locked down with it. I would suggest moving the on-going discussion in kubernetes-dev.

**Comment by spiffxp** [comment]
/close

discussed at latest sig-release meeting, if the linked PR doesn't fully address this issue, feel free to reopen

whether `--approval-requires-issue` should be turned off for kubernetes/kubernetes is a separate decision we couldn't make today, predicated mostly on whether someone is actually willing to implement something that consumes linked issues for release notes
