### ISSUE TITLE
prow: even if /retest-not-required is automatically determined, the first series of tests is kicked off

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#3738]
When a PR touches only docs and the system can determine as such and apply the `retest-not-required-docs-only` label, it seems like Prow still kicks off a round of tests immediately for the PR. Would be awesome if this did not happen.

**Comment by kargakis** [comment]
`retest-not-required*` means that the SQ will not rerun the tests for a second time. Agreed though that for doc changes, it would be nice to merge directly w/o running any tests, although somebody could argue that running tests on doc changes is a nice way to deflake stuff.

**Comment by xiangpengzhao** [comment]
>running tests on doc changes is a nice way to deflake stuff.

Indeed a nice way. But it costs the cluster resources unnecessarily (?)

**Comment by stevekuznetsov** [comment]
> Indeed a nice way. But it costs the cluster resources unnecessarily (?)

My take as well

**Comment by spxtr** [comment]
The general solution is to use bazel to query for the list of affected tests and only run those. Then we don't need `retest-not-required`, it just won't run any tests! We're testing this out [here](https://github.com/kubernetes/test-infra/blob/master/verify/bazel-test-affected.sh) and it seems to work well. We will need to be doing this in order to decide whether or not to run e2e tests as well.

**Comment by kargakis** [comment]
@spxtr I am ambivalent about depending on bazel for functionality that needs to be in prow. There are cases where we don't want to run tests that bazel is unlike to cover (eg. #4319).
