### ISSUE TITLE
prow: host a dynamically generated list of commands

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#3741]
It would be awesome if the list of commands that is linked in the bot comments could be hosted and dynamically generated depending on which plugins are enabled. 

/area prow
/cc @cblecker

**Comment by spiffxp** [comment]
/area mungegithub
handles the /approve comment

**Comment by stevekuznetsov** [comment]
Ah, so threading that through might be tricky. I see.

**Comment by spxtr** [comment]
This was an idea that @apelisse had, where instead of having some random regex, prow plugins could call some function that would register a command. This has a few upsides, one of which is that we would have a list of commands at runtime that we could expose on some dashboard. I don't think it's worth the effort though.

**Comment by BenTheElder** [comment]
I think we ought to be able to provide and endpoint with that information, we could combine the commands from both on a page somewhere.

Alternatively, we may not have commands that aren't prow plugins at some point and then we'd only have to make the plugin registration provide this. I like that idea a lot but I agree that it seems low importance for now. I may take a stab at some point.

**Comment by spiffxp** [comment]
I wasn't a fan of [/help when it was last suggested](https://github.com/kubernetes/test-infra/issues/2823) just because I didn't really want to see /help-spam littered throughout PR's that would fall out of date as commands were updated and improved.  A live endpoint to query and/or website would be way better.  As above, it's a matter of time investment.

**Comment by kargakis** [comment]
> I wasn't a fan of /help when it was last suggested just because I didn't really want to see /help-spam littered throughout PR's that would fall out of date as commands were updated and improved. A live endpoint to query and/or website would be way better. As above, it's a matter of time investment.

Today, the approval message ([example](https://github.com/kubernetes/kubernetes/pull/52127#issuecomment-327956514)) is essentially that; a blob of text that spams my PRs and falls out of date as far as prow commands go or it happens to be up to date because someone made the effort to update commands.md. Yet, commands.md doesn't let me know which commands I can actually use. Once we move approvals in prow, I think it should be easy to swap commands.md with a `<details>` blob that holds all the valid commands straight from the plugins config.

**Comment by kargakis** [comment]
@cjwagner has been fixing this

/assign cjwagner
