### ISSUE TITLE
mungegithub: should be able to apply approved label if jenkins is down

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3744]
I don't have access to the mungegithub logs, but it appears jenkins is down, and it appears the mungegithub submit queue loop frequency dropped to 0, or slowed way down.

http://velodrome.k8s.io/dashboard/db/monitoring?panelId=4&fullscreen&from=1501153226291&to=1501174852958

/area mungegithub
/kind bug

**Comment by spiffxp** [comment]
E.g. https://github.com/kubernetes/kubernetes/pull/49597

**Comment by spiffxp** [comment]
and the label was applied, maybe mungegithub was really slow, similar to plank in this situation? https://github.com/kubernetes/test-infra/issues/3742

**Comment by cjwagner** [comment]
The problem was that mungegithub was waiting for status contexts to switch to the pending state after triggering retests which didn't happen when jenkins was broken. The submit-queue does this waiting from a separate thread in order to prevent blocking other mungers, but the stale-green-ci munger calls `WaitForPending` inside the munge function [here](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/stale-green-ci.go#L108). This blocked the submit-queue for 2 hours every time it was executed while jenkins was down. I'll make a PR with a fix.
