### ISSUE TITLE
Migrate manual scalability jobs to prow

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3774]
/cc @krzyzacy @spxtr @shyamjvs @gmarek 

There's no reason for these to continue living on jenkins.

We can manually schedule prow jobs with `mkpj --config-file=prow/config.yaml --job=ci-whatever | kubectl create -f -` see [mkpj](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/mkpj) docs (which are actually in the prow root unfortunately)

We can either set them to run with a long period or else create a second `prow/manual-config.yaml` somewhere (it needn't even be in the same repo) that we can use for scheduling these jobs as needed.

For jobs where we want to ensure that two do not run together we can have one run_after_success on the other.

**Comment by krzyzacy** [comment]
@spxtr does an empty interval mean it would never run or it would always run?

**Comment by shyamjvs** [comment]
Thanks for filing this issue. There are a few concerns to be addressed prior to this migration.

We need strong scheduling requirements for scale jobs (not sure how many of them can be satisfied on prow currently):
- They shouldn't be run on weekends as they need special (manual) care in case of failures
- They cannot run in parallel as then they would fail (potentially in many weird ways)
- Having just frequency is not enough, as we want to time them for specific points in time ([this doc](https://github.com/kubernetes/community/blob/master/contributors/devel/release/scalability-validation.md#automate-large-cluster-tests) gives more details on their desired schedule and reasons for choosing so)
- The prow containers running the scale jobs should be accessible by scalability team easily (this hopefully is already true)

**Comment by fejta** [comment]
I think we should leave this scheduling complexity of out periodic jobs. People with unusual scheduling requirements can write their own controller which schedules prow jobs according to their requirements.

**Comment by ignacyk** [comment]
Can we use CronJobs in Prow instead? If we need them to be in Beta or Stable, it would be still better to align the timelines of migration rather than write a throw-away code.

**Comment by fejta** [comment]
Yes you can use CronJobs, but I am not sure that is the best plan as a) I'm not sure that will allow you to schedule a bi-weekly job either and b) that will diverge from all the other jobs.

What throw-away code are you worried about?

**Comment by shyamjvs** [comment]
+1 to making use of cronjobs which is one of the paradigms k8s already offers over re-writing a custom controller for the same (I guess that's the throw-away code @ignacyk meant). Btw - there's a plan to migrate cronjobs to beta (https://github.com/kubernetes/kubernetes/issues/41039) in 1.8.

> I'm not sure that will allow you to schedule a bi-weekly job 

We can do it using 2 cron tabs (https://stackoverflow.com/a/19276777). Besides, not all the jobs are bi-weekly and also the plan is to move some of the bi-weekly ones to weekly eventually.

>  that will diverge from all the other jobs

Not sure if that's a reason for not supporting cron jobs. We still seem to have jobs on jenkins that're using cron tabs (for e.g [soak tests](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci-soak.yaml), [node tests](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci-repo.yaml#L209-L244), etc) and it would be a huge convenience if prow supports it (would be one more reason why prow is beautiful :).

Besides, using cron tabs makes things more predictable. For e.g if the prow cluster goes down, we would not restart a job when it comes back up after a couple of hours because of using cron tabs. While with period-based approach there's a chance that jobs would be shifted by some phase each time prow restarts (unless we preserve some state). Just a consideration to take note of.

**Comment by spxtr** [comment]
> I think we should leave this scheduling complexity of out periodic jobs.

I don't think their needs are too far out. We can think about how to augment prow's scheduling to fit their needs without too much difficulty.

> Besides, using cron tabs makes things more predictable. For e.g if the prow cluster goes down, we would not restart a job when it comes back up after a couple of hours because of using cron tabs.

Prow stores state in the same place CronJobs do, they're just called ProwJobs. We restart individual components of the cluster every day. If the entire cluster goes down then they will behave exactly like CronJobs :)

> While with period-based approach there's a chance that jobs would be shifted by some phase each time prow restarts (unless we preserve some state). Just a consideration to take note of.

It uses the start time for deciding when to start the job, so at most it will shift by thirty seconds or so each week. This isn't ideal, though.

**Comment by shyamjvs** [comment]
> Prow stores state in the same place CronJobs do, they're just called ProwJobs. We restart individual components of the cluster every day. If the entire cluster goes down then they will behave exactly like CronJobs :)

Clean!

> It uses the start time for deciding when to start the job, so at most it will shift by thirty seconds or so each week. This isn't ideal, though.

Awesome - 30s is probably something we can live with for a while. However, would it be possible to time the first run of a job (so that all subsequent runs can also be ensured to run at the same time of the day on the same day of a week)? Because then we can time the first run and set the time interval to '24 * 7 * 2' hours to make it run biweekly.

**Comment by spxtr** [comment]
> However, would it be possible to time the first run of a job (so that all subsequent runs can also be ensured to run at the same time of the day on the same day of a week)? Because then we can time the first run and set the time interval to '24 * 7 * 2' hours to make it run biweekly.

That's possible, just merge your new job spec at the time you want it to happen.

We will need to make a small change to sinker in before this proceeds. Right now it will clear the old prowjob after a couple days, so we need it to persist at least one of each periodic prowjob.

**Comment by krzyzacy** [comment]
/assign

@shyamjvs I think I'll probably just implement cron support in prow

**Comment by BenTheElder** [comment]
> @shyamjvs I think I'll probably just implement cron support in prow

(discussed at standup today, cron in horologium/prow looks reasonable enough) 👍

**Comment by krzyzacy** [comment]
I have a rough draft, but things I still need:
- cancel a cron entry if the job is deleted
- abort a cron trigger if the previous job is still running

And it's super easy to migrate from duration string to cron string, as cron string supports format like `every 2h30min45s`

**Comment by shyamjvs** [comment]
Great - thanks for working on it.

**Comment by krzyzacy** [comment]
(done)
