### ISSUE TITLE
Prow and gubernator provide insufficient information to debug outages

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3787]
We need some way for
* bootstrap to log the prowjob yaml used to launch this testing
* gubernator and testgrid to display this info

/cc @spxtr @rmmh @michelle192837

**Comment by spiffxp** [comment]
I didn't see anything concrete in v1.9 sig-testing roadmap about this, so took a best guess and added to 2018-goals

**Comment by BenTheElder** [comment]
/assign
I want to improve this logging portion of this in Q1.

We can at least see the prowjob yaml in the re-run link on deck for now, but we should log this to GCS.

I'm at least logging the image name where possible now so we know the image revision that was used, which makes the build log mostly sufficient to trace back how a job was run since we already log the scenario args, but this could be better.

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
Logging the prowjob yaml is something I intend to do with the logging sidecar, which does exist now though not in k8s prow yet (and doesn't log this yet).

**Comment by stevekuznetsov** [comment]
Also with the advent of the logging controller that is watching for test pods ... we can start adding more to that logic as well.

**Comment by spiffxp** [comment]
/milestone 2019-goals
We'll be coming up on a year for this issue, have we made sufficient progress?

**Comment by BenTheElder** [comment]
bootstrap.py sneaks extra info into artifacts now :^)

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/lifecycle frozen
I'm not sure I like freezing this but I think it merits discussion / rescoping before outright closing

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
/close
Spyglass displays prowjob yaml if the ProwJob CR still exists in the prow cluster's api, and a gcs reporter puts pod info as a separate artifact in GCS
