### ISSUE TITLE
ok-to-test not detected in review approval

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#3827]
Example: https://github.com/kubernetes/kubernetes/pull/49872

Other commands like `/lgtm` are

**Comment by nlandolfi** [comment]
I think a fix requires trigger plugin to register a `plugins.ReviewEventHandler` and check for `/ok-to-test` there as well.

@spxtr thoughts? I can volunteer to fix this if you see fit.

**Comment by spxtr** [comment]
SG. @cjwagner did this for other plugins.

**Comment by cjwagner** [comment]
Yeah the lgtm plugin uses review events and review comment events.

**Comment by kargakis** [comment]
@cjwagner is this fixed now?

**Comment by cjwagner** [comment]
No this hasn't been fixed.
The Trigger plugin has to list all comments to see if an `/ok-to-test` command exists every time it wants to check that a non-member PR is trusted. Checking reviews and review comments for this command would require at least 2 additional API tokens every time. Is that worth it?

**Comment by kargakis** [comment]
Can't we start handling `review_comment`s?

**Comment by cjwagner** [comment]
We could, but that doesn't allow us to skip listing the reviews and review comments. We could check `review_comment` events and remove the `do-not-merge/needs-ok-to-test` label if the comment contains `/ok-to-test`, but we would still need to list all reviews and review comments when checking if a non-member PR is trusted to prevent race conditions with other events. See the discussion in the comments at the end of this PR https://github.com/kubernetes/test-infra/pull/5246.

**Comment by fejta** [comment]
I'm not entirely convinced that `/lgtm` should serve as an `/ok-to-test`. Historically `/lgtm` meant "I will test this commit but do not trust your next one, which will also not have an LGTM label"

We may want to keep this behavior

**Comment by kargakis** [comment]
> Historically /lgtm meant "I will test this commit but do not trust your next one, which will also not have an LGTM label"

I was thinking about this recently and I agree. Once external contributors have `ok-to-test`, they can push whatever they want and it will get tested. I think we should at least provide an option to enable this behavior, so every new commit will need to be reviewed before tests run.

**Comment by ixdy** [comment]
I think this is illustrating a workflow that's currently missing in prow and tide.

With the munger, we remove lgtm if any commits are changed, so it's possible to approve a change to be merged but automatically require reapproval if anything changes.

AFAIK, this isn't possible with prow or tide.
I can `/lgtm` something, but that won't actually allow it to be merged unless I also `/ok-to-test` it. But if I do that, there's nothing to prevent it from being merged if anything changes.

It's also frustrating that I can't approve a PR to be merged without allowing all subsequent commits to be automatically tested, either - I have to `/ok-to-test` a PR to get tide to merge it.

**Comment by cjwagner** [comment]
@ixdy Good point. The way Tide is configured now that workflow isn't possible.

> With the munger, we remove lgtm if any commits are changed, so it's possible to approve a change to be merged but automatically require reapproval if anything changes.

The Submit Queue just handles this by ignoring `needs-ok-to-test` when triggering tests. With the SQ if a PR is untrusted, but LGTMed, it will be tested once at the time of `/lgtm` and then the SQ will comment with `/test all` to trigger retesting. The munge bot is an org member so the `/test all` triggers testing even if the PR has `needs-ok-to-test`.

I think we can solve this by changing the Tide query to allow triggering tests on PRs that have `needs-ok-to-test` and also employing the `lgtm-after-commit` munger (hopefully a plugin soon https://github.com/kubernetes/test-infra/issues/3795). That would allow us to stop testing a PR if it changes (because `lgtm` will be removed and it will no longer match the Tide query), but it would allow Tide to trigger retests as needed so long as the PR branch hasn't changed.

**Comment by spiffxp** [comment]
/help
I still see people using /ok-to-test in PR reviews (as comments, aka no approval or change requested) and nothing happening

**Comment by BenTheElder** [comment]
> I still see people using /ok-to-test in PR reviews (as comments, aka no approval or change requested) and nothing happening

This includes me. Intuitively I should at least skim a PR's contents before `/ok-to-test` so it makes sense to leave this as a comment from the "files changed" UI, which makes a review comment instead of a normal comment :|

**Comment by cjwagner** [comment]
Switching from the `needs-ok-to-test` label to a positive, `ok-to-test` label would allow the trigger plugin to check if a PR is ok to test by listing labels instead of listing issue comments, reviews, and review comments which would save API tokens.
Using a positive label instead of a negative one avoids all the race conditions that force us to list comments and check for `/ok-to-test` instead of just checking for a label.

**Comment by BenTheElder** [comment]
We should just save all [PR | Issue] state in GitHub labels always :-)
Who needs etcd / CRDs when you have GitHub? /s

**Comment by cblecker** [comment]
I understand the idea, but also, ugghhhhh.. label overload. Having a label just to say testing is okay.. bleh. Ugly. (No, I don't have a better suggestion)

**Comment by BenTheElder** [comment]
/kind bug
xref #7801 was a dupe reporting this by @xiangpengzhao

**Comment by matthyx** [comment]
Hi, I also like the suggestion of @cjwagner to switch to a positive `ok-to-test` instead of the negative one... but we have to plan the migration path:
1. fix this bug (as we anyway need to parse correctly the reviews)
2. add support for `ok-to-test` in trigger and maybe other plugins concerned (so basically supporting both old and new behavior)
3. add `ok-to-test` to all active PR that don't have `need-ok-to-test`
4. remove `need-ok-to-test` flags to PR
5. remove code that relies on `need-ok-to-test`

What do you think?

**Comment by cblecker** [comment]
@cjwagner Do you envision `ok-to-test` be needed on *all* PRs, or only those from non-org members? e.g. prow looks for the label, *or* IsMember

**Comment by BenTheElder** [comment]
One more downside to positive labels in the short term is that they're
likely to be accidentally removed when users with write access edit labels
in the GitHub UI 🙄

**Comment by cjwagner** [comment]
> Do you envision ok-to-test be needed on all PRs, or only those from non-org members? e.g. prow looks for the label, or IsMember

@cblecker  I was imagining all PRs (that would save the most API tokens), but only requiring the label on non-member PRs seems like a good compromise. If we went that route the label bloat would only affect a small fraction of PRs and even though we would be using more API tokens than if we always required the `ok-to-test` label, we would still be using fewer than we use currently.
That seems like a good starting point even if we end up deciding later that we want to require the label on all PRs.

**Comment by cjwagner** [comment]
> Alright, should we ask sig-contributor-experience to get their opinion on requiring ok-to-test for non-members PRs?

Yeah that sounds like the next step. Maybe post in the sig-testing and sig-contribex slack channels?

**Comment by matthyx** [comment]
Sorry I have been delayed by verify-owners issue... I will prepare the message and post it Monday morning (California time) I think it will have more visibility than during the weekend.

**Comment by cblecker** [comment]
And once we have that design proposal, we should send it out for comment to the contribex and testing e-mail lists, rather than just Slack.

**Comment by matthyx** [comment]
Okay, I can start working on that and drive it if you wish... but where should it be written? Do we have a space for RFCs or something similar?

**Comment by matthyx** [comment]
I think I've found it... gonna write it in https://github.com/kubernetes/community/tree/master/contributors/design-proposals/testing

**Comment by matthyx** [comment]
Now that the KEP has been merged, I will start implementing it soon... stay tuned.

**Comment by matthyx** [comment]
KEP implementation tracked in #9754
