### ISSUE TITLE
k8s-merge-robot doesn't assign assignees automatically from this morning

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3860]
See: 
https://github.com/kubernetes/kubernetes/pull/49995

https://github.com/kubernetes/kubernetes/pull/49996

https://github.com/kubernetes/kubernetes/pull/49997 
(note: k8s-ci-robot assigned @fejta later because of his `/lgtm`?  https://github.com/kubernetes/kubernetes/pull/49997#event-1188821702)

https://github.com/kubernetes/kubernetes/pull/50000

https://github.com/kubernetes/kubernetes/pull/50001

**Comment by xiangpengzhao** [comment]
I can manually `/assign somebody`.
See: https://github.com/kubernetes/kubernetes/pull/50000#event-1188946051

/cc @fejta @spiffxp

**Comment by xiangpengzhao** [comment]
These PRs are now assigned. Don't know why they weren't assigned this morning.

**Comment by cjwagner** [comment]
This wasn't a bug in mungegithub in the sense that there was a failure to assign users. Mungegithub was just very backed up and hadn't munged those PRs in a while due to a bug that caused the munger to stall for a while when it tried to read mergability for PRs that are already merged. That bug was fixed in #3832 and I deployed the change just before 11pm Pacific time last night.  I'm going to close this issue since it should be resolved already. Please reopen it if you see this happen again.

**Comment by xiangpengzhao** [comment]
Thanks @cjwagner !
