### ISSUE TITLE
Tests are started per commit for postsubmit jobs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3910]
Postsubmits are started on every Github push event. This means that every commit in a PR will start a new job, plus the merge commit will start its own job. Since the submit queue explicitly uses merges, does it make sense to update the trigger plugin to start jobs only on merge commits?

/area prow

/cc @spxtr @stevekuznetsov

**Comment by spxtr** [comment]
Oh, that's not what I expected. I assumed that because the push event contains multiple commits, they would send one per merge with all the commits in the PR together. I guess they send one per commit instead.

I'm not sure that we want to start jobs only on merge commits, since occasionally people push directly.

**Comment by kargakis** [comment]
This is really bad when we do rebases where we bring in a ton of commits. Unclear how to fix it though. @stevekuznetsov @cjwagner
