### ISSUE TITLE
Fix jenkins jobs updater

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#4028]
I believe I regressed this awhile back when I updated the jenkins master and removed some plugins
/assign @ixdy 
who has been working on this

**Comment by ixdy** [comment]
Things are still kinda broken.

We re-use the same container each time we run the updater (not sure why), and now that we're cleaning the workspace between runs (https://github.com/kubernetes/test-infra/pull/4025) the volume mount goes bad.

I guess we can stop leaving the container running? I'm not sure what badness that might cause.

**Comment by fejta** [comment]
that's weird that we leave the container running

**Comment by fejta** [comment]
IMO that job violates our rule that all things are a) clone test infra b) bootstrap.py --job

**Comment by ixdy** [comment]
I think this is an artifact of the way things [used to be a while ago](https://github.com/kubernetes/test-infra/blob/2bbf72b3534359994c86d14ed44ed3bffaca83fe/jenkins/update-jobs.sh#L44-L46) - since we stored the git repo inside of the container, and we were cloning `kubernetes/kubernetes`, it was expensive to clone it each time.

Now it's probably safe to just run and delete the container each time.

**Comment by ixdy** [comment]
argh.
```
+ git clone https://github.com/kubernetes/test-infra -b master
Cloning into 'test-infra'...
+ cd test-infra
+ ./jenkins/update-jobs.sh jenkins/job-configs:jenkins/job-configs/kubernetes-jenkins
cannot enable tty mode on non tty input
```

**Comment by ixdy** [comment]
appears to finally work again.
