### ISSUE TITLE
Submit-queue one label bypass all requirement

### ISSUE THREAD

**Issue by yutongz** [kubernetes/test-infra#4058]
Am I able to set one single label and as long as a PR has this label, submit-queue will forget about all other label requirement (approve, lgtm, release-note). And also I hope this kind of super-power labels can be defined in the config.

I want this since we have periodical PRs created one robot and hope they can be merged by merge-robot without human involved.

**Comment by kargakis** [comment]
You can write a job that lists all the generated PRs and add all the required labels in them.

**Comment by yutongz** [comment]
Yes, that definitely is a solution. But if we can have one special label for one specific category e.g. fast-forward, that would be clearer and easier to manage.

**Comment by fejta** [comment]
/assign @spxtr 

Please see the design doc for the submit queue redesign - https://groups.google.com/d/msg/kubernetes-sig-testing/tBWTEOEfrO4/k5um2t5xAgAJ

If this is an emergency, please contact the go.k8s.io/oncall buildcop to manually merge your emergency fix.

Otherwise we intend to specify a well known search query. And anything which is in that list is on the queue and will merge.

**Comment by kargakis** [comment]
tide to the resqueue!
