### ISSUE TITLE
Bazel is missing some failures

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#4083]
[This pull-request](https://github.com/kubernetes/kubernetes/pull/50558) is removing `pkg/watch/doc.go` but doesn't update the corresponding `BUILD` file. It should fail to `bazel build`, shouldn't it? 

EDIT: It's also missing `pkg/api/errors/doc.go`.

**Comment by krzyzacy** [comment]
```
W0812 15:57:19.463] Run: ('bazel', 'query', '--keep_going', '--noshow_progress', 'kind(.*_binary, rdeps(set(//cmd/... //pkg/... //federation/... //plugin/... //third_party/... //examples/... //test/... //vendor/k8s.io/...), set(//pkg/api:BUILD //pkg:BUILD //hack:verify-generated-protobuf.sh //hack:.golint_failures )))')
W0812 15:57:19.474] INFO: $TEST_TMPDIR defined: output root default is '/root/.cache/bazel'.
W0812 15:57:48.701] ____Empty results
W0812 15:57:48.707] Run: ('bazel', 'build')
```

hummmm because there's no binary affected?

**Comment by krzyzacy** [comment]
Maybe we'll need something like `verify/update-bazel` in k/k as well.

**Comment by ixdy** [comment]
hm, this is tricky.

We didn't catch this in presubmit tests because we only run affected builds/tests, and we [filter out deletions from the git diff](https://github.com/kubernetes/test-infra/blob/e055c28529275bd25eca697eaba4d5d08d6811f2/scenarios/kubernetes_bazel.py#L61) because that can cause us to try to test things that don't exist.

The rule not getting deleted in a gazelle bug (https://github.com/bazelbuild/rules_go/issues/332), time to fix unclear.

I guess we can switch off `--affected` until gazelle is fixed.

**Comment by ixdy** [comment]
I'm a little surprised the `bazel query` didn't fail, but I guess it only looks at BUILD rules, not at the actual sources underneath.

**Comment by krzyzacy** [comment]
Actually let's leave this open until we flip `--affected` back.

**Comment by xiangpengzhao** [comment]
Hmm, my bad. I do believe I had run `hack/update-bazel.sh` and committed all the files it touched before I created https://github.com/kubernetes/kubernetes/pull/50558 :)

**Comment by apelisse** [comment]
@xiangpengzhao Absolutely not your fault. The problem comes from the system that didn't catch that :-)

**Comment by xiangpengzhao** [comment]
@apelisse :smile:
