### ISSUE TITLE
prow: determine roadmap for github client in prow

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#4240]
Today, an internal client is used for GitHub interaction in Prow, unlike in mungegithub. What are the long-term plans for this? Do we intend to maintain this internal client? Do we intend to migrate in the future? What are the pros and cons we see for both approaches?

/cc @spxtr @kargakis @fejta @marun

**Comment by spxtr** [comment]
Do you mean [k8s.io/test-infra/prow/github](https://github.com/kubernetes/test-infra/tree/master/prow/github)? I originally used go-github, but there were a few reasons to switch:

1. go-github doesn't handle retries or pagination. I needed those things for all calls, so I needed to wrap its calls anyway.
1. go-github had some strange flakes that I've forgotten all about.
1. go-github is more difficult to test due to its overall structure. The `client.*Service` stuff makes it just a bit trickier. A good wrapper would solve this problem. See https://github.com/google/go-github/issues/113.
1. GitHub's API is a simple, well-documented REST API. It's very easy to write REST clients in Go.

I don't think it's likely to switch back anytime soon. Instead, I see us using a small, thin wrapper around [github.com/shurcooL/githubql](https://github.com/shurcooL/githubql). It's just one or two methods to wrap, so it's much easier than before. Pagination is still manual, but it doesn't require messing with HTTP headers. The GitHub v4 API is The Future according to them.

**Comment by stevekuznetsov** [comment]
> go-github doesn't handle retries or pagination. I needed those things for all calls, so I needed to wrap its calls anyway.

Are the upstream authors against adding support for this?

> go-github is more difficult to test due to its overall structure.

If we keep the current:

```go
type githubClient interface {
    MethodICareAboutInThisContext()
}
```

wrappers that we have today, I'm not sure that gets any harder for us

> GitHub's API is a simple, well-documented REST API. It's very easy to write REST clients in Go.

It is, but it feels like the dark ages when everything is stringly-typed and non-discoverable.

**Comment by stevekuznetsov** [comment]
> Instead, I see us using a small, thin wrapper around github.com/shurcooL/githubql.

This is a compelling reason not to worry about changing any of the current client code

**Comment by spxtr** [comment]
> Do we have a tracking issue for it?

Nope, since it's still pretty experimental. Feel free to either open a new issue or turn this one into a tracking issue.

> Do we know when that API will stabilize?

Not sure, but as long as we vendor it it's not too painful. I doubt that the general structure will change much, since it currently supports most operations.

**Comment by spxtr** [comment]
> Are the upstream authors against adding support for this?

I think it's outside the scope of go-github. Their library is simply a thin wrapper around the API.

> It is, but it feels like the dark ages when everything is stringly-typed and non-discoverable.

:european_castle: :crossed_swords: :crown: I don't think it's stringly-typed, but it certainly is non-discoverable.

**Comment by stevekuznetsov** [comment]
Cool. I'll open an issue to move to the graph API. Thanks for the insights!
