### ISSUE TITLE
cadvisor-push failing starting between 8/22 and 8/24

### ISSUE THREAD

**Issue by dashpole** [kubernetes/test-infra#4403]
Fails with the error:
`Unable to locate package dmsetup`

Previously it passed with:
`dmsetup is already the newest version.`
`dmsetup set to manually installed.`

**Comment by dashpole** [comment]
Running on `agent-heavy-08-b` nodes.
[Testgrid](https://k8s-testgrid.appspot.com/sig-node#cadvisor-push)

**Comment by krzyzacy** [comment]
cc @ixdy 
/shrug

**Comment by ixdy** [comment]
It looks like that job is using the `golang:latest` docker image:
```
I0825 02:29:47.519] Status: Downloaded newer image for golang:latest
```

I'm guessing that's roughly around when go 1.9 was released, and so the image was updated.
Mysteriously, it seems that the `golang:1.8.3` image comes pre-installed with dmsetup, whereas `golang:1.9` does not:
```console
$ docker run --rm -ti golang:1.9 dmsetup version
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"dmsetup\\\": executable file not found in $PATH\"\n"
$ docker run --rm -ti golang:1.8.3 dmsetup version
Library version:   1.02.90 (2014-09-01)
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper ? and kernel driver 
Command failed
```

The Dockerfile has an `apt-get install`:
https://github.com/google/cadvisor/blob/1df21eaa592316b0889db44ab0b3c22d66846482/deploy/canary/Dockerfile#L4

but since there's no `apt-get update`, and there's no cache in the image, it fails.

Assuming you do actually need dmsetup in the build image, you can add `apt-cache update &&` and `&& apt-get clean` to fix this. Or you can remove that line, if you don't need dmsetup.

cc @vishh @tallclair
