### ISSUE TITLE
Do not comment that my PR is approved

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#4460]
Similar to not commenting that my PR is lgtm'd. I probably don't understand what an approval means and as long as my PR is set to merge I don't really care.

@kubernetes/sig-contributor-experience-proposals

**Comment by grodrigues3** [comment]
Can you explain the proposed workflow in more depth?

I assume PR authors do care when their PR is not approved and they want to know what needs to be done in order to get the PR merged (hence the NOT approved comment and link to OWNERS files).

But if we create a comment indicating the PR is not approved, we have to at the very least delete it when the PR is approved.  Are you suggesting that we don't create a new comment?  If so, why?  Is it too noisy?

**Comment by spxtr** [comment]
> Are you suggesting that we don't create a new comment? If so, why? Is it too noisy?

Yes, it's unnecessary noise. Ideally, once your PR is ready to go there is no bot comment remaining.

**Comment by kargakis** [comment]
@grodrigues3 we have to create a comment when the PR is not approved. But when the PR is approved, similar to when it is lgtm'd, the bot should just add the label and call it a day.

**Comment by spiffxp** [comment]
I'm not sure I'm in favor of this.  The comment provides a useful audit of whose approval counted and why.  I wouldn't be able to figure that out just by looking at random people's /lgtm and /approve comments.

**Comment by kargakis** [comment]
@spiffxp will https://github.com/kubernetes/test-infra/issues/4340 be helpful in that regard?

**Comment by spiffxp** [comment]
It might provide an approximation but it's going to be fuzzy, and leaves out the "why" part

I get that it's noise on single-approver or self-approvable PR's, but the comment to me still represents the best point-in-time snapshot of the decision that "this is approved, because it's linked to this issue, and because these people, associated with these files, said yes."

**Comment by cblecker** [comment]
> I'm not sure I'm in favor of this. The comment provides a useful audit of whose approval counted and why. I wouldn't be able to figure that out just by looking at random people's /lgtm and /approve comments.

+1. It's helpful to have that point in time, explicit audit trail especially considering that comments generated by a user can be removed by that user. Anyone can leave a comment "/approve", but you don't necessarily know which files without tracking it down.

**Comment by kargakis** [comment]
We can at least stop adding the message in case self-approvals are on and the PR is approved as soon as it's opened. I understand the need to have the comment around in case there have been approvals by other persons but the message is pretty annoying when it is posted on every PR that I open and for which no other explicit approval has happened.

**Comment by kargakis** [comment]
We can at least stop adding the message in case self-approvals are on and the PR is approved as soon as it's opened. I understand the need to have the comment around in case there have been approvals by other persons but the message is pretty annoying when it is posted on every PR that I open and for which no other explicit approval is required.
