### ISSUE TITLE
F-Secure lists ci-test.k8s.io and submit-queue.k8s.io as harmful

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#449]
Example:

![image](https://cloud.githubusercontent.com/assets/5442475/17948838/37a55d2c-6a5b-11e6-820f-8017308f9bd3.png)
 :cry: 

@ixdy

**Comment by ixdy** [comment]
that's odd. wonder what we did.

@rmmh

**Comment by ixdy** [comment]
As best I can tell F-Secure is just wrong. I don't think it's anything we did.

Any of their debugging tools to help webmasters seem to have been shut down years ago. I'm not impressed.

**Comment by rmmh** [comment]
This happened a while ago with SafeBrowsing when ci-test or pr-test was redirecting to the GCS storage browser.

Based on some brief forums results, it looks like F-Secure might be marking URLs that start redirecting to different domains as evil. ci-test is redirecting to gubernator instead of GCS for that URL now.

**Comment by fejta** [comment]
Has F-Secure finished scolding us for changing the redirection target?

**Comment by rmmh** [comment]
Closing, since I can neither test nor fix this.
