### ISSUE TITLE
git links on Gubernator CI results are broken

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#4540]
From https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/14106.

Clicked on `v1.9.0-alpha.0.558+108ee220966677` on top and it linked to https://github.com/None/commit/108ee220966677.

**Comment by porridge** [comment]
I fact, ALL git links are broken. E.g. in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/28
The links to code within assertion failure messages lead to URLs such as https://github.com/None/blob/95b4312899b109/test/e2e/autoscaling/horizontal_pod_autoscaling.go#L70

It feels like a configuration issue, and fixing this would improve productivity a lot.

**Comment by BenTheElder** [comment]
cc @rmmh 
As long as the refs are right it should be possible to copy the refs and still find the revision(s) in the meantime.

**Comment by porridge** [comment]
@BenTheElder I don't understand what you mean... Copy to where?

**Comment by BenTheElder** [comment]
All of these just appear to have `None` in place of the repo because the repo metadata is missing. We know the repo is `kubernetes/kubernetes` so `s/None/$REPO/`.

What I meant by copying them though is that they're git refs you can use standard git commands and GitHub URLs to inspect them. EG the one in the original post is for the ref `108ee220966677` which can is on GitHub at [`https://github.com/kubernetes/kubernetes/commit/108ee220966677`](https://github.com/kubernetes/kubernetes/commit/108ee220966677) or viewable locally with say ` git show 108ee220966677`.

Same for your URLs.

**Comment by rmmh** [comment]
This was fixed in #6209.
