### ISSUE TITLE
prow/size: +5 -3 PR currently has size/XXL label applied

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#4613]
https://github.com/kubernetes/kubernetes/pull/52589

It may have initially been a much larger PR?

https://github.com/kubernetes/kubernetes/pull/52589#issuecomment-330347315
>It may be due to I targeted master branch before changing it to release-1.7. It should be fine as long as the codes target release-1.7.

Maybe retargeting triggered an event the size plugin ignores?

**Comment by spxtr** [comment]
Interesting! Looks like [this list](https://github.com/kubernetes/test-infra/blob/b82b634d8fa4af8451f70051158478c659c6efe1/prow/plugins/size/size.go#L53-L58) isn't complete, since PR edit events can also change the diff. @nlandolfi might be busy these days with school, so if anyone else wants to jump on and fix then I'd appreciate it. It's an easy fix.

**Comment by xiangpengzhao** [comment]
PR #4627 sent :)
