### ISSUE TITLE
Manual trigger for pausing testing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#4638]
@rmmh mentioned in the community "sig-testing test-infra oncall standup" meeting today that it might be helpful to have a manual switch we can use to temporarily shed testing load while we are EG fixing Jenkins.

My thoughts are:
- Open a test-infra issue with a special label that will disable triggering in Prow
- Have the trigger plugin reply to trigger attempts with a comment linking to the test-infra issue
- Re-enable testing once the issue is closed.

We can additionally separately send messages ourselves to the appropriate channels and then when the incident is over we can search GitHub for the trigger comments linking to the issue and trigger them.

**Comment by spxtr** [comment]
It's an interesting idea, and certainly possible. However, I'm not sure it's worth the effort to automate all of this.

Instead, it might be worth adding a label called something like `kind/incident` and then linking to [a search for that label](https://github.com/kubernetes/test-infra/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Akind%2Fincident) instead of just all test-infra issues.

**Comment by BenTheElder** [comment]
My intention that the commment should link to the test-infra issue which currently has the label (`kind/incident` then) causing the trigger to be ignored. Linking to a search might be simpler but I think it might be more useful to see the specific incident associated with the comment. I definitely think that it should be done via a label on an issue tracking the incident.

I'm not sure it would take much effort, but it should probably be something we do *after* everything is currently settled.

**Comment by BenTheElder** [comment]
This was discussed some more off and on, but we haven't planned exactly how we want to implement this yet and it doesn't seem terribly urgent at the moment.
