### ISSUE TITLE
Make pull-kubernetes-e2e-gce-gpu blocking

### ISSUE THREAD

**Issue by mindprince** [kubernetes/test-infra#4642]
The `pull-kubernetes-e2e-gce-gpu` job has been running for a while on every PR and has been reasonably non-flaky: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-gpu

We recently stopped running all non-blocking tests on every PR in #4640.

I would like to make the `pull-kubernetes-e2e-gce-gpu` blocking if there are no objections.

**Comment by krzyzacy** [comment]
cc @spiffxp

**Comment by krzyzacy** [comment]
Let's make the gpu job working on prow instead of Jenkins and we can make it always run and blocking. @BenTheElder is working towards it.

**Comment by BenTheElder** [comment]
ref https://github.com/kubernetes/test-infra/pull/4639 for the most recent PR, I've had a job pass now and once that config is updated I expect this should work. we can probably officially migrate to prow soon but I want to see it pass more :-)

**Comment by BenTheElder** [comment]
Following up, I've gotten one run in since #4639, and it was succesful.
Runs [here]( http://prow.k8s.io/?type=presubmit&repo=kubernetes%2Fkubernetes&pull=46662&job=pull-kubernetes-e2e-gce-gpu-prow), `Sep 19 22:17:49` is the start time of the first one after that PR.
Also [here](https://k8s-gubernator.appspot.com/pr/46662) under `pull-kubernetes-e2e-gce-gpu-prow`.

I will run more and keep an eye on them.

**Comment by BenTheElder** [comment]
This also [works on release-1.7](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52755/pull-kubernetes-e2e-gce-gpu-prow/14/) and has [4 succesful runs](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-gpu-prow) since #4639.
I think we can probably switch the GPU job to run on Prow any time @mindprince.

**Comment by krzyzacy** [comment]
I think we can flip it to prow now to give @mindprince more signals :-)

**Comment by mindprince** [comment]
Awesome. Thanks guys!

**Comment by krzyzacy** [comment]
We'll watch the job for a few days (until code freeze maybe), and @mindprince you will want to propose to release team to make the job blocking (maybe join our burndown meeting next Monday?) :-)

**Comment by krzyzacy** [comment]
@jdumars FYI

**Comment by BenTheElder** [comment]
This job has been pretty well behaved, perhaps we can make it blocking after the release is done? I think we will need to propose it somewhere (the sig-testing meeting maybe?)

**Comment by spiffxp** [comment]
Just bumped into a quota issue

https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-e2e-gce-gpu
```
W0929 18:01:58.316] ERROR: (gcloud.compute.networks.create) Could not fetch resource:
W0929 18:01:58.317]  - Quota 'SUBNETWORKS' exceeded.  Limit: 160.0
```

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/4472 for probably the best solution, though generally we should be fine via `max_concurrency` and the janitor.

**Comment by BenTheElder** [comment]
Adding a note: the networking quota issue has been solved for this job and the fix is being rolled out to other jobs (thanks @MrHohn !)

**Comment by krzyzacy** [comment]
/unassign @jdumars 
/assign @mindprince @BenTheElder 
I guess feel free to send or update the PR to make it blocking before 1.9

**Comment by BenTheElder** [comment]
@krzyzacy I did: https://github.com/kubernetes/test-infra/issues/5134
