### ISSUE TITLE
Investigate configuring kuberentes anywhere commit used for e2e testing

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes/test-infra#4680]
That way a new image does not need to be built every time we need to bump k8s anywhere.

**Comment by pipejakob** [comment]
For context, here is the comment that triggered this issue:

> @luxas @pipejakob @jessicaochen this does not look like a good pattern in general to me now - this need to be configurable through a flag rather than built in to the runner and we have to push a new image every time.

https://github.com/kubernetes/test-infra/pull/4679#issuecomment-331261103

**Comment by pipejakob** [comment]
I'll admit that the initial implementation of this (doing a `git checkout` of a specific commit in the image runner) was just the quickest solution to get at the [desired behavior](https://github.com/kubernetes/kubeadm/issues/191), but now that I've thought about it, here is my defense of having the version in the runner.

I want our solution here to have two properties:

1) Upstream changes to kubernetes-anywhere shouldn't be able to immediately break all of our e2e tests. The project doesn't have presubmit validation, automated testing, or clear guarantees on what functionality is meant to be stable and supported, so I worry that it would be just another source of random test failures that would require constant triaging and fixing.
2) Since we do occasionally want to pick up upstream changes from kubernetes-anywhere, we should be able to do test runs to sanity-check that newer versions don't break our e2e tests before actually making those changes live.

When the image runner specifies the commit to use, (2) becomes very easy to verify in an accurate way: I can use prow's "rerun" functionality to submit a new instance of an e2e job, for any job that I want, with a substituted image that I've built locally. I don't need to open a pull request, or get any code in test-infra merged, I can just make the change locally, build and push the new image (not used by any job), and then submit a new job to prow using the new image version. If the test run succeeds, then I can open a PR for these local changes and to bump the image version in prow's `config.yaml` so that all of our e2e jobs pick up the change. If the test run failed, there's nothing to rollback, since nothing was committed.

If we move the kubernetes-anywhere commit out of the image runner and into a flag, then if I want to validate that a newer commit still works in our e2e jobs, I have to update `jobs/config.json` for one of the jobs I want to test in order to change the flag, open a PR, get it reviewed and merged, and then trigger the e2e test to check if it still works. If it does, I have to open another PR to change the flag for every job, and get it reviewed/merged. If the job doesn't pass, I have to open a new pull request to revert the previous change in order to fix the e2e job I was testing.

I might be missing a different way to model this as a flag that would allow for an easier workflow than described above, but the first option (what we currently have) seems much more straight-forward to me. Is there a reason we want to minimize image churn? Another way of framing this is that kubernetes-anywhere is a tool we use as part of the image, just like kubetest, gcloud, or terraform. All of those other tools are bundled into the image so that they are explicitly versioned together, why shouldn't the kubernetes-anywhere version be tied to the image version? We could actually bake it into the image instead of doing a `git clone` and `git checkout`, but conceptually it's the same thing.

**Comment by krzyzacy** [comment]
I would suggest this SHA can be a env var in prow config -

ref https://github.com/kubernetes/test-infra/tree/master/prow#how-to-run-a-given-job-on-prow, you can mkpj to get your podspec, and simply sub out the SHA and pipe into `kubectl apply` if you want to test local changes. And I would suggest you have a canary job to test kubeadm head as well.

**Comment by krzyzacy** [comment]
Ultimately I think kuberneres-anywhere should have its own presubmit job :-)

**Comment by pipejakob** [comment]
I'm still not sure I understand the objection to bumping the image. Are we trying to save on storage? Is it a philosophical objection, or technical? We bump the image every time we change kubetest, for instance.

**Comment by krzyzacy** [comment]
@pipejakob I just feel that it's not flexible - for example if I want to test against kubeadm head, I cannot use  the current kubeadm image anymore? And plus @luxas don't have permission for pushing the image, but if it is configurable he can change the config easier.

**Comment by luxas** [comment]
What @krzyzacy said :-)
