### ISSUE TITLE
Heapster GCE e2e test failing with permission denied error

### ISSUE THREAD

**Issue by mksalawa** [kubernetes/test-infra#471]
```
go install os/user: open /usr/local/go/pkg/linux_amd64/os/user.a: permission denied
go install net: open /usr/local/go/pkg/linux_amd64/net.a: permission denied
```

Suite **heapster-pull-build-test-e2e** ([https://github.com/kubernetes/heapster/pull/1271](https://github.com/kubernetes/heapster/pull/1271))

[Full logs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/1271/heapster-pull-build-test-e2e/452/)

@piosz suggested that `sudo make clean` might be enough to solve it.

**Comment by piosz** [comment]
@fejta @kubernetes/test-infra-maintainers I don't have permissions to login into the machine. Could you please try to execute `sudo make clean` there? This is pretty important since it blocks us from releasing stable Heapster vesion for Kubernetes 1.4 release.

**Comment by piosz** [comment]
This was fixed by @gmarek in #1273

**Comment by fejta** [comment]
`make clean` from where?

Unfortunately this is non-trivial as there are 75 potential machines that we need to run this on!

* Is there a reason this job does not run in a container?
* Could we add this bit of cleanup to https://github.com/kubernetes/test-infra/blob/master/jenkins/hourly_maintenance.py?
* When you say it was fixed by https://github.com/kubernetes/heapster/pull/1273 does that mean we can close this?

**Comment by piosz** [comment]
I'll try to migrate to run this job in a container. We haven't done it yet because it didn't have enough priority. The problem was on our side and Marek fixed it. The issue can be closed (I don't have permissions). Thanks @fejta

**Comment by fejta** [comment]
Sweet, thanks so much to you both!
