### ISSUE TITLE
federation push hyperkube image does not work using bazel build

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/test-infra#4947]
We are trying to migrate federation pre-submit jobs from jenkins to prow. So we have below query:
- Can we still continue to use the default build mechanism using `make quick-release`?
- Should we use `make bazel-release` instead for future-proofing?

**Issue with federation using bazel build:**
kubetest `--build=bazel` option seems to be not working for federation. We could change our [existing mechanism](https://github.com/kubernetes/kubernetes/blob/master/federation/develop/develop.sh#L90:L136) of building and pushing hyperkube image to bazel, if bazel supports customisation of docker image build and push, so that we can specify the registry and the tag.

@ixdy, do you have any suggestions, on how to progress?

Here is the build log which failed to push hyperkube image. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-federation-e2e-gce-canary/629/

/cc @kubernetes/sig-multicluster-bugs @madhusudancs @marun @irfan @krzyzacy

**Comment by BenTheElder** [comment]
- `make bazel-release` works great on Prow so far, `make quick-release` does not (since it needs to spawn docker containers). We might have an option to get [`make release-in-a-container`]() in the future but that involves not using docker in the build.

- `kubetest --build=bazel` internally calls `make bazel-release`

- Bazel should be able to customize docker image registry and tag in [rules_docker](https://github.com/bazelbuild/rules_docker#container_push).

cc @krzyzacy for Jenkins -> Prow

**Comment by shashidharatd** [comment]
This is a non-issue for federation now, since image is not pushed to registry after build and instead will be pushed by federation-up.sh script during federation control plane bring-up.
