### ISSUE TITLE
Make it possible to explicitely disable testing for a PR

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#500]
Hi, could we make it possible to apply a label on a PR that disables all tests except for Jenkins Verification?
That would be useful in some cases where the PR is super WIP and e2e testing isn't needed.

For example: https://github.com/kubernetes/kubernetes/pull/31221.
Now it runs all tests on every commit change, but that's completely unnecessary since we're not gonna merge it anytime soon.

The main reason for doing this is in order to reduce load on your machines, which should be used for other things (`make release`)

WDYT?

**Comment by spxtr** [comment]
I don't think it would reduce the load too much since most PRs will still want all the tests, and we'll want to run all the tests before merging. I think `[skip ci]` in the PR body might have actually done what you suggest, but that won't work soon.

The code deciding what tests to run is in the `ciongke` folder. We're switching off of the Jenkins plugin, and we'll have much more control.

**Comment by spxtr** [comment]
Related: I think one of the best ways to reduce load will be to make it so that if you update a PR it will cancel the Jenkins job that is currently testing. This won't be hard to do, I just haven't added it in yet.

**Comment by luxas** [comment]
> Related: I think one of the best ways to reduce load will be to make it so that if you update a PR it will cancel the Jenkins job that is currently testing. This won't be hard to do, I just haven't added it in yet.

That would already be a significant improvement

**Comment by ixdy** [comment]
Another helpful improvement would be to do a `make release` only once per trigger, and then share the build results for all of the various e2e scenarios. I don't know how that setup would work with the Jenkins plugin (which is why we haven't really even tried it yet), but it should be easier with our out-of-Jenkins triggering.

**Comment by luxas** [comment]
I think a build/verification initial job would be the best way.
It would first run `make quick-release`, then upload the binaries to a bucket somewhere and then trigger all other tests. Lastly, it would run `hack/verify-all.sh`
In parallell with the build/verification job, a full `make release` job should be run.

This approach would reduce the current five `make quick-release` jobs to just one `make quick-release` and one `make release`, and the e2e tests wouldn't even be started if the binaries can't be compiled.

This along with not running the e2e tests when the `retest-not-required[-docs-only]` labels are present, would dramatically reduce the load on your machines I think.

WDYT?

**Comment by spxtr** [comment]
Agreed.

**Comment by spxtr** [comment]
We could optimize even further by having the build/unit test jobs run on more powerful machines than the e2e jobs.

**Comment by luxas** [comment]
Status on this issue?

**Comment by spxtr** [comment]
I'm going to make it so that you can say `@k8s-bot skip this` in the PR body to hold off on testing. Haven't started working on it but it won't be hard to do. If you would like to make it happen sooner, the change will go in to [this file](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/hook/githubagent.go) and shouldn't be too difficult.

**Comment by k82cn** [comment]
@spxtr , maybe the issues started with `WIP` is better :). It's also hands up to reviewers that the issue is not ready to review.

**Comment by k82cn** [comment]
@spxtr , how about the command `@k8s-bot skip this`? I think that's helpful :).

**Comment by fejta** [comment]
Dup of https://github.com/kubernetes/test-infra/issues/1522
