### ISSUE TITLE
E2E tests should use a time-stamped cluster name

### ISSUE THREAD

**Issue by maisem** [kubernetes/test-infra#510]
It's really hard to dig through logs (especially on GKE) if all the clusters are named jenkins-e2e.

cc @jlowdermilk @spxtr @goltermann

**Comment by ixdy** [comment]
The counterpoint is that using the same cluster name each time means we can clean up resources from a previous run if it failed to clean up properly. (This is a fixable problem, but we need to consider it before changing how we name clusters.)

**Comment by ixdy** [comment]
vaguely related: https://github.com/kubernetes/test-infra/issues/39

**Comment by jlowdermilk** [comment]
Checking for resources from a previous run should be trivial if your naming scheme follows a template. All you have to do is pass an appropriate [`--filter`](https://cloud.google.com/sdk/gcloud/reference/topic/filters) to the gcloud command that lists resources. Example

```
gcloud compute instances list --project=k8s-jkns-e2e-gke-ci --filter='name ~ gke-jenkins-e2e[a-z0-9-_]+'
```

**Comment by fejta** [comment]
We auto create a cluster name when `--cluster=`. As long as the name is unique we can update make this behavior whatever we want:
https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e.py#L313

Closing this because it is not clear we want to do this and nothing has happened in multiple quarters.
