### ISSUE TITLE
PR becomes inactive again after new comments are deleted.

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#5239]
See in: https://github.com/kubernetes/kubernetes/pull/45465#issuecomment-340150637

This PR hasn't been active in some days and I comment something like `/hold`. The PR becomes active. But when I delete my new comment, the PR becomes inactive again (k8s-merge-robot tells me by the referenced comment above).

I'm not sure if this behavior is correct.

/cc @BenTheElder @cblecker @cjwagner @kargakis

**Comment by cblecker** [comment]
I think this is intended functionality based on https://github.com/kubernetes/test-infra/blob/44cad37f826e990ef9651e8cdaa9d362d08385c0/mungegithub/mungers/close-stale.go#L114-L190

- Look for last human comment
- Look for "interesting events".. which at the moment looks to be creating or reopening a PR
- Find the latest of the two, and use that to calculate last modification time

Because the munger doesn't track "state" per ce, it gleans this from the PR. If a comment is deleted, then it can't be considered the last human comment. A similar situation can occur if you delete an "/ok-to-test" comment.. then the bots don't know that the PR is "trusted".

**Comment by xiangpengzhao** [comment]
Is there any way for the munger tracking the state of a PR (last time it was touched, the touch can be manually adding a label; a human comment, even it is deleted then; a rebase, etc)?

**Comment by cblecker** [comment]
Why would that be desireable? If a comment gets deleted, why would we care?

**Comment by xiangpengzhao** [comment]
In this issue context, that might prevent the PR to be marked as stale. I'm not strongly on it though.

**Comment by cblecker** [comment]
If the comment gets deleted, then I think it's fair for the bot to not consider something that doesn't exist anymore when calculating activity. Trying to track objects and actions that no longer exist also makes it really hard to track/diagnose problems with bots, as they now have an internal state that is different than what exists on github.

**Comment by xiangpengzhao** [comment]
Makes sense to me. @cblecker Thanks for clarification! :+1:
/close
