### ISSUE TITLE
Update OWNERS documentation to reflect its new home (prow)

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5333]
The [appovers README](https://github.com/kubernetes/test-infra/blob/31a2e95173bd87d91e011d0edfd844b869fa89e7/prow/plugins/approve/approvers/README.md) has a bunch of mungegithub-related points that need to be converted to prow-related once the related mungers referred inside the doc are moved into prow plugins.

/assign @cjwagner 
/area prow
/kind documentation

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/assign me
/milestone 1.12
Looks like I found the separate issue I was asking for in https://github.com/kubernetes/test-infra/issues/8422#issuecomment-404667828
@cjwagner @matthyx I assigned to me because I have Opinions (see aformentioned comment) but if either of you would prefer please go for it

**Comment by spiffxp** [comment]
/assign
... right, I forgot how to self-assign

**Comment by spiffxp** [comment]
Since I'm working https://github.com/kubernetes/test-infra/issues/9007

I'm going to update owners docs to include:
- filters
- required_reviewers

I've long stopped considering the docs here as the "owners" docs, and instead point people to https://go.k8s.io/owners where possible.  The reason I've avoided touching these is they elaborate on the approvers algorithm.  

@kargakis @cjwagner I'd rather outright delete these docs.  Failing that, I think they need to be trimmed to answering just the "How does the reviewer selection mechanism work? approver selection mechanism work?" questions.  WDYT?

**Comment by kargakis** [comment]
On top of those questions, it would be nice to document how prow can be
configured to use OWNERS.

**Comment by cjwagner** [comment]
Yeah I think we ultimately should have:
- What OWNERS files can be used for.
- How to configure them.
- Brief overview of behavior.

**Comment by stevekuznetsov** [comment]
Is this also the sort of doc we want to serve from `deck`? Could make it interactive with loaded config, keep it local and up to date, make it relevant for all deployments.

**Comment by spiffxp** [comment]
/milestone 2019-goals
/unassign
/help

I'm doubtful I will get to this in v1.14 timeframe.  I am willing to help review if someone else wants to take a crack.

**Comment by matthyx** [comment]
😭 @spiffxp, reopen?
