### ISSUE TITLE
expose os distro information on testgrid for node e2e

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/test-infra#544]
Now almost all node e2e test result can be accessed publically through testgrid, which is really useful for the development velocity. Unfortunately it doesn't include os distro information here. For example, clicking the link at: https://k8s-testgrid.appspot.com/google-node#kubelet-serial-gce-e2e&include-filter-by-regex=MemoryE&graph-metrics=test-duration-minutes

One will see:

[k8s.io] MemoryEviction [Slow] [Serial] [Disruptive] when there is memory pressure should evict pods in the correct order (besteffort first, then burstable, then guaranteed)
[k8s.io] MemoryEviction [Slow] [Serial] [Disruptive] when there is memory pressure should evict pods in the correct order (besteffort first, then burstable, then guaranteed) [4]
[k8s.io] MemoryEviction [Slow] [Serial] [Disruptive] when there is memory pressure should evict pods in the correct order (besteffort first, then burstable, then guaranteed) [3]
...

I believe each one of them matches to an os distro, unfortunately there is no easy way for me to find which one is which. 

cc/ @kubernetes/sig-node

**Comment by fejta** [comment]
With https://github.com/kubernetes/test-infra/pull/626 and https://github.com/kubernetes/test-infra/issues/581 we have the ability to add arbitrary metadata to test runs.

We should support more customized `TestNameConfig` in a test group's configuration, including `name_format`.

I would expect to be able to do something like the following:

```
test_name_config:
- name_format: '%s [%s]'
- name_elements:
    - name: true
    - metadata: gce_node_image
```
which should result in the following row name: `Cadvisor should be healthy on every node. [gci-base-52-8350-75-0]` (assuming the test name is Cadvisor... and the node image name is gci-base...)

Also, we should update [`KubeDescribe` in `framework.go`](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/framework.go#L795) to append a flag-defined prefix (maybe reuse [`TestContext.Prefix`](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L167)?) rather than the `k8s.io` literal

**Comment by Random-Liu** [comment]
@fejta Thanks a lot! This will be super helpful to us!

**Comment by krzyzacy** [comment]
seems it's still me :-) I'll take it.

**Comment by krzyzacy** [comment]
ref https://github.com/kubernetes/test-infra/pull/2433
