### ISSUE TITLE
[release-1.9] periodic-kubeadm-gce-1-9 building from release-1.8 branch

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#5769]
There are two `version` tags. The main one seems to be pointing to the release-1.8 branch, which causes `find_green_build` to fail to find a good run.

Is this supposed to be a version-skewed test? The name doesn't indicate as such.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/periodic-kubernetes-e2e-kubeadm-gce-1-9/139

key | value
-- | --
Result | SUCCESS
Tests | 0 failed / 170 succeeded
Started | 2017-11-30 11:20 PST
Elapsed | 1h4m
Version | v1.8.5-beta.0.43+e22774fbe88837
Builder | 6a55a3e2-d603-11e7-a235-0a580a6c001f
infra-commit | 8b35d3fe5
job-version | v1.9.0-beta.0.713+5898890a735c4e
repo | k8s.io/kubernetes
repo-commit | e22774fbe88837403e507df24448bdb24c2b1f82
repos | {u'k8s.io/kubernetes': u'release-1.8'}
version | v1.9.0-beta.0.713+5898890a735c4e

**Comment by BenTheElder** [comment]
/cc @luxas @krzyzacy 
I'll compare it to the configs for the 1.8 jobs.

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/periodic-kubernetes-bazel-build-1-9/143 - the periodic bazel build was failing now for release-1.9 :-(

**Comment by enisoc** [comment]
Filed https://github.com/kubernetes/release/issues/473 for the bazel build.

**Comment by luxas** [comment]
Thanks @enisoc for filing, root cause seems to be https://github.com/kubernetes/test-infra/pull/5576#discussion_r154494066, basically a typo

@BenTheElder why doesn't periodic-kubernetes-e2e-kubeadm-gce-1-9 and periodic-kubernetes-e2e-kubeadm-gce-upgrade-1-8-1-9 seem to be present anymore in https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml? Have they been deleted and if so for what reason? They were chained after the bazel 1.9 build job in the initial https://github.com/kubernetes/test-infra/pull/5576 PR :thinking:

**Comment by luxas** [comment]
@enisoc you're completely right, this job should solely test the creation of kubeadm clusters on the release-1.9 branch, no skew testing should be performed here.

**Comment by BenTheElder** [comment]
Yes, that job had the wrong branch and is fixed now thanks to @xiangpengzhao. 
Unfortunately our config is large enough now that GitHub will no longer expand diffs which makes this fun to review `:joy:`

**Comment by BenTheElder** [comment]
@luxas I haven't removed any periodic jobs, the only thing I'm aware of is @krzyzacy changing the rate at which the bazel jobs run to reduce boskos pressure from the chained kubeadm jobs.
