### ISSUE TITLE
run_if_changed jobs cannot be manually triggered on PRs that do not match

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5833]
https://github.com/kubernetes/kubernetes/pull/56554

It seems tentatively that `/test pull-kubernetes-cross` doesn't work since this job doesn't change any files matching the regex. I think we had a discussion about this previously in the comments on another PR but I don't have it handy. This is a regression we should probably sort out AFAIK.

/area prow
/cc @cjwagner @kargakis

**Comment by BenTheElder** [comment]
FYI @m1093782566

**Comment by BenTheElder** [comment]
I've suggested temporarily adding a `build/do-not-merge-this-file` as a workaround to trigger the test while we sort this out, but that's a pretty ugly hack we shouldn't depend on.

**Comment by BenTheElder** [comment]
see also https://github.com/kubernetes/kubernetes/pull/55289#issuecomment-349509802

**Comment by cjwagner** [comment]
The discussion was on #5655.

Since RunIfChanged jobs cannot match `/test all` (enforced by presubmit), my main concern is moot.
The only other downside is the case where a RunIfChanged job is manually triggered and fails and then needs to be ignored for merging, but pushing a new commit should be an okay work-around until we implement a `/skip` command.

**Comment by cjwagner** [comment]
I'll make a PR with the change.
