### ISSUE TITLE
Possible Testgrid Bug?

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5886]
<img width="1178" alt="screen shot 2017-12-09 at 3 25 02 pm" src="https://user-images.githubusercontent.com/917931/33800489-40253360-dcf5-11e7-981b-3e2eb635a3ee.png"></img>
[https://k8s-testgrid.appspot.com/sig-scalability-gce#Summary](https://k8s-testgrid.appspot.com/sig-scalability-gce#Summary)

There are some failed jobs back on 11-20 and prior but all recent runs appear to be totally green, I suspect this is because the AfterSuite is not reporting on the newer runs.
Is this WAI and if so can we change the behavior or configure this without hiding the past results?

/assign @michelle192837 
/cc @porridge @shyamjvs

**Comment by michelle192837** [comment]
This is WAI. Number of recent runs is 10 by default, and AfterSuite isn't being discounted yet because we look for failing results in recent runs. If there were a passing run for AfterSuite this wouldn't report failing, but the most recent result in the last 10 runs has a failure for AfterSuite instead.

This can be waited out with a few more runs, or the number of recent runs on this test group/dashboard can be reduced. (Maybe 4 or so to get the last day's worth of results, it looks like).

**Comment by porridge** [comment]
If this is WAI on testgrid side, then perhaps it should be fixed on the e2e
framework side, to report green status for AfterSuite (etc)?

**Comment by BenTheElder** [comment]
WAI on e2e side as well I think, we don't put green for things that don't
run. Hmm

**Comment by BenTheElder** [comment]
This is not a testgrid bug, though perhaps this should be tracked / fixed in k/k
/close
