### ISSUE TITLE
Some label prefixes should only ever exist once per issue

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#6095]
For example:
- it doesn't make sense for an issue to have multiple priority/foo labels
- it doesn't make sense for an issue to have multiple lifecycle/foo labels (stale, rotten, and frozen at the same time)

However there are label prefixes that can exist more than once, eg:
- An issue that involves multiple sig should have multiple sig/foo labels

This may be a use case for a rewrite of the label plugin, or just some special case logic to add.

**Comment by spiffxp** [comment]
The `priority/foo` thing doesn't align with the practice of having a `priority/failing-test` and `priority/critical-urgent` assigned to the same issue, but in practice I have never seen "failing test" used as a priority, just another dimension.  Better IMO to migrate that to `kind/failing-test`

**Comment by cblecker** [comment]
+1 to this
cc: @fejta

**Comment by stevekuznetsov** [comment]
We explicitly did not support priority for the `tide` pools... maybe we should just retire those labels anyway?

**Comment by spiffxp** [comment]
Priority labels are useful for triaging issues, they're not going away anytime soon.  The `queue/*` labels? Those can probably go away at some point, but that's orthogonal.

**Comment by stevekuznetsov** [comment]
@cjwagner your framework has this called out explicitly right?

**Comment by cjwagner** [comment]
@stevekuznetsov Yes, there will be a command type that manages a set of labels from a class, allowing at most one label from the class to be applied at a time.

**Comment by cjwagner** [comment]
/remove-lifecycle stale
/lifecycle frozen
This will be addressed by the label command framework, but I don't plan to work on the framework during Q4.

**Comment by spiffxp** [comment]
/priority important-longterm
Taking a guess that we may try and get to this next release cycle

**Comment by jberkus** [comment]
This would be really helpful to have for priority/.  Issues/PRs with multiple priority tags cause problems for Release Team automation.

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
I'm taking no action on this in ~2 years as a sign that it's no longer that important
/sig contributor-experience

**Comment by nikhita** [comment]
Still relevant.

/reopen
/remove-lifecycle rotten

**Comment by vincepri** [comment]
@nikhita @spiffxp Is this something we could make configurable (if someone works on it)? We're planning to add a `priority/release-blocker` label in Cluster API in addition to the critical-urgent ones to signify that a release can be delayed if a particular issue or PR doesn't get merged, or if we don't have enough consensus. 

We tried to have a simple label called `release-blocking`, although the bot refuses to apply the label https://github.com/kubernetes-sigs/cluster-api/issues/4337#issuecomment-804458826 because it's not in the list of additional labels, so we were thinking about the priority prefix, any suggestions?

**Comment by nikhita** [comment]
>  Is this something we could make configurable (if someone works on it)?

While it's not difficult to configure this technically, I'm a little hesitant on allowing multiple priority labels.

> We're planning to add a priority/release-blocker label in Cluster API in addition to the critical-urgent ones to signify that a release can be delayed

A few approaches here:
- Define `priority/release-blocker` > `priority/critical-urgent` priority-wise for Cluster API
- Add a `kind/release-blocker` instead since there can be multiple kind labels

**Comment by kikisdeliveryservice** [comment]
Another example of this came up today: tracked/** 

We hit an issue that was tracked/out-of-tree and tracked/yes simultaneously, but an issue should only have 1 such tracked/** label

**Comment by amirrmonfared** [comment]
Hello @RaghavRoy145 
Are you still working on it? if not let me hand it over. 🙂

**Comment by jberkus** [comment]
closing because [migrated to prow repo](https://github.com/kubernetes-sigs/prow/issues/179)

/close
