### ISSUE TITLE
Issue Mover From One Repo To Another

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/test-infra#6103]
I've been running into cases where an issue should be moved from one repo to another. If we break out parts of Kubernetes into separate repos this may happen to some others.

Before I look at using [probot for this](https://probot.github.io/apps/move/) I thought I'd ask here. Are there any plans to add something like this to prow?

**Comment by BenTheElder** [comment]
That tool looks cool.

I don't think Prow per se is the right place for this functionality since
it would involve scraping lots of historical data (as opposed to being
primarily webhook based) and probably needs a different token (since it
will take lots of API calls) etc. There's some precedent for tooling like
this in the status / label migration tooling though.

**Comment by BenTheElder** [comment]
I also don't think anyone has plans to build something like this currently.
