### ISSUE TITLE
test-grid tab stays red forever.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/test-infra#6533]
https://k8s-testgrid.appspot.com/sig-node-containerd#node-e2e-benchmark

After we fix a test. New test rows are created, but old test rows are still red...
And the test tab stays red, too.

It's hard to monitor test result because of this.

@kubernetes/sig-testing-bugs

**Comment by BenTheElder** [comment]
/assign @michelle192837 

FWIW I think this is WAI, those tests *are* still red. Eventually they won't be in the tab depending on the number of days kept.

**Comment by krzyzacy** [comment]
it looks not red to me

**Comment by rmmh** [comment]
It takes more than one passing test run for things to not be considered red.

**Comment by michelle192837** [comment]
@rmmh Not by default; num_passes_to_disable_alert = 1 unless someone has specifically changed that in their config.

However, these did not have passing test runs, they stopped running and had no results after. So this is working as intended, since the failures didn't have a passing run proving they passed, and the failure was in recent runs. If you would like failures to stop earlier, you can adjust num_recent_columns (which controls, among other things, how many runs are considered 'recent' for the purposes of saying a test is stale)

**Comment by Random-Liu** [comment]
Ha, it become green. Thanks!
