### ISSUE TITLE
Need "non-user-facing" label for PRs

### ISSUE THREAD

**Issue by nickchase** [kubernetes/test-infra#6545]
We're using a new autogeneration process for release notes, and to make things more manageable, we'd like people to be able to specify that a change is non-user-facing so that we can omit it from the release-notes process.

Ideally we'd require either "user-facing" or "non-user-facing" but if that's not possible than just the one works.

**Comment by BenTheElder** [comment]
I think the label sync tooling + the command framework will make this sort of thing easier.

Are we still looking to autogenerate the notes?

**Comment by nickchase** [comment]
We are, but for 1.13 you should talk to @marpaia

**Comment by marpaia** [comment]
Hey @BenTheElder, what's the command framework? I'm happy to discuss how we can get this kind of label integrated with the release note generation process.

**Comment by cjwagner** [comment]
The `release-note` plugin may be more complicated if it used the command framework because of how it interacts with the `release-note` markdown block in PR bodies. It is one of the plugins that probably are not worth migrating.

Additionally, I'm not going to have time to work on the command framework for a while so don't wait up on it.
