### ISSUE TITLE
upload cross-builds from master to gs://kubernetes-release-dev

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/test-infra#670]
:+1:

**Comment by ixdy** [comment]
@mikedanese can you explain how you're planning to use these artifacts?

**Comment by mikedanese** [comment]
We are using these artifacts for CI/nightly builds of debian/rpm packages. I want this:

https://github.com/kubernetes/release/blob/master/debian/xenial/kubeadm/debian/rules

To be pulling stuff hosted at gs://kubernetes-release-dev. It would also just be nice to have cross platform nightlies.

**Comment by ixdy** [comment]
@mikedanese do you really want the latest (possibly broken) nightly unless of a stable version?

**Comment by mikedanese** [comment]
@ixdy, yes. We'd like to publish both stable and nightly builds. Nightly builds are used for testing close to master.

**Comment by luxas** [comment]
ping @ixdy 
Is someone from @kubernetes/sig-testing going to work on this?
Would be awesome!

**Comment by ixdy** [comment]
The non-trivial part of this is that **kubernetes-build** does a quick-release (linux/amd64-only) and uploads its artifacts to `gs://kubernetes-release-dev/ci`. The **kubernetes-cross-build** job will take longer to complete, so I'm not sure how to handle its artifacts in a way that doesn't collide.

There are basically three options I see:
 1. Revert to old behavior and make only **kubernetes-cross-build** upload artifacts to GCS. This results in a longer turnaround time from commit -> things actually running in e2e tests (important for build breakage fixes and SQ latency).
 2. Make **kubernetes-cross-build** upload to a different path. (Kinda ugly, since now we'd have `ci/` and `ci-cross/` or `ci/cross/`.)
 3. Make **kubernetes-cross-build** overwrite any existing tarballs. This gets a little ugly too, since if **kubernetes-build** then runs again on the same sha (which has happened), it'll overwrite the **kubernetes-cross-build** binaries itself. And I'm not sure if GCS/gsutil will do the right thing if the tarballs are overwritten while they're being downloaded by an e2e test.

Anyone have a better idea?

**Comment by spxtr** [comment]
4. Make `kubernetes-build` upload to another path, since it's not a full release anyway. The e2es will have to pull from there instead.

I think 2 is best, and it's not that ugly.

**Comment by rmmh** [comment]
I like 2 as well, ci-cross sounds fine. Do we have any automation that consumes cross builds?

**Comment by ixdy** [comment]
No automation yet (hence we haven't been uploading them), but this issue was opened because there is a desire to have something consuming them.

There's a slight inconsistency in that the artifacts uploaded by the -release variants *are* full cross-builds, so `ci/1.4.1-beta*` actually does have everything, whereas `ci-cross/1.4.1-beta*` won't exist. It's probably not a big deal, though.

**Comment by ixdy** [comment]
http://gcsweb.k8s.io/gcs/kubernetes-release-dev/ci-cross

**Comment by ixdy** [comment]
(though that link is kinda broken until https://github.com/kubernetes/test-infra/pull/774 is merged and pushed)
