### ISSUE TITLE
k8s-ci-robot: Stop adding authors of the PRs to approved list

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/test-infra#6857]
This has been bugging me for a while: When someone sends a PR, they're listed like they've just `/approve`d their own PR.

Here's an example:

>  ![image](https://user-images.githubusercontent.com/159209/36287976-424e450c-126d-11e8-96f9-5ca980f30d0b.png)

Is this by design? It does not make a whole lot of sense to me. I think even the approvers themselves should explicitly `/approve` their own PRs when it's ready to go.

**Comment by BenTheElder** [comment]
Oops. I didn't see this before. This is configurable per repo, and for some repos like kubernetes implicit self approval is indeed how things are configured.

**Comment by stevekuznetsov** [comment]
So is this a bug in the message when that flag is not set?

/remove-lifecycle rotten
/area prow
/kind bug

**Comment by nikhita** [comment]
> So is this a bug in the message when that flag is not set?

No, the message is fine when the flag is set. There are even tests for it.

https://github.com/kubernetes/test-infra/blob/2bdc42592ba581f0aa51562e4975f6803546acc6/prow/plugins/approve/approve_test.go#L214-L248

This occurs in PR mentioned in the main issue body because that's a PR in k/community and we have implicit self approval there: https://github.com/kubernetes/community/pull/1733.

Closing this.
/close
