### ISSUE TITLE
RFE: tot fallbacks to directories specific to the prowjob type

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7056]
IIUC and based on the [GCS layout](https://github.com/kubernetes/test-infra/tree/master/gubernator#gcs-bucket-layout), tot uses a bucket for [postsubmits](https://github.com/kubernetes/test-infra/blob/80fd41d2feee8a8554db9a6d012e22f9cf5ac04a/prow/cmd/tot/main.go#L53) to fallback for every job. Things re `latest-build.txt` get more confusing because I find it in various places eg. [inside a PR bucket](http://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/60580/pull-kubernetes-node-e2e/), [inside the presubmit top-level bucket for a job](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-e2e/latest-build.txt) (which seems desirable for us), whereas I cannot find it in a [bucket](https://storage.googleapis.com/kubernetes-jenkins/logs/pull-kubernetes-node-e2e/latest-build.txt) where tot expects to find it. 

I am integrating tot into our deployment currently and I am forced to use our presubmit bucket for every job which is far from ideal. https://github.com/kubernetes/test-infra/pull/3041 has some discussion about deprecating tot and doing something else but I believe the story around it should be sound since it serves as a great tool for migrating away from Jenkins versioning. That being said, I am proposing the following changes:
- [x] update `initupload` to upload `latest-build.txt` for every job in its top-level directory based on its type and the documented GCS layout. Add `latest-build.txt` into the GCS layout document (missing currently) . Batch jobs should use the same number as presubmits. (https://github.com/kubernetes/test-infra/pull/7068)
- [ ] update `tot` to read the prow config, accept the top level bucket, and determine the rest of the path based on the documented GCS layout and the type of the prowjob that it is requested to vend a number for. Batch jobs should use the same number as presubmits. (https://github.com/kubernetes/test-infra/pull/7072)

@stevekuznetsov @BenTheElder @spxtr @rmmh @krzyzacy @cjwagner thoughts?

/area prow
/kind feature

**Comment by stevekuznetsov** [comment]
Is there any other use for `latest-build.txt`? If not, I'm not entirely convinced we need it. Uploading it is inherently racy, and when `tot` determines that it needs to do a fallback it can just query GCS for the job directories that already exist to determine what the latest pushed build was, no?

**Comment by stevekuznetsov** [comment]
Alternatively, before we move forward on this ... since the GCS layout of all things in the system seems to be the most ad hoc / "it is because it is" ... we should sit down, determine what our needs are for a storage solution and make a design document that cleanly and concisely exposes that. GCS right now is a huge headache.

**Comment by kargakis** [comment]
> Uploading it is inherently racy, and when tot determines that it needs to do a fallback it can just query GCS for the job directories that already exist to determine what the latest pushed build was, no?

Yeah, sounds more robust. I would expect it to be something that the GCS api provides but I need to look.

**Comment by BenTheElder** [comment]
gubernator uses latest-build IIRC

**Comment by rmmh** [comment]
The simplest _direct_ thing here would be to add another flag for where to fallback for presubmit jobs, identified by some prefix (`pull-`): 

- If a job number request comes in and tot doesn't know about the job, fetch the last build:
    - If the job name starts with "pull-": https://storage.googleapis.com/kubernetes-jenkins/pr-logs/directory/$JOB/latest-build.txt
    - Otherwise: https://storage.googleapis.com/kubernetes-jenkins/logs/$JOB/latest-build.txt

Note that this still doesn't solve migrating jenkins jobs that upload to a different directory based on repo path.

Making initupload put links for everything into `gs://kubernetes-jenkins/directory/$JOB/` would work well. Ensuring job names are globally unique is easy and already done. This would also allow us to deprecate sequential build IDs and tot altogether, since other tools could do a fast reverse-sequential list (listing a directory of 1000 files is fast, listing a directory of 1000 directories with 100 files each is very slow).

**Comment by kargakis** [comment]
> The simplest direct thing here would be to add another flag for where to fallback for presubmit jobs, identified by some prefix (pull-):

The prefix would need to be configurable and at that point I think it's better to just use the prow config in order to figure out whether the requested job is a presubmit or not.

**Comment by kargakis** [comment]
> Alternatively, before we move forward on this ... since the GCS layout of all things in the system seems to be the most ad hoc / "it is because it is" ... we should sit down, determine what our needs are for a storage solution and make a design document that cleanly and concisely exposes that. GCS right now is a huge headache.

initupload already creates paths based on the prowjob type and I expect tot to use the same logic so while I agree with you, let's tackle this in a separate issue/discussion as it sounds non-blocking for fixing tot.

**Comment by kargakis** [comment]
> The prefix would need to be configurable

Also, prow doesn't invalidate presubmits that start with different prefixes today so it's technically an ok thing to do.
