### ISSUE TITLE
Incubating a new project at kubernetes-sigs

### ISSUE THREAD

**Issue by dhilipkumars** [kubernetes/test-infra#7184]
Hi All,

We have incubated a [new project](https://github.com/kubernetes-sigs/scheduling_poseidon) into `kubernetes-sigs` sponsored by scheduler-sig.  We have a couple of questions. 

1. Are k8s bots already configured to look at other organizations? If no what is the procedure to do that?
2. Do we have an example project that has configured Bots , CI & CD pipe-line for projects outside k/*?

cc: @kubernetes/sig-scheduling-misc @shivramsrivastava @deepak-vij @timothysc

**Comment by BenTheElder** [comment]
1) yes, we have repos in a couple orgs, but if we add a new org we have to
configure it (EG sending webhooks to an app must be configured on each org
*or* repo) where is this project exactly?

2) yes, see EG https://github.com/kubernetes-sig-testing/frameworks

**Comment by dhilipkumars** [comment]
The project is here: https://github.com/kubernetes-sigs/scheduling_poseidon

**Comment by stevekuznetsov** [comment]
Do we want that under `kubernetes-sig-scheduling` ?

**Comment by BenTheElder** [comment]
We need to get @spiffxp or someone else with the appropriate GitHub permissions to set up the webhook for Prow, then we can enable [plugins](https://prow.k8s.io/plugins), test jobs, and the merge automation as desired.

**Comment by dhilipkumars** [comment]
> Do we want that under kubernetes-sig-scheduling ?
@timothysc Is there a scheduler sig specific org just like the one for testing?

**Comment by stevekuznetsov** [comment]
@dhilipkumars yes: https://github.com/kubernetes-sig-scheduling

**Comment by dhilipkumars** [comment]
@stevekuznetsov that organization looks more appropriate for this project,  but i will defer it to Tim and Bobby on why they chose this organization instead.
cc: @timothysc @bsalamat

**Comment by bsalamat** [comment]
I am fine with hosting the Poseidon project in SIG scheduling repo, but these SIG repos are very new and I am not aware of the details of their locations, etc. @timothysc has set up this repo. He should be able to help.

**Comment by resouer** [comment]
What's the relationship of: 

https://github.com/kubernetes-sig-scheduling
and
https://github.com/kubernetes-sigs

An will https://github.com/kubernetes-incubator be deprecated?

Will be appreciate if anyone can provide more context and background ...

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/blob/master/kubernetes-repositories.md

Please use kubernetes-sigs.  An org level webhook is already setup, and most plugins are enabled (ref #6623).  At this point if you have additional plugins you want to setup for your repo (ie: approval, trigger), you can PR them in via changes to prow/plugins.yaml and prow/config.yaml same as we allow for kubernetes/* and kubernetes-incubator/*

The creation of all of the other kubernetes-sig-foo orgs was a landgrab on our part in case we wanted to head that direction.  We used kubernetes-sig-testing as an experiment, but have since decided to to move ahead with kubernetes-sigs instead.  It's easier to administer one org than ~30

We will migrate kubernetes-sig-testing/frameworks to kubernetes-sigs/testing_frameworks 

I'm looking and not finding much int the way of official looking docs on incubator being retired, or kubernetes-sigs being the place, so I'll open up some issues to follow up.  Let me know if this has answered your questions @resouer @dhilipkumars

**Comment by timothysc** [comment]
> We will migrate kubernetes-sig-testing/frameworks to kubernetes-sigs/testing_frameworks 

done.  

We should nuke the other orgs too.

**Comment by dhilipkumars** [comment]
@spiffxp and @timothysc Thanks, both of you for the clarification, I was thinking this is `kubernetes-sigs` was an older org and our project needs to move.
