### ISSUE TITLE
new close labels need command support

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7251]
https://github.com/kubernetes/test-infra/pull/7200

FWIW, I'm not sure the proliferation of more labels is super helpful though vs descriptive text in this case (unless we're trying to track some stats on issue closing?). Kubernetes has tons of labels cc @spiffxp 

A *lot* of issues are also going to be closed due to staleness which will not have any particular reason.

**Comment by spiffxp** [comment]
I'm still not super sold on these labels TBH.  Personally I would have opted to hold out on adding the labels until we had the bot command for them to better flesh out the use cases.

Right now `/close` is limited to org members or authors, whereas I gather the intent of these labels is to allow anyone to identify candidates for closure.  Having different invocations of the same command limited to different groups seems weird to me, so I don't think `/close [reason]` is the right syntax for this.

What about modifying these to be `triage/foo` and adding a `/triage` command to the label plugin?

**Comment by spiffxp** [comment]
>What about modifying these to be triage/foo and adding a /triage command to the label plugin?

Based on discussion during today's contribex meeting and comments at https://github.com/kubernetes/community/pull/1970 it seems like consensus is to move ahead with this suggestion.  Please correct me if I'm wrong @spzala @cblecker 

/sig contributor-experience

**Comment by spzala** [comment]
Thanks @spiffxp I will be creating a PR to rename these labels. There is one more thing that was discussed outside the contribX meeting under https://github.com/kubernetes/community/pull/1970 was that, can we rename "kind/support" to "triage/support-request" (as @cblecker suggested or something related) to keep all labels related to triage under "triage/*", considering kind/support is targeted for triage. I mentioned that I will be discussing this with you :-). Please let me know your thoughts. Since kind/support is a legacy label, I am not sure if it needs a broader discussion. I will be working on renaming close/* to triage/* separately from renaming kind/support to make these changes quick. Thanks!

**Comment by cblecker** [comment]
Whipped up a quick PR to add support for the triage class of labels to the label plugin.

This would allow the `/triage need-information` command to add the `triage/need-information` label.
