### ISSUE TITLE
tide: allow exclusion of branches from merge pool

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7450]
We want to shutdown merges to master when a Kubernetes rebase lands but continue merging to release branches. It should be easy to update tide's config to support this.

@cjwagner @stevekuznetsov @mfojtik @deads2k 

/area prow
/kind enhancement

**Comment by kargakis** [comment]
> I may phrase it as selective branch merging, but this feature would be great. Making sure the SQ is temporarily off for particular branches during freezes will be very helpful.

Yeah, I just gave a concrete use case for which  "selective branch merging" is needed :) 

Btw the SQ is off for ever. Now, merges in Origin are handled by a different service with better prow integration.

**Comment by stevekuznetsov** [comment]
The query syntax doesn't allow for branches to be specified... do we want to do milestones instead? How is the k8s code freeze process going to integrate with `tide`? 

/cc @cjwagner

**Comment by cjwagner** [comment]
@stevekuznetsov Branches **can** be specified in with the query syntax: https://help.github.com/articles/searching-issues-and-pull-requests/#search-based-on-branch-names

The query syntax isn't great for milestones. If you specify multiple milestones Github seems to return results for any milestone, not just the ones listed. So in order to consider PRs for multiple milestones we would need to use multiple tide queries.
https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+milestone%3Av1.11+milestone%3Anext-candidate
This might be considered a bug? I would expect the `milestone` tag to behave like the `repo` tag when specified repeatedly.

**Comment by stevekuznetsov** [comment]
Looks like I am totally blind :O
