### ISSUE TITLE
prow: cherrypicker: allow picks across forks

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7587]
I would like to be able to cherry-pick commit `A` from repo `a` into a fork of repo `a`, not just into other branches of `a`.

/kind feature
/area prow
/cc @kargakis @deads2k

**Comment by deads2k** [comment]
@mfojtik @derekwaynecarr @liggitt @soltysh @bparees I think we've all had this on our wishlist for a while now.

**Comment by kargakis** [comment]
@deads2k as I understand it, the #1 use case for this is to cherry-pick from k8s back to origin, right? In that case we would also need to specify additional information in the cherrypick command to apply the patch in vendor and also prefix the commits' titles with `UPSTREAM:` (optionally since others don't use it). Though, I think with path labeling that we now have with prow, the commit naming convention is redundant. Other common cases for cherry-picking across forks? Origin -> ose? Anyone else that is not covered by the publishing bots?

**Comment by deads2k** [comment]
I was thinking just origin to OSE.  Other companies trying to maintain kube may appreciate a kube/kube to <company>/kube, but it's not a priority for me.

**Comment by kargakis** [comment]
Repo to fork is simpler and I would prefer to see just that implemented (if somebody ever tackles this).

**Comment by kargakis** [comment]
Any thoughts on the new format? Some options:
1.
```
/cherrypick org/repo#branch
```
2. 
```
/cherrypick org/repo branch
```
Others?

**Comment by soltysh** [comment]
:+1: for no#1 since that's a format being used across other places when using branch name

**Comment by kargakis** [comment]
The problem with 1 is that it will break cherrypicking to branches that include slashes in their name.
