### ISSUE TITLE
Resource name conflicts when different presubmit jobs' runs have same BUILD_NUMBER

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#7592]
For presubmit jobs, we're constructing names for instance-group, network and other resources based on the build number. So for e.g, if presubmit A's 234th run and presubmit B's 234th run both happen to run at the same time in the same project, there will be a conflict b/w those - causing failures. Since both of them will name resources like network, instance-prefix, etc as `e2e-234`.

I'm actually observing such failures quite frequently b/w the following 2 presubmit jobs I recently enabled (roughly at the same time):
- pull-kubernetes-e2e-gce-100-performance
- pull-kubernetes-kubemark-e2e-gce-big

We need to fix this asap. One way to do that would be to allow appending a unique prefix to the name string (i.e in front of `e2e-N`).

cc @BenTheElder @krzyzacy

**Comment by shyamjvs** [comment]
I'm not sure how frequently this is causing flakes in our other presubmits.

**Comment by krzyzacy** [comment]
wait, are those two presubmit shares the same project?

**Comment by shyamjvs** [comment]
That sounds a bit hacky and can give wrong info about how long the job has been around :).
How about my solution in #7596 ?

**Comment by BenTheElder** [comment]
Prefer #7596 but we are actively considering switching to snowflake numbers instead of incremental ids from tot @shyamjvs 

I think the main concern holding back any switch is the increased cost of scanning GCS for jobs, @rmmh probably has the best idea of how feasible this is. 

Like you mentioned tot vended ids do give a nice insight into how long the job has been around so there are probably some other considerations...
