### ISSUE TITLE
Feature branches should behave like master for testing purposes?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#7636]
Example PR failing due to bad test-infra assumption:

https://github.com/kubernetes/kubernetes/pull/62359

**Comment by ixdy** [comment]
/assign @BenTheElder 

We identified at least two issues:
1. The `kubernetes_verify` scenario (used by the `pull-kubernetes-integration` and `pull-kubernetes-verify` jobs) requires the branch to either be named `master` or `release-X.Y` to determine which version of the test image to use. @BenTheElder is going to fix this to assume anything not matching `release-X.Y` should use the master-branch version.
2. mungegithub seems to be identifying this PR as a cherrypick, likely because it's not targeting the master branch. We probably need to change this logic to only consider things targeting a `release-` branch as a cherrypick.

**Comment by ixdy** [comment]
OK, the faulty logic in mungegithub is pretty clear:
https://github.com/kubernetes/test-infra/blob/008760d57cf7c77a60ea1560060cc4be3bd941bc/mungegithub/mungers/cherrypick-label-unapproved.go#L76

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/blob/008760d57cf7c77a60ea1560060cc4be3bd941bc/mungegithub/mungers/cherrypick-auto-approve.go#L108 
might also be problematic.

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/test-infra/pull/7637 for verify. 

verify is... terrible. there are other open issues about this. the fix for this is trivial and out though.

**Comment by BenTheElder** [comment]
Generally speaking things *should* treat non-release branches the same as master, verify / integration are full of legacy hacks... I don't know much about the cherrypick munger. Those two should be fixed now though (just triggered retest to verify)

**Comment by lavalamp** [comment]
Thank you!

**Comment by ixdy** [comment]
We also seem to be missing automatic branch protection on feature branches currently, I think because kubernetes/kubernetes is still using the mungegithub implementation, which only targets master.

cc @fejta

**Comment by ixdy** [comment]
Also, the cla label seems to be missing.

**Comment by BenTheElder** [comment]
We've been discussing the branch protection issue offline, not sure what the best answer will be there, probably getting @fejta's next

> Also, the cla label seems to be missing.

xref: https://github.com/kubernetes/test-infra/pull/7493
