### ISSUE TITLE
`approve` plugin makes assumptions about OWNERS file implementation

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#7690]
The `approve` plugin is not working with regex filtering because it makes a bunch of undocumented assumptions about the implementation of the `repoowners` package which aren't necessarily true for regex filtered OWNERS files (thats what I get for copying code from mungegithub...)
Some invalid assumptions that are not provided by the interface:
- Approvers in OWNERS files are able to approve any file in the directory or subdirectories.
- OWNERS files contain one set of approvers.
- Files in the same directory have the same approvers.

The `approve` plugin will need a pretty significant rewrite to support regex filtering. It was due for one anyways; it is very inefficient and excessively complex, but I don't think I'll have the cycles to do this in the near future.

Other OWNERS file based plugins (`blunderbuss`, `owners-label`) are unaffected by this problem and should work properly with regexp filtering.

Sorry for the trouble Jeff :frowning_face:

/kind bug
/area prow
cc @ixdy @rmmh

**Comment by spiffxp** [comment]
/lifecycle frozen
Also a note to self: this is the issue to link when describing why OWNERS regex filters don't work for approvers

**Comment by cblecker** [comment]
Is there clear enough direction here for this to be `help wanted`, @cjwagner?

**Comment by cjwagner** [comment]
> Is there clear enough direction here for this to be help wanted, @cjwagner?

Definitely not. It is unclear how approver suggestions and the list of files that still need approval should work with regexp filtering.

**Comment by BenTheElder** [comment]
suggestion https://github.com/kubernetes/kubernetes/pull/76162#issuecomment-480099120

**Comment by cjwagner** [comment]
That suggestion SGTM and seems clear enough.
/help

**Comment by nikhita** [comment]
/assign

I really want this functionality :)

**Comment by rlenferink** [comment]
What is the status of this? We’d like to use this for k/website as well :)

**Comment by nikhita** [comment]
I looked into the plugin and realized that it needs a lot of work (like @cjwagner mentioned), just haven't had the time to implement it yet.

**Comment by matthyx** [comment]
Since @nikhita owns it...
/remove-help

**Comment by mmitoraj** [comment]
Hi, could you tell me what are the plans for the `approve` plugin to work with regex filtering? Can I expect the feature in the near future? :)

**Comment by stevekuznetsov** [comment]
@mmitoraj I don't think there are any current plans to make this better, but we are always happy to provide reviews and guidance if someone wants to pick this one up!

**Comment by michal-hudy** [comment]
As this is something that blocks our integration with Tide, I can try to solve this issue.

To start working on it, I need a clear statement of what is the expected behavior because I only tried Tide, I don't use it on a daily basis - we are using GitHub codeowners functionality currently.

If it is hard to describe expectations I can prepare a proposition to consider, but first I need to dig into `approve` plugin :)

**Comment by cblecker** [comment]
@michal-hudy Thanks for your interest! Let me see if I can sketch out some design goals.

/unassign @nikhita 
/assign

**Comment by cblecker** [comment]
As @cjwagner said in the original issue, `approve` makes a bunch of assumptions about how it reads and handles OWNERS files.

Instead of tracking things on a directory by directory basis, approve needs to track the approval status of each file. It also needs some UX changes to be able to display and represent what files may need to be approved, if only some files in a directory have been approved. The UX needs to be able to balance being verbose enough to clearly indicate what still needs approval, without being overwhelmingly long.

As an example of what a regex OWNERS file looks like, you can check out https://github.com/kubernetes/kubernetes/blob/master/OWNERS. In that file, ixdy should be able to approve any `*.bzl`, `BUILD`, or `BUILD.bazel` files in both the root directory, as well as any sub directory.

Let me know if this clears up what the goals if this are, and if you have any other questions :)

/unassign

**Comment by matthyx** [comment]
@nikhita do you have time to come back to this? Do you want me to have a look?

**Comment by liggitt** [comment]
we also would use this to assign targeted reviewers/approvers for CHANGELOG*.md files in the repo root

**Comment by dudicoco** [comment]
What is the status of this issue?

**Comment by matthyx** [comment]
@dudicoco looks like nobody's currently working on it...
If you need that fix, I can take a look, or if you want to work on it that's possible too!

**Comment by nikhita** [comment]
@ykakarap and I are working on it. We have a POC that works already!  

We are writing up more tests and will create a KEP soon. :smile:

**Comment by matthyx** [comment]
Awesome!

**Comment by sttts** [comment]
🎉 thanks!

**Comment by sbueringer** [comment]
@nikhita Just wanted to ask if there is an update to the status of this issue.
We would also be really interested in this feature.

**Comment by ykakarap** [comment]
Hi @sbueringer ,
I and @nikhita are working on this. We are introducing changes to the aprpoval plugin that addresses these issues and more. 
We are working on a KEP and it will be out soon.

**Comment by evankanderson** [comment]
@nikhita and @ykakarap -- are you still working on this, or does this need another search for an owner? (ha!)

**Comment by wuhuizuo** [comment]
I implemented a fixing in #29970.

PTAL 😄

**Comment by pohly** [comment]
Can someone confirm that https://github.com/kubernetes/test-infra/pull/29970 is available in production?

**Comment by BenTheElder** [comment]
Something merged that long ago is definitely in production unless it was reverted.

https://github.com/kubernetes/test-infra/commit/70514017da452358e5a159b8867cf41f7692f966 put v20240517-ea10bd814 into prod (note this will be a commit in the kubernetes-sigs/prow repo now) and we can see at prow.k8s.io in the sidebar menu at the bottom that `v20240517-ea10bd814` is being served by the frontend so we can be reasonably confident that this commit was deployed for the other components (if we wanted to look further there's a job to do the deploy and we could check the logs)
