### ISSUE TITLE
aws: IAM/roles are leaking

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#7736]
manually deleted ~100, should be good for a few days, but we need to fix the leak?

assign to a few aws experts 

/assign @zmerlynn @justinsb @chrislovecnm

**Comment by justinsb** [comment]
So I think this happens when a PR is revised quickly:

https://k8s-gubernator.appspot.com/pr/62308
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/62308/pull-kubernetes-e2e-kops-aws/83531/

https://k8s-gubernator.appspot.com/pr/62496
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/62496/pull-kubernetes-e2e-kops-aws/83735/

Not sure exactly what is happening to the job when a revised PR is pushed quickly.

In any case, I'll look into adding it to the AWS janitor to catch these leaks.

**Comment by AishSundar** [comment]
This one of our top flakes for last week : http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1

**Comment by liggitt** [comment]
Curious why sig-cli got tagged for this

**Comment by mengqiy** [comment]
This doesn't seems to be a sig cli issue.
/remove sig cli

**Comment by krzyzacy** [comment]
should be fixed with https://github.com/kubernetes/test-infra/pull/7740
