### ISSUE TITLE
Support run_after_failure jobs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7951]
Brought up during kubecon

@krzyzacy @cjwagner 

/area prow
/kind feature

**Comment by stevekuznetsov** [comment]
We should think through a clear boundary for the logic that we want to support here, these sorts of logic things cause the majority of correctness bugs in `prow`.

**Comment by krzyzacy** [comment]
simply `run_after`, and some condition like `succeed`?

**Comment by BenTheElder** [comment]
If we're going to do that, I think something a tad more general might be
worth thinking about. The coupling of our triggering to job definitions is
a bit awkward right now. We also have a couple of mutually exclusive
prowjob fields already..

**Comment by krzyzacy** [comment]
yeah, also that :-)

**Comment by sipian** [comment]
While using prow for Prometheus, I really missed this feature.
 Also discussed a bit on slack with @cjwagner & @fejta.
If there is a consensus, I would like to implement this.
It seems just need to add a similar feature like runAfterSuccess to [kube.PodFailed](https://github.com/kubernetes/test-infra/blob/master/prow/plank/controller.go#L373) & [kube.PodPending](https://github.com/kubernetes/test-infra/blob/master/prow/plank/controller.go#L388)

**Comment by cjwagner** [comment]
I don't think that is the consensus. Like Ben is saying, we really need something more general than tacking on another triggering mechanism.
`run_after_success` is already a problem because it has to be specifically handled in a number of places and introduces dependencies between jobs. Here are some examples:
- Tide doesn't always work properly with `run_after_success` jobs because it doesn't yet have logic to correctly trigger parent jobs of required `run_after_success` child jobs.
- https://github.com/kubernetes/test-infra/pull/8492#issuecomment-401125711
- https://github.com/kubernetes/test-infra/pull/8415#issue-196287044

I'm worried that adding a new triggering mechanism without generalizing and exposing a better interface to Prow components will result in more technical debt and bugs like these.
This could probably use a design discussion breakout session?

**Comment by kargakis** [comment]
Managing run_after_success jobs has indeed been very problematic. Today I was thinking of splitting creation of run_after_success jobs into its own service that has some advantages over the current state of things. Namely, prow controllers (plank, jenkins operator) are going to be simplified:
- we can remove the github client entirely once reporting is its own service 
- we trim rbac for agent controllers down since they don't need access to create prowjobs anymore
- no need to extend agent controllers for handling run_after_whatever anymore and less code to maintain

The extra service can also handle creation of run_after_success jobs for tide I think which means that tide is also going to be slightly simplified?

**Comment by BenTheElder** [comment]
I like this idea a lot.

I'd love to see a refactor someday (not necessarily worth the effort, but
it could be nice...) where we manage to totally decouple triggering from
job definitions so anyone can more easily integrate triggers for say, "run
if a release is tagged on github", "run a downgrade job if my cluster is
unresponsive", etc...
