### ISSUE TITLE
Need test coverage on CVM

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/test-infra#800]
@vishh @maisem @mtaufen @fabioy @bgrant0607 

https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gke.yaml specifies the node image in many places to be "gci" by using 

`export KUBE_GKE_IMAGE_TYPE="gci"`

Presumably these were added to all of the `gci-` test suites because the default image was CVM. But now that the default image is GCI, all of the tests that don't specify an image are using GCI in addition to all of the tests that specify GCI as the image. There are ZERO tests that specify CVM as the image to be used in the tests. 

From what I can tell, this means that we have duplicate test coverage (2x coverage on GCI) and a testing gap (0 coverage on CVM).

**Comment by mtaufen** [comment]
Argh you're right. Now that the default node image is `gci`, all of the test jobs that got `container_vm` coverage by assuming `container_vm` was the default need to be updated. I think this probably only applies to the GKE tests because IIRC the container-vm coverage for GCI was explicitly specified with `KUBE_NODE_OS_DISTRIBUTION="debian"`, but it's worth checking those too.

To be clear, the fix for GKE tests should be to add `export KUBE_GKE_IMAGE_TYPE="container_vm"` to the envs that are missing it.

**Comment by vishh** [comment]
AFAIK, @maisem attempted to locak down cvm testing prior to v1.4.0.

**Comment by maisem** [comment]
The default for testing was set to CONTAINER_VM for this exact reason, its less than ideal that it's set in a different repository but we do have coverage for CVM.
This was done in kubernetes/kubernetes#33125 and was cherry-picked into 1.4 in kubernetes/kubernetes#33134.

This change wasn't required to be cherry-picked into 1.3 and prior branches because the default in GKE was switched at 1.4.0.

**Comment by roberthbailey** [comment]
Thanks for keeping an eye on this.

**Comment by mtaufen** [comment]
Ok, great, good to know our assumption that no-explicit-image-set means container-vm on nodes will hold for GKE testing.
