### ISSUE TITLE
kube-flannel status showing "CrashLoopBackOff" in worker nodes 

### ISSUE THREAD

**Issue by SamDhina** [kubernetes/test-infra#8176]
Hi ,

I have setup a kubernetes cluster in oracle linux 7 OS with one master node and two worker nodes . After i Joined the worker node with token the kube-flannel network is not running and in web UI logs of kube-flannel i'm getting the below error . Any one have the solution to rebuild the flannel network in worker node alone .
**********************************************************

Logs from 
kube-flannel 
in 
kube-flannel-ds-4ndjb 

I0530 11:36:21.811384 1 main.go:470] Determining IP address of default interface 
I0530 11:36:21.812815 1 main.go:483] Using interface with name eth0 and address 192.168.10.177 
I0530 11:36:21.813027 1 main.go:500] Defaulting external address to interface address (192.168.10.177) 
I0530 11:36:21.839060 1 kube.go:130] Waiting 10m0s for node controller to sync 
I0530 11:36:21.839130 1 kube.go:283] Starting kube subnet manager 
I0530 11:36:22.839317 1 kube.go:137] Node controller sync successful 
I0530 11:36:22.839375 1 main.go:235] Created subnet manager: Kubernetes Subnet Manager - k8s-wnode1 
I0530 11:36:22.839391 1 main.go:238] Installing signal handlers 
I0530 11:36:22.839608 1 main.go:348] Found network config - Backend type: vxlan 
I0530 11:36:22.839740 1 vxlan.go:119] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false 
E0530 11:36:22.840180 1 main.go:280] Error registering network: failed to acquire lease: node "k8s-wnode1" pod cidr not assigned 
I0530 11:36:22.840379 1 main.go:328] Stopping shutdownHandler...
************************************************************************************************************

kube-system   kube-flannel-ds-4ndjb                    0/1       CrashLoopBackOff

**Comment by cblecker** [comment]
Please re-post your question to [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans Stack Overflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search Stack Overflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

---
/kind support
/close
