### ISSUE TITLE
milestone bot spam detracts from monitoring issues

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8205]
It's very difficult to actually subscribe to Kubernetes issues / PRs when code slush / freeze comes around due to the enormous amount of these messages:

![image](https://user-images.githubusercontent.com/917931/40856630-6a1042ca-658d-11e8-9179-887d61e1550d.png)

We should seriously consider if posting this once-a-day on each thread actually helps anyone.

/sig contribex
/cc @jberkus @cblecker @cjwagner @marun

**Comment by jberkus** [comment]
So the milestone bot nags folks daily or every 3 days (depending on the issue) because we expect progress in that window of time, and it's critical that issue/PR owners keep their issues updated.

While I agree that the milestone bot hasn't been spectacularly effective in doing this, do you have suggestions on something else we could do that isn't bot nagging?

**Comment by BenTheElder** [comment]
Can we nag folks that actually have permissions to fix these things to look
through the issues that have some label instead? Most of the people
receiving these messages can't really do anything about them.

**Comment by jberkus** [comment]
That would be great.  And ... a job for test-infra?

Step one is completing replacing the milestone munger with Prow.  Until we do that, no other changes are happening.

**Comment by cblecker** [comment]
I'd suggest some off-github method for doing this, or some way of aggregating the issues/PRs so that it's easier to review/digest, then a bunch of spam every 3 days.

I would actually say it's up to sig-release (not just the current release team, but those involved with the sig) to define what the desired process/procedure is. Then we can figure out engineering resources to make the code happen.

The key being, and feedback I'd agree with: The current process is ineffective, spammy, and presents a poor contributor experience. We don't really have time to fix it in the middle of the 1.11 cycle, but we need a long view to this process.

**Comment by cblecker** [comment]
@kubernetes/sig-release-members @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort

**Comment by BenTheElder** [comment]
> That would be great. And ... a job for test-infra?

The issue *is* filed in test-infra, I'm happy to work on something once we have consensus on what to do or even if we agree that we don't want the current situation, but sig-release and sig-contributor-experience need to be involved in discussing *what* we should do before any test-infra folk change this.

@cblecker's comment sums up my thoughts  nicely:
> The current process is ineffective, spammy, and presents a poor contributor experience. We don't really have time to fix it in the middle of the 1.11 cycle, but we need a long view to this process. 

Looking forward beyond the current release I'd love to identify a better solution to getting things through the milestone properly and implement.

**Comment by cblecker** [comment]
/remove-lifecycle stale

Very much still active :)

**Comment by cblecker** [comment]
Actually, did we just move away from the milestone maintainer completely?

@tpepper

**Comment by justaugustus** [comment]
@cblecker yep, this can be closed.

Milestone munger was disabled:
- https://github.com/kubernetes/test-infra/pull/8909
- https://github.com/kubernetes/sig-release/issues/243

/close

**Comment by BenTheElder** [comment]
Yes!! :tada:
