### ISSUE TITLE
Make more test suite block submit queue

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/test-infra#824]
When we cut an alpha release, the release tool looks at the following test suites:
- kubernetes-e2e-gce
- kubernetes-e2e-gce-serial
- kubernetes-e2e-gce-slow
- kubernetes-kubemark-5-gce
- kubernetes-e2e-gce-reboot
- kubernetes-e2e-gce-scalability
- kubernetes-test-go
- kubernetes-e2e-gke-serial

It grabs the most recent build where all of these were green.

However, only `kubernetes-e2e-gce`, `kubernetes-e2e-gce-slow`, and `kubernetes-test-go` block the submit queue when red. That means the other suites can become red without anyone noticing and remain so for multiple days. For example, I'm trying to cut a v1.5.0.alpha release and the tool can not find a green build because `kubernetes-e2e-gce-serial` has been failing for 2 days.

Arguably, if these suites are important enough to block a release, we should be blocking the submit queue and having bugs filed to get them fixed when they go red. I believe the reason these suites are non-blocking is because they are slow to run, and we don't want a single failure to block the queue for hours.

How about making these suites block the submit queue on failure, but only they fail N times in a row?

CC @mml

**Comment by spxtr** [comment]
Note that even if they don't block the submit queue, we still file issues when they break.

**Comment by saad-ali** [comment]
> Note that even if they don't block the submit queue, we still file issues when they break.

True. But these bugs don't seem to get the kind of immediate attention they deserve unless they are blocking the submit queue.

**Comment by spxtr** [comment]
Agreed. Unfortunately, the serial suite is often super flaky, plus it's slow. It might be that once we pull the disruptive tests out then it'll get better.

**Comment by saad-ali** [comment]
@jingxu97 is working on pulling the disruptive (destructive) tests out into a separate suite. Once that is done, we should proceed with blocking on serial. How about the others, e.g. scalability?

**Comment by mml** [comment]
I actually think the *N times in a row* rule is worth implementing regardless.  Transient flakes in the current slow suites can cause too much chaos already, and we can always set N to 1.

That said, I wonder if it should be *failing for more than N minutes*.  Look at what just happened here...

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/

**Comment by spxtr** [comment]
We already have the ability to rerun tests to check for flakes.

**Comment by mml** [comment]
fyi @lavalamp

**Comment by lavalamp** [comment]
I still object to making tests block the queue if they don't have things covered by presubmits.

BTW @grodrigues3's change to stop making P0's is in, so there should be less noise in the future.

If we still lack visibility, we need to do something to make it more visible. I think this should take the form of a dashboard or a report. "Can't cut a release right now because [gce-serial, gke-serial] are failing."

Blocking everyone in the whole project over these things is just too expensive, both in terms of productivity and morale...

@fejta is going to have to be the guardian of this while I'm gone :)

**Comment by fejta** [comment]
I would like to try and decouple two important goals:
1. We want to maximize the velocity of new changes
2. We want to highlight failing tests and get appropriate amounts of attention on them.

I recognize that we have struggle with goal (2) at various times. I think we can come up with a better solution than sacrificing goal (1) by blocking the submit queue to encourage people to look into additional CI jobs.

Specifically I want to head towards a future world that defines three classes of tests (I'm choosing fruit names at random):

* Pomegranate tests: tests which run on every PR, we expect these to pass at every commit
* Banana tests: tests which run at every build, we expect these to pass at every build
* Radish tests: tests which run at every release, we expect these to pass at every release

Specifically I want to move to a world where there is a 1:1 correspondence between the PR tests we need to run and what needs to pass to commit. If all the PR tests pass we will commit your PR as soon as possible.

In order to do that we need to figure out ensure that we find and fix CI failures quickly, and right now we don't know how to do that without making them block PRs.

**Comment by saad-ali** [comment]
> We want to highlight failing tests and get appropriate amounts of attention on them.

This is the biggest challenge...

> Radish tests: tests which run at every release, we expect these to pass at every release

Especially for these types of release tests--that tend to only get attention when a release needs to be cut.

Look forward to anything we can do to make this better.

**Comment by fejta** [comment]
Closing this out because we intend to eliminate all blocking suites in favor of relying exclusively on presubmits: https://docs.google.com/document/d/10AN_hgEM77CLtfZ-3v7zRV4ep5phqw2jc0jY4n8WRus/edit

At the same time we improved (and are improving) the ability to find failures:
* Each dashboard at http://testgrid.k8s.io now includes a Summary tab which shows all tabs with consistent failures.
* We also have http://go.k8s.io/triage which summarizes failures across jobs, and @cjwagner working to automatically create issues for the top problems.
