### ISSUE TITLE
Bazel caching flake: Build Timeout during download

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#8405]
```
W0620 00:47:55.713] WARNING: Error reading from the remote cache:
W0620 00:47:55.714] Connection reset by peer
```
Here are 2 examples of this flake from different jobs:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/8399/pull-test-infra-bazel/17244/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/8328/pull-test-infra-lint/3069/

/kind bug
/area greenhouse
/assign @BenTheElder 
/cc @stevekuznetsov

**Comment by BenTheElder** [comment]
```
W0620 00:47:55.713] WARNING: Error reading from the remote cache:
W0620 00:47:55.714] Connection reset by peer
```
I mean that's just the network call / download flaking. This doesn't stop testing.
The problem here is when it later tries to keep downloading until the build times out (from the looks of the logs)... not sure what else we can do about that. 
> W0620 01:01:00.768] [4,324 / 4,331] GoLink prow/cmd/sidecar/linux_amd64_pure_stripped/sidecar; 767s remote-cache

That's way over the default timeout.. I think we may need to tune the `--.*retry.*` flags [here](https://docs.bazel.build/versions/master/command-line-reference.html#build-options).

**Comment by BenTheElder** [comment]
There are no errors in the greenhouse logs, this is probably a cluster / node / pod level network flake. We should make bazel handle this better though.
/remove-area greenhouse
/area bazel

**Comment by BenTheElder** [comment]
I think I'm going to opt to let the queue drain a bit more before I tweak any of the caching settings.

**Comment by BenTheElder** [comment]
Commenting on upstream issue(s), though we still might want to tune some of these existing flags potentially. Will come back to this later.

**Comment by BenTheElder** [comment]
I'm not seeing this in current bazel. Current failures are generally due to downloading things from the broader internet that are _not_ cached, or due to code that actually doesn't build / test correctly.
