### ISSUE TITLE
Testing and reporting out-of-tree unit tests

### ISSUE THREAD

**Issue by akutz** [kubernetes/test-infra#8876]
In-tree providers that are moving (or have moved) out-of-tree may currently have unit tests that:

1. [Block PRs and releases](https://github.com/kubernetes/test-infra/blob/bc7d6af3a7f4b5f0eda8d844222842e079982077/prow/config.yaml#L1321-L1453) via the Prow job(s) `pull-kubernetes-bazel-test` 
2. Are reported on the test-grid via [`presubmits-kubernetes-blocking`](https://github.com/kubernetes/test-infra/blob/bc7d6af3a7f4b5f0eda8d844222842e079982077/testgrid/config.yaml#L6039-L6088)

On Slack @spiffxp indicated that there is not currently a way to identify unit test SIG/feature association, but with out-of-tree providers, there kind of is (the repo will be owned by some SIG).

1. Should these in-tree unit tests that currently block PRs and releases  continue to do so once out-of-tree?
2. If so, how should these tests be visualized on the test-grid now that the tests will (probably?) no longer be executed as part of `pull-kuberentes-bazel-test`? Should `presubmits-kubernetes-blocking` include test results from out-of-tree unit tests?

I submit that even if unit tests were formerly presubmits-blocking for k/k, **it no longer makes sense for K8s to be blocked for out-of-tree providers**. 

In fact, it's one of the primary reasons the providers have been moved out of three. Therefore, I propose that unit tests for out-of-tree providers:

1. Should **not** be presubmit, blocking for k/k
2. Should **not** be a member of `presubmits-kubernetes-blocking` on the test-grid
3. Can (and likely should) be presubmit, blocking for the out-of-tree provider repository's PRs
4. Should be visible on the test-grid as `presubmits-PROVIDER-blocking`

Using the in-tree vSphere cloud provider as an example, here's how the process would look when transitioning the provider's in-tree unit tests to [`kuberentes/cloud-provider-vsphere`](https://github.com/kubernetes/cloud-provider-vsphere):

1. Create (if necessary) a top-level category on the test-grid for the SIG that owns the cloud provider.
2. Create a test-grid definition for `presubmits-cloud-provider-PROVIDER-blocking` for unit tests that are blocking.

**sig-vmware**
![image](https://user-images.githubusercontent.com/101085/43359732-f7f3de2e-926c-11e8-84f3-a4c0f937424a.png)

**presubmits-cloud-provider-vsphere-blocking**
![image](https://user-images.githubusercontent.com/101085/43359728-e5341aa6-926c-11e8-8cbd-0a4055e3b574.png)

![image](https://user-images.githubusercontent.com/101085/43360849-54d117b6-9285-11e8-9f20-88defbf131e9.png)

**Comment by timothysc** [comment]
> Should these in-tree unit tests that currently block PRs and releases continue to do so once out-of-tree? 

No, unit tests should be implemented and maintained by the provider.  The provider can surface issues to the release team via federated testing if it so desires.

**Comment by akutz** [comment]
Hi @timothysc,

To be clear, you:

1. Agree with the above issue's assertion:
>  **it no longer makes sense for K8s to be blocked for out-of-tree providers**
2. Disagree that out-of-tree unit tests should be visualized on the test-grid in any capacity

Did I understand you correctly?

**Comment by tpepper** [comment]
Out of tree tests do need to be visible to the project in a consistent way.  I could concede unit tests not needing to be propagated up into the top level k8s test grid.  Tests of broader system interactions' testing (ie: integration, e2e, conformance) really should be visible.

But we're talking here just about running and reporting results first right?  Once that plumbing is in place, we can and surely will move over time what is and is not release blocking.  Seems like at least two conversations are happening here.

**Comment by akutz** [comment]
Hi @tpepper,

There are definitely two discussions, but I don’t think that in and of itself is a bad thing. Not sure where things took a left turn. So far everyone seems to agree with the original proposal:

1. Out of tree unit tests shouldn’t block k/k
2 Out of tree unit tests can still appear in test grid

**Comment by spiffxp** [comment]
Some historical context: 
- the dashboard names are just names and don't technically cause anything to happen
- all the dashboards under 'presubmits' used to be named 'presubmits-repo' for the kubernetes/repo that they corresponded to
- we split the k/k presubmits into blocking/non-blocking because we have so many, and some aren't blocking... I honestly don't know without digging deeper whether all the jobs listed for other repos are blocking
- an example of an out of tree repo that has its own blocking presubmits: [presubmits-kops](https://k8s-testgrid.appspot.com/presubmits-kops)

Back to the original questions:

>1. Should these in-tree unit tests that currently block PRs and releases continue to do so once out-of-tree?

No.

>2. If so, how should these tests be visualized on the test-grid now that the tests will (probably?) no longer be executed as part of pull-kuberentes-bazel-test? 

The current [presubmits-cloud-provider-vsphere-blocking](https://k8s-testgrid.appspot.com/presubmits-cloud-provider-vsphere-blocking) looks fine to me.  Were it me, I would probably rename it to presubmits-cloud-provider-vsphere.

I would also push for sig-vmware to have a dashboard group that displays results for all job/tests for which they are responsible.  You can see how sig-cluster-lifecycle is doing this for their cluster-api-provider repos, eg: [cluster-api-provider-gcp](https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-cluster-api-provider-gcp)

> Should presubmits-kubernetes-blocking include test results from out-of-tree unit tests?

No.

**Comment by akutz** [comment]
Hi @spiffxp,

Thank you for such great feedback. FYI, I just opened #8900 to create a top-level test-grid category for VMware-related tests. I also wanted to invite you to participate in the [discussion](https://docs.google.com/document/d/1bW2WxS1tprXwC9VBFDcs8W5yh9MNytj8f73_7TGNNWM/edit?usp=sharing) regarding what to name a top-level category for VMware-related tests. We considered using `sig-xyz`, but for various reasons and the tricky ownership issues related to SIGs at the moment, we believe `vmware` is the best option for organizing VMware related tests on the test-grid.

**Comment by akutz** [comment]
Hi @spiffxp,

> The current presubmits-cloud-provider-vsphere-blocking looks fine to me. Were it me, I would probably rename it to presubmits-cloud-provider-vsphere.

We used `presubmits-cloud-provider-vsphere-blocking` to be consistent with convention for other presubmit, blocking tests. Blocking in this case refers to the vSphere cloud provider repo, not k/k. Perhaps a new variation on blocking would be useful to distinguish between tests that block k/k and tests that block out-of-tree code on the test grid?

**Comment by BenTheElder** [comment]
The only reason we broke kubernetes into blocking and not-blocking is because there are a number of presubmits that don't block, and we (= test-infra maintainers) are more interested in checking up on the -blocking dashboard to make sure blocking presubmits aren't excessively failing.

The` release-.*-blocking` dashboards have some actual meaning (though in reality releases may block on more than that...), the rest are entirely for humans to discover and monitor at their discretion.

**Comment by akutz** [comment]
Hi @BenTheElder,

That makes sense and I had guessed as much. Your advice, if I understand it correctly, is to start without a blocking/nonblocking distinction and add it later only if necessary. I can appreciate that.

**Comment by figo** [comment]
The name `presubmits-cloud-provider-vsphere` lgtm, thanks

**Comment by spiffxp** [comment]
/close
It's unclear to me whether there is anything left to be done here.  If so, please /reopen and clarify
