### ISSUE TITLE
/area /kind commands are still effective in html comments <!-- and -->

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/test-infra#8937]
At https://github.com/knative/serving/issues/1797
the issue template shows users all /area and /kind commands, in a `<!-- -->` block

If users don't delete that, all labels are accidentally added.

Can prow detect and ignore whatever is in comment blocks?

**Comment by BenTheElder** [comment]
k/k's template puts these like:
```
uncomment one of the following:
> /foo bar
> /foo baz
```

Right now the commands are simple regexes against the comments like `(?mi)^/lgtm(?: no-issue)?\s*$`. Even just indenting the unwanted commands should work since we match on `^/command` typically.

Alternatively we can add prepreocessing to prow to match and eliminate HTML comment blocks from comments before matching comments. I'd favor just fixing the template to not match though, over adding an HTML parser to prow's comment handling...

cc @cjwagner 
/area prow
/kind enhancement

**Comment by grantr** [comment]
The purpose of the comment in the template is to hide `/area` commands and get a cleaner issue body. There's no need to make Prow ignore comments - currently we want Prow to *not* ignore comments!

The comments seem like they might cause more confusion (for issue creators and subsequent viewers) than the lack of command clutter is worth. @mattmoor WDYT about removing them from the template?

**Comment by ahmetb** [comment]
I guess that makes sense. Feel free to close this.
