### ISSUE TITLE
Analytics for Prow

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8981]
I'm thinking of adding an optional flag in deck that takes in a js snipplet via a mounted secret, which can provide us some prow usage data and who clicked what.

We can bind the OSS prow to k8s-ci-robot, and transfer ownership of the bot account once we migrated to CNCF.

cc @stevekuznetsov @munnerz @sebastienvas (to see if this can help/bother you)

/area prow
cc @cjwagner

**Comment by mithrav** [comment]
Can we use Stackdriver/Prometheus in some fashion?

**Comment by krzyzacy** [comment]
@mithrav we should use Prometheus for prow metrics, analytics is mostly for web traffic I think?

**Comment by stevekuznetsov** [comment]
Is there a more fleshed out design doc that focuses on what questions we are trying to answer, etc?

**Comment by mithrav** [comment]
ok cool

**Comment by krzyzacy** [comment]
@stevekuznetsov I don't have a design doc, I'm simply interested in seeing how many people have clicked into deck and which page they visit. I can bring it up in the next sig-testing meeting.

**Comment by munnerz** [comment]
I think this would be interesting data to collect, although definitely not critical.

It *could* help expose pages that users get 'lost' in (i.e. through the 'user flow' page in Google Analytics). I think there are probably some areas that are not-so-obvious.

This will become even more useful once Prow also serves up job logs etc., as I think there's a lot to be desired in the current gubernator UX and we could start to get an idea of what users find tricky/non-trivial.

**Comment by krzyzacy** [comment]
@munnerz yup, that's coming up soon (https://github.com/kubernetes/test-infra/pull/8921)

**Comment by cjwagner** [comment]
I think it would also be useful as a way to measure how much the different pages of Deck are actually being used.
I think that right now, most PR authors never go to Deck and might not even know it exists. As Tide spreads to more repos and the PR dashboard become more usable that will probably change. It would be helpful to measure how many people are actually using the front ends we are providing so that we can make sure that they are properly exposed.
