### ISSUE TITLE
Prow should consider `.gitattributes` when assigning size labels.

### ISSUE THREAD

**Issue by mattmoor** [kubernetes/test-infra#9003]
e.g. if codegen produces a lot of code, which is hidden in Github reviews by .gitattributes, then the change may be small.

**Comment by BenTheElder** [comment]
/area prow
/kind enhancement
cc @stevekuznetsov @cjwagner

**Comment by BenTheElder** [comment]
the size label logic has something like this hardcoded in, using .gitattributes instead could be nice :smile:

**Comment by cjwagner** [comment]
We should do this for vendored code too.

**Comment by blatayue** [comment]
Is using a .generated_files config too much to ask? Or we should just want more configurability options?

**Comment by stevekuznetsov** [comment]
/kind feature
/help

The `size` plugin adds labels like `size/S` to pull requests when they are updated. Today, it loads the `.generated_files` configuration for the repo in order to determine which files should be considered:

https://github.com/kubernetes/test-infra/blob/8faa040989cf8552683dcdd4400505ca62a3c408/prow/plugins/size/size.go#L91

https://github.com/kubernetes/test-infra/blob/8faa040989cf8552683dcdd4400505ca62a3c408/prow/plugins/size/size.go#L108-L114

We should add support for the plugin to load `.gitattributes` files as well and determine if any paths are excluded using GitHub's [`linguist-generated`](https://help.github.com/articles/customizing-how-changed-files-appear-on-github/) attribute. If a change is excluded, we should not consider it for the `size` calculation.

**Comment by matthyx** [comment]
Should be consider also the `$GIT_DIR/info/attributes` file?

**Comment by matthyx** [comment]
Also, as I understand it, for a given file, [attributes](https://git-scm.com/docs/gitattributes) can come from `$GIT_DIR/info/attributes` or any `.gitattributes` in parent directories (not sure about global and system-wide, does it even makes sense in our case?):
> When deciding what attributes are assigned to a path, Git consults $GIT_DIR/info/attributes file (which has the highest precedence), .gitattributes file in the same directory as the path in question, and its parent directories up to the toplevel of the work tree (the further the directory that contains .gitattributes is from the path in question, the lower its precedence). Finally global and system-wide files are considered (they have the lowest precedence).

So basically I have to find and parse all `.gitattributes` in the repo, store them in a sort of tree, and reconstruct the attributes for each considered file depending on its location and parents?

**Comment by matthyx** [comment]
@stevekuznetsov can you confirm?

**Comment by stevekuznetsov** [comment]
@matthyx that seems correct. However, I would maybe do a quick search to see how many projects currently using `size` are using the dir-relative attributes, anecdotally it seems like it would be few. It seems like you'd get the majority of the benefit from this feature with a minimum amount of work by not implementing support for the full attributes tree. Either way you want to approach it seems OK to me.
