### ISSUE TITLE
prow: trigger: negative matches in run_if_changed 

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#9095]
What's the best way to run a job for _any_ changes other than those in a specific directory? We just had some developers add this config:

```yaml
    # The abomination below is equivilent to `^((?!Documentation).)*$`. Since
    # Go doesn't support negative lookaheads, we are stuck with the following.
    run_if_changed: "^([^D]|D(D|oD|ocD|ocuD|ocum(D|e(D|n(D|t(D|aD|atD|atiD|atioD)))))*([^Do]|o[^Dc]|oc[^Du]|ocu[^Dm]|ocum([^De]|e([^Dn]|n([^Dt]|t([^Da]|a[^Dt]|at[^Di]|ati[^Do]|atio[^Dn]))))))*(D(D|oD|ocD|ocuD|ocum(D|e(D|n(D|t(D|aD|atD|atiD|atioD)))))*(o|oc|ocu|ocum(e(n(t(a|at|ati|atio)?)?)?)?)?)?$"
```

/area prow
/kind question
/cc @cjwagner @BenTheElder @fejta

**Comment by BenTheElder** [comment]
@munnerz [had this problem](https://kubernetes.slack.com/archives/C09QZ4DQB/p1523564294000543), for which we also just did a regex to move on https://play.golang.org/p/L7216AvaZ2z. It only needed to match a top level `docs/.*` so the regex was a bit simpler (`(^[^d].*$)|(^.[^o].*$)|(^..[^c].*$)|(^...[^s].*$)|(^....[^/].*$)`).

We could probably add `run_if_not_changed` but it will add more complexity and I'm starting to think `run_if_changed` is generally an anti-pattern, FWIW. We tend to let broken PRs through every so often due to this, whereas we don't save much by skipping most tests.

**Comment by munnerz** [comment]
Yeah this regex, whilst it works very well (and I'm thankful for @BenTheElder writing it!) is probably my least favourite thing in our configuration 🙄

How is this sort of thing generally represented in other CI systems, if at all?
