### ISSUE TITLE
prow: approvers: require N approvers per file

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#9113]
It's been requested to allow a repo to opt into N approvers per leaf file rather than just one. Any architectural issues to this? Would be a little bit of a foot-gun in case there did not actually exist N approvers for a leaf, but it should be OK to doc that.

/area prow
/kind feature
/cc @BenTheElder @cjwagner @krzyzacy

**Comment by cjwagner** [comment]
The approve plugin is a bit of a mess. It already doesn't work properly if regexp filtered `approvers` sections are used. The main difficulty is generating approver recommendations and showing which OWNERS files still require approval. Adding additional requirements for selecting multiple approvers from a single file would change that and how overlapping approvers have to be handled.

If this is needed it would be nice to see some details on how it would be achieved.

**Comment by BenTheElder** [comment]
I think this is sane in concept as long as there are at least N top level approvers for the repo, and the repo in question really wants this, but as Cole mentioned it would require pretty substantial changes to the approvers plugin.

OTOH, these architectural changes could also be helpful if we wanted to properly support glob/regex for owners to own some files rather than directories, which we sort of have a broken version of now IIRC.

**Comment by fabiand** [comment]
Can we reopen this, is anybody requesting N>1 approvers for certain PRs? And how is this implemented if nt with this plugin?
