### ISSUE TITLE
lint should detect when there is a package comment on another file in the package

### ISSUE THREAD

**Issue by paulangton** [kubernetes/test-infra#9118]
The command `/lint` currently adds a review comment when there is no package comment on a file, even if there is a package comment on a different file in the package (see #8922 for an example). It should be able to figure out if there is a valid package comment somewhere in the package and not add a review comment if that is the case.

/kind bug

**Comment by stevekuznetsov** [comment]
I'm pretty sure this is due to our threshold being set incorrectly low. I thought we fixed that?

**Comment by matthyx** [comment]
@stevekuznetsov it looks like this particular problem.Confidence is 0.9 which is the same or higher as the following test cases:
- Check names with underscore (0.9)
- Check names with all caps (0.8)
- Check stutter in function names (0.8)
- Check stutter in type names (0.8)
- Check variable declaration: should drop type (0.8)
- Check variable declaration: should drop value (int) (0.9)
- Check variable declaration: should drop value (float32) (0.9)

Do you think it's wise to bump confidence to 1 and tolerate all these lint issues?

Otherwise someone need to contribute to [golint](https://github.com/golang/lint/blob/master/lint.go#L417)...

**Comment by matthyx** [comment]
@stevekuznetsov can I have your advice on threshold?
Personally I don't see how we can solve this, unless maybe we regex and ignore that particular golint error in the plugin...

**Comment by stevekuznetsov** [comment]
Wait. given your link isn't it at `0.2`?

**Comment by matthyx** [comment]
> Wait. given your link isn't it at `0.2`?

Yeah, this is what I thought, but then playing around with the debugger on golint plugin and a test case, I found out it was in fact 0.8 - if you want I can make more investigations next week...

**Comment by stevekuznetsov** [comment]
We should submit that as a fix to their doc, very misleading. Agreed if it's 0.8 we cannot do anything here

**Comment by matthyx** [comment]
Sorry, you're right, the confidence is indeed 0.2 as verified in this branch:
https://github.com/kubernetes/test-infra/compare/master...matthyx:9118

Probably during my tests I wrote a wrong test case that triggered this [line](https://github.com/golang/lint/blob/master/lint.go#L411) instead.

This issue is indeed solved when confidence is > 0.2

**Comment by matthyx** [comment]
@stevekuznetsov I cannot close this issue... can you do it?

**Comment by idealhack** [comment]
@matthyx thanks for your investigation here. you can close the issue by telling the bot:
/close
