### ISSUE TITLE
adopt github issue templates

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9344]
see: https://github.com/kubernetes/org/tree/master/.github/ISSUE_TEMPLATE

we can have a lovely UI with different templates for different kinds of issues and make it easier and simpler for contributors to file bugs / feature requests etc

![image](https://user-images.githubusercontent.com/917931/45390868-bbe7eb00-b5d5-11e8-9afb-5c4d6e3337a7.png)

/kind enhancement
/area github
cc @cblecker @cjwagner @spiffxp

**Comment by shubheksha** [comment]
Working on this will for k/k, will pick this up for test-infra too!
/assign
I'll comb through the issues once to come up with a relevant list for this repo 😄

**Comment by spiffxp** [comment]
/sig contributor-experience
/kind cleanup
/area github
ping @shubheksha, any progress on this?

**Comment by BenTheElder** [comment]
hmm I'm not sure if we need others. (sorry for the huge delay!)
cc @cjwagner @krzyzacy @fejta

**Comment by cjwagner** [comment]
I don't have a strong opinion on area templates, but I think it would be a little confusing to have both area and kind templates given that those concepts are orthogonal.
If there is an `area/prow` and a `kind/bug` template, which would I use to create an issue about a Prow bug?

**Comment by cjwagner** [comment]
The labels aren't contradictory, but they are orthogonal. It makes sense to have both labels on an issue like the one I described, but I don't think it is possible to select multiple templates at once (please correct me if I'm wrong, I just took a quick look). So if we have one template for the `area/prow` label and one for the `kind/bug` label, it won't be obvious which to choose since both labels should be applied.

**Comment by shubheksha** [comment]
Ah, I get what you mean. I'll start with the those two first and then we can add more if necessary :)

**Comment by BenTheElder** [comment]
Thanks all!
