### ISSUE TITLE
Prow starter RBAC needs to set matching namespace

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9394]
as soon as user (@AishSundar) switch to a different pod_namespace, everything :boom: 

cc @stevekuznetsov @BenTheElder @paulangton @cjwagner 

/area prow
/assign

**Comment by krzyzacy** [comment]
(also our current prow deployments... we actually didn't apply them :man_facepalming: )

**Comment by cjwagner** [comment]
I don't understand what the problem is. Can you explain what the user was trying to do and what happened that was unexpected?

**Comment by krzyzacy** [comment]
So Role/RoleBinding are namespaced. When user add something like `pod_namespace: foo`, controllers, like plank, will try to list pods from that namespace, and got permission denied. 

ClusterRole/ClusterRoleBinding can operate on cluster scope.

(I hit it with crier already, the lister is listing all prowjobs across the cluster and got the same permission error)

**Comment by krzyzacy** [comment]
ok, then at least we need to fix the existing config (looks like the rbac we have under cluster/ is not deployed, but as soon as we migrate to cncf it will :boom: ) 

and also add docs to starter.yaml.

Probably it's easier just to make starter set `pod_namespace: test-pods`

**Comment by BenTheElder** [comment]
I don't think you should run prow in a cluster with other services due to arbitrary pod-specs, fwiw. And starter.yaml is meant to be a simple setup, not a production one.

**Comment by BenTheElder** [comment]
RBAC or not, I can trivially make an evil prowjob that does terrible things to your cluster and I don't care what namespace you put me in :^) If you want security, run your pods in a different cluster, period.

**Comment by stevekuznetsov** [comment]
> RBAC or not, I can trivially make an evil prowjob that does terrible things to your cluster 

 How?

**Comment by BenTheElder** [comment]
New Kubernetes users blindly applying manifests to their cluster do not have PSP in place, or particularly secure CRI for one.

**Comment by stevekuznetsov** [comment]
I guess we also enforce that you don't run privileged pods. Agreed that with privileged pods and host mounts you can do whatever, but that's `sudo` access on your nodes as far as I'm concerned and it's crazy y'all do it :)

**Comment by BenTheElder** [comment]
Right, you all enforce this, but a new prow user is very, very likely not.

We enforce things run in particular clusters, on those they're just worker nodes and people can indeed run privileged code. Cluster level isolation is stronger anyhow.

**Comment by stevekuznetsov** [comment]
So I guess I could challenge you to write a ProwJob with a PodSpec that a) I would approve for merge into our config and b) would not get denied by the cluster config, since we _do_ care about security :)

**Comment by BenTheElder** [comment]
Sure, YOUR cluster config probably would deny most of these, but you're not using starter.yaml :^)

**Comment by stevekuznetsov** [comment]
In any case the fact that it's possible to have an insecure cluster does not imply that we should forget about RBAC and just give cluster-level access. The starter.yaml should be self-consistent but give the minimal privileges necessary to work.

**Comment by BenTheElder** [comment]
> since we do care about security

please don't imply that we don't. our prow prevents access to important resources through cluster-level-isolation, which is preferable.

**Comment by stevekuznetsov** [comment]
> please don't imply that we don't.

I meant the starter.yaml strawman user here!

**Comment by BenTheElder** [comment]
I think if a user wants to secure RBAC properly, they should manage their own config and they will need to consider what namespace to use within their own, secured cluster with PSP etc. But really they should run prow in one cluster and jobs in at least one more, because containers themselves have problems :-)

**Comment by stevekuznetsov** [comment]
Right but since security is hard and RBAC is opaque to many I am not super comfortable suggesting the use of Cluster RBAC where it is not necessary to new users that may not know any better to change it to fit their needs.

**Comment by BenTheElder** [comment]
That seems fair enough, but I also don't think it's a strong sticking point, because I think it's much more important to suggest that they **do not** schedule CI workloads in the cluster with their prow secrets and merge robot. It's too fickle, regularly has escapes, and we have good support for using multiple clusters. We will never do that ourselves for this reason, and we should not recommend it. starter.yaml is the easy way to play with prow, NOT the way to do a serious deployment.

**Comment by BenTheElder** [comment]
We should really have a separate guide on how to get started on a more serious deployment with all the bells and whistles :-)

**Comment by stevekuznetsov** [comment]
> I think it's much more important to suggest that they do not schedule CI workloads in the cluster with their prow secrets

IDK, as mentioned before -- if we cannot use k8s in a secure multi-tenant manner, there is a huge hole in the k8s user story. I'd much rather tell people to run with PSP and not to schedule privileged pods as test workloads because even if the multi-cluster deployment limits the blast radius it's still not going to be fun when someone pwns the nodes on your build cluster.

To the point of this issue, though, if we just made the RBAC that got checked in self-consistent with the pod namespace, wouldn't that solve the immediate problem? Why is Cluster RBAC something that `starter.yaml` needs?

**Comment by fejta** [comment]
/assign
/close

Should be fixed?
