### ISSUE TITLE
/lgtm doesn't take effect with text appended

### ISSUE THREAD

**Issue by jessiezcc** [kubernetes/test-infra#9402]
Actual:
when I do "/lgtm bla bla", /lgtm doesn't actually apply. 

Expected:
/lgtm should still work

**Comment by dims** [comment]
@jessiezcc if you are upto it :) we just need to adjust the regex here : 
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/lgtm/lgtm.go#L36-L39

**Comment by fejta** [comment]
IMO we should keep the current pattern of requiring commands to start on a new line and be the only thing on that line.

It is perhaps confusing the first time someone runs into it but it makes for simpler code. And humans are compatively good at adjusting this way. 

Also: There's an option to make a GitHub approving review be considered /approve and/or /lgtm. I'd recommend enabling that functionality if you want a clearer lgtm process.

**Comment by BenTheElder** [comment]
yeah, we've kept these tight so that we're not for example, trying to parse github flavored markdown and figure out if these are in a comment block. commands work when they are

/foo

or:

/foo [argument]

And no other way. If you want to write a line with /foo and have it not work, you make the line not match with anything else on the line.

**Comment by stevekuznetsov** [comment]
Looks like there is consensus that this is WAI.

/close
