### ISSUE TITLE
redo the Monitoring velodrome dashboard

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9458]
http://velodrome.k8s.io/dashboard/db/monitoring?orgId=1&from=now-30d&to=now

We probably need to investigate/redo the following graphs:
- github token usage: why is k8s-merge-robot's token still seeing usage?
- submit-queue stats: we need some way to be able to compare PR velocity before/after the cutover, IMO the tide hourly merge rate is inscrutable for this... do we re-implement? use devstats?
- time since last merge: we probably want to re-implement this

We may want to consider removing the following:
- blackbox prober: has this ever actually failed?
- mungegithub loop frequency: this is no longer relevant

/area velodrome
/sig testing
/priority important-soon

**Comment by spiffxp** [comment]
FYI @cjwagner
The k8s-merge-robot token usage is the one that weirds me out the most

**Comment by cjwagner** [comment]
> - github token usage: why is k8s-merge-robot's token still seeing usage?

Aaaaa its the ghost of Mungegithub! 👻
I'll take a look there may be some other deployments that use that token. I know that velodrome uses some tokens to periodically check the remaining tokens to produce that graph. I hope it isn't using 300+ tokens per hour on its own...

> - submit-queue stats: we need some way to be able to compare PR velocity before/after the cutover, IMO the tide hourly merge rate is inscrutable for this... do we re-implement? use devstats?

I think the hourly merge rate is mainly useless because the window is too small. The SQ graph used daily merge rate which is probably more scrutable. I'll switch the tide merge rate graph to use days instead of hours for now. I'm definitely open to implementing better metrics or creating better graphs if anyone has requests on what they would like to see.

> - time since last merge: we probably want to re-implement this

I think I can make a graph for this with the metrics that are already being exported.

> - blackbox prober: has this ever actually failed?

I'm not sure what that graph is even supposed to display. I think we got some prober alerts after https://submit-queue.k8s.io was turned down though.

> - mungegithub loop frequency: this is no longer relevant

I'll delete this graph.

**Comment by cjwagner** [comment]
So in addition to the token counter using the `k8s-merge-robot` token, there are also 14 fetcher deployments that are using the token. https://github.com/kubernetes/test-infra/blob/a53fae5dffc30ebf962c89641159e06b9c1056bf/velodrome/fetcher/deployment.yaml#L25

There are 16 repos configured in [`config.yaml`](https://github.com/kubernetes/test-infra/blob/master/velodrome/config.yaml), but it looks like the difference of 2 is because the updates for `istio/fortio` and `tensorflow/tensorflow` were never deployed (probably thanks to the 'creative' deployment mechanism).

https://github.com/kubernetes/test-infra/blob/a53fae5dffc30ebf962c89641159e06b9c1056bf/velodrome/config.yaml#L170
https://github.com/kubernetes/test-infra/blob/a53fae5dffc30ebf962c89641159e06b9c1056bf/velodrome/config.yaml#L193

I'd like to get rid of as many of these velodrome deployments as possible because I suspect that they are not used at all (2 of the configured deployments weren't even deployed), but we'll still want to find people to confirm that this isn't going to break any workflows.

**Comment by spiffxp** [comment]
/miletone v1.13
Let's see if we can close this out this release cycle

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
I have since done some of these things in https://github.com/kubernetes/test-infra/pull/11005

> * submit-queue stats: we need some way to be able to compare PR velocity before/after the cutover, IMO the tide hourly merge rate is inscrutable for this... do we re-implement? use devstats?

I removed this, we now have tide pool and merge rate graphs. I also find devstats to be useful for comparisons across mungegithub/tide usage.

> * time since last merge: we probably want to re-implement this

I removed this.  We may want something like this back in.  The biggest hangup these days isn't no-merging, but no-batch-merging.

> * blackbox prober: has this ever actually failed?

I removed this

> * mungegithub loop frequency: this is no longer relevant

Cole removed this

Leaving this open to pull out the velodrome token usage into its own issue

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

With the standalone stack coming soon this will be fixed.

**Comment by spiffxp** [comment]
/milestone v1.16
I feel like we should either call this done, or do what it takes with the monitoring stack to finish this off

**Comment by spiffxp** [comment]
Monitoring token usage of velodrome seems similar to https://github.com/kubernetes/test-infra/issues/5338 to me
