### ISSUE TITLE
Wait for Github-checks statuses

### ISSUE THREAD

**Issue by ant31** [kubernetes/test-infra#9512]
Hi, 

On kubespray we are now using github-checks instead of github-statuses. 
Now the bot is merging PR,  even if the checks are red/failing. 
Previously it was waiting that all statuses go green

As a workaround, I'm going to add 'required' statuses in the repo configuration. But it would be nice if the bot was aware of the github-checks. 

Couple examples of the problem:
1. https://github.com/kubernetes-incubator/kubespray/pull/3360/checks  -> Failed
 - 'k8s-ci-robot merged commit 62b1ea2 into kubernetes-incubator:master
2. https://github.com/kubernetes-incubator/kubespray/pull/3342/checks
 -  k8s-ci-robot merged commit 7fa682b into kubernetes-incubator:master

**Comment by BenTheElder** [comment]
The checks API is also not trivial to integrate with for existing projects, it requires migrating from oauth integration / standard webhooks to a GitHub "app" for preview access to the API.

**Comment by BenTheElder** [comment]
Also, for tests the bot can control triggering, the bot enforces that the tests have passed against the current target branch commit and the current PR commit together; and it can derive which test jobs should block merges from their config.

I think third party checks will always require config to tell the bot which to block on.

**Comment by ant31** [comment]
The issue continue on kubespray even with after configured context to be required. 
How the bot can still merge with a required failing context ? 

- https://github.com/kubernetes-incubator/kubespray/pull/3378/checks
- Kubespray CI Pipeline: Required

W

**Comment by BenTheElder** [comment]
As I said above, we cannot block on checks because they are only available to "github apps" which is not how prow is built, it uses an oauth token. The checks API is not available to us. We can only block on commit "statuses" which show up at the bottom of the PR, not in the checks pane.

These were green:
<img width="742" alt="screen shot 2018-09-26 at 9 41 20 am" src="https://user-images.githubusercontent.com/917931/46095014-5caade80-c170-11e8-9056-92ed527eb4f6.png">

**Comment by stevekuznetsov** [comment]
This sounds like a reasonable extension once it's not a tech preview API and we have access to it. Agreed with Ben here.

**Comment by BenTheElder** [comment]
Sorry today has been hectic, trying to catch up on these. I don't think we want to make an extra API call for each PR, IIRC we're able to get the status currently when we ask for the PRs, I'll defer to @cjwagner and @stevekuznetsov who've more recently touched the merge robot.

I do believe the robot is an admin on the k8s orgs, which may explain what you're seeing.

We'd certainly like this to work.. but is there any chance you can post statuses from your integration instead of just checks? We have good tooling around statuses _today_ and they're the standard for blocking merges across all the CI I've seen, checks mainly seem to be leveraged for lints currently.

Alternatively if Cole and Steve are open to it perhaps PR the merge robot to handle checks? The code is in `prow/` as "tide".

**Comment by cjwagner** [comment]
> I don't think we want to make an extra API call for each PR

Yeah, that would not be acceptable. I'd only want to accept this change if it doesn't significantly affect token usage and doesn't add much complexity. I don't know of any other users of Tide who are using GitHub checks (the APIs are still in preview) so this would need to avoid negatively impacting performance and token usage.

**Comment by ant31** [comment]
> but is there any chance you can post statuses from your integration instead of just checks

Yes, this what we re going to do.

>I don't think we want to make an extra API call for each PR
>> Yeah, that would not be acceptable.

Yes, it could be a config: 
```
      repos:
        $repo:
          required_status_checks:
            contexts:
               - cla/linuxfoundation
            checks:
               - a-github-check
```
