### ISSUE TITLE
tide dashboard bug:

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9558]
<img width="1336" alt="screen shot 2018-09-24 at 8 38 11 pm" src="https://user-images.githubusercontent.com/917931/45991437-cc6a7d80-c039-11e8-8c48-7fd7d7f8aba8.png">

**Comment by BenTheElder** [comment]
/area prow/tide
cc @cjwagner

**Comment by stevekuznetsov** [comment]
I swear we saw this before... what was it?

**Comment by BenTheElder** [comment]
I didn't get a chance to dig in but I suspect we still have a bug somewhere as prow.k8s.io should be rather up to date

**Comment by cjwagner** [comment]
IIRC it happens when a PR in a batch leaves the pool. Once that happens we fail to look up the `PullRequest` for the PR number and an empty `PullRequest` is used (hence the 0).

We should filter these PRs out of the pending batch that we report and omit the pending batch altogether if all PRs are filtered out. That way if everything in a batch leaves the pool we will trigger a new batch.
