### ISSUE TITLE
Command isn't recognized in comment left via email reply

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#9834]
See: https://github.com/kubernetes/community/issues/923#issuecomment-430126237

bot didn't recognize command `/remove-lifecycle stale` in such comment.

**Comment by nikhita** [comment]
I wonder if that's a one-off thing because I leave commands with email replies when I'm aware of the issue/PR _lots_ of times and it works. :eyes: 

Examples:

https://github.com/kubernetes/kubernetes/issues/65973#issuecomment-427685620
https://github.com/kubernetes/kubernetes/issues/62326#issuecomment-427762483
https://github.com/kubernetes/code-generator/issues/24#issuecomment-425714928
https://github.com/kubernetes/kubectl/issues/490#issuecomment-415091866
https://github.com/kubernetes/kube-openapi/issues/75#issuecomment-415091789

**Comment by xiangpengzhao** [comment]
@nikhita it seems so.
/cc @BenTheElder PTAL :)

**Comment by BenTheElder** [comment]
I also use commands via email pretty often, I'd guess we just missed a webhook for yours.

**Comment by nikhita** [comment]
> I also use commands via email pretty often, I'd guess we just missed a webhook for yours.

Looks like this was the case. I'll close this issue for now. Let's reopen again if we see this happening frequently.

/close

**Comment by TBBle** [comment]
Just saw (probably) this happen on https://github.com/kubernetes/kubernetes/issues/80996, which was closed because https://github.com/kubernetes/kubernetes/issues/80996#issuecomment-633327886 was apparently ignored or missed, and that went unnoticed by the issue author.

**Comment by nikhita** [comment]
> Just saw (probably) this happen on kubernetes/kubernetes#80996, which was closed because kubernetes/kubernetes#80996 (comment) was apparently ignored or missed, and that went unnoticed by the issue author.

I have admin access on the repo, so I looked at the raw text for the comment https://github.com/kubernetes/kubernetes/issues/80996#issuecomment-633327886. The comment has an additional space before the `/remove-lifcycle rotten` text which is why the bot didn't catch it.

In either case, I have reopened the issue for you. :+1:

**Comment by TBBle** [comment]
Should the bot have accepted that command? I realise that might open up risks of catching commands that were not intended to be caught, but given that the UI renders it 'stripped', it's not wonderful UX that the bot works off whitespace-different data than it shows the users.

**Comment by BenTheElder** [comment]
That's been rejected in the past and I'd probably expect the maintainers to reject it again, but if you're interested in discussing it again probably a new issue will be more visible.

**Comment by TBBle** [comment]
As long as it's been discussed, at least I know what to watch out for. I don't use GitHub via email, so it's academic to me personally. Two reported occurrences in two years (_assuming_ the first report here was the same problem) isn't really "happening frequently".
