### ISSUE TITLE
gopherage html only works via bazel run //gopherage -- html

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9978]
/kind bug
/assign @Katharine 

works via bazel
```
$ bazel run //gopherage -- html ~/sandbox/monkeys/diff.cov -o ~/sandbox/monkeys/diff.html
INFO: Analysed target //gopherage:gopherage (0 packages loaded).
INFO: Found 1 target...
Target //gopherage:gopherage up-to-date:
  bazel-bin/gopherage/darwin_amd64_stripped/gopherage
INFO: Elapsed time: 3.273s, Critical Path: 0.28s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
```

does not work via go install then run within k/test-infra dir
```
spiffxp@spiffxp-macbookpro:test-infra (master %)$ gopherage html ~/sandbox/monkeys/diff.cov -o ~/sandbox/monkeys/diff.html
Couldn't read JavaScript: open gopherage/cmd/html/static/browser_bundle.es6.js: no such file or directory.spiffxp@spiffxp-macbookpro:test-infra (master %)$
```

does not work via go install then run in random dir
```
spiffxp@spiffxp-macbookpro:monkeys$ gopherage html diff.cov -o diff.html
Resource directory does not exist.spiffxp@spiffxp-macbookpro:monkeys$
```

**Comment by Katharine** [comment]
So this is a [known issue](https://github.com/kubernetes/test-infra/blob/master/gopherage/cmd/html/html.go#L69-L70), in part because bazel uses a different directory layout.

Fixing it is a bit tricky. While we can detect that we are not running under bazel and try a different path, the resources we want are themselves generated by bazel, and won't exist if you just `go install` it. To the best of my knowledge (which is limited here), the only way to make this work is to commit the generated artifacts (which might be the way to go? I don't know).

**Comment by spiffxp** [comment]
I can't vouch for the cleanliness of this approach, but I believe kubernetes' e2e.test binary uses go-bindata to embed the resources. 

- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/testfiles/testfiles.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/generated/gobindata_util.go

However, some googling appears to have revealed the original repo disappeared.  There is a hard fork around: https://github.com/a-urth/go-bindata.

We could also consider something like https://github.com/gobuffalo/packr

**Comment by spiffxp** [comment]
/milestone v1.14

Let's see if we can make gopherage usable as a standalone binary

**Comment by Katharine** [comment]
hey, I actually fixed this one!

/remove-lifecycle stale
